// Governed Discovery Answer Bank. Source authority: Drive 02.04.01 EL8 Question & Signal Matrix Workbook.
// Typed evidence only: contributor, fit, salience and relationship answers never manufacture state severity.
const a=(id,parentId,text,effect)=>Object.freeze({id,parentId,text,effect:Object.freeze(effect)});
const ordinal=(p,c,rows)=>rows.map(([s,t,v])=>a(`${p}.${s}`,p,t,{kind:'state',constructId:c,value:v}));
const facet=(p,c,k,rows)=>rows.map(([s,t,v,negative=false])=>a(`${p}.${s}`,p,t,{kind:negative?'negative_facet':'facet',constructId:c,key:k,value:v,...(negative?{cannotEraseState:true}:{})}));
const context=(p,k,rows)=>rows.map(([s,t,v])=>a(`${p}.${s}`,p,t,{kind:'context',key:k,value:v}));
const planning=(p,k,rows)=>rows.map(([s,t,v])=>a(`${p}.${s}`,p,t,{kind:'planning_constraint',key:k,value:v}));
const uncertain=(p,s,t='Not sure')=>a(`${p}.${s}`,p,t,{kind:'uncertain'});
export const ANSWER_BANK_VERSION='0.6.0-reconciliation';
export const ANSWER_BANK=Object.freeze([
// General opening orientation: routing only.
...context('GEN001','routing_prior',[["01",'Money or financial pressure','financial'],["02",'Work, school, or responsibilities','occupational'],["03",'Health or physical condition','physical_condition'],["04",'Low energy or tiredness','energy'],["05",'Sleep','sleep'],["06",'Stress or difficult emotions','emotional'],["07",'Relationships','relationships'],["08",'Feeling lonely or unsupported','support_loneliness'],["09",'Home or surroundings','environmental'],["10",'Focus or getting started','focus_activation'],["11",'Direction, purpose, or knowing what to do next','direction_purpose_next_step']]),a('GEN001.12','GEN001','Something else',{kind:'unclassified_context'}),a('GEN001.13','GEN001','I’m generally doing well',{kind:'positive_path'}),a('GEN001.14','GEN001','I’m not sure',{kind:'uncertain'}),
// Physical.
a('PHY001.01','PHY001','Weight or body composition',{kind:'routing',constructId:'BODY_WEIGHT_CONCERN',value:'clarify'}),a('PHY001.02','PHY001','Exercise, movement, or activity level',{kind:'routing',constructId:'ACTIVITY_LEVEL',value:'clarify'}),a('PHY001.03','PHY001','Physical symptoms or discomfort',{kind:'scope_presence',constructId:'PHYSICAL_CONDITION',value:'reported',noSeverity:true}),a('PHY001.04','PHY001','Something else',{kind:'unclassified_context'}),a('PHY001.05','PHY001','None of these',{kind:'negative_scope'}),uncertain('PHY001','06'),
...ordinal('PHY100','BODY_WEIGHT_CONCERN',[["01",'Not at all','not_at_all'],["02",'A little','little'],["03",'Quite a bit','quite_a_bit']]),uncertain('PHY100','04'),
...planning('PHY101','physical_fit',[["01",'Keep cost very low','low_cost'],["02",'Keep it short','short'],["03",'Accessibility or mobility needs','accessibility_mobility'],["04",'Pain, symptoms, or a health condition','symptoms_condition'],["05",'Professional guidance may be needed','professional_guidance']]),a('PHY101.06','PHY101','No special limitation',{kind:'none'}),uncertain('PHY101','07'),
...ordinal('PHY200','SLEEP_QUALITY',[["01",'Very well','very_well'],["02",'Okay','okay'],["03",'Not great','not_great'],["04",'Really struggling','really_struggling']]),uncertain('PHY200','05'),
...context('PHY201','sleep_context',[["01",'Sleep timing or schedule','schedule'],["02",'Stress or thoughts','stress_thoughts'],["03",'Noise, light, temperature, or other surroundings','environment'],["04",'Physical discomfort or health symptoms','physical_symptoms']]),a('PHY201.05','PHY201','Something else',{kind:'context',key:'sleep_context',value:'other'}),a('PHY201.06','PHY201','Nothing obvious',{kind:'negative_context',key:'sleep_context'}),uncertain('PHY201','07'),
...context('PHY202','sleep_relationship',[["01",'More energy','energy'],["02",'Better focus','focus'],["03",'More energy and better focus','energy_focus']]),a('PHY202.04','PHY202','Neither noticeably changes',{kind:'negative_relationship',key:'sleep_relationship'}),uncertain('PHY202','05'),
...ordinal('PHY300','ENERGY_FUNCTION',[["01",'Very well','very_well'],["02",'Okay','okay'],["03",'Not great','not_great'],["04",'Really struggling','really_struggling']]),uncertain('PHY300','05'),
...context('PHY301','energy_context',[["01",'Poor sleep','poor_sleep'],["02",'A busy or irregular schedule','schedule'],["03",'Stress','stress'],["04",'Being less active than usual','activity'],["05",'Health or physical symptoms','physical_health'],["06",'Difficulty getting started','activation']]),a('PHY301.07','PHY301','Something else',{kind:'context',key:'energy_context',value:'other'}),a('PHY301.08','PHY301','Nothing obvious',{kind:'negative_context',key:'energy_context'}),uncertain('PHY301','09'),
...ordinal('PHY400','ACTIVITY_LEVEL',[["01",'6–7 days','6_7_days'],["02",'3–5 days','3_5_days'],["03",'1–2 days','1_2_days'],["04",'0 days','0_days']]),uncertain('PHY400','05'),
...planning('PHY401','activity_type',[["01",'Walking or outdoor activity','walking_outdoor'],["02",'Home or bodyweight activity without equipment','home_bodyweight'],["03",'Using equipment at home','home_equipment'],["04",'Gym or fitness facility','gym'],["05",'Another option','other']]),a('PHY401.06','PHY401','None of these are practical right now',{kind:'planning_constraint',key:'activity_type',value:'none_practical'}),uncertain('PHY401','07'),
...planning('PHY402','activity_barrier',[["01",'Time or schedule','time_schedule'],["02",'Cost','cost'],["03",'Space or location','space_location'],["04",'Mobility or accessibility','mobility_accessibility'],["05",'Pain or physical symptoms','pain_symptoms'],["06",'I need professional guidance before changing activity','professional_guidance'],["07",'Getting started','activation_context']]),a('PHY402.08','PHY402','Nothing obvious',{kind:'none'}),uncertain('PHY402','09'),
...ordinal('PHY500','ACTIVATION',[["01",'Rarely or never','rarely_never'],["02",'Sometimes','sometimes'],["03",'Often','often']]),uncertain('PHY500','04'),
// Financial.
...ordinal('FIN001','FINANCIAL_STRAIN',[["01",'Never','never'],["02",'Rarely','rarely'],["03",'Sometimes','sometimes'],["04",'Often','often'],["05",'Almost always','almost_always']]),uncertain('FIN001','06'),
...facet('FIN002','FINANCIAL_STRAIN','required_expense_coverage',[["01",'Comfortably','comfortable',true],["02",'I can cover them, but with little room left','tight_covered'],["03",'It is difficult to cover all of them','difficult'],["04",'I cannot currently cover all of them','cannot_cover']]),uncertain('FIN002','05'),
...context('FIN003','financial_context',[["01",'No current income','no_income'],["02",'Income does not cover what I need','income_shortfall'],["03",'Income is uncertain or irregular','irregular_income'],["04",'Regular expenses are difficult to cover','expense_difficulty'],["05",'Debt or required debt payments','debt'],["06",'A recent unexpected expense or financial shock','financial_shock']]),a('FIN003.07','FIN003','Something else',{kind:'context',key:'financial_context',value:'other'}),a('FIN003.08','FIN003','None of these',{kind:'negative_context',key:'financial_context'}),uncertain('FIN003','09'),
...facet('FIN004','FINANCIAL_STRAIN','financial_choice_limitation',[["01",'Not at all','none',true],["02",'A little','little'],["03",'Somewhat','some'],["04",'Quite a bit','substantial'],["05",'Very much','very_high']]),uncertain('FIN004','06'),
...facet('FIN005','FINANCIAL_STRAIN','financial_payment_risk',[["01",'I expect to cover them','expected_covered',true],["02",'I expect to cover them, but it will be tight','tight_covered'],["03",'I may miss one or more required payments','may_miss'],["04",'I am already behind on one or more required payments','already_behind']]),uncertain('FIN005','05'),
...facet('FIN006','FINANCIAL_STRAIN','financial_resilience',[["01",'I could cover it','can_cover',true],["02",'I probably could, but it would be difficult','probably_difficult'],["03",'I probably could not','probably_cannot'],["04",'I could not cover it','cannot_cover']]),uncertain('FIN006','05'),
...context('FIN007','at_risk_obligation',[["01",'Housing','housing'],["02",'Utilities','utilities'],["03",'Food','food'],["04",'Transportation','transportation'],["05",'Medication or healthcare','healthcare'],["06",'Debt or minimum payments','debt'],["07",'Another required expense','other']]),a('FIN007.08','FIN007','None',{kind:'negative_facet',constructId:'FINANCIAL_STRAIN',key:'at_risk_obligation',value:'none',cannotEraseState:true}),uncertain('FIN007','09'),
...['01','02','03','04','05'].map((s,i)=>a(`FIN008.${s}`,'FIN008',['Very clearly','Mostly clearly','I know some of it','I do not have a clear picture','Not sure'][i],{kind:'deferred',key:'financial_visibility'})),
...planning('FIN009','financial_fit',[["01",'Keep it quick and manageable','quick'],["02",'Keep the effort low right now','low_effort'],["03",'Keep the cost very low','low_cost'],["04",'I may need help accessing information, accounts, or services','access_help'],["05",'I may need another person or professional involved','other_person_professional']]),a('FIN009.06','FIN009','No special limitation',{kind:'none'}),uncertain('FIN009','07'),
// Intellectual.
...ordinal('INT001','FOCUS_FUNCTION',[["01",'Never','never'],["02",'Rarely','rarely'],["03",'Sometimes','sometimes'],["04",'Often','often'],["05",'Almost always','almost_always']]),uncertain('INT001','06'),
...facet('INT002','FOCUS_FUNCTION','focus_impact',[["01",'Not at all','none',true],["02",'A little','little'],["03",'Somewhat','some'],["04",'Quite a bit','substantial'],["05",'Very much','very_high']]),uncertain('INT002','06'),
...context('INT003','focus_context',[["01",'I felt tired or low on energy','low_energy'],["02",'My sleep had been poor','poor_sleep'],["03",'I felt stressed or worried','stress'],["04",'I was not clear about what to do next','clarity'],["05",'Getting started was difficult','activation'],["06",'There were frequent demands, distractions, or interruptions','interruptions'],["07",'The place I was in made concentrating difficult','environment']]),a('INT003.08','INT003','Nothing specific stood out',{kind:'negative_context'}),a('INT003.09','INT003','Something else',{kind:'context',key:'focus_context',value:'other'}),uncertain('INT003','10'),
...planning('INT005','focus_fit',[["01",'I only have short blocks of uninterrupted time','short_blocks'],["02",'I cannot reliably control interruptions','interruptions'],["03",'My energy changes a lot during the day','energy_variability'],["04",'I do not have a reliable place to concentrate','no_reliable_place'],["05",'Getting started is harder than staying focused','activation_context']]),a('INT005.06','INT005','Nothing obvious',{kind:'none'}),uncertain('INT005','07'),
// Emotional: state, relationship context, duration/impact facets and Planning resources are distinct.
...ordinal('EMT001','PRESSURE_PATTERN',[["01",'Never','never'],["02",'Rarely','rarely'],["03",'Sometimes','sometimes'],["04",'Often','often'],["05",'Almost always','almost_always']]),uncertain('EMT001','06'),
...context('EMT002','stress_context',[["01",'Work or school demands','work_school'],["02",'Money or financial pressure','financial'],["03",'Conflict or difficulty with other people','relationship'],["04",'Feeling alone or unsupported','support_loneliness'],["05",'Problems at home or in my surroundings','home_surroundings'],["06",'Health, pain, sleep, or low energy','physical_cluster']]),a('EMT002.07','EMT002','No specific situation consistently stood out',{kind:'negative_context',key:'stress_context'}),a('EMT002.08','EMT002','Something else',{kind:'context',key:'stress_context',value:'other'}),uncertain('EMT002','09'),
...facet('EMT003','PRESSURE_PATTERN','stress_duration',[["01",'Less than 2 weeks','lt_2_weeks'],["02",'2–4 weeks','2_4_weeks'],["03",'1–3 months','1_3_months'],["04",'More than 3 months','gt_3_months']]),a('EMT003.05','EMT003','They are not noticeably affecting daily life',{kind:'negative_facet',constructId:'PRESSURE_PATTERN',key:'stress_functional_impact',value:'none_noticeable',cannotEraseState:true}),uncertain('EMT003','06'),
...facet('EMT004','PRESSURE_PATTERN','stress_impact',[["01",'Not at all','none',true],["02",'A little','little'],["03",'Somewhat','some'],["04",'Quite a bit','substantial'],["05",'Very much','very_high']]),uncertain('EMT004','06'),
...context('EMT005','coping_resource',[["01",'Rest or recovery time','rest_recovery'],["02",'Movement or time outside','movement_outside'],["03",'Talking with someone I trust','trusted_person'],["04",'More structure or fewer demands','structure_fewer_demands'],["05",'Quiet time, reflection, or a calming practice','quiet_reflection']]),a('EMT005.06','EMT005','Something else',{kind:'planning_resource',key:'coping_resource',value:'other'}),a('EMT005.07','EMT005','Nothing clearly helped',{kind:'planning_context',key:'coping_resource',value:'none_clear'}),uncertain('EMT005','08'),
// Environmental: interference, factor identity, Safety context, housing stability and feasibility stay separate.
...ordinal('ENV001','ENVIRONMENTAL_INTERFERENCE',[["01",'Never','never'],["02",'Rarely','rarely'],["03",'Sometimes','sometimes'],["04",'Often','often'],["05",'Almost always','almost_always']]),uncertain('ENV001','06'),
...context('ENV002','environment_factor',[["01",'Noise or frequent interruptions','noise_interruptions'],["02",'Not enough privacy','privacy'],["03",'Not enough usable space or too much crowding','crowding_space'],["04",'Temperature, air quality, smoke, dampness, or similar physical conditions','physical_conditions'],["05",'Accessibility or difficulty using the space','accessibility'],["06",'Transportation or location makes important activities difficult','transport_location'],["07",'Conflict or tension with people I live with','household_relationship']]),a('ENV002.08','ENV002','Uncertainty about being able to stay where I live',{kind:'routing',constructId:'HOUSING_STABILITY',value:'clarify'}),a('ENV002.09','ENV002','Something else',{kind:'context',key:'environment_factor',value:'other'}),a('ENV002.10','ENV002','None of these',{kind:'negative_context',key:'environment_factor'}),uncertain('ENV002','11'),
a('ENV003.01','ENV003','Yes',{kind:'safety_context',key:'contextual_safety_home',value:'safe',cannotClearOtherEvidence:true}),a('ENV003.02','ENV003','Mostly',{kind:'safety_context',key:'contextual_safety_home',value:'mostly_safe'}),a('ENV003.03','ENV003','No',{kind:'safety_trigger',key:'contextual_safety_home',value:'not_physically_safe',requiresImmediacyClarification:true}),a('ENV003.04','ENV003','Not sure',{kind:'safety_uncertain',key:'contextual_safety_home'}),a('ENV003.05','ENV003','I prefer not to answer',{kind:'nonresponse',key:'contextual_safety_home',cannotInferDanger:true}),
...ordinal('ENV004','HOUSING_STABILITY',[["01",'I expect to be able to stay here','expected_secure'],["02",'There is some uncertainty','some_uncertainty'],["03",'I may have to leave or lose this housing','may_lose_housing'],["04",'This is temporary housing','temporary_housing']]),uncertain('ENV004','05'),a('ENV004.06','ENV004','Not applicable',{kind:'not_applicable'}),
a('ENV005.01','ENV005','A lot',{kind:'planning_context',key:'environment_changeability',value:'high'}),a('ENV005.02','ENV005','Some of it',{kind:'planning_context',key:'environment_changeability',value:'some'}),a('ENV005.03','ENV005','Very little',{kind:'planning_constraint',key:'environment_changeability',value:'very_little'}),a('ENV005.04','ENV005','None right now',{kind:'planning_constraint',key:'environment_changeability',value:'none',notEvidenceInsufficiency:true}),uncertain('ENV005','05'),
// Remaining domains are retained only where already fully represented; next reconciliation pass replaces these with exhaustive tab-derived semantics.
...ordinal('SOC001','RELATIONSHIP_STRAIN',[["01",'Never','never'],["02",'Rarely','rarely'],["03",'Sometimes','sometimes'],["04",'Often','often'],["05",'Almost always','almost_always']]),...ordinal('SOC101','LONELINESS',[["01",'Never','never'],["02",'Rarely','rarely'],["03",'Sometimes','sometimes'],["04",'Often','often'],["05",'Almost always','almost_always']]),...ordinal('SPT001','DIRECTION_CLARITY',[["01",'Very clear','very_clear'],["02",'Mostly clear','mostly_clear'],["03",'Somewhat clear','somewhat_clear'],["04",'Not very clear','not_very_clear'],["05",'Not clear at all','not_clear']]),...ordinal('SPT002','MEANING_PURPOSE',[["01",'Very much','very_strong'],["02",'Quite a bit','strong'],["03",'Somewhat','moderate'],["04",'A little','low'],["05",'Not at all','absent']]),
]);
export const ANSWER_BY_ID=Object.freeze(Object.fromEntries(ANSWER_BANK.map(x=>[x.id,x])));export const ANSWERS_BY_QUESTION=Object.freeze(Object.fromEntries([...new Set(ANSWER_BANK.map(x=>x.parentId))].map(id=>[id,Object.freeze(ANSWER_BANK.filter(x=>x.parentId===id))])));export function assertUniqueAnswerIds(){if(Object.keys(ANSWER_BY_ID).length!==ANSWER_BANK.length)throw new Error('Duplicate governed Discovery answer ID');return true;}export default ANSWER_BANK;
