// Reconstructed non-General/non-Safety Discovery answer semantics.
// Temporary implementation module imported only by answerBank.js; retire after exhaustive Drive reconstruction.
const a=(id,parentId,text,effect)=>Object.freeze({id,parentId,text,effect:Object.freeze(effect)});
const ordinal=(p,c,rows)=>rows.map(([s,t,v])=>a(`${p}.${s}`,p,t,{kind:'state',constructId:c,value:v}));
const facet=(p,c,k,rows)=>rows.map(([s,t,v,negative=false])=>a(`${p}.${s}`,p,t,{kind:negative?'negative_facet':'facet',constructId:c,key:k,value:v,...(negative?{cannotEraseState:true}:{})}));
const context=(p,k,rows)=>rows.map(([s,t,v])=>a(`${p}.${s}`,p,t,{kind:'context',key:k,value:v}));
const planning=(p,k,rows)=>rows.map(([s,t,v])=>a(`${p}.${s}`,p,t,{kind:'planning_constraint',key:k,value:v}));
const uncertain=(p,s,t='Not sure')=>a(`${p}.${s}`,p,t,{kind:'uncertain'});
export const DOMAIN_ANSWER_BANK=Object.freeze([
...ordinal('FIN001','FINANCIAL_STRAIN',[["01",'Never','never'],["02",'Rarely','rarely'],["03",'Sometimes','sometimes'],["04",'Often','often'],["05",'Almost always','almost_always']]),uncertain('FIN001','06'),
...ordinal('INT001','FOCUS_FUNCTION',[["01",'Never','never'],["02",'Rarely','rarely'],["03",'Sometimes','sometimes'],["04",'Often','often'],["05",'Almost always','almost_always']]),uncertain('INT001','06'),
...ordinal('EMT001','PRESSURE_PATTERN',[["01",'Never','never'],["02",'Rarely','rarely'],["03",'Sometimes','sometimes'],["04",'Often','often'],["05",'Almost always','almost_always']]),uncertain('EMT001','06'),
...ordinal('ENV001','ENVIRONMENTAL_INTERFERENCE',[["01",'Never','never'],["02",'Rarely','rarely'],["03",'Sometimes','sometimes'],["04",'Often','often'],["05",'Almost always','almost_always']]),uncertain('ENV001','06'),
...ordinal('PHY200','SLEEP_QUALITY',[["01",'Very well','very_well'],["02",'Okay','okay'],["03",'Not great','not_great'],["04",'Really struggling','really_struggling']]),uncertain('PHY200','05'),
...ordinal('PHY300','ENERGY_FUNCTION',[["01",'Very well','very_well'],["02",'Okay','okay'],["03",'Not great','not_great'],["04",'Really struggling','really_struggling']]),uncertain('PHY300','05'),
...ordinal('PHY400','ACTIVITY_LEVEL',[["01",'6–7 days','6_7_days'],["02",'3–5 days','3_5_days'],["03",'1–2 days','1_2_days'],["04",'0 days','0_days']]),uncertain('PHY400','05'),
...context('OCC001','occupational_context',[["01",'Work or finding work','work'],["02",'School, training, or finding training','school'],["03",'Both work and school or training','both'],["04",'I don’t currently have a job','no_current_job']]),a('OCC001.05','OCC001','Something else',{kind:'unclassified_context'}),uncertain('OCC001','06'),
...ordinal('OCC002','JOB_SECURITY',[["01",'Stable and expected to continue','stable'],["02",'Mostly stable, with some uncertainty','some_uncertainty'],["03",'Hours, role, work, or schooling are uncertain','unstable'],["04",'I do not currently have work or school and want it','absent_wanted']]),a('OCC002.05','OCC002','I am not working or in school by choice right now',{kind:'context',key:'occupational_status',value:'not_participating_by_choice'}),a('OCC002.06','OCC002','Not applicable to me right now',{kind:'not_applicable'}),
...facet('OCC003','JOB_SECURITY','stability_worry',[["01",'Never','never',true],["02",'Rarely','rarely'],["03",'Sometimes','sometimes'],["04",'Often','often']]),a('OCC003.05','OCC003','Not applicable',{kind:'not_applicable'}),
...context('OCC004','occupational_contributor',[["01",'I do not currently have work','no_current_work'],["02",'I am not currently in the school or training I want','not_in_desired_training'],["03",'Uncertainty about whether my current situation will continue','continuation_uncertainty'],["04",'Hours or schedule','hours_schedule'],["05",'More demands than I can reasonably keep up with','excessive_demands'],["06",'Unclear expectations or responsibilities','unclear_expectations'],["07",'Too little control over how or when I do it','low_control'],["08",'Too little opportunity to use or develop my skills','limited_skill_development'],["09",'Conflict or difficult relationships there','relationship_conflict'],["10",'It does not fit what I want from it','poor_fit']]),a('OCC004.11','OCC004','Something else',{kind:'unclassified_context'}),a('OCC004.12','OCC004','Nothing major',{kind:'negative_context',key:'occupational_contributor'}),uncertain('OCC004','13'),
...facet('OCC005','JOB_SECURITY','occupational_role_interference',[["01",'Never','never',true],["02",'Rarely','rarely'],["03",'Sometimes','sometimes'],["04",'Often','often']]),a('OCC005.05','OCC005','Not applicable',{kind:'not_applicable'}),
...planning('OCC006','occupational_fit',[["01",'Time or schedule','time_schedule'],["02",'Income or cost makes changing difficult','income_cost'],["03",'Transportation or location','transport_location'],["04",'Caregiving or family responsibilities','caregiving_family'],["05",'Skills, credentials, or experience requirements','skills_credentials'],["06",'Health, energy, or accessibility','health_energy_accessibility'],["07",'Not enough suitable opportunities available','opportunity_availability'],["08",'Something else','other']]),a('OCC006.09','OCC006','Nothing obvious',{kind:'none'}),uncertain('OCC006','10'),
...context('OCC007','no_income_driver',[["01",'I am actively looking, but have not found a suitable opportunity yet','active_search'],["02",'I am not currently looking for work','not_looking'],["03",'Health, energy, or accessibility is limiting what I can do','health_energy_accessibility'],["04",'Caregiving or family responsibilities','caregiving_family'],["05",'Transportation or location','transport_location'],["06",'Skills, credentials, or experience requirements','skills_credentials'],["07",'Schedule or availability','schedule_availability'],["08",'I am waiting for a job, start date, decision, or another expected source of income','waiting_expected_income'],["09",'I am trying to build self-employment or another source of income instead','self_employment']]),a('OCC007.10','OCC007','Something else',{kind:'unclassified_context'}),uncertain('OCC007','11','I am not sure'),
a('OCC100.01','OCC100','A lot',{kind:'planning_resource',key:'schedule_control',value:'high',cannotEraseState:true}),a('OCC100.02','OCC100','Some',{kind:'planning_context',key:'schedule_control',value:'some'}),a('OCC100.03','OCC100','A little',{kind:'planning_constraint',key:'schedule_control',value:'low'}),a('OCC100.04','OCC100','Almost none',{kind:'planning_constraint',key:'schedule_control',value:'very_low'}),a('OCC100.05','OCC100','Not applicable',{kind:'not_applicable'}),
a('OCC101.01','OCC101','Never',{kind:'negative_facet',constructId:'SCHEDULE_DISRUPTION',key:'routine_interference',value:'never',cannotEraseState:true}),...ordinal('OCC101','SCHEDULE_DISRUPTION',[["02",'Once','once'],["03",'A few days','few_days'],["04",'Most days','most_days']]),a('OCC101.05','OCC101','Not applicable',{kind:'not_applicable'}),
...ordinal('SOC001','RELATIONSHIP_STRAIN',[["01",'Never','never'],["02",'Rarely','rarely'],["03",'Sometimes','sometimes'],["04",'Often','often'],["05",'Almost always','almost_always']]),a('SOC001.06','SOC001','Not applicable',{kind:'not_applicable'}),uncertain('SOC001','07'),
...facet('SOC002','RELATIONSHIP_STRAIN','relationship_impact',[["01",'Not at all','none',true],["02",'A little','little'],["03",'Somewhat','some'],["04",'A lot','high']]),a('SOC002.05','SOC002','Not applicable',{kind:'not_applicable'}),uncertain('SOC002','06'),
...context('SOC003','relationship_driver',[["01",'Conflict or arguments','conflict_arguments'],["02",'Communication problems','communication'],["03",'Trust concerns','trust'],["04",'Distance or not enough time together','distance_time'],["05",'Not feeling supported','feeling_unsupported'],["06",'Boundaries or expectations','boundaries_expectations']]),a('SOC003.07','SOC003','Something else',{kind:'unclassified_context'}),a('SOC003.08','SOC003','Nothing major',{kind:'negative_context',key:'relationship_driver'}),uncertain('SOC003','09'),
a('SOC004.01','SOC004','The other person may not want to participate',{kind:'planning_constraint',key:'relationship_fit',value:'other_person_unwilling'}),a('SOC004.02','SOC004','Direct contact or confrontation would not feel safe or appropriate',{kind:'safety_constraint',key:'relationship_contact',value:'unsafe_or_inappropriate'}),a('SOC004.03','SOC004','Distance or limited contact',{kind:'planning_constraint',key:'relationship_fit',value:'distance_limited_contact'}),a('SOC004.04','SOC004','Limited time or conflicting schedules',{kind:'planning_constraint',key:'relationship_fit',value:'time_schedule'}),a('SOC004.05','SOC004','I need to maintain distance or boundaries',{kind:'preference',key:'relationship_boundary',value:'maintain_distance'}),a('SOC004.06','SOC004','I do not want to change this relationship right now',{kind:'preference',key:'relationship_change',value:'declined'}),a('SOC004.07','SOC004','No obvious limitation',{kind:'none'}),uncertain('SOC004','08'),
...ordinal('SOC100','SUPPORT_AVAILABILITY',[["01",'Yes, reliably','reliable'],["02",'Probably, but not reliably','unreliable'],["03",'Not really','not_really']]),a('SOC100.04','SOC100','I would rather not seek support right now',{kind:'preference',key:'support_seeking',value:'declined'}),uncertain('SOC100','05'),
...ordinal('SOC101','LONELINESS',[["01",'Never','never'],["02",'Rarely','rarely'],["03",'Sometimes','sometimes'],["04",'Often','often'],["05",'Almost always','almost_always']]),uncertain('SOC101','06'),
...context('SOC102','desired_support',[["01",'Someone who will listen or understand','emotional_listening'],["02",'Practical help with something','practical_help'],["03",'Advice or useful information','advice_information'],["04",'Someone to spend time or do things with','companionship'],["05",'Feeling included in a group or community','belonging']]),a('SOC102.06','SOC102','I do not need more support or connection right now',{kind:'preference',key:'desired_support',value:'none_now',cannotEraseState:true}),uncertain('SOC102','07'),
...planning('SOC103','support_access',[["01",'The people I would turn to are not available','people_unavailable'],["02",'I do not feel comfortable opening up','opening_up'],["03",'Time or schedule','time_schedule'],["04",'Distance, transportation, mobility, or access','distance_access'],["05",'I do not have much energy for social effort','low_energy_context'],["06",'Conflict or tension makes contact difficult','conflict_tension'],["07",'I prefer more time alone right now','prefer_alone']]),a('SOC103.08','SOC103','Nothing obvious',{kind:'none'}),uncertain('SOC103','09'),
...ordinal('SPT001','DIRECTION_CLARITY',[["01",'Very clear','very_clear'],["02",'Mostly clear','mostly_clear'],["03",'Somewhat clear','somewhat_clear'],["04",'Not very clear','not_very_clear'],["05",'Not clear at all','not_clear']]),uncertain('SPT001','06'),
...ordinal('SPT002','MEANING_PURPOSE',[["01",'Very much','very_strong'],["02",'Quite a bit','strong'],["03",'Somewhat','moderate'],["04",'A little','low'],["05",'Not at all','absent']]),uncertain('SPT002','06'),
a('SPT003.01','SPT003','I am unsure what deserves my attention now',{kind:'discriminator',constructId:'DIRECTION_CLARITY',key:'direction_type',value:'present_priority',noAdditiveSeverity:true}),a('SPT003.02','SPT003','I am unsure what I want to work toward longer term',{kind:'discriminator',constructId:'DIRECTION_CLARITY',key:'direction_type',value:'long_term_goal',noAdditiveSeverity:true}),a('SPT003.03','SPT003','My daily life does not feel very meaningful or worthwhile',{kind:'routing',constructId:'MEANING_PURPOSE',value:'clarify'}),a('SPT003.04','SPT003','I am unsure what matters most to me when making choices',{kind:'routing',constructId:'VALUES_CLARITY',value:'clarify'}),a('SPT003.05','SPT003','I know what matters, but I am unsure what next step to take',{kind:'routing',constructId:'NEXT_STEP_CLARITY',value:'clarify'}),a('SPT003.06','SPT003','Nothing feels notably unclear or missing',{kind:'negative_discriminator',key:'direction_meaning_values_next_step',cannotEraseState:true}),a('SPT003.07','SPT003','Something else',{kind:'unclassified_context'}),uncertain('SPT003','08'),
...planning('SPT004','purpose_action_fit',[["01",'Time or competing demands','time_demands'],["02",'Money or financial constraints','financial'],["03",'Low energy','energy'],["04",'Not enough support from people around me','support'],["05",'Difficulty getting started','activation_context'],["06",'I am not sure what action would fit','action_unclear'],["07",'Something else','other']]),a('SPT004.08','SPT004','Nothing obvious',{kind:'none'}),uncertain('SPT004','09'),
]);
export default DOMAIN_ANSWER_BANK;
