// Governed Emotional Discovery registry. Source: Drive 02.04.01 — Emotional.
const q=(id,o)=>Object.freeze({id,dimension:'Emotional',status:'conditional',reconciled:true,...o});
const a=(id,parentId,text,effect)=>Object.freeze({id,parentId,text,effect:Object.freeze(effect)});
const state=(p,c,rows)=>rows.map(([s,text,value])=>a(`${p}.${s}`,p,text,{kind:'state',constructId:c,value}));
const facet=(p,c,key,rows)=>rows.map(([s,text,value,negative=false])=>a(`${p}.${s}`,p,text,{kind:negative?'negative_facet':'facet',constructId:c,key,value,...(negative?{cannotEraseState:true}:{})}));
const ctx=(p,key,rows)=>rows.map(([s,text,value])=>a(`${p}.${s}`,p,text,{kind:'context',key,value}));
const u=(p,s,text='Not sure')=>a(`${p}.${s}`,p,text,{kind:'uncertain'});
export const QUESTIONS=Object.freeze([
q('EMT001',{text:'In the past 7 days, how often did you feel stressed or overwhelmed?',responseType:'single',role:'state-probe',construct:'Stress state',constructId:'PRESSURE_PATTERN',stage:'Adaptive state evidence',burden:.16}),
q('EMT002',{text:'In the past 7 days, when you felt stressed or overwhelmed, what was happening around those times? Select any that fit.',responseType:'multi',role:'discriminator',construct:'Stress context',constructId:'PRESSURE_PATTERN',stage:'Adaptive discrimination',burden:.2}),
q('EMT003',{text:'About how long have stress or difficult emotions been noticeably affecting your daily life?',responseType:'single',role:'deepening',construct:'Duration',constructId:'EMOTIONAL_STATE',stage:'Adaptive deepening',burden:.12}),
q('EMT004',{text:'In the past 7 days, how much did stress or difficult emotions interfere with your usual daily activities?',responseType:'single',role:'impact-probe',construct:'Stress impact',constructId:'EMOTIONAL_STATE',stage:'Adaptive deepening',burden:.14}),
q('EMT005',{text:'In the past 7 days, what, if anything, seemed to make stressful periods easier to handle? Select any that fit.',responseType:'multi',role:'support-probe',construct:'Existing supports',constructId:'EMOTIONAL_STATE',stage:'Adaptive Fit',burden:.12})]);
export const ANSWERS=Object.freeze([
...state('EMT001','PRESSURE_PATTERN',[['01','Never','never'],['02','Rarely','rarely'],['03','Sometimes','sometimes'],['04','Often','often'],['05','Almost always','almost_always']]),u('EMT001','06'),
...ctx('EMT002','stress_context',[['01','Work or school demands','work_school'],['02','Money or financial pressure','financial'],['03','Conflict or difficulty with other people','relationship'],['04','Feeling alone or unsupported','support_loneliness'],['05','Problems at home or in my surroundings','home_surroundings'],['06','Health, pain, sleep, or low energy','physical_cluster']]),a('EMT002.07','EMT002','No specific situation consistently stood out',{kind:'negative_context',key:'stress_context',cannotEraseState:true}),a('EMT002.08','EMT002','Something else',{kind:'unclassified_context'}),u('EMT002','09'),
...facet('EMT003','EMOTIONAL_STATE','stress_duration',[['01','Less than 2 weeks','lt_2_weeks'],['02','2–4 weeks','2_4_weeks'],['03','1–3 months','1_3_months'],['04','More than 3 months','gt_3_months']]),a('EMT003.05','EMT003','They are not noticeably affecting daily life',{kind:'negative_facet',constructId:'EMOTIONAL_STATE',key:'stress_functional_impact',value:'none_noticeable',cannotEraseState:true}),u('EMT003','06'),
...facet('EMT004','EMOTIONAL_STATE','stress_impact',[['01','Not at all','none',true],['02','A little','little'],['03','Somewhat','some'],['04','Quite a bit','substantial'],['05','Very much','very_high']]),u('EMT004','06'),
...ctx('EMT005','coping_resource',[['01','Rest or recovery time','rest_recovery'],['02','Movement or time outside','movement_outside'],['03','Talking with someone I trust','trusted_person'],['04','More structure or fewer demands','structure_fewer_demands'],['05','Quiet time, reflection, or a calming practice','quiet_reflection']]),a('EMT005.06','EMT005','Something else',{kind:'planning_resource',key:'coping_resource',value:'other'}),a('EMT005.07','EMT005','Nothing clearly helped',{kind:'planning_context',key:'coping_resource',value:'none_clear'}),u('EMT005','08')]);
export default Object.freeze({questions:QUESTIONS,answers:ANSWERS});