// Governed Environmental Discovery registry. Source: Drive 02.04.01 — Environmental.
const q=(id,o)=>Object.freeze({id,dimension:'Environmental',status:'conditional',reconciled:true,...o});
const a=(id,parentId,text,effect)=>Object.freeze({id,parentId,text,effect:Object.freeze(effect)});
const state=(p,c,rows)=>rows.map(([s,text,value])=>a(`${p}.${s}`,p,text,{kind:'state',constructId:c,value}));
const u=(p,s,text='Not sure')=>a(`${p}.${s}`,p,text,{kind:'uncertain'});
export const QUESTIONS=Object.freeze([
q('ENV001',{text:'Over the past 7 days, how often did something about your home or immediate surroundings interfere with your usual daily activities?',responseType:'single',role:'state-probe',construct:'Home interference',constructId:'ENVIRONMENTAL_INTERFERENCE',stage:'Adaptive state evidence',burden:.18}),
q('ENV002',{text:'Which conditions, if any, seemed connected with times daily life was harder recently? Select any that fit.',responseType:'multi',role:'discriminator',construct:'Home conditions',constructId:'ENVIRONMENTAL_INTERFERENCE',stage:'Adaptive discrimination',burden:.2}),
q('ENV003',{text:'Do you currently feel physically safe where you live?',responseType:'single',role:'safety-probe',construct:'Home safety',stage:'Governed Safety clarification',burden:.2,status:'safety-governed'}),
q('ENV004',{text:'How secure is your current housing for the near future?',responseType:'single',role:'state-probe',construct:'Housing stability',constructId:'HOUSING_STABILITY',stage:'Adaptive state evidence',burden:.18}),
q('ENV005',{text:'For the environmental difficulty that matters most, how much can you realistically change yourself right now?',responseType:'single',role:'feasibility-probe',construct:'Environmental feasibility',stage:'Adaptive Fit',burden:.12})]);
export const ANSWERS=Object.freeze([
...state('ENV001','ENVIRONMENTAL_INTERFERENCE',[['01','Never','never'],['02','Rarely','rarely'],['03','Sometimes','sometimes'],['04','Often','often'],['05','Almost always','almost_always']]),u('ENV001','06'),
...['01|Noise or frequent interruptions|noise_interruptions','02|Not enough privacy|privacy','03|Not enough usable space or too much crowding|crowding_space','04|Temperature, air quality, smoke, dampness, or similar physical conditions|physical_conditions','05|Accessibility or difficulty using the space|accessibility','06|Transportation or location makes important activities difficult|transport_location','07|Conflict or tension with people I live with|household_relationship','08|Uncertainty about being able to stay where I live|housing_stability_context'].map(x=>{const [s,text,value]=x.split('|');return a(`ENV002.${s}`,'ENV002',text,{kind:'context',key:'environment_factor',value});}),a('ENV002.09','ENV002','Something else',{kind:'unclassified_context'}),a('ENV002.10','ENV002','None of these',{kind:'negative_context',key:'environment_factor',cannotEraseState:true}),u('ENV002','11'),
a('ENV003.01','ENV003','Yes',{kind:'safety_context',key:'contextual_safety_home',value:'safe',cannotClearOtherEvidence:true}),a('ENV003.02','ENV003','Mostly',{kind:'safety_context',key:'contextual_safety_home',value:'mostly_safe'}),a('ENV003.03','ENV003','No',{kind:'safety_trigger',key:'contextual_safety_home',value:'not_physically_safe',requiresImmediacyClarification:true}),a('ENV003.04','ENV003','Not sure',{kind:'safety_uncertain',key:'contextual_safety_home'}),a('ENV003.05','ENV003','I prefer not to answer',{kind:'nonresponse',cannotInferDanger:true}),
...state('ENV004','HOUSING_STABILITY',[['01','I expect to be able to stay here','expected_secure'],['02','There is some uncertainty','some_uncertainty'],['03','I may have to leave or lose this housing','may_lose_housing'],['04','This is temporary housing','temporary_housing']]),u('ENV004','05'),a('ENV004.06','ENV004','Not applicable',{kind:'not_applicable'}),
a('ENV005.01','ENV005','A lot',{kind:'planning_context',key:'environment_changeability',value:'high'}),a('ENV005.02','ENV005','Some of it',{kind:'planning_context',key:'environment_changeability',value:'some'}),a('ENV005.03','ENV005','Very little',{kind:'planning_constraint',key:'environment_changeability',value:'very_little'}),a('ENV005.04','ENV005','None right now',{kind:'planning_constraint',key:'environment_changeability',value:'none',notEvidenceInsufficiency:true}),u('ENV005','05')]);
export default Object.freeze({questions:QUESTIONS,answers:ANSWERS});