// Reconciled General + Safety answer semantics from Drive 02.04.01.
// Temporary split during registry reconstruction; merge into answerBank.js at final normalization.
const a=(id,parentId,text,effect)=>Object.freeze({id,parentId,text,effect:Object.freeze(effect)});
const routing=(id,p,text,value)=>a(id,p,text,{kind:'routing',value,noDirectSeverity:true});
const neutral=(id,p,text,kind='context')=>a(id,p,text,{kind});
export const GENERAL_SAFETY_ANSWER_BANK=Object.freeze([
// GEN001 orientation: routing/salience only.
routing('GEN001.01','GEN001','Money or financial pressure','financial'),routing('GEN001.02','GEN001','Work, school, or responsibilities','occupational'),routing('GEN001.03','GEN001','Health or physical condition','physical_condition'),routing('GEN001.04','GEN001','Low energy or tiredness','energy'),routing('GEN001.05','GEN001','Sleep','sleep'),routing('GEN001.06','GEN001','Stress or difficult emotions','emotional'),routing('GEN001.07','GEN001','Relationships','relationships'),routing('GEN001.08','GEN001','Feeling lonely or unsupported','social_support_loneliness'),routing('GEN001.09','GEN001','Home or surroundings','environmental'),routing('GEN001.10','GEN001','Focus or getting started','focus_activation'),routing('GEN001.11','GEN001','Direction, purpose, or knowing what to do next','direction_meaning_next_step'),a('GEN001.12','GEN001','Something else',{kind:'unclassified_context'}),a('GEN001.13','GEN001','I’m generally doing well',{kind:'positive_path'}),a('GEN001.14','GEN001','I’m not sure',{kind:'uncertain'}),
// Deferred broad orientation.
...['Too much to do or not enough time','Low energy or poor sleep','Stress or difficult emotions','Money pressure','Relationship or people problems','Difficulty getting started'].map((t,i)=>a(`GEN010.0${i+1}`,'GEN010',t,{kind:'driver_context',noDirectSeverity:true})),neutral('GEN010.07','GEN010','Nothing consistently stands out','none'),neutral('GEN010.08','GEN010','Not sure','uncertain'),
...['Mostly structured and predictable','Busy, with a lot to juggle','It changed a lot from day to day','Mostly unstructured'].map((t,i)=>a(`GEN011.0${i+1}`,'GEN011',t,{kind:'planning_context',key:'routine_structure',noDirectSeverity:true})),neutral('GEN011.05','GEN011','Not sure','uncertain'),
...['People I care about','Making progress toward something','Fun, hobbies or things I enjoy','Responsibilities or people depending on me','Purpose, values or something bigger than me'].map((t,i)=>a(`GEN012.0${i+1}`,'GEN012',t,{kind:'protective_resource',cannotEraseState:true})),neutral('GEN012.06','GEN012','I’m not sure right now','uncertain'),
// Positive path.
...['Help me keep what is working','Help me improve something that is already okay','Help me make progress toward a goal','Help me understand my patterns over time','Help me explore what I might want to work on','I do not need EL8 to work on anything right now'].map((t,i)=>a(`GEN100.0${i+1}`,'GEN100',t,{kind:'positive_goal',value:i+1,noWellnessScore:true})),neutral('GEN100.07','GEN100','Not sure yet','uncertain'),
...['My health, energy, or routines','Relationships or support','Work, school, or responsibilities','Money or financial stability','Home or daily environment','Learning, growth, direction, or purpose','Something else'].map((t,i)=>a(`GEN101.0${i+1}`,'GEN101',t,{kind:'positive_strength',cannotEraseState:true})),neutral('GEN101.08','GEN101','Not sure','uncertain'),
// Priority/salience and relationship discriminators never establish severity.
...['Less money pressure','Work or school feeling steadier','Sleeping better','Having more energy','Relationships or support improving','Feeling less stressed','Home or surroundings feeling easier','Feeling clearer about what to do next'].map((t,i)=>a(`GEN200.0${i+1}`,'GEN200',t,{kind:'priority_salience',noDirectSeverity:true})),neutral('GEN200.09','GEN200','Not sure','uncertain'),
a('GEN201.01','GEN201','Mostly circumstances or events in my life',{kind:'context_hypothesis',value:'circumstances'}),a('GEN201.02','GEN201','Mostly how I have been feeling or functioning',{kind:'context_hypothesis',value:'functioning'}),a('GEN201.03','GEN201','A mix of both',{kind:'context_hypothesis',value:'mixed'}),neutral('GEN201.04','GEN201','Not sure','uncertain'),
...['Sleep','Energy','Mood or stress','Focus','Getting started','Money decisions','Relationships','Daily routine'].map((t,i)=>a(`GEN202.0${i+1}`,'GEN202',t,{kind:'interaction_hypothesis',value:t,noCausality:true,noDirectSeverity:true})),neutral('GEN202.09','GEN202','Not sure','uncertain'),
...['Money','Work or school','Relationships or support','Health, sleep, or energy','Home or surroundings','Future plans or direction'].map((t,i)=>a(`GEN204.0${i+1}`,'GEN204',t,{kind:'recent_salience',value:t,noDirectSeverity:true})),neutral('GEN204.07','GEN204','Nothing in particular','none'),neutral('GEN204.08','GEN204','Not sure','uncertain'),
// Correction/control semantics.
a('GEN300.01','GEN300','My earlier answer was closer',{kind:'correction',preference:'earlier'}),a('GEN300.02','GEN300','My newer answer is closer',{kind:'correction',preference:'newer'}),a('GEN300.03','GEN300','Both are accurate in different situations',{kind:'correction',preference:'context_dependent'}),neutral('GEN300.04','GEN300','I’m not sure','uncertain'),
a('GEN301.01','GEN301','No',{kind:'correction',value:'no_misclassification'}),
...['work','money','relationships','support','home','direction'].map((v,i)=>a(`GEN301.0${i+2}`,'GEN301',`Yes — it is not mainly ${v}`,{kind:'scope_priority_correction',value:v,cannotEraseState:true})),neutral('GEN301.08','GEN301','Not sure','uncertain'),a('GEN301.09','GEN301','Yes — it is not mainly my physical health or condition',{kind:'scope_priority_correction',value:'physical_condition',cannotEraseState:true}),a('GEN301.10','GEN301','Yes — it is not mainly my energy',{kind:'scope_priority_correction',value:'energy',cannotEraseState:true}),a('GEN301.11','GEN301','Yes — it is not mainly my sleep',{kind:'scope_priority_correction',value:'sleep',cannotEraseState:true}),a('GEN301.12','GEN301','Yes — it is not mainly stress or difficult emotions',{kind:'scope_priority_correction',value:'emotional',cannotEraseState:true}),a('GEN301.13','GEN301','Yes — it is not mainly focus or concentration',{kind:'scope_priority_correction',value:'focus',cannotEraseState:true}),
a('GEN400.01','GEN400','No',{kind:'functional_impact_context',value:'none',cannotEraseState:true}),a('GEN400.02','GEN400','Yes, but only a little',{kind:'functional_impact_context',value:'minor'}),a('GEN400.03','GEN400','Yes, clearly',{kind:'functional_impact_context',value:'clear'}),neutral('GEN400.04','GEN400','Not sure','uncertain'),
a('GEN401.01','GEN401','Yes',{kind:'manageability_context',value:'manageable_without_help',cannotEraseState:true}),a('GEN401.02','GEN401','Some do and some do not',{kind:'manageability_context',value:'mixed'}),a('GEN401.03','GEN401','No',{kind:'manageability_context',value:'additional_help_useful'}),neutral('GEN401.04','GEN401','Not sure','uncertain'),
a('GEN900.01','GEN900','Yes, this is accurate enough',{kind:'handoff_control',value:'accepted'}),a('GEN900.02','GEN900','Not quite — I need to change something',{kind:'handoff_control',value:'targeted_correction'}),a('GEN900.03','GEN900','I’m not sure yet',{kind:'handoff_control',value:'uncertain'}),a('GEN901.01','GEN901','Yes',{kind:'member_control',value:'continue'}),a('GEN901.02','GEN901','Not right now',{kind:'member_control',value:'pause',noWellnessEvidence:true}),
// Safety remains design-only and categorical. No answer independently clears an activated Safety concern.
a('SFT000.01','SFT000','Yes',{kind:'safety_state',value:'immediate_danger_affirmed',designOnly:true,decisionCritical:true}),a('SFT000.02','SFT000','No',{kind:'safety_state',value:'immediate_danger_not_affirmed',designOnly:true,cannotClearSafety:true}),a('SFT000.03','SFT000','I’m not sure',{kind:'safety_uncertainty',designOnly:true,decisionCritical:true}),a('SFT000.04','SFT000','I prefer not to answer',{kind:'safety_uncertainty',value:'declined',designOnly:true,cannotClearSafety:true}),
a('SFT001.01','SFT001','Yes',{kind:'safety_state',value:'current_intent_affirmed',designOnly:true,decisionCritical:true}),a('SFT001.02','SFT001','I’m having thoughts, but I do not intend to act on them',{kind:'safety_state',value:'current_thoughts_without_stated_intent',designOnly:true,decisionCritical:true}),a('SFT001.03','SFT001','No',{kind:'safety_state',value:'current_intent_not_affirmed',designOnly:true,cannotClearSafety:true}),a('SFT001.04','SFT001','I’m not sure',{kind:'safety_uncertainty',designOnly:true,decisionCritical:true}),a('SFT001.05','SFT001','I prefer not to answer',{kind:'safety_uncertainty',value:'declined',designOnly:true,cannotClearSafety:true}),
a('SFT002.01','SFT002','Yes',{kind:'safety_state',value:'reports_able_to_stay_safe',designOnly:true,cannotClearSafety:true}),a('SFT002.02','SFT002','No',{kind:'safety_state',value:'reports_unable_to_stay_safe',designOnly:true,decisionCritical:true}),a('SFT002.03','SFT002','I’m not sure',{kind:'safety_uncertainty',designOnly:true,decisionCritical:true}),a('SFT002.04','SFT002','I prefer not to answer',{kind:'safety_uncertainty',value:'declined',designOnly:true,cannotClearSafety:true}),
]);
export const GENERAL_SAFETY_ANSWER_BY_ID=Object.freeze(Object.fromEntries(GENERAL_SAFETY_ANSWER_BANK.map(x=>[x.id,x])));
export default GENERAL_SAFETY_ANSWER_BANK;
