// Governed General Discovery registry. Source authority: Drive 02.04.01 — General.
const q=(id,text,responseType,role,o={})=>Object.freeze({id,text,responseType,role,dimension:'General',status:'conditional',reconciled:true,...o});
const a=(id,parentId,text,effect,o={})=>Object.freeze({id,parentId,text,effect:Object.freeze(effect),...o});
const options=(p,key,texts,kind='context')=>texts.map((text,i)=>a(`${p}.${String(i+1).padStart(2,'0')}`,p,text,{kind,key,value:String(i+1),noDirectSeverity:true}));
const unsure=(p,s,text='Not sure')=>a(`${p}.${s}`,p,text,{kind:'uncertain'});
export const QUESTIONS=Object.freeze([
q('GEN001','Thinking about your life lately, what has been bothering you or making things harder? Select any that fit.','multi','general',{status:'active',burden:.3}),
q('GEN010','Thinking about recent difficult days, what has most often made the day harder?','single','orientation',{status:'deferred',burden:.14}),q('GEN011','Thinking about the past 7 days, which best describes your day-to-day routine?','single','orientation',{status:'deferred',burden:.12}),q('GEN012','When life has been going well, what has most helped you keep going?','single','orientation',{burden:.12}),
q('GEN100','It sounds like things are generally going okay. What would make EL8 most useful to you right now?','single','goal-probe',{burden:.1}),q('GEN101','What is working well that you would most want to protect or build on?','single','strength-probe',{burden:.1}),
q('GEN200','If one thing improved over the next 7 days, which change would help your daily life most?','single','discriminator',{burden:.3}),q('GEN201','Which best describes what seems connected to daily life feeling harder right now?','single','discriminator',{burden:.2}),q('GEN202','When this issue affects you, which area do you usually notice changing first?','single','discriminator',{burden:.25}),q('GEN204','Thinking about the past 7 days, which area have you spent the most time worrying about or trying to deal with?','single','discriminator',{burden:.25}),
q('GEN300','Your answers point in different directions. Which option best describes what you mean?','single','contradiction',{burden:.18}),q('GEN301','Did EL8 misunderstand which area is making daily life harder?','single','correction',{burden:.18}),q('GEN400','Thinking about the past 7 days, has anything made it meaningfully harder to do your usual daily activities?','single','healthy-verification',{burden:.14}),q('GEN401','Do the issues you selected feel manageable without additional help right now?','single','healthy-verification',{burden:.14}),q('GEN900','Before we move on, does this feel like an accurate enough picture of what you want EL8 to work from?','single','handoff-validation',{burden:.08}),q('GEN901','Do you want to answer more questions about this right now?','single','opt-out',{status:'member-controlled',burden:.08})]);
export const ANSWERS=Object.freeze([
a('GEN001.01','GEN001','Money or financial pressure',{kind:'routing_prior',route:'Financial',noDirectSeverity:true}),a('GEN001.02','GEN001','Work, school, or responsibilities',{kind:'routing_prior',route:'Occupational',noDirectSeverity:true}),a('GEN001.03','GEN001','Health or physical condition',{kind:'routing_prior',route:'PHYSICAL_CONDITION',noDirectSeverity:true}),a('GEN001.04','GEN001','Low energy or tiredness',{kind:'routing_prior',route:'ENERGY_FUNCTION',noDirectSeverity:true}),a('GEN001.05','GEN001','Sleep',{kind:'routing_prior',route:'SLEEP_QUALITY',noDirectSeverity:true}),a('GEN001.06','GEN001','Stress or difficult emotions',{kind:'routing_prior',route:'PRESSURE_PATTERN',noDirectSeverity:true}),a('GEN001.07','GEN001','Relationships',{kind:'routing_prior',route:'RELATIONSHIP_STRAIN',noDirectSeverity:true}),a('GEN001.08','GEN001','Feeling lonely or unsupported',{kind:'routing_prior',route:'social_support_loneliness',noDirectSeverity:true}),a('GEN001.09','GEN001','Home or surroundings',{kind:'routing_prior',route:'Environmental',noDirectSeverity:true}),a('GEN001.10','GEN001','Focus or getting started',{kind:'routing_prior',route:'focus_activation',noDirectSeverity:true}),a('GEN001.11','GEN001','Direction, purpose, or knowing what to do next',{kind:'routing_prior',route:'direction_meaning_next_step',noDirectSeverity:true}),a('GEN001.12','GEN001','Something else',{kind:'unclassified'}),a('GEN001.13','GEN001','I’m generally doing well',{kind:'positive_path'}),a('GEN001.14','GEN001','I’m not sure',{kind:'uncertain_start'}),
...options('GEN010','difficult_day_driver',['Too much to do or not enough time','Low energy or poor sleep','Stress or difficult emotions','Money pressure','Relationship or people problems','Difficulty getting started','Nothing consistently stands out']),unsure('GEN010','08'),
...options('GEN011','routine_context',['Mostly structured and predictable','Busy, with a lot to juggle','It changed a lot from day to day','Mostly unstructured']),unsure('GEN011','05'),
...options('GEN012','protective_resource',['People I care about','Making progress toward something','Fun, hobbies or things I enjoy','Responsibilities or people depending on me','Purpose, values or something bigger than me']),a('GEN012.06','GEN012','I’m not sure right now',{kind:'uncertain'}),
...options('GEN100','positive_goal',['Help me keep what is working','Help me improve something that is already okay','Help me make progress toward a goal','Help me understand my patterns over time','Help me explore what I might want to work on','I do not need EL8 to work on anything right now'],'preference'),a('GEN100.07','GEN100','Not sure yet',{kind:'uncertain'}),
...options('GEN101','positive_strength_area',['My health, energy, or routines','Relationships or support','Work, school, or responsibilities','Money or financial stability','Home or daily environment','Learning, growth, direction, or purpose','Something else'],'resource'),unsure('GEN101','08'),
...options('GEN200','priority_salience',['Less money pressure','Work or school feeling steadier','Sleeping better','Having more energy','Relationships or support improving','Feeling less stressed','Home or surroundings feeling easier','Feeling clearer about what to do next'],'priority'),unsure('GEN200','09'),
...options('GEN201','context_hypothesis',['Mostly circumstances or events in my life','Mostly how I have been feeling or functioning','A mix of both'],'relationship_hypothesis'),unsure('GEN201','04'),
...options('GEN202','interaction_hypothesis',['Sleep','Energy','Mood or stress','Focus','Getting started','Money decisions','Relationships','Daily routine'],'relationship_hypothesis'),unsure('GEN202','09'),
...options('GEN204','recent_salience',['Money','Work or school','Relationships or support','Health, sleep, or energy','Home or surroundings','Future plans or direction','Nothing in particular'],'priority'),unsure('GEN204','08'),
...options('GEN300','correction',['My earlier answer was closer','My newer answer is closer','Both are accurate in different situations'],'correction'),a('GEN300.04','GEN300','I’m not sure',{kind:'uncertain'}),
a('GEN301.01','GEN301','No',{kind:'correction',value:'no_change'}),...['Yes — it is not mainly work','Yes — it is not mainly money','Yes — it is not mainly relationships','Yes — it is not mainly support','Yes — it is not mainly home','Yes — it is not mainly direction'].map((text,i)=>a(`GEN301.0${i+2}`,'GEN301',text,{kind:'scope_priority_correction',value:['work','money','relationships','support','home','direction'][i],cannotEraseState:true})),a('GEN301.08','GEN301','Not sure',{kind:'uncertain'}),...['Yes — it is not mainly my physical health or condition','Yes — it is not mainly my energy','Yes — it is not mainly my sleep','Yes — it is not mainly stress or difficult emotions','Yes — it is not mainly focus or concentration'].map((text,i)=>a(`GEN301.${String(i+9).padStart(2,'0')}`,'GEN301',text,{kind:'scope_priority_correction',value:['physical_condition','energy','sleep','stress_emotions','focus'][i],cannotEraseState:true},{status:'design-only'})),
a('GEN400.01','GEN400','No',{kind:'negative_function_evidence',cannotEraseState:true}),a('GEN400.02','GEN400','Yes, but only a little',{kind:'functional_impact_context',value:'little'}),a('GEN400.03','GEN400','Yes, clearly',{kind:'functional_impact_context',value:'clear'}),unsure('GEN400','04'),
a('GEN401.01','GEN401','Yes',{kind:'planning_context',key:'manageability',value:'manageable'}),a('GEN401.02','GEN401','Some do and some do not',{kind:'planning_context',key:'manageability',value:'mixed'}),a('GEN401.03','GEN401','No',{kind:'planning_context',key:'manageability',value:'additional_help_may_be_useful'}),unsure('GEN401','04'),
a('GEN900.01','GEN900','Yes, this is accurate enough',{kind:'handoff_confirmation',value:'accepted'}),a('GEN900.02','GEN900','Not quite — I need to change something',{kind:'handoff_control',value:'targeted_correction'}),a('GEN900.03','GEN900','I’m not sure yet',{kind:'handoff_control',value:'uncertain'}),a('GEN901.01','GEN901','Yes',{kind:'continuation_preference',value:'continue'}),a('GEN901.02','GEN901','Not right now',{kind:'opt_out',value:'pause_stop'})]);
export default Object.freeze({questions:QUESTIONS,answers:ANSWERS});