// Governed Intellectual Discovery registry. Source: Drive 02.04.01 — Intellectual.
const q=(id,o)=>Object.freeze({id,dimension:'Intellectual',status:'conditional',reconciled:true,...o});
const a=(id,parentId,text,effect)=>Object.freeze({id,parentId,text,effect:Object.freeze(effect)});
const state=(p,c,rows)=>rows.map(([s,text,value])=>a(`${p}.${s}`,p,text,{kind:'state',constructId:c,value}));
const u=(p,s,text='Not sure')=>a(`${p}.${s}`,p,text,{kind:'uncertain'});
export const QUESTIONS=Object.freeze([
q('INT001',{text:'Thinking about the past 7 days, how often was it hard to stay focused on something you needed or wanted to do?',responseType:'single',role:'state-probe',construct:'Focus state',constructId:'FOCUS_FUNCTION',stage:'State',burden:.16}),
q('INT002',{text:'Thinking about the past 7 days, how much did difficulty focusing interfere with things that mattered to you?',responseType:'single',role:'impact-probe',construct:'Focus impact',constructId:'FOCUS_FUNCTION',stage:'Deepening',burden:.18}),
q('INT003',{text:'When focusing was difficult in the past 7 days, what did you notice around those times? Select any that fit.',responseType:'multi',role:'discriminator',construct:'Focus contributors',stage:'Discrimination',burden:.2}),
q('INT004',{text:'Thinking about the past 7 days, how often did you have a chance to do something that kept your mind interested or engaged?',responseType:'single',role:'engagement-probe',construct:'Cognitive engagement',stage:'Deferred',burden:.1,status:'deferred'}),
q('INT005',{text:'If you wanted to make focusing easier right now, what would need to be taken into account? Select any that fit.',responseType:'multi',role:'feasibility-probe',construct:'Focus feasibility',stage:'Fit',burden:.11})]);
export const ANSWERS=Object.freeze([
...state('INT001','FOCUS_FUNCTION',[['01','Never','never'],['02','Rarely','rarely'],['03','Sometimes','sometimes'],['04','Often','often'],['05','Almost always','almost_always']]),u('INT001','06'),
...[['01','Not at all','none',true],['02','A little','little'],['03','Somewhat','some'],['04','Quite a bit','substantial'],['05','Very much','very_high']].map(([s,text,value,negative=false])=>a(`INT002.${s}`,'INT002',text,{kind:negative?'negative_facet':'facet',constructId:'FOCUS_FUNCTION',key:'focus_impact',value,...(negative?{cannotEraseState:true}:{})})),u('INT002','06'),
...[['01','I felt tired or low on energy','low_energy'],['02','My sleep had been poor','poor_sleep'],['03','I felt stressed or worried','stress_worry'],['04','I was not clear about what to do next','next_step_unclear'],['05','Getting started was difficult','activation_difficulty'],['06','There were frequent demands, distractions, or interruptions','demands_interruptions'],['07','The place I was in made concentrating difficult','environment']].map(([s,text,value])=>a(`INT003.${s}`,'INT003',text,{kind:'context',key:'focus_context',value})),a('INT003.08','INT003','Nothing specific stood out',{kind:'negative_context',key:'focus_context',cannotEraseState:true}),a('INT003.09','INT003','Something else',{kind:'unclassified_context'}),u('INT003','10'),
...['01|Never','02|Rarely','03|Sometimes','04|Often','05|Almost always'].map(x=>{const [s,text]=x.split('|');return a(`INT004.${s}`,'INT004',text,{kind:'deferred_candidate',key:'cognitive_engagement_opportunity',noDirectEvidence:true});}),a('INT004.06','INT004','Not sure',{kind:'deferred_candidate',key:'cognitive_engagement_opportunity',uncertain:true,noDirectEvidence:true}),
...[['01','I only have short blocks of uninterrupted time','short_blocks'],['02','I cannot reliably control interruptions','uncontrolled_interruptions'],['03','My energy changes a lot during the day','energy_variability'],['04','I do not have a reliable place to concentrate','no_reliable_place'],['05','Getting started is harder than staying focused','activation_context']].map(([s,text,value])=>a(`INT005.${s}`,'INT005',text,{kind:'planning_constraint',key:'focus_fit',value})),a('INT005.06','INT005','Nothing obvious',{kind:'none'}),u('INT005','07')]);
export default Object.freeze({questions:QUESTIONS,answers:ANSWERS});