// Governed Occupational Discovery registry. Source authority: Drive 02.04.01 — Occupational.
const q=(id,text,responseType,role,o={})=>Object.freeze({id,text,responseType,role,dimension:'Occupational',status:'conditional',reconciled:true,...o});
const a=(id,p,text,effect)=>Object.freeze({id,parentId:p,text,effect:Object.freeze(effect)});
const u=(p,s)=>a(`${p}.${s}`,p,'Not sure',{kind:'uncertain'});
const context=(p,key,rows)=>rows.map(([s,text,value,kind='context'])=>a(`${p}.${s}`,p,text,{kind,key,value,noDirectSeverity:true}));
export const QUESTIONS=Object.freeze([
q('OCC001','Which situation are you mainly talking about?','single','discriminator',{burden:.1}),q('OCC002','Which best describes your work or school situation right now?','single','state-probe',{constructId:'JOB_SECURITY',burden:.16}),q('OCC003','In the past 4 weeks, how often did you worry about losing work, hours, a role, or another important source of work or school stability?','single','state-probe',{constructId:'JOB_SECURITY',burden:.18}),q('OCC004','What seems connected to the work, school, or training difficulty you are experiencing right now? Select any that fit.','multi','discriminator',{burden:.2}),q('OCC005','In the past 4 weeks, how often did work, school, training, or related responsibilities interfere with the time or energy you needed elsewhere?','single','impact-probe',{burden:.16}),q('OCC006','What could limit your ability to improve your work, school, or training situation right now? Select any that fit.','multi','feasibility-probe',{burden:.12}),q('OCC007','Because you said you currently have no income, what factors are contributing to that right now? Select any that apply.','multi','driver-discriminator',{burden:.12}),q('OCC100','How much control do you usually have over when you work, study, or handle your main daily responsibilities?','single','control-probe',{burden:.16}),q('OCC101','In the past 7 days, how often did your schedule interfere with sleep, regular meals, or another routine that matters to you?','single','impact-probe',{constructId:'SCHEDULE_DISRUPTION',burden:.16})]);
export const ANSWERS=Object.freeze([
...context('OCC001','occupational_context',[["01",'Work or finding work','work'],["02",'School, training, or finding training','school_training'],["03",'Both work and school or training','both'],["04",'I don’t currently have a job','no_current_job'],["05",'Something else','other','unclassified_context']]),u('OCC001','06'),
...['Stable and expected to continue','Mostly stable, with some uncertainty','Hours, role, work, or schooling are uncertain','I do not currently have work or school and want it'].map((text,i)=>a(`OCC002.0${i+1}`,'OCC002',text,{kind:'state',constructId:'JOB_SECURITY',value:['stable','some_uncertainty','unstable','absent_wanted'][i]})),a('OCC002.05','OCC002','I am not working or in school by choice right now',{kind:'context',key:'occupational_context',value:'not_participating_by_choice',noDirectSeverity:true}),a('OCC002.06','OCC002','Not applicable to me right now',{kind:'not_applicable'}),
...['Never','Rarely','Sometimes','Often'].map((text,i)=>a(`OCC003.0${i+1}`,'OCC003',text,{kind:i===0?'negative_facet':'facet',constructId:'JOB_SECURITY',key:'stability_worry',value:['never','rarely','sometimes','often'][i],noAdditiveState:true,...(i===0?{cannotEraseState:true}:{})})),a('OCC003.05','OCC003','Not applicable',{kind:'not_applicable'}),
...context('OCC004','occupational_contributor',[["01",'I do not currently have work','no_current_work'],["02",'I am not currently in the school or training I want','not_in_desired_school_training'],["03",'Uncertainty about whether my current situation will continue','continuation_uncertainty'],["04",'Hours or schedule','hours_schedule'],["05",'More demands than I can reasonably keep up with','excessive_demands'],["06",'Unclear expectations or responsibilities','unclear_expectations'],["07",'Too little control over how or when I do it','low_control'],["08",'Too little opportunity to use or develop my skills','limited_skill_development'],["09",'Conflict or difficult relationships there','work_school_relationship_conflict'],["10",'It does not fit what I want from it','poor_role_fit'],["11",'Something else','other','unclassified_context'],["12",'Nothing major','nothing_major','negative_context']]),u('OCC004','13'),
...['Never','Rarely','Sometimes','Often'].map((text,i)=>a(`OCC005.0${i+1}`,'OCC005',text,{kind:i===0?'negative_context':'context',key:'occupational_role_interference',value:['never','rarely','sometimes','often'][i],noDirectSeverity:true,...(i===0?{cannotEraseState:true}:{})})),a('OCC005.05','OCC005','Not applicable',{kind:'not_applicable'}),
...context('OCC006','occupational_fit',[["01",'Time or schedule','time_schedule','planning_constraint'],["02",'Income or cost makes changing difficult','income_cost','planning_constraint'],["03",'Transportation or location','transport_location','planning_constraint'],["04",'Caregiving or family responsibilities','caregiving_family','planning_constraint'],["05",'Skills, credentials, or experience requirements','skills_credentials_experience','planning_constraint'],["06",'Health, energy, or accessibility','health_energy_accessibility','planning_constraint'],["07",'Not enough suitable opportunities available','limited_opportunities','planning_constraint'],["08",'Something else','other','unclassified_context'],["09",'Nothing obvious','nothing_obvious','planning_context']]),u('OCC006','10'),
...context('OCC007','no_income_driver',[["01",'I am actively looking, but have not found a suitable opportunity yet','active_search_no_suitable_opportunity'],["02",'I am not currently looking for work','not_currently_looking'],["03",'Health, energy, or accessibility is limiting what I can do','health_energy_accessibility_constraint','planning_constraint'],["04",'Caregiving or family responsibilities','caregiving_family_constraint','planning_constraint'],["05",'Transportation or location','transport_location_constraint','planning_constraint'],["06",'Skills, credentials, or experience requirements','skills_credentials_experience_constraint','planning_constraint'],["07",'Schedule or availability','schedule_availability_constraint','planning_constraint'],["08",'I am waiting for a job, start date, decision, or another expected source of income','waiting_expected_income'],["09",'I am trying to build self-employment or another source of income instead','building_alternative_income'],["10",'Something else','other','unclassified_context']]),u('OCC007','11'),
...['A lot','Some','A little','Almost none'].map((text,i)=>a(`OCC100.0${i+1}`,'OCC100',text,{kind:i<2?'planning_context':'planning_constraint',key:'schedule_control',value:['high','some','low','very_low'][i],noDirectSeverity:true})),a('OCC100.05','OCC100','Not applicable',{kind:'not_applicable'}),
a('OCC101.01','OCC101','Never',{kind:'negative_facet',constructId:'SCHEDULE_DISRUPTION',key:'routine_interference',value:'never',cannotEraseState:true}),...['Once','A few days','Most days'].map((text,i)=>a(`OCC101.0${i+2}`,'OCC101',text,{kind:'state',constructId:'SCHEDULE_DISRUPTION',value:['once','few_days','most_days'][i]})),a('OCC101.05','OCC101','Not applicable',{kind:'not_applicable'})]);
export default Object.freeze({questions:QUESTIONS,answers:ANSWERS});