// Governed Occupational Discovery registry. Source: Drive 02.04.01 — Occupational.
const q=(id,text,responseType,role,o={})=>Object.freeze({id,text,responseType,role,dimension:'Occupational',status:'conditional',reconciled:true,...o}); const a=(id,p,text,effect)=>Object.freeze({id,parentId:p,text,effect:Object.freeze(effect)}); const u=(p,s)=>a(`${p}.${s}`,p,'Not sure',{kind:'uncertain'});
export const QUESTIONS=Object.freeze([q('OCC001','Which situation are you mainly talking about?','single','discriminator',{burden:.1}),q('OCC002','Which best describes your work or school situation right now?','single','state-probe',{constructId:'JOB_SECURITY',burden:.16}),q('OCC003','In the past 4 weeks, how often did you worry about losing work, hours, a role, or another important source of work or school stability?','single','state-probe',{burden:.18}),q('OCC004','What seems connected to the work, school, or training difficulty you are experiencing right now? Select any that fit.','multi','discriminator',{burden:.2}),q('OCC005','In the past 4 weeks, how often did work, school, training, or related responsibilities interfere with the time or energy you needed elsewhere?','single','impact-probe',{burden:.16}),q('OCC006','What could limit your ability to improve your work, school, or training situation right now? Select any that fit.','multi','feasibility-probe',{burden:.12}),q('OCC007','Because you said you currently have no income, what factors are contributing to that right now? Select any that apply.','multi','driver-discriminator',{burden:.12}),q('OCC100','How much control do you usually have over when you work, study, or handle your main daily responsibilities?','single','control-probe',{burden:.16}),q('OCC101','In the past 7 days, how often did your schedule interfere with sleep, regular meals, or another routine that matters to you?','single','impact-probe',{constructId:'SCHEDULE_DISRUPTION',burden:.16})]);
const rows=(p,key,texts)=>texts.map((text,i)=>a(`${p}.${String(i+1).padStart(2,'0')}`,p,text,{kind:'context',key,value:String(i+1)}));
export const ANSWERS=Object.freeze([
...rows('OCC001','occupational_context',['Work or finding work','School, training, or finding training','Both work and school or training','I don’t currently have a job','Something else']),u('OCC001','06'),
...['Stable and expected to continue','Mostly stable, with some uncertainty','Hours, role, work, or schooling are uncertain','I do not currently have work or school and want it'].map((text,i)=>a(`OCC002.0${i+1}`,'OCC002',text,{kind:'state',constructId:'JOB_SECURITY',value:['stable','some_uncertainty','unstable','absent_wanted'][i]})),a('OCC002.05','OCC002','I am not working or in school by choice right now',{kind:'context',key:'occupational_context',value:'not_participating_by_choice'}),a('OCC002.06','OCC002','Not applicable to me right now',{kind:'not_applicable'}),
...['Never','Rarely','Sometimes','Often'].map((text,i)=>a(`OCC003.0${i+1}`,'OCC003',text,{kind:i===0?'negative_facet':'facet',constructId:'JOB_SECURITY',key:'stability_worry',value:['never','rarely','sometimes','often'][i],...(i===0?{cannotEraseState:true}:{})})),a('OCC003.05','OCC003','Not applicable',{kind:'not_applicable'}),
...rows('OCC004','occupational_contributor',['I do not currently have work','I am not currently in the school or training I want','Uncertainty about whether my current situation will continue','Hours or schedule','More demands than I can reasonably keep up with','Unclear expectations or responsibilities','Too little control over how or when I do it','Too little opportunity to use or develop my skills','Conflict or difficult relationships there','It does not fit what I want from it','Something else','Nothing major']),u('OCC004','13'),
...['Never','Rarely','Sometimes','Often'].map((text,i)=>a(`OCC005.0${i+1}`,'OCC005',text,{kind:i===0?'negative_facet':'facet',key:'occupational_role_interference',value:['never','rarely','sometimes','often'][i],...(i===0?{cannotEraseState:true}:{})})),a('OCC005.05','OCC005','Not applicable',{kind:'not_applicable'}),
...rows('OCC006','occupational_fit',['Time or schedule','Income or cost makes changing difficult','Transportation or location','Caregiving or family responsibilities','Skills, credentials, or experience requirements','Health, energy, or accessibility','Not enough suitable opportunities available','Something else','Nothing obvious']),u('OCC006','10'),
...rows('OCC007','no_income_driver',['I am actively looking, but have not found a suitable opportunity yet','I am not currently looking for work','Health, energy, or accessibility is limiting what I can do','Caregiving or family responsibilities','Transportation or location','Skills, credentials, or experience requirements','Schedule or availability','I am waiting for a job, start date, decision, or another expected source of income','I am trying to build self-employment or another source of income instead','Something else']),u('OCC007','11'),
...['A lot','Some','A little','Almost none'].map((text,i)=>a(`OCC100.0${i+1}`,'OCC100',text,{kind:i<2?'planning_context':'planning_constraint',key:'schedule_control',value:['high','some','low','very_low'][i]})),a('OCC100.05','OCC100','Not applicable',{kind:'not_applicable'}),
a('OCC101.01','OCC101','Never',{kind:'negative_facet',constructId:'SCHEDULE_DISRUPTION',key:'routine_interference',value:'never',cannotEraseState:true}),...['Once','A few days','Most days'].map((text,i)=>a(`OCC101.0${i+2}`,'OCC101',text,{kind:'state',constructId:'SCHEDULE_DISRUPTION',value:['once','few_days','most_days'][i]})),a('OCC101.05','OCC101','Not applicable',{kind:'not_applicable'})]); export default Object.freeze({questions:QUESTIONS,answers:ANSWERS});