// Governed Social Discovery registry. Source: Drive 02.04.01 — Social.
const q=(id,o)=>Object.freeze({id,dimension:'Social',status:'conditional',reconciled:true,...o});
const a=(id,parentId,text,effect)=>Object.freeze({id,parentId,text,effect:Object.freeze(effect)});
const state=(p,c,rows)=>rows.map(([s,text,value])=>a(`${p}.${s}`,p,text,{kind:'state',constructId:c,value}));
const ctx=(p,key,rows)=>rows.map(([s,text,value])=>a(`${p}.${s}`,p,text,{kind:'context',key,value}));
const plan=(p,key,rows)=>rows.map(([s,text,value])=>a(`${p}.${s}`,p,text,{kind:'planning_constraint',key,value}));
const u=(p,s,text='Not sure')=>a(`${p}.${s}`,p,text,{kind:'uncertain'});
export const QUESTIONS=Object.freeze([
q('SOC001',{text:'During the past 7 days, how often did tension or conflict in a close relationship bother you?',responseType:'single',role:'state-probe',constructId:'RELATIONSHIP_STRAIN',burden:.16}),q('SOC002',{text:'During the past 7 days, how much did relationship problems interfere with your usual activities or ability to focus?',responseType:'single',role:'impact-probe',burden:.16}),q('SOC003',{text:'What has been difficult in your close relationships lately? Select any that fit.',responseType:'multi',role:'discriminator',burden:.2}),q('SOC004',{text:'If you wanted to improve or protect a relationship, what would EL8 need to account for? Select any that fit.',responseType:'multi',role:'feasibility-probe',burden:.11}),q('SOC100',{text:'If you needed emotional support right now, is there someone you could turn to?',responseType:'single',role:'state-probe',constructId:'SUPPORT_AVAILABILITY',burden:.14}),q('SOC101',{text:'During the past 7 days, how often did you feel isolated or disconnected from other people?',responseType:'single',role:'state-probe',constructId:'LONELINESS',burden:.16}),q('SOC102',{text:'What kind of support or connection would be most useful right now?',responseType:'single',role:'discriminator',burden:.18}),q('SOC103',{text:'Which things, if any, currently limit access to support or social connection? Select any that fit.',responseType:'multi',role:'feasibility-probe',burden:.11})]);
export const ANSWERS=Object.freeze([
...state('SOC001','RELATIONSHIP_STRAIN',[['01','Never','never'],['02','Rarely','rarely'],['03','Sometimes','sometimes'],['04','Often','often'],['05','Almost always','almost_always']]),a('SOC001.06','SOC001','Not applicable',{kind:'not_applicable'}),u('SOC001','07'),
...['Not at all','A little','Somewhat','A lot'].map((text,i)=>a(`SOC002.0${i+1}`,'SOC002',text,{kind:i===0?'negative_facet':'facet',constructId:'RELATIONSHIP_STRAIN',key:'relationship_impact',value:['none','little','some','high'][i],...(i===0?{cannotEraseState:true}:{})})),a('SOC002.05','SOC002','Not applicable',{kind:'not_applicable'}),u('SOC002','06'),
...ctx('SOC003','relationship_driver',[['01','Conflict or arguments','conflict_arguments'],['02','Communication problems','communication'],['03','Trust concerns','trust'],['04','Distance or not enough time together','distance_time'],['05','Not feeling supported','feeling_unsupported'],['06','Boundaries or expectations','boundaries_expectations'],['07','Something else','other'],['08','Nothing major','none']]),u('SOC003','09'),
...plan('SOC004','relationship_fit',[['01','The other person may not want to participate','other_person_unwilling'],['02','Direct contact or confrontation would not feel safe or appropriate','unsafe_or_inappropriate_contact'],['03','Distance or limited contact','distance_limited_contact'],['04','Limited time or conflicting schedules','time_schedule'],['05','I need to maintain distance or boundaries','maintain_distance'],['06','I do not want to change this relationship right now','declined'],['07','No obvious limitation','none']]),u('SOC004','08'),
...state('SOC100','SUPPORT_AVAILABILITY',[['01','Yes, reliably','reliable'],['02','Probably, but not reliably','unreliable'],['03','Not really','not_really']]),a('SOC100.04','SOC100','I would rather not seek support right now',{kind:'preference',key:'support_seeking',value:'declined'}),u('SOC100','05'),
...state('SOC101','LONELINESS',[['01','Never','never'],['02','Rarely','rarely'],['03','Sometimes','sometimes'],['04','Often','often'],['05','Almost always','almost_always']]),u('SOC101','06'),
...ctx('SOC102','desired_support',[['01','Someone who will listen or understand','emotional_listening'],['02','Practical help with something','practical_help'],['03','Advice or useful information','advice_information'],['04','Someone to spend time or do things with','companionship'],['05','Feeling included in a group or community','belonging'],['06','I do not need more support or connection right now','none_now']]),u('SOC102','07'),
...plan('SOC103','support_access',[['01','The people I would turn to are not available','people_unavailable'],['02','I do not feel comfortable opening up','opening_up'],['03','Time or schedule','time_schedule'],['04','Distance, transportation, mobility, or access','distance_access'],['05','I do not have much energy for social effort','low_energy_context'],['06','Conflict or tension makes contact difficult','conflict_tension'],['07','I prefer more time alone right now','prefer_alone'],['08','Nothing obvious','none']]),u('SOC103','09')]);
export default Object.freeze({questions:QUESTIONS,answers:ANSWERS});