import assert from 'node:assert/strict';
import test from 'node:test';
import {createDiscoverySession,nextDiscoveryStep,setResolution,deriveStates,requestDiscoveryStop,CONCERN_RESOLUTION} from './discovery-controller.js';

const orientation=(id,priority)=>({id,role:'orientation',openingPriority:priority,options:[]});
const gateway={id:'G1',role:'gateway',gatewayEligible:true,options:[]};
const positive={id:'PTH1',role:'goal-probe',path:'positive',decisionCritical:true,options:[]};
const ordinary={id:'C1',role:'driver-probe',concernId:'c1',addressesUnresolvedUncertainty:true,options:[]};

test('explicit orientation limit is bounded and uses opening priority rather than bank order',()=>{const bank=[orientation('low',1),orientation('high',100),orientation('middle',50),gateway];const session=createDiscoverySession({questionBank:bank,orientationLimit:2});const first=nextDiscoveryStep(session);const second=nextDiscoveryStep(session);const third=nextDiscoveryStep(session);assert.equal(first.question.id,'high');assert.equal(second.question.id,'middle');assert.equal(session.asked.includes('low'),false);assert.equal(third.question.id,'G1');assert.equal(third.reason,'gateway-candidate');assert.equal(session.questionsAsked,3)});
test('zero orientation limit permits sequence research without locking an opening format',()=>{const session=createDiscoverySession({questionBank:[orientation('matrix',100),gateway],orientationLimit:0});const step=nextDiscoveryStep(session);assert.equal(step.question.id,'G1');assert.equal(session.asked.includes('matrix'),false)});
test('gateway is not mandatory unless explicitly eligible',()=>{const session=createDiscoverySession({questionBank:[orientation('opening',100),{...gateway,gatewayEligible:false}],orientationLimit:0});const step=nextDiscoveryStep(session);assert.equal(step.type,'finish');assert.equal(step.stop.reason,'no-material-concern-established');assert.equal(step.stop.incomplete,true)});
test('new concerns begin unresolved rather than in a process-state label',()=>{const session=createDiscoverySession({concernIds:['c1'],questionBank:[],orientationLimit:0});assert.equal(deriveStates(session)[0].resolutionState,CONCERN_RESOLUTION.UNRESOLVED)});
test('dismissed concern reaches positive goal path before ordinary sufficiency closes Discovery',()=>{const session=createDiscoverySession({concernIds:['c1'],questionBank:[positive],orientationLimit:0});setResolution(session,'c1',CONCERN_RESOLUTION.DISMISSED);const step=nextDiscoveryStep(session);assert.equal(step.type,'question');assert.equal(step.question.id,'PTH1');assert.equal(step.reason,'positive-goal-path')});
test('unresolved concern is not treated as a positive-path dismissal',()=>{const session=createDiscoverySession({concernIds:['c1'],questionBank:[positive,ordinary],orientationLimit:0});const step=nextDiscoveryStep(session);assert.notEqual(step.reason,'positive-goal-path');assert.notEqual(step.question?.id,'PTH1')});
test('established concern satisfies concern resolution for handoff',()=>{const session=createDiscoverySession({concernIds:['c1'],questionBank:[],orientationLimit:0});setResolution(session,'c1',CONCERN_RESOLUTION.ESTABLISHED);const step=nextDiscoveryStep(session);assert.equal(step.type,'finish');assert.equal(step.stop.reason,'sufficient-coverage');assert.equal(step.stop.incomplete,false)});
test('legacy and session-level labels cannot masquerade as concern resolutions',()=>{const session=createDiscoverySession({concernIds:['c1']});for(const legacy of ['triaged','nonIssue','deferred'])assert.throws(()=>setResolution(session,'c1',legacy),/invalid concern resolution state/)});
test('member can stop Discovery without falsely resolving an open concern',()=>{const session=createDiscoverySession({concernIds:['c1'],questionBank:[ordinary],orientationLimit:0});requestDiscoveryStop(session);const step=nextDiscoveryStep(session);assert.equal(step.type,'finish');assert.equal(step.stop.reason,'member-stopped');assert.equal(step.stop.incomplete,true);assert.deepEqual(step.stop.defer,['c1']);assert.equal(deriveStates(session)[0].resolutionState,CONCERN_RESOLUTION.UNRESOLVED)});
test('outer guardrail remains an explicit research bound for unresolved traversal',()=>{const session=createDiscoverySession({concernIds:['c1'],questionBank:[ordinary],orientationLimit:0,outerGuardrail:0});const step=nextDiscoveryStep(session);assert.equal(step.type,'finish');assert.equal(step.stop.reason,'outer-guardrail');assert.equal(step.stop.incomplete,true)});
