import assert from 'node:assert/strict';
import * as discovery from './discovery-engine.js';
import {deriveConcernState} from './concern-projection.js';
import {makeObservation} from './contracts.js';
import {DISCOVERY_BANK,observationsForAnswer} from './question-bank-adapter.js';
import {createDiscoverySession,nextDiscoveryStep,discoveryOutput} from '../../app/onboarding/discovery-runtime.js';
assert.equal(discovery.DISCOVERY_VERSION,'v4');const runtime=discovery.session({concernIds:[]});assert.ok(runtime);assert.equal(runtime.version,'v4');assert.equal(typeof discovery.next(runtime),'object');assert.equal(typeof discovery.trace(runtime),'object');const portSession=createDiscoverySession({concernIds:[]});assert.ok(portSession);assert.equal(typeof nextDiscoveryStep(portSession),'object');const proposal=discoveryOutput(portSession);assert.ok(proposal&&typeof proposal==='object');assert.ok('trace'in proposal);assert.equal('plan'in proposal,false,'Discovery browser output must not expose a Discovery-owned plan');
// Orientation is adaptive and bounded. The runtime must honor explicit orientation priority rather than bank order,
// and must not encode a specific opening format (including a matrix) as a permanent architectural invariant.
const broad=discovery.session({concernIds:[]});let broadStep=discovery.next(broad);assert.equal(broadStep.question.id,'O5');assert.equal(broadStep.question.role,'orientation');discovery.answer(broad,broadStep.question,'stability');broadStep=discovery.next(broad);assert.equal(broadStep.question.role,'orientation');assert.notEqual(broadStep.question.id,'O5');discovery.answer(broad,broadStep.question,'busy');broadStep=discovery.next(broad);assert.ok(broad.questionsAsked<=2,'default orientation should remain bounded');assert.ok(broad.concernIds.length>0,'orientation evidence should seed plausible concerns before deepening');assert.notEqual(broadStep.question?.id,'G1');assert.notEqual(broadStep.reason,'gateway');assert.equal(broad.phase,'deepen');
const once=createDiscoverySession({concernIds:['money_pressure','physical_condition','poor_sleep','low_focus']});once.phase='deepen';let step=nextDiscoveryStep(once);assert.equal(step.type,'triage');discovery.triage(once,{money_pressure:3,physical_condition:3,poor_sleep:1,low_focus:1});step=nextDiscoveryStep(once);assert.notEqual(step.type,'triage');assert.notEqual(step.type,'priority-resolution');
const fitObservation=makeObservation({id:'fit:1',questionId:'FIT1',concernId:'low_activity',effects:[{type:'feasibility',target:'low_activity',feasibility:{capacity:'low',scheduleFlexibility:'low'}},{type:'constraint',target:'low_activity',value:'limited_transport'},{type:'support',target:'low_activity',value:'partner_support'}]}),fitState=deriveConcernState([fitObservation],'low_activity');assert.equal(fitState.feasibility.values.capacity,'low');assert.equal(fitState.feasibility.values.scheduleFlexibility,'low');assert.deepEqual(fitState.feasibility.constraints,['limited_transport']);assert.deepEqual(fitState.feasibility.supports,['partner_support']);
const activityFitQuestion=DISCOVERY_BANK.find(q=>q.id==='PH1B'),activityFitObservations=observationsForAnswer(activityFitQuestion,['time','cost','mobility']),activityFitState=deriveConcernState(activityFitObservations,'energy');assert.equal(activityFitState.feasibility.values.scheduleFlexibility,'low');assert.equal(activityFitState.feasibility.values.costSensitivity,'high');assert.equal(activityFitState.feasibility.values.accessibilityNeeds,true);assert.ok(activityFitState.feasibility.constraints.includes('limited_time'));assert.ok(activityFitState.feasibility.constraints.includes('limited_budget'));assert.ok(activityFitState.feasibility.constraints.includes('mobility_accessibility'));
// Discovery owns evidence and feasibility projection, not final priority or intervention selection.
const output=discoveryOutput(createDiscoverySession({concernIds:['low_energy']}));for(const forbidden of ['plan','memberPlan','candidateActions','selectedActionIds','recommendedPriorities','confirmedPriorities','interventions'])assert.equal(forbidden in output,false,`Discovery output must not own ${forbidden}`);console.log('canonical Discovery v4 adaptive-orientation + onboarding boundary + feasibility regression tests passed');
