import assert from 'node:assert/strict';
import * as discovery from './discovery-engine.js';
import {deriveConstructState} from './construct-projection.js';
import {makeObservation} from './contracts.js';
import {DISCOVERY_BANK,observationsForAnswer,constructsForAnswer,safetyContextForAnswer} from './observationNormalizer.js';
import {createDiscoverySession,nextDiscoveryStep,answerDiscoveryQuestion,answerDiscoveryInteraction,discoveryOutput,discoveryPriorityCandidates} from '../../app/onboarding/discovery-runtime.js';

assert.equal(typeof discovery.version,'undefined');
assert.ok(DISCOVERY_BANK.some(q=>q.role==='baseline-discriminator'));
assert.equal(typeof discovery.relate,'undefined');
assert.equal(typeof discovery.skipRelationships,'undefined');

const opening=DISCOVERY_BANK.find(q=>q.id==='Q000001');
assert.ok(opening);assert.deepEqual(constructsForAnswer(opening,'A000001'),[]);assert.equal(observationsForAnswer(opening,'A000001',{timestamp:1})[0]?.effects.length,0);

const positive=createDiscoverySession({constructIds:[]});let matrix=nextDiscoveryStep(positive);assert.equal(matrix.type,'matrix');assert.equal(matrix.questions.length,8);let answers={};for(const q of matrix.questions)answers[q.id]=q.options.find(o=>o.text==='Going well')?.id;answerDiscoveryInteraction(positive,matrix,answers);let step=nextDiscoveryStep(positive);assert.equal(step.type,'finish');assert.equal(step.stop.reason,'baseline-complete-no-active-concern');const positiveOutput=discoveryOutput(positive);for(const key of ['version','plan','memberPlan','selectedActions','priorityChoices'])assert.equal(key in positiveOutput.trace,false);

const narrowed=createDiscoverySession({constructIds:[]});matrix=nextDiscoveryStep(narrowed);answers={};for(const q of matrix.questions)answers[q.id]=q.options.find(o=>o.text==='Going well')?.id;const financial=matrix.questions.find(q=>String(q.dimension).toUpperCase()==='FINANCIAL');answers[financial.id]=financial.options.find(o=>o.text==='Difficult')?.id;answerDiscoveryInteraction(narrowed,matrix,answers);step=nextDiscoveryStep(narrowed);assert.equal(step.type,'question');assert.equal(step.interaction,'unified-canonical-driver-triage');assert.equal(step.question.id,'CANONICAL_DRIVER_TRIAGE');assert.equal(step.question.responseMode,'multi');const optionConstructIds=step.question.options.map(x=>x.constructId).filter(Boolean);assert.equal(new Set(optionConstructIds).size,optionConstructIds.length,'Q2 must expose each canonical driver at most once');assert.ok(step.question.options.some(x=>x.constructId==='FINANCIAL_STRAIN'&&x.text==='Financial strain'),'Financial driver must use the canonical construct label');for(const label of ['Not sure','None of these','Something else'])assert.ok(step.question.options.some(o=>o.text===label),`Q2 must retain ${label}`);const job=step.question.options.find(o=>o.constructId==='JOB_SECURITY');assert.ok(job);answerDiscoveryQuestion(narrowed,step.question,[job.id]);assert.ok(narrowed.constructIds.includes('JOB_SECURITY'));assert.equal(narrowed.driverKnown.JOB_SECURITY??false,false);
step=nextDiscoveryStep(narrowed);assert.ok(['driver-triage','question'].includes(step.type),'After Q2, member-facing Discovery must continue through graph triage or selective Deepen');if(step.type==='driver-triage'){assert.equal(step.interaction,'graph-driver-triage');assert.ok(step.questions.length>0);assert.ok(step.questions.every(q=>q.constructId&&q.options.some(o=>o.text==='Not sure')));const graphAnswers=Object.fromEntries(step.questions.map(q=>[q.id,q.options.find(o=>o.text==='Not sure').id]));answerDiscoveryInteraction(narrowed,step,graphAnswers);assert.ok(Object.keys(narrowed.driverSelections).length>0,'Graph driver triage must persist explicit dispositions')}

const severitySession=createDiscoverySession({constructIds:['ACTIVITY_LEVEL'],baselineCoverage:{PHYSICAL:{state:'difficult'}}});severitySession.phase='graph';severitySession.observationLog=[makeObservation({id:'obs:activity',questionId:'Q:test',constructId:'ACTIVITY_LEVEL',answerValue:'test',specificityLevel:3,timestamp:1,effects:[{type:'evidence',target:'ACTIVITY_LEVEL',polarity:'supports',strength:1,certainty:'definitive',sourceType:'direct',temporality:'current'}]})];let severityStep=nextDiscoveryStep(severitySession);while(severityStep.type==='driver-triage'&&severityStep.interaction==='graph-driver-triage'){answerDiscoveryInteraction(severitySession,severityStep,Object.fromEntries(severityStep.questions.map(q=>[q.id,'no'])));severityStep=nextDiscoveryStep(severitySession)}if(severityStep.type==='driver-triage'&&severityStep.interaction==='graph-severity-triage'){assert.ok(severityStep.questions.some(q=>q.constructId==='ACTIVITY_LEVEL'));answerDiscoveryInteraction(severitySession,severityStep,Object.fromEntries(severityStep.questions.map(q=>[q.id,'unsure'])));assert.equal(severitySession.severityResponses.ACTIVITY_LEVEL.memberReportedUnknown,true);const afterUnknown=nextDiscoveryStep(severitySession);assert.notEqual(afterUnknown.interaction,'graph-severity-triage','Explicit severity uncertainty must not loop')}

const safetyQuestion=DISCOVERY_BANK.find(q=>q.id==='Q000001');const unsafe=safetyContextForAnswer(safetyQuestion,'A000002');if(unsafe.requiresImmediacyClarification){const safetySession=createDiscoverySession({constructIds:[]});discovery.answer(safetySession,safetyQuestion,'A000002');assert.equal(discovery.next(safetySession).type,'safety')}

const observation=makeObservation({id:'obs:activity',questionId:'Q:test',constructId:'ACTIVITY_LEVEL',answerValue:'test',specificityLevel:3,timestamp:1,effects:[{type:'evidence',target:'ACTIVITY_LEVEL',polarity:'supports',strength:1,certainty:'definitive',sourceType:'direct',temporality:'current'},{type:'constraint',target:'ACTIVITY_LEVEL',key:'access',value:'limited_transport',sourceType:'direct',temporality:'current'},{type:'support',target:'ACTIVITY_LEVEL',key:'support',value:'partner_support',sourceType:'direct',temporality:'current'},{type:'feasibility',target:'ACTIVITY_LEVEL',feasibility:{capacity:'low',schedule:'low'},sourceType:'direct',temporality:'current'}]});const activity=deriveConstructState([observation],'ACTIVITY_LEVEL');assert.equal(activity.qualitativeConfidence,'WELL_SUPPORTED');assert.ok(activity.feasibility.constraints.includes('limited_transport'));assert.ok(activity.feasibility.supports.includes('partner_support'));

const candidateOutput={trace:{states:[{constructId:'FINANCIAL_STRAIN',qualitativeConfidence:'WELL_SUPPORTED',memberImportance:3,resolutionState:'triaged',evidenceRefs:['Q1']},{constructId:'PHYSICAL_CONDITION',qualitativeConfidence:'MODERATE',memberImportance:1,resolutionState:'triaged',evidenceRefs:['Q2']},{constructId:'ENERGY_FUNCTION',qualitativeConfidence:'LIMITED',memberImportance:3,resolutionState:'triaged',evidenceRefs:['Q3']} ]}};const candidates=discoveryPriorityCandidates(candidateOutput);assert.deepEqual(candidates.map(x=>x.constructId),['FINANCIAL_STRAIN','PHYSICAL_CONDITION']);assert.equal(candidates[0].label,'Financial strain');
console.log('Discovery runtime regression: orientation, canonical/deduplicated Q2 routing, graph driver/severity member interactions, explicit uncertainty, Safety, feasibility, and priority handoff are covered without legacy scheduler execution.');