import BANK,{observationsForAnswer} from './question-bank-adapter.js';
import {createDiscoverySession,appendObservation,nextDiscoveryStep,markTriaged,deriveStates,activateConcerns,setResolution,recordPriorityResolution,mergeFacts,DISCOVERY_VERSION} from './discovery-controller.js';
import {safetyGate} from '../safety/gate.js';
export function session(options={}){const s=createDiscoverySession({concernIds:options.concernIds??[],questionBank:options.questionBank??BANK,labels:options.labels??{},outerGuardrail:options.outerGuardrail??18,orientationLimit:options.orientationLimit??null,facts:options.facts??{}});s.assessmentStart=Date.now();s.questionTimings=[];s.safetyContextualSignals={...(options.safetyContextualSignals||{})};s.safetyConfirmation=options.safetyConfirmation||null;s.safety=safetyGate({stage:'discovery',contextualSignals:s.safetyContextualSignals,confirmation:s.safetyConfirmation,concernRefs:s.concernIds});return s}
export function setSafetyContext(s,contextualSignals={},confirmation=null){s.safetyContextualSignals={...(s.safetyContextualSignals||{}),...contextualSignals};if(confirmation!==undefined)s.safetyConfirmation=confirmation;const refs=(s.observationLog||[]).map(x=>x.id).filter(Boolean);s.safety=safetyGate({stage:'discovery',contextualSignals:s.safetyContextualSignals,confirmation:s.safetyConfirmation,observationRefs:refs,evidenceRefs:refs,concernRefs:s.concernIds});return s}
export function next(s){if(s.safety?.pauseOrdinaryFlow)return{type:'safety',safety:s.safety,states:deriveStates(s)};return nextDiscoveryStep(s)}
export function recordQuestionTiming(s,questionId,startedAt,completedAt=Date.now()){s.questionTimings.push({questionId,startedAt,completedAt,durationSeconds:Math.max(0,(completedAt-startedAt)/1000)});return s}
export function answer(s,question,answerIds){const ids=Array.isArray(answerIds)?answerIds:[answerIds],observations=observationsForAnswer(question,ids);if(['gateway','orientation'].includes(question.role))activateConcerns(s,[...new Set(observations.flatMap(o=>o.effects??[]).filter(e=>e.type==='evidence'&&e.polarity==='supports'&&e.strength>0).map(e=>e.target))]);for(const o of observations){if(['gateway','orientation'].includes(question.role)&&o.concernId&&!s.concernIds.includes(o.concernId))continue;appendObservation(s,o)}return setSafetyContext(s,{},s.safetyConfirmation)}
export function seedFacts(s,facts={}){return mergeFacts(s,facts)}
function applyImportance(s,importanceByConcern={},questionId='TRIAGE'){const now=Date.now();for(const[concernId,value]of Object.entries(importanceByConcern))if(s.concernIds.includes(concernId)){appendObservation(s,{id:`${questionId}:${concernId}:${now}`,questionId,concernId,answerValue:value,specificityLevel:0,timestamp:now,effects:Object.freeze([{type:'importance',target:concernId,value,sourceType:'direct',temporality:'current'}])});if(questionId==='TRIAGE')setResolution(s,concernId,Number(value)===0?'deferred':'triaged')}markTriaged(s);return s}
export function seedImportance(s,importanceByConcern={}){return applyImportance(s,importanceByConcern,'BASELINE_IMPORTANCE')}
export function seedBaselineTopics(s,topics=[]){const now=Date.now();s.baselineTopics={...(s.baselineTopics||{})};for(const x of topics){if(!x?.concernId||!x?.topic||!s.concernIds.includes(x.concernId))continue;(s.baselineTopics[x.concernId]??=[]).push(x.topic);appendObservation(s,{id:`BASELINE_TOPIC:${x.concernId}:${x.topic}:${now}`,questionId:'BASELINE_TOPIC',concernId:x.concernId,answerValue:x.topic,specificityLevel:2,timestamp:now,effects:Object.freeze([{type:'evidence',target:x.concernId,polarity:'supports',strength:.35,certainty:'graded',sourceType:'direct',temporality:'current'}])})}return s}
export function seedBaselineSignals(s,signals={}){const now=Date.now();for(const indicator of signals.indicatorSignals||[]){if(indicator?.value==null)continue;const strength=indicator.value===1?.72:indicator.value===2?.52:indicator.value===3?.12:indicator.value===4?.38:.58,polarity=indicator.value<=3?'supports':'contradicts';for(const concernId of indicator.concerns||[]){if(!s.concernIds.includes(concernId))continue;appendObservation(s,{id:`BASELINE_INDICATOR:${indicator.id}:${concernId}:${now}`,questionId:'BASELINE_INDICATOR',concernId,answerValue:indicator.value,specificityLevel:1,timestamp:now,effects:Object.freeze([{type:'evidence',target:concernId,polarity,strength,certainty:'graded',sourceType:'direct',temporality:'current'}])})}}return s}
export function triage(s,importanceByConcern={}){return applyImportance(s,importanceByConcern,'TRIAGE')}
// Temporary member-choice capture used by Discovery UX. It records evidence of member emphasis only;
// canonical Prioritization remains the authority for downstream focus selection.
export function prioritize(s,concernIds=[]){s.priorityChoices=[...new Set(concernIds)].filter(id=>s.concernIds.includes(id)).slice(0,2);return recordPriorityResolution(s,s.priorityChoices)}
export function resolve(s,concernId,resolutionState,opts={}){return setResolution(s,concernId,resolutionState,opts)}
function traceStates(s){const states=deriveStates(s).map(x=>({...x,baselineTopics:s.baselineTopics?.[x.concernId]||[]})),chosen=s.priorityChoices??[];return chosen.length?states.map(x=>({...x,memberPrioritySelected:chosen.includes(x.concernId)})):states}
export function complete(s){if(!s.assessmentCompleted)s.assessmentCompleted=Date.now();return s}
export function trace(s){const end=s.assessmentCompleted??Date.now(),duration=Math.max(0,(end-s.assessmentStart)/1000);return{version:s.version,phase:s.phase,questionsAsked:s.questionsAsked,asked:[...s.asked],timing:{assessmentStart:new Date(s.assessmentStart).toISOString(),assessmentCompleted:s.assessmentCompleted?new Date(s.assessmentCompleted).toISOString():null,totalDurationSeconds:duration,questionCount:s.questionsAsked,averageSecondsPerQuestion:s.questionTimings.length?s.questionTimings.reduce((a,x)=>a+x.durationSeconds,0)/s.questionTimings.length:null,questionTimings:[...s.questionTimings]},activeConcerns:[...s.concernIds],triaged:s.triaged,incomplete:s.incomplete,priorityChoices:[...(s.priorityChoices??[])],states:traceStates(s),facts:{...(s.facts||{})},observations:[...s.observationLog],safety:s.safety||null,safetySignals:s.safety?.contextual?.signals||[]}}
export {BANK,DISCOVERY_VERSION};export default{BANK,DISCOVERY_VERSION,session,next,answer,setSafetyContext,seedFacts,seedImportance,seedBaselineTopics,seedBaselineSignals,triage,prioritize,resolve,recordQuestionTiming,complete,trace};