import BANK,{observationsForAnswer,constructsForAnswer,safetyContextForAnswer,openingPathForAnswer,baselineCoverageForAnswer} from './observationNormalizer.js';
import {createDiscoverySession,appendObservation,nextDiscoveryStep,markTriaged,deriveStates,setResolution,mergeFacts,activateConstructs,DISCOVERY_VERSION} from './discovery-controller.js';
import {safetyGate} from '../safety/gate.js';
export function session(options={}){const s=createDiscoverySession({constructIds:options.constructIds??[],questionBank:options.questionBank??BANK,labels:options.labels??{},outerGuardrail:options.outerGuardrail??null,facts:options.facts??{}});s.assessmentStart=Date.now();s.questionTimings=[];s.baselineCoverage={...(options.baselineCoverage||{})};s.safetyContextualSignals={...(options.safetyContextualSignals||{})};s.safetyConfirmation=options.safetyConfirmation||null;s.safety=safetyGate({stage:'discovery',contextualSignals:s.safetyContextualSignals,confirmation:s.safetyConfirmation,concernRefs:s.constructIds});return s}
export function setSafetyContext(s,contextualSignals={},confirmation=null){s.safetyContextualSignals={...(s.safetyContextualSignals||{}),...contextualSignals};if(confirmation!==undefined)s.safetyConfirmation=confirmation;const refs=(s.observationLog||[]).map(x=>x.id).filter(Boolean);s.safety=safetyGate({stage:'discovery',contextualSignals:s.safetyContextualSignals,confirmation:s.safetyConfirmation,observationRefs:refs,evidenceRefs:refs,concernRefs:s.constructIds});return s}
export function next(s){if(s.safety?.pauseOrdinaryFlow)return{type:'safety',safety:s.safety,states:deriveStates(s)};return nextDiscoveryStep(s)}
export function recordQuestionTiming(s,questionId,startedAt,completedAt=Date.now()){s.questionTimings.push({questionId,startedAt,completedAt,durationSeconds:Math.max(0,(completedAt-startedAt)/1000)});return s}
function applyGovernedFocusedSufficiency(s,question){if(!question?.maySatisfyFocusedEvidence)return;const targets=question.constructIds?.length?question.constructIds:[question.constructId].filter(Boolean),states=deriveStates(s);for(const constructId of targets){const state=states.find(x=>x.constructId===constructId);if(state&&!state.excluded&&state.qualitativeConfidence==='WELL_SUPPORTED')setResolution(s,constructId,'sufficient',{driverKnown:true})}}
export function answer(s,question,answerIds){const routed=constructsForAnswer(question,answerIds);if(routed.length)activateConstructs(s,routed);const openingPath=openingPathForAnswer(question,answerIds);if(openingPath)s.openingPath=openingPath;for(const baseline of baselineCoverageForAnswer(question,answerIds))s.baselineCoverage[baseline.dimension]={state:baseline.state,effectId:baseline.effectId,questionId:question.id,timestamp:Date.now()};for(const o of observationsForAnswer(question,answerIds))appendObservation(s,o);applyGovernedFocusedSufficiency(s,question);const safety=safetyContextForAnswer(question,answerIds);if(safety.requiresImmediacyClarification)s.safetyRequiresImmediacyClarification=true;return setSafetyContext(s,safety.contextualSignals,s.safetyConfirmation)}
export function seedFacts(s,facts={}){return mergeFacts(s,facts)}
function applyImportance(s,importanceByConstruct={},questionId='TRIAGE'){const now=Date.now();for(const[constructId,value]of Object.entries(importanceByConstruct))if(s.constructIds.includes(constructId)){appendObservation(s,{id:`${questionId}:${constructId}:${now}`,questionId,constructId,answerValue:value,specificityLevel:0,timestamp:now,effects:Object.freeze([{type:'importance',target:constructId,value,sourceType:'direct',temporality:'current'}])});if(questionId==='TRIAGE')setResolution(s,constructId,Number(value)===0?'deferred':'triaged')}markTriaged(s);return s}
export function seedImportance(s,importanceByConstruct={}){return applyImportance(s,importanceByConstruct,'DISCOVERY_IMPORTANCE')}
export function triage(s,importanceByConstruct={}){return applyImportance(s,importanceByConstruct,'TRIAGE')}
export function resolve(s,constructId,resolutionState,opts={}){return setResolution(s,constructId,resolutionState,opts)}
export function complete(s){if(!s.assessmentCompleted)s.assessmentCompleted=Date.now();return s}
export function trace(s){const end=s.assessmentCompleted??Date.now(),duration=Math.max(0,(end-s.assessmentStart)/1000);return{version:s.version,phase:s.phase,openingPath:s.openingPath??null,questionsAsked:s.questionsAsked,asked:[...s.asked],timing:{assessmentStart:new Date(s.assessmentStart).toISOString(),assessmentCompleted:s.assessmentCompleted?new Date(s.assessmentCompleted).toISOString():null,totalDurationSeconds:duration,questionCount:s.questionsAsked,averageSecondsPerQuestion:s.questionTimings.length?s.questionTimings.reduce((a,x)=>a+x.durationSeconds,0)/s.questionTimings.length:null,questionTimings:[...s.questionTimings]},baselineCoverage:{...(s.baselineCoverage||{})},activeConstructs:[...s.constructIds],triaged:s.triaged,incomplete:s.incomplete,states:deriveStates(s),facts:{...(s.facts||{})},observations:[...s.observationLog],safety:s.safety||null,safetySignals:s.safety?.contextual?.signals||[],safetyRequiresImmediacyClarification:s.safetyRequiresImmediacyClarification===true}}
export {BANK,DISCOVERY_VERSION};export default{BANK,DISCOVERY_VERSION,session,next,answer,setSafetyContext,seedFacts,seedImportance,triage,resolve,recordQuestionTiming,complete,trace};