import BANK,{observationsForAnswer,normalizeAnswerIds,factsForAnswer} from './question-bank-adapter.js';
import {createDiscoverySession,appendObservation,nextDiscoveryStep,markTriaged,deriveStates,activateConcerns,setResolution,recordPriorityResolution,mergeFacts,requestDiscoveryStop,DISCOVERY_VERSION,CONCERN_RESOLUTION} from './discovery-controller.js';
import {safetyGate} from '../safety/gate.js';
export function session(options={}){const s=createDiscoverySession({concernIds:options.concernIds??[],questionBank:options.questionBank??BANK,labels:options.labels??{},outerGuardrail:options.outerGuardrail??null,stageMinimum:options.stageMinimum??1,facts:options.facts??{}});s.assessmentStart=Date.now();s.questionTimings=[];s.safetyContextualSignals={...(options.safetyContextualSignals||{})};s.safetyConfirmation=options.safetyConfirmation||null;s.safety=safetyGate({stage:'discovery',contextualSignals:s.safetyContextualSignals,confirmation:confirmationForGate(s.safetyConfirmation),concernRefs:s.concernIds});return s}
function confirmationForGate(confirmation){if(!confirmation)return null;if(confirmation.immediateDanger===true||confirmation.intent===true||confirmation.canStaySafe===false)return confirmation;return ['immediateDanger','intent','canStaySafe'].every(key=>typeof confirmation[key]==='boolean')?confirmation:null}
export function setSafetyContext(s,contextualSignals={},confirmation=undefined){s.safetyContextualSignals={...(s.safetyContextualSignals||{}),...contextualSignals};if(confirmation!==undefined)s.safetyConfirmation=confirmation;const refs=(s.observationLog||[]).map(x=>x.id).filter(Boolean);s.safety=safetyGate({stage:'discovery',contextualSignals:s.safetyContextualSignals,confirmation:confirmationForGate(s.safetyConfirmation),observationRefs:refs,evidenceRefs:refs,concernRefs:s.concernIds});return s}
export function next(s){if(s.safety?.pauseOrdinaryFlow)return{type:'safety',safety:s.safety,states:deriveStates(s)};return nextDiscoveryStep(s)}
export function recordQuestionTiming(s,questionId,startedAt,completedAt=Date.now()){s.questionTimings.push({questionId,startedAt,completedAt,durationSeconds:Math.max(0,(completedAt-startedAt)/1000)});return s}
function safetyConfirmationForAnswer(question,ids,current=null){if(question.path!=='safety'||!question.safetyConfirmationField)return current;const id=ids[0];if(id==='unsure'||id==='prefer_not')return current;const next={...(current||{})};if(question.safetyConfirmationField==='immediateDanger')next.immediateDanger=id==='yes';else if(question.safetyConfirmationField==='intent')next.intent=id==='yes';else if(question.safetyConfirmationField==='canStaySafe')next.canStaySafe=id==='yes';return next}
const NON_CONCERN_GATEWAY_IDS=new Set(['other','well','unsure']);
function directlyReportedConcernIds(question,ids,observations){if(question.id==='G1')return ids.filter(id=>!NON_CONCERN_GATEWAY_IDS.has(id));if(question.role!=='concern-scope')return[];return[...new Set(observations.flatMap(o=>o.effects??[]).filter(e=>e.type==='evidence'&&e.polarity==='supports'&&e.strength>0).map(e=>e.target))]}
const RESOLUTION_ROLES=new Set(['state-probe','concern-scope','confirmation']);
function resolveFromDirectEvidence(s,question){if(!RESOLUTION_ROLES.has(question.role))return s;const touched=new Set(question.concernIds?.length?question.concernIds:[question.concernId].filter(Boolean));for(const state of deriveStates(s)){if(!touched.has(state.concernId)||state.resolutionState!==CONCERN_RESOLUTION.UNRESOLVED)continue;if(state.excluded)setResolution(s,state.concernId,CONCERN_RESOLUTION.DISMISSED);else if((state.evidenceSummary?.supports||[]).includes(question.id))setResolution(s,state.concernId,CONCERN_RESOLUTION.ESTABLISHED)}return s}
export function answer(s,question,answerIds){const ids=normalizeAnswerIds(question,answerIds),observations=observationsForAnswer(question,ids),answerFacts=factsForAnswer(question,ids);if(Object.keys(answerFacts).length)mergeFacts(s,answerFacts);const directConcerns=directlyReportedConcernIds(question,ids,observations);if(directConcerns.length)activateConcerns(s,directConcerns);for(const o of observations){if(question.role==='orientation')continue;if(question.role==='gateway'&&o.concernId&&!s.concernIds.includes(o.concernId))continue;appendObservation(s,o)}resolveFromDirectEvidence(s,question);if(question.path==='safety'){const confirmation=safetyConfirmationForAnswer(question,ids,s.safetyConfirmation);s.safetyConfirmation=confirmation;return setSafetyContext(s,{explicitSafetyConcern:true},confirmation)}return setSafetyContext(s,{},s.safetyConfirmation)}
export function seedFacts(s,facts={}){return mergeFacts(s,facts)}
function applyImportance(s,importanceByConcern={},questionId='TRIAGE'){const now=Date.now();for(const[concernId,value]of Object.entries(importanceByConcern))if(s.concernIds.includes(concernId))appendObservation(s,{id:`${questionId}:${concernId}:${now}`,questionId,concernId,answerValue:value,specificityLevel:0,timestamp:now,effects:Object.freeze([{type:'importance',target:concernId,value,sourceType:'direct',temporality:'current'}])});markTriaged(s);return s}
export function seedImportance(s,importanceByConcern={}){return applyImportance(s,importanceByConcern,'BASELINE_IMPORTANCE')}
export function seedBaselineTopics(s,topics=[]){const now=Date.now();s.baselineTopics={...(s.baselineTopics||{})};for(const x of topics){if(!x?.concernId||!x?.topic||!s.concernIds.includes(x.concernId))continue;(s.baselineTopics[x.concernId]??=[]).push(x.topic);appendObservation(s,{id:`BASELINE_TOPIC:${x.concernId}:${x.topic}:${now}`,questionId:'BASELINE_TOPIC',concernId:x.concernId,answerValue:x.topic,specificityLevel:2,timestamp:now,effects:Object.freeze([])})}return s}
export function seedBaselineSignals(s,signals={}){const now=Date.now();for(const indicator of signals.indicatorSignals||[]){if(indicator?.value==null)continue;for(const concernId of indicator.concerns||[]){if(!s.concernIds.includes(concernId))continue;appendObservation(s,{id:`BASELINE_INDICATOR:${indicator.id}:${concernId}:${now}`,questionId:'BASELINE_INDICATOR',concernId,answerValue:indicator.value,specificityLevel:1,timestamp:now,effects:Object.freeze([])})}}return s}
export function triage(s,importanceByConcern={}){return applyImportance(s,importanceByConcern,'TRIAGE')}
export function stop(s){return requestDiscoveryStop(s)}
export function prioritize(s,concernIds=[]){s.priorityChoices=[...new Set(concernIds)].filter(id=>s.concernIds.includes(id)).slice(0,2);return recordPriorityResolution(s,s.priorityChoices)}
export function resolve(s,concernId,resolutionState,opts={}){return setResolution(s,concernId,resolutionState,opts)}
function traceStates(s){const states=deriveStates(s).map(x=>({...x,baselineTopics:s.baselineTopics?.[x.concernId]||[]})),chosen=s.priorityChoices??[];return chosen.length?states.map(x=>({...x,memberPrioritySelected:chosen.includes(x.concernId)})):states}
export function complete(s){if(!s.assessmentCompleted)s.assessmentCompleted=Date.now();return s}
export function trace(s){const end=s.assessmentCompleted??Date.now(),duration=Math.max(0,(end-s.assessmentStart)/1000);return{version:s.version,phase:s.phase,questionsAsked:s.questionsAsked,asked:[...s.asked],timing:{assessmentStart:new Date(s.assessmentStart).toISOString(),assessmentCompleted:s.assessmentCompleted?new Date(s.assessmentCompleted).toISOString():null,totalDurationSeconds:duration,questionCount:s.questionsAsked,averageSecondsPerQuestion:s.questionTimings.length?s.questionTimings.reduce((a,x)=>a.durationSeconds,0)/s.questionTimings.length:null,questionTimings:[...s.questionTimings]},activeConcerns:[...s.concernIds],triaged:s.triaged,incomplete:s.incomplete,memberStopped:s.memberStopped===true,priorityChoices:[...(s.priorityChoices??[])],states:traceStates(s),facts:{...(s.facts||{})},observations:[...s.observationLog],safety:s.safety||null,safetySignals:s.safety?.contextual?.signals||[]}}
export {BANK,DISCOVERY_VERSION,CONCERN_RESOLUTION};export default{BANK,DISCOVERY_VERSION,CONCERN_RESOLUTION,session,next,answer,setSafetyContext,seedFacts,seedImportance,seedBaselineTopics,seedBaselineSignals,triage,stop,prioritize,resolve,recordQuestionTiming,complete,trace};