import {ALL_QUESTIONS,getAnswer,getAnswersForQuestion,getEffectsForAnswer,isRuntimeQuestion,isExecutableEffect} from '../registries/registry.js';
import {makeObservation} from './contracts.js';
import {isConstructId} from '../../registries/taxonomy/index.js';

const specificityForRole=role=>({general:0,orientation:0,'orientation-baseline':0,'concern-scope':1,'state-probe':2,'condition-probe':2,'impact-probe':2,'urgency-probe':2,'resilience-probe':2,'control-probe':2,discriminator:2,deepening:2,confirmation:2,'support-probe':3,'driver-discriminator':3,'feasibility-probe':3,'obligation-probe':3,contradiction:2,correction:2,'handoff-validation':1,'healthy-verification':1,'safety-probe':3,'goal-probe':1,'strength-probe':1,'opt-out':1}[role]??1);
const activeAnswer=row=>{const status=String(row?.['Runtime Status']??row?.['Audit Status']??'').toLowerCase();return !status.includes('design-only')&&!status.includes('deferred')&&!status.includes('retired')};
const qid=q=>q.id??q['Question ID']; const role=q=>q.role??q['Role'];
const targetForEffect=e=>e?.['Target ID / Construct']??null; const valueForEffect=e=>e?.Value??null; const keyForEffect=e=>e?.Key??null; const effectType=e=>String(e?.['Effect Type']??'').toUpperCase();
function runtimeEffect(effect){if(!effect||!isExecutableEffect(effect))return[];const target=targetForEffect(effect),value=valueForEffect(effect),key=keyForEffect(effect),base={sourceType:'direct',temporality:'current'};if(target&&!isConstructId(target))return[];switch(effectType(effect)){case'EVIDENCE':case'STATE':return target?[{type:'evidence',target,polarity:'supports',strength:1,certainty:'definitive',stateValue:value,...base}]:[];case'NEGATIVE_EVIDENCE':return target?[{type:'evidence',target,polarity:'contradicts',strength:.5,certainty:'graded',cannotEraseState:true,value,...base}]:[];case'FACET':case'IMPACT':case'CONTEXT':return target?[{type:'evidence',target,polarity:'supports',strength:.5,certainty:'graded',facet:key,value,...base}]:[];case'CONSTRAINT':return target?[{type:'constraint',target,key,value:value??key,...base}]:[];case'SUPPORT':return target?[{type:'support',target,key,value:value??key,...base}]:[];case'FEASIBILITY':return target?[{type:'feasibility',target,feasibility:{[key??'context']:value??true},...base}]:[];default:return[]}}
function governedTargetsForQuestion(id){const targets=getAnswersForQuestion(id).filter(activeAnswer).flatMap(answer=>getEffectsForAnswer(answer['Answer ID']).filter(isExecutableEffect).map(targetForEffect)).filter(isConstructId);return[...new Set(targets)]}
function maySatisfyFocusedEvidence(row){return /may itself satisfy focused|may itself satisfy activity|may itself satisfy focused evidence/i.test(`${row['Decision Use']??''} ${row['Registry Notes']??''}`)}
function toRuntimeQuestion(row){const id=row['Question ID'],targets=governedTargetsForQuestion(id),declared=row['Primary Construct']&&isConstructId(row['Primary Construct'])?row['Primary Construct']:null,constructIds=targets.length?targets:declared?[declared]:[];return Object.freeze({id,text:row.Question,responseType:String(row['Response Type']||'Single').toLowerCase(),responseMode:String(row['Response Type']||'Single').toLowerCase(),role:row.Role,dimension:row['Primary Dimension'],constructId:constructIds.length===1?constructIds[0]:null,constructIds:Object.freeze(constructIds),maySatisfyFocusedEvidence:maySatisfyFocusedEvidence(row),status:row['Runtime Status'],burden:Number(row.Burden??1),specificityLevel:specificityForRole(row.Role),options:Object.freeze(getAnswersForQuestion(id).filter(activeAnswer).map(a=>Object.freeze({id:a['Answer ID'],text:a.Answer,status:a['Runtime Status']??'active'})))})}
export const DISCOVERY_BANK=Object.freeze(ALL_QUESTIONS.filter(isRuntimeQuestion).map(toRuntimeQuestion));
export function normalizeAnswerIds(question,answerIds){const questionId=qid(question);if(!getAnswersForQuestion(questionId).length&&!ALL_QUESTIONS.some(row=>row['Question ID']===questionId))return[];let ids=[...new Set((Array.isArray(answerIds)?answerIds:[answerIds]).filter(Boolean))].filter(id=>getAnswer(id)?.['Parent Question ID']===questionId);if(question.responseMode!=='multi'&&ids.length>1)ids=ids.slice(0,1);return ids}
export function answerEffects(question,answerIds){return normalizeAnswerIds(question,answerIds).flatMap(id=>getEffectsForAnswer(id)).filter(isExecutableEffect)}
export function baselineCoverageForAnswer(question,answerIds){return answerEffects(question,answerIds).filter(e=>effectType(e)==='BASELINE_COVERAGE').map(e=>Object.freeze({dimension:String(targetForEffect(e)||'').replace(/^DIMENSION_/,''),state:valueForEffect(e),effectId:e['Effect ID']}))}
export function openingPathForAnswer(question,answerIds){if(qid(question)!=='Q000001')return null;const answers=new Set(normalizeAnswerIds(question,answerIds));if(answers.has('A000013'))return'positive';if(answers.has('A000014'))return'uncertain';if(answers.has('A000012'))return'unclassified';return null}
export function safetyContextForAnswer(question,answerIds){const contextualSignals={};let requiresImmediacyClarification=false;for(const effect of answerEffects(question,answerIds)){const type=effectType(effect),target=targetForEffect(effect),key=keyForEffect(effect),value=valueForEffect(effect);if(type==='SAFETY_TRIGGER'){contextualSignals.explicitSafetyConcern=true;requiresImmediacyClarification=true}else if(type==='SAFETY_UNCERTAIN'||(type==='UNCERTAINTY'&&String(target||'').includes('SAFETY')))contextualSignals[key??'safety_uncertain']=.9;else if(type==='SAFETY_CONTEXT'&&String(value).toLowerCase().includes('safe'))contextualSignals[key??'safety_context']=.65}return Object.freeze({contextualSignals:Object.freeze(contextualSignals),requiresImmediacyClarification})}
export function constructsForAnswer(question,answerIds){const constructs=[];for(const effect of answerEffects(question,answerIds)){const target=targetForEffect(effect);if(effectType(effect)==='ROUTE'&&target&&isConstructId(target))constructs.push(target)}return[...new Set(constructs)]}
export function observationsForAnswer(question,answerIds,{timestamp=Date.now()}={}){return normalizeAnswerIds(question,answerIds).map(answerId=>{const governed=getEffectsForAnswer(answerId).filter(isExecutableEffect),effects=governed.flatMap(runtimeEffect),targets=governed.filter(e=>effectType(e)!=='BASELINE_COVERAGE').map(targetForEffect).filter(target=>target&&isConstructId(target)),constructId=targets.length===1?targets[0]:null;return makeObservation({id:`${qid(question)}:${answerId}:${timestamp}`,questionId:qid(question),constructId,answerValue:answerId,specificityLevel:question.specificityLevel??specificityForRole(role(question)),timestamp,effects})})}
export default DISCOVERY_BANK;