import {QUESTIONS} from '../registries/index.js';
import {getAnswer,getAnswersForQuestion,getEffectsForAnswer,resolvePermanentId,isRuntimeQuestion,isExecutableEffect} from '../registries/registry.js';
import {makeObservation} from './contracts.js';

const specificityForRole=role=>({general:0,orientation:0,'concern-scope':1,'state-probe':2,'condition-probe':2,'impact-probe':2,'urgency-probe':2,'resilience-probe':2,'control-probe':2,discriminator:2,deepening:2,confirmation:2,'support-probe':3,'driver-discriminator':3,'feasibility-probe':3,'obligation-probe':3,contradiction:2,correction:2,'handoff-validation':1,'healthy-verification':1,'safety-probe':3,'goal-probe':1,'strength-probe':1,'opt-out':1}[role]??1);
const activeAnswer=row=>{const status=String(row?.['Runtime Status']??row?.['Audit Status']??'').toLowerCase();return !status.includes('design-only')&&!status.includes('deferred')&&!status.includes('retired')};
const qid=q=>q.id??q['Question ID'];
const role=q=>q.role??q['Role'];
const targetForEffect=e=>e?.['Target ID / Construct']??null;
const valueForEffect=e=>e?.Value??null;
const keyForEffect=e=>e?.Key??null;
const effectType=e=>String(e?.['Effect Type']??'').toUpperCase();
function runtimeEffect(effect){if(!effect||!isExecutableEffect(effect))return[];const target=targetForEffect(effect),value=valueForEffect(effect),key=keyForEffect(effect),base={sourceType:'direct',temporality:'current'};switch(effectType(effect)){case'EVIDENCE':case'STATE':return target?[{type:'evidence',target,polarity:'supports',strength:1,certainty:'definitive',stateValue:value,...base}]:[];case'NEGATIVE_EVIDENCE':return target?[{type:'evidence',target,polarity:'contradicts',strength:.5,certainty:'graded',cannotEraseState:true,value,...base}]:[];case'FACET':case'IMPACT':case'CONTEXT':return target?[{type:'evidence',target,polarity:'supports',strength:.5,certainty:'graded',facet:key,value,...base}]:[];case'CONSTRAINT':return target?[{type:'constraint',target,key,value:value??key,...base}]:[];case'SUPPORT':return target?[{type:'support',target,key,value:value??key,...base}]:[];case'FEASIBILITY':return target?[{type:'feasibility',target,feasibility:{[key??'context']:value??true},...base}]:[];default:return[]}}
function toRuntimeQuestion(row){const id=row['Question ID'];return Object.freeze({id,legacyId:row['Legacy ID']||null,text:row.Question,responseType:String(row['Response Type']||'Single').toLowerCase(),responseMode:String(row['Response Type']||'Single').toLowerCase(),role:row.Role,dimension:row['Primary Dimension'],constructId:row['Primary Construct']&&/^[A-Z][A-Z0-9_]+$/.test(row['Primary Construct'])?row['Primary Construct']:null,status:row['Runtime Status'],burden:Number(row.Burden??1),specificityLevel:specificityForRole(row.Role),options:Object.freeze(getAnswersForQuestion(id).filter(activeAnswer).map(a=>Object.freeze({id:a['Answer ID'],legacyId:a['Legacy ID']||null,text:a.Answer,status:a['Runtime Status']??'active'})))})}
export const DISCOVERY_BANK=Object.freeze(QUESTIONS.filter(isRuntimeQuestion).map(toRuntimeQuestion));
export function normalizeAnswerIds(question,answerIds){const questionId=resolvePermanentId(qid(question));let ids=[...new Set((Array.isArray(answerIds)?answerIds:[answerIds]).filter(Boolean).map(resolvePermanentId))].filter(id=>getAnswer(id)?.['Parent Question ID']===questionId);if(question.responseMode!=='multi'&&ids.length>1)ids=ids.slice(0,1);return ids}
export function answerEffects(question,answerIds){return normalizeAnswerIds(question,answerIds).flatMap(id=>getEffectsForAnswer(id)).filter(isExecutableEffect)}
export function openingPathForAnswer(question,answerIds){if(resolvePermanentId(qid(question))!=='Q000001')return null;const legacy=new Set(normalizeAnswerIds(question,answerIds).map(getAnswer).filter(Boolean).map(a=>a['Legacy ID']));if(legacy.has('GEN001.13'))return'positive';if(legacy.has('GEN001.14'))return'uncertain';if(legacy.has('GEN001.12'))return'unclassified';return null}
export function safetyContextForAnswer(question,answerIds){const contextualSignals={};let requiresImmediacyClarification=false;for(const effect of answerEffects(question,answerIds)){const type=effectType(effect),key=keyForEffect(effect),value=valueForEffect(effect);if(type==='SAFETY_TRIGGER'){contextualSignals.explicitSafetyConcern=true;requiresImmediacyClarification=true}else if(type==='SAFETY_UNCERTAIN')contextualSignals[key??'safety_uncertain']=.9;else if(type==='SAFETY_CONTEXT'&&String(value).toLowerCase().includes('safe'))contextualSignals[key??'safety_context']=.65}return Object.freeze({contextualSignals:Object.freeze(contextualSignals),requiresImmediacyClarification})}
export function constructsForAnswer(question,answerIds){const constructs=[];for(const effect of answerEffects(question,answerIds))if(effectType(effect)==='ROUTE'&&targetForEffect(effect))constructs.push(targetForEffect(effect));return[...new Set(constructs)]}
export function observationsForAnswer(question,answerIds,{timestamp=Date.now()}={}){return normalizeAnswerIds(question,answerIds).map(answerId=>{const governed=getEffectsForAnswer(answerId).filter(isExecutableEffect),effects=governed.flatMap(runtimeEffect),targets=governed.map(targetForEffect).filter(Boolean),constructId=targets.length===1?targets[0]:null;return makeObservation({id:`${qid(question)}:${answerId}:${timestamp}`,questionId:qid(question),constructId,answerValue:answerId,specificityLevel:question.specificityLevel??specificityForRole(role(question)),timestamp,effects})})}
export default DISCOVERY_BANK;
