import { QUESTION_BANK, QUESTION_BANK_COLUMNS } from './questions/index.js';
import { makeObservation } from './contracts.js';

const C=Object.freeze(Object.fromEntries(QUESTION_BANK_COLUMNS.map((name,index)=>[name,index])));
const CONSTRUCTS=Object.freeze(['EMOTIONAL_STATE','PRESSURE_PATTERN','SLEEP_QUALITY','ENERGY_FUNCTION','LONELINESS','JOB_SECURITY','FINANCIAL_STRAIN','FINANCIAL_CONTROL','ENVIRONMENTAL_SUPPORT','MEANING_PURPOSE','RELATIONSHIP_STRAIN','SUPPORT_AVAILABILITY','PHYSICAL_CONDITION','ACTIVITY_LEVEL','FOCUS_FUNCTION','ACTIVATION','SCHEDULE_DISRUPTION','BODY_WEIGHT_CONCERN','VALUES_CLARITY','NEXT_STEP_CLARITY','DIRECTION_CLARITY','COGNITIVE_ENGAGEMENT']);
const GATEWAY_ROUTES=Object.freeze({'GEN001.01':['FINANCIAL_STRAIN','FINANCIAL_CONTROL'],'GEN001.02':['JOB_SECURITY','SCHEDULE_DISRUPTION'],'GEN001.03':['PHYSICAL_CONDITION'],'GEN001.04':['ENERGY_FUNCTION'],'GEN001.05':['SLEEP_QUALITY'],'GEN001.06':['PRESSURE_PATTERN','EMOTIONAL_STATE'],'GEN001.07':['RELATIONSHIP_STRAIN'],'GEN001.08':['LONELINESS','SUPPORT_AVAILABILITY'],'GEN001.09':['ENVIRONMENTAL_SUPPORT'],'GEN001.10':['FOCUS_FUNCTION','ACTIVATION'],'GEN001.11':['DIRECTION_CLARITY','MEANING_PURPOSE','VALUES_CLARITY','NEXT_STEP_CLARITY']});
function text(row,...columns){return columns.map(name=>String(row[C[name]]??'')).join(' ')}
function constructs(row){const hay=text(row,'Primary Concern / Construct','Signals / Effects','Audit Notes','Decision Use');return CONSTRUCTS.filter(id=>new RegExp(`\\b${id}\\b`).test(hay))}
function role(row){const raw=String(row[C.Role]??'').toLowerCase();if(row[C['Canonical ID']]==='GEN001')return'gateway';if(raw.includes('orientation')||String(row[C['Scheduling / Stage']]??'').toLowerCase().includes('orient'))return'orientation';if(raw.includes('discriminator'))return'discriminator';if(raw.includes('confirmation'))return'confirmation';if(raw.includes('feasibility'))return'feasibility-probe';if(raw.includes('bridge'))return'bridge';return'state-probe'}
function responseMode(row){const raw=String(row[C['Response Type']]??'').toLowerCase();if(raw.includes('multi'))return'multi';if(raw.includes('scale'))return'scale';if(raw.includes('structured')||raw.includes('free text'))return'structured';return'single'}
function activeQuestion(row){if(row[C['Item Type']]!=='Question')return false;const status=`${row[C['Audit Status']]??''} ${row[C['Runtime Status']]??''}`.toLowerCase();return !/(deferred|future candidate|retire|remove|hold)/.test(status)}
const rowsById=new Map(QUESTION_BANK.map(row=>[row[C['Canonical ID']],row]));
function optionFor(row){return Object.freeze({id:row[C['Canonical ID']],label:row[C['Question / Answer']],constructIds:Object.freeze(constructs(row)),signals:String(row[C['Signals / Effects']]??''),exclusiveWithinGroup:/exclusive/i.test(String(row[C['Response Type']]??''))})}
export const DISCOVERY_QUESTIONS=Object.freeze(QUESTION_BANK.filter(activeQuestion).map(row=>{const id=row[C['Canonical ID']],answerRows=QUESTION_BANK.filter(candidate=>candidate[C['Item Type']]==='Answer'&&String(candidate[C['Canonical ID']]).startsWith(`${id}.`));const constructIds=constructs(row);return Object.freeze({id,text:row[C['Question / Answer']],responseMode:responseMode(row),role:role(row),constructId:constructIds[0]??null,constructIds:Object.freeze(constructIds),options:Object.freeze(answerRows.map(optionFor)),scheduling:String(row[C['Scheduling / Stage']]??''),runtimeStatus:String(row[C['Runtime Status']]??''),burden:Number(row[C.Burden])||0})}));
export function normalizeAnswerIds(question,answerIds){let ids=[...new Set((Array.isArray(answerIds)?answerIds:[answerIds]).filter(Boolean))];if(question.responseMode!=='multi'&&ids.length>1)ids=ids.slice(0,1);if(question.responseMode==='multi'){const exclusive=ids.find(id=>question.options.find(option=>option.id===id)?.exclusiveWithinGroup);if(exclusive)ids=[exclusive]}return ids}
function effectForAnswer(answerRow,constructId){const semantics=text(answerRow,'Signals / Effects','Audit Notes');const lower=semantics.toLowerCase();if(/no direct|routing_prior|routes to|context only|hypothesis/.test(lower))return null;const contradicts=/contradict|not present|absent|no current/.test(lower);return Object.freeze({type:'evidence',target:constructId,polarity:contradicts?'contradicts':'supports',strength:/definitive|direct state|direct_state/.test(lower)?1:0.7,certainty:/definitive/.test(lower)?'definitive':'graded',sourceType:'direct',temporality:'current'})}
export function observationsForAnswer(question,answerIds,{timestamp=Date.now()}={}){const out=[];for(const answerId of normalizeAnswerIds(question,answerIds)){const row=rowsById.get(answerId);if(!row)continue;if(question.id==='GEN001'){for(const constructId of GATEWAY_ROUTES[answerId]??[])out.push(makeObservation({id:`${answerId}:${constructId}:${timestamp}`,questionId:question.id,constructId,answerValue:answerId,timestamp,effects:[{type:'routing',target:constructId,sourceType:'direct',temporality:'current'}]}));if(!(GATEWAY_ROUTES[answerId]?.length))out.push(makeObservation({id:`${answerId}:${timestamp}`,questionId:question.id,answerValue:answerId,timestamp,effects:[]}));continue}const ids=constructs(row);if(!ids.length){out.push(makeObservation({id:`${answerId}:${timestamp}`,questionId:question.id,constructId:question.constructId,answerValue:answerId,timestamp,effects:[]}));continue}for(const constructId of ids){const effect=effectForAnswer(row,constructId);out.push(makeObservation({id:`${answerId}:${constructId}:${timestamp}`,questionId:question.id,constructId,answerValue:answerId,timestamp,effects:effect?[effect]:[]}))}}return out}
export default DISCOVERY_QUESTIONS;
