import BANK,{observationsForAnswer} from './question-bank-adapter.js';
import {createRound3Session,appendObservation,nextRound3Step,markTriaged,buildPlan,deriveStates,activateConcerns,setResolution,recordPriorityResolution} from './round3-controller.js';
import {buildMemberPlan} from './member-plan.js';
export function session(options={}){const s=createRound3Session({concernIds:options.concernIds??[],questionBank:options.questionBank??BANK,labels:options.labels??{},outerGuardrail:options.outerGuardrail??14});s.assessmentStart=Date.now();s.questionTimings=[];s.selectedActions=[];return s}
export function next(s){return nextRound3Step(s)}
export function recordQuestionTiming(s,questionId,startedAt,completedAt=Date.now()){s.questionTimings.push({questionId,startedAt,completedAt,durationSeconds:Math.max(0,(completedAt-startedAt)/1000)});return s}
export function answer(s,question,answerIds){const ids=Array.isArray(answerIds)?answerIds:[answerIds];const observations=observationsForAnswer(question,ids);if(question.role==='gateway')activateConcerns(s,[...new Set(observations.flatMap(o=>o.effects??[]).filter(e=>e.type==='evidence'&&e.polarity==='supports').map(e=>e.target))]);for(const o of observations){if(question.role==='gateway'&&o.concernId&&!s.concernIds.includes(o.concernId))continue;appendObservation(s,o)}return s}
function applyImportance(s,importanceByConcern={},questionId='TRIAGE'){const now=Date.now();for(const[concernId,value]of Object.entries(importanceByConcern))if(s.concernIds.includes(concernId))appendObservation(s,{id:`${questionId}:${concernId}:${now}`,questionId,concernId,answerValue:value,specificityLevel:0,timestamp:now,effects:Object.freeze([{type:'importance',target:concernId,value,sourceType:'direct',temporality:'current'}])});markTriaged(s);return s}
export function seedImportance(s,importanceByConcern={}){return applyImportance(s,importanceByConcern,'BASELINE_IMPORTANCE')}
export function triage(s,importanceByConcern={}){return applyImportance(s,importanceByConcern,'TRIAGE')}
export function prioritize(s,concernIds=[]){s.priorityChoices=[...new Set(concernIds)].filter(id=>s.concernIds.includes(id)).slice(0,2);return recordPriorityResolution(s,s.priorityChoices)}
export function resolve(s,concernId,resolutionState,opts={}){return setResolution(s,concernId,resolutionState,opts)}
function planStates(s){const states=deriveStates(s),chosen=s.priorityChoices??[];return chosen.length?states.map(x=>({...x,memberPrioritySelected:chosen.includes(x.concernId)})):states}
export function memberPlan(s){return buildMemberPlan(planStates(s))}
export function chooseActions(s,actionIds=[]){s.selectedActions=[...new Set(actionIds)].slice(0,2);return s}
export function complete(s){if(!s.assessmentCompleted)s.assessmentCompleted=Date.now();return s}
export function trace(s){const end=s.assessmentCompleted??Date.now(),duration=Math.max(0,(end-s.assessmentStart)/1000);return{version:s.version,phase:s.phase,questionsAsked:s.questionsAsked,asked:[...s.asked],timing:{assessmentStart:new Date(s.assessmentStart).toISOString(),assessmentCompleted:s.assessmentCompleted?new Date(s.assessmentCompleted).toISOString():null,totalDurationSeconds:duration,questionCount:s.questionsAsked,averageSecondsPerQuestion:s.questionTimings.length?s.questionTimings.reduce((a,x)=>a+x.durationSeconds,0)/s.questionTimings.length:null,questionTimings:[...s.questionTimings]},activeConcerns:[...s.concernIds],triaged:s.triaged,incomplete:s.incomplete,priorityChoices:[...(s.priorityChoices??[])],selectedActions:[...(s.selectedActions??[])],states:planStates(s),plan:buildPlan(s),memberPlan:memberPlan(s),observations:[...s.observationLog]}}
export {BANK};export default{BANK,session,next,answer,seedImportance,triage,prioritize,resolve,memberPlan,recordQuestionTiming,chooseActions,complete,trace};