import test from 'node:test';
import assert from 'node:assert/strict';
import {buildOnboardingAdaptivePlan,planningEvidenceFromDiscovery} from './adaptive-plan.js';
import {assertPlanReadyForActivation} from './activation-readiness.js';

const state=(concernId,confidence=.88,extra={})=>({concernId,resolutionState:'sufficient',evidenceConfidence:confidence,memberImportance:3,memberPrioritySelected:true,readiness:3,evidenceRefs:[`e:${concernId}`],...extra});
const output=(states,focusIds=states.map(x=>x.concernId),load='Manageable')=>({trace:{states},plan:{focus:focusIds.map(id=>({concernId:id,label:id,evidenceConfidence:states.find(x=>x.concernId===id)?.evidenceConfidence??.8,memberSelected:true,evidenceRefs:[`e:${id}`]}))},baselineHandoff:{signals:{feasibility:{overall_load:load},constraints:[]}}});
const plan=(discoveryOutput,confirmedPriorities,selectionEvidence={},capacity=null)=>buildOnboardingAdaptivePlan({discoveryOutput,recommendedPriorities:confirmedPriorities,confirmedPriorities,baselineHandoff:discoveryOutput.baselineHandoff,selectionEvidence,capacity});

test('Money-only: supported focus reaches decision-relevant selection deepening, not rediscovery',()=>{const o=output([state('money',.92)],['money']);const p=plan(o,['money']);assert.equal(p.status,'deepen');assert.equal(p.reason,'selection_evidence_required');assert.deepEqual(p.selectionDeepening.requirements.map(x=>x.evidenceKey),['financial.current_snapshot']);assert.throws(()=>assertPlanReadyForActivation(p))});

test('Money-only: one selection answer produces a canonical plan',()=>{const o=output([state('money',.92)],['money']);const p=plan(o,['money'],{'financial.current_snapshot':'Understand where my money is going'});assert.equal(p.status,'active');assert.equal(p.active[0].driver,'money_pressure');assert.equal(p.active[0].id,'money_snapshot')});

test('Health-only: canonical parent focus uses specific physical evidence and produces a bounded plan',()=>{const o=output([state('physical_condition',.87,{sourceConcernId:'health'})],['health']);const evidence=planningEvidenceFromDiscovery(o,['health']);assert.equal(evidence.length,1);assert.equal(evidence[0].concernId,'health');const p=plan(o,['health']);assert.notEqual(p.reason,'insufficient_evidence');assert.equal(p.status,'active');assert.ok(p.active.length>=1&&p.active.length<=2);assert.ok(p.active.every(a=>a.driver==='low_activity'))});

test('Money + Health: both confirmed focuses cross Discovery → Planning',()=>{const o=output([state('money',.91),state('physical_condition',.86,{sourceConcernId:'health'})],['money','health']);const p=plan(o,['money','health']);assert.notEqual(p.reason,'insufficient_evidence');assert.equal(p.status,'deepen');assert.ok(p.selectionDeepening.requirements.some(r=>r.evidenceKey==='financial.current_snapshot'));const after=plan(o,['money','health'],{'financial.current_snapshot':'Understand where my money is going'});assert.equal(after.status,'active');assert.ok(after.active.length>=1&&after.active.length<=2);assert.ok(after.active.some(a=>a.driver==='money_pressure'))});

test('Three-focus high-load case stays bounded to one active action',()=>{const o=output([state('money',.93),state('poor_sleep',.9),state('work',.86)],['money','poor_sleep','work'],'Overwhelming');const p=plan(o,['money','poor_sleep','work'],{'financial.current_snapshot':'Understand where my money is going','baseline.sleep_pattern':'Usually 5–6 hours with an inconsistent bedtime'},'low');assert.equal(p.status,'active');assert.equal(p.active.length,1);assert.ok(['money_pressure','poor_sleep','work_instability'].includes(p.active[0].driver))});

test('Three-focus medium-load case never creates three simultaneous actions',()=>{const o=output([state('money',.93),state('poor_sleep',.9),state('work',.86)],['money','poor_sleep','work']);const p=plan(o,['money','poor_sleep','work'],{'financial.current_snapshot':'Understand where my money is going','baseline.sleep_pattern':'Usually 5–6 hours with an inconsistent bedtime'});assert.equal(p.status,'active');assert.ok(p.active.length>=1&&p.active.length<=2)});

test('activation evidence can be supplied immediately without waiting reviewDays',()=>{const o=output([state('money',.9)],['money']);let p=plan(o,['money'],{'financial.current_snapshot':'Understand where my money is going'});const activation={};for(const r of p.deepening?.blocking||[]){const key=r.evidenceKey||r.requirementId||r.id;if(key)activation[key]=r.options?.[0]||'QA evidence supplied'}p=buildOnboardingAdaptivePlan({discoveryOutput:o,recommendedPriorities:['money'],confirmedPriorities:['money'],baselineHandoff:o.baselineHandoff,selectionEvidence:{'financial.current_snapshot':'Understand where my money is going'},evidence:activation});if((p.deepening?.blocking||[]).length===0&&p.activationStatus!=='needs_plan_specific_assessment')assert.ok(assertPlanReadyForActivation(p).length>=1);assert.notEqual(p.reviewDays,0)});

test('stale or forged active object still fails activation gate',()=>{assert.throws(()=>assertPlanReadyForActivation({status:'active',active:[{id:'fake',driver:'money_pressure'}],selectionDeepening:{required:true},deepening:{blocking:[]},activationStatus:'ready'}));assert.throws(()=>assertPlanReadyForActivation({status:'active',active:[],selectionDeepening:{required:false},deepening:{blocking:[]},activationStatus:'ready'}))});

console.log('accelerated canonical onboarding scenario QA passed');
