// Onboarding → canonical Adaptive Plan bridge.
// Discovery semantics are normalized only by the canonical Discovery → Planning handoff.
import { buildPlan } from '../../intelligence/planning/plan-engine.js';
import { buildPlanningHandoff } from '../../intelligence/planning/discovery-handoff.js';

const DRIVER_MAP=Object.freeze({physical_condition:'low_activity',work_pressure:'work_instability',low_direction:'lack_direction'});
function canonicalState(state={}){const concernId=DRIVER_MAP[state.concernId]||state.concernId;return{...state,concernId,readiness:state.readiness??state.feasibility?.values?.readiness??null};}
export function planningEvidenceFromDiscovery(output={},confirmedPriorities=[]){const wanted=new Set((confirmedPriorities||[]).map(String));const selected=(output.trace?.states||[]).filter(state=>wanted.has(String(state.concernId))).map(canonicalState);return buildPlanningHandoff({selected,backlog:[]}).ranked;}
export function onboardingPlanContext({baselineHandoff={},capacity=null,selectionEvidence={},evidence={},rejectedActionIds=[]}={}){const signals=baselineHandoff?.signals||{},feasibility=signals.feasibility||{},inferredCapacity=capacity||(feasibility.overall_load==='Overwhelming'||feasibility.readiness==='Not ready'?'low':'medium');return{capacity:inferredCapacity,constraints:Array.isArray(signals.constraints)?signals.constraints:signals.constraints?[signals.constraints]:[],selectionEvidence,evidence,rejectedActionIds,consent:true};}
export function buildOnboardingAdaptivePlan({discoveryOutput={},confirmedPriorities=[],baselineHandoff={},capacity=null,selectionEvidence={},evidence={},rejectedActionIds=[]}={}){const ranked=planningEvidenceFromDiscovery(discoveryOutput,confirmedPriorities);return buildPlan({ranked},onboardingPlanContext({baselineHandoff,capacity,selectionEvidence,evidence,rejectedActionIds}));}
export function onboardingPlanView(plan={}){return{status:plan.status||'observe',reason:plan.reason||null,actions:(plan.active||[]).map(action=>({id:action.id,title:action.title,dimension:action.dimension,measurement:action.measurement,rationale:action.rationale,reviewDays:action.reviewDays,driver:action.driver,deepeningRequirements:(plan.deepening?.requirements||[]).filter(req=>req.actionId===action.id)})),selectionDeepening:plan.selectionDeepening||{required:false,requirements:[]},selectionEvidence:plan.selectionEvidence||null,activationStatus:plan.activationStatus||null,deepening:plan.deepening||{required:false,blocking:[],optional:[],requirements:[]},reviewDays:plan.reviewDays||null,uncertainty:plan.uncertainty||null,decisionTrace:plan.decisionTrace||null};}
