import test from 'node:test';import assert from 'node:assert/strict';import{buildDiscoverySnapshotHandoff}from'./discovery-snapshot-handoff.js';import{createDiscoveryFromSnapshot,discoveryPrioritizationInput,planningHandoffFromDiscovery,buildOnboardingPlan}from'./canonical-planning-pipeline.js';import{appendObservation,setResolution}from'../../intelligence/discovery/discovery-controller.js';
const snapshot=()=>buildDiscoverySnapshotHandoff({candidate_concerns:['money'],member_priority_concerns:['money'],feasibility:{time:'<5 min',overall_load:'Difficult'}});
const establish=(s,id='money')=>{appendObservation(s,{concernId:id,questionId:`discovery-${id}`,effects:[{type:'evidence',target:id,polarity:'supports',strength:.9},{type:'importance',target:id,value:'high'}]});setResolution(s,id,'sufficient',{driverKnown:true});return s};
test('opening snapshot cannot activate an Action',()=>{const b=snapshot();assert.equal(b.selectedActionIds,undefined);assert.equal(b.candidateActions,undefined)});
test('snapshot feasibility preserves uncertainty instead of defaulting to medium',()=>{const s=createDiscoveryFromSnapshot(buildDiscoverySnapshotHandoff({candidate_concerns:['health'],member_priority_concerns:['health']}));assert.equal(s.facts.snapshotFeasibility.capacity,'unknown')});
test('ambiguous money concern is held for discrimination rather than split into two constructs',()=>{const s=establish(createDiscoveryFromSnapshot(snapshot()));const h=discoveryPrioritizationInput(s,{memberStateRevision:4});assert.equal(h.candidates.length,0);assert.deepEqual(new Set(h.heldAmbiguous.map(x=>x.constructId)),new Set(['FINANCIAL_STRAIN','FINANCIAL_CONTROL']))});
test('valid focus without a generic Action remains a Prioritization candidate',()=>{const handoff=buildDiscoverySnapshotHandoff({candidate_concerns:['low_energy'],member_priority_concerns:['low_energy'],feasibility:{}});const s=establish(createDiscoveryFromSnapshot(handoff),'low_energy');const h=discoveryPrioritizationInput(s,{memberStateRevision:5});assert.deepEqual(h.candidates.map(x=>x.constructId),['ENERGY_FUNCTION']);assert.equal(h.candidates[0].planningContract.disposition,'conditional_action')});
test('held Action availability does not suppress a valid focus upstream',()=>{const handoff=buildDiscoverySnapshotHandoff({candidate_concerns:['relationship_strain'],member_priority_concerns:['relationship_strain'],feasibility:{}});const s=establish(createDiscoveryFromSnapshot(handoff),'relationship_strain');const h=discoveryPrioritizationInput(s,{memberStateRevision:6});assert.deepEqual(h.candidates.map(x=>x.constructId),['RELATIONSHIP_STRAIN']);assert.ok(h.candidates[0].planningContract)});
test('unambiguous resolved Discovery concern becomes canonical Prioritization candidate',()=>{const handoff=buildDiscoverySnapshotHandoff({candidate_concerns:['poor_sleep'],member_priority_concerns:['poor_sleep'],feasibility:{}});const s=createDiscoveryFromSnapshot(handoff);activateSleep(s);const h=planningHandoffFromDiscovery(s,{memberStateRevision:2});assert.equal(h.prioritization.recommended[0].constructId,'SLEEP_QUALITY');assert.equal(h.prioritization.memberStateRevision,2)});
function activateSleep(s){appendObservation(s,{concernId:'poor_sleep',questionId:'sleep',effects:[{type:'evidence',target:'poor_sleep',polarity:'supports',strength:.9}]});setResolution(s,'poor_sleep','sufficient',{driverKnown:true});return s}
test('full onboarding chain requires member Focus confirmation before Planning',()=>{const handoff=buildDiscoverySnapshotHandoff({candidate_concerns:['poor_sleep'],member_priority_concerns:['poor_sleep'],feasibility:{}});const s=activateSleep(createDiscoveryFromSnapshot(handoff));const out=buildOnboardingPlan({session:s,memberStateRevision:3,focusDecisions:[{constructId:'SLEEP_QUALITY',decision:'accepted'}]});assert.equal(out.confirmation.accepted[0].constructId,'SLEEP_QUALITY');assert.equal(out.plan.status,'proposed');assert.ok(out.plan.proposedActions.length>=1);assert.ok(out.plan.proposedActions.every(x=>!('intervention_id'in x)&&!('problem_id'in x)))});
