import test from 'node:test';import assert from 'node:assert/strict';import{buildDiscoverySnapshotHandoff}from'./discovery-snapshot-handoff.js';import{createDiscoveryFromSnapshot,discoveryPrioritizationInput,planningHandoffFromDiscovery,buildOnboardingPlan}from'./canonical-planning-pipeline.js';import{appendObservation,setResolution}from'../../intelligence/discovery/discovery-controller.js';
const snapshot=()=>buildDiscoverySnapshotHandoff({condition_baseline:{Financial:'Struggling'},member_priority:'Financial',functional_impact:['Financial'],worsening:['Financial'],feasibility:{time:'<5 min',overall_load:'Difficult'}});
const establish=(s,id='money')=>{appendObservation(s,{concernId:id,questionId:`discovery-${id}`,effects:[{type:'evidence',target:id,polarity:'supports',strength:.9},{type:'importance',target:id,value:'high'}]});setResolution(s,id,'sufficient',{driverKnown:true});return s};
test('opening snapshot cannot activate an Action',()=>{const b=snapshot();assert.equal(b.selectedActionIds,undefined);assert.equal(b.candidateActions,undefined)});
test('snapshot feasibility preserves uncertainty instead of defaulting to medium',()=>{const s=createDiscoveryFromSnapshot(buildDiscoverySnapshotHandoff({condition_baseline:{Physical:'Struggling'},member_priority:'Physical',functional_impact:['Physical']}));assert.equal(s.facts.snapshotFeasibility.capacity,'unknown')});
test('ambiguous legacy money alias is held for discrimination rather than split into two constructs',()=>{const s=establish(createDiscoveryFromSnapshot(snapshot()));const h=discoveryPrioritizationInput(s,{memberStateRevision:4});assert.equal(h.candidates.length,0);assert.deepEqual(new Set(h.heldAmbiguous.map(x=>x.constructId)),new Set(['FINANCIAL_STRAIN','FINANCIAL_CONTROL']))});
test('unambiguous resolved Discovery concern becomes canonical Prioritization candidate',()=>{const handoff={...snapshot(),candidateConcerns:['poor_sleep'],uncertainty:{requiresDiscoveryConfirmation:true},signals:{feasibility:{}}};const s=createDiscoveryFromSnapshot(handoff);activateSleep(s);const h=planningHandoffFromDiscovery(s,{memberStateRevision:2});assert.equal(h.prioritization.recommended[0].constructId,'SLEEP_QUALITY');assert.equal(h.prioritization.memberStateRevision,2)});
function activateSleep(s){appendObservation(s,{concernId:'poor_sleep',questionId:'sleep',effects:[{type:'evidence',target:'poor_sleep',polarity:'supports',strength:.9}]});setResolution(s,'poor_sleep','sufficient',{driverKnown:true});return s}
test('full onboarding chain requires member Focus confirmation before Planning',()=>{const handoff={...snapshot(),candidateConcerns:['poor_sleep'],uncertainty:{requiresDiscoveryConfirmation:true},signals:{feasibility:{}}};const s=activateSleep(createDiscoveryFromSnapshot(handoff));const out=buildOnboardingPlan({session:s,memberStateRevision:3,focusDecisions:[{constructId:'SLEEP_QUALITY',decision:'accepted'}]});assert.equal(out.confirmation.accepted[0].constructId,'SLEEP_QUALITY');assert.equal(out.plan.status,'proposed');assert.ok(out.plan.proposedActions.length>=1);assert.ok(out.plan.proposedActions.every(x=>!('intervention_id'in x)&&!('problem_id'in x)))});
