import * as Discovery from '../../intelligence/discovery/discovery-engine.js';
import {constructsForAnswer} from '../../intelligence/discovery/observationNormalizer.js';
import {CONSTRUCT_BY_ID,isConstructId} from '../../registries/taxonomy/index.js';
import {handoffAudit} from '../../intelligence/discovery/sufficiency.js';
const STORAGE_KEY='el8_onboarding_discovery_v7';
const GRAPH_DRIVER_PREFIX='GRAPH_DRIVER:';const GRAPH_SEVERITY_PREFIX='GRAPH_SEVERITY:';
const option=(id,text)=>Object.freeze({id,text,label:text});
const humanize=value=>String(value||'').replaceAll('_',' ').toLowerCase().replace(/(^|\s)\S/g,c=>c.toUpperCase());
// Member-facing driver identity is owned by the canonical construct registry, never by
// the dimension/path/relationship alias through which the construct happened to surface.
const memberLabel=value=>CONSTRUCT_BY_ID[value]?.label||humanize(value);
const escapeKey=text=>{const v=String(text||'').trim().toLowerCase();if(v.includes('something else')||v==='other')return'other';if(v==='none'||v.includes('none of'))return'none';if(v.includes('not sure')||v.includes('unsure'))return'unsure';return null};
function unifiedBaselineDriverInteraction(step){
 const canonical=new Map(),escapes=new Map();
 for(const question of step.questions??[])for(const sourceOption of question.options??[]){
  const constructIds=constructsForAnswer(question,sourceOption.id);
  if(constructIds.length===1){const constructId=constructIds[0],prior=canonical.get(constructId);if(prior){prior.sources.push({question,answerId:sourceOption.id});continue}canonical.set(constructId,{id:`DRIVER:${constructId}`,text:memberLabel(constructId),label:memberLabel(constructId),constructId,sources:[{question,answerId:sourceOption.id}]});continue}
  const key=escapeKey(sourceOption.text);if(key&&!escapes.has(key))escapes.set(key,{id:key==='other'?'something_else':key,text:key==='other'?'Something else':key==='none'?'None of these':'Not sure',label:key==='other'?'Something else':key==='none'?'None of these':'Not sure',escape:key});
 }
 const options=[...canonical.values(),...['unsure','none','other'].map(k=>escapes.get(k)).filter(Boolean)].map(x=>Object.freeze({...x,sources:x.sources?Object.freeze(x.sources):undefined}));
 const question=Object.freeze({id:'CANONICAL_DRIVER_TRIAGE',text:'What seems connected to what’s going on?',responseMode:'multi',options:Object.freeze(options)});
 return Object.freeze({...step,interaction:'unified-canonical-driver-triage',questions:Object.freeze([question]),originalQuestions:Object.freeze([...(step.questions??[])]),presentation:Object.freeze({memberFacingAsOneInteraction:true,compactWrappingButtons:true,combineOptions:true,showDimensionLabels:false,canonicalDriverIdentity:true})});
}
function graphDriverInteraction(step){const questions=(step.landscape?.candidates??[]).filter(x=>x.memberDisposition==null).map(candidate=>{const label=memberLabel(candidate.constructId);return Object.freeze({id:`${GRAPH_DRIVER_PREFIX}${candidate.constructId}`,constructId:candidate.constructId,text:`Could ${label} be connected to what is going on?`,label,responseMode:'single',options:Object.freeze([option('yes','Yes'),option('no','No'),option('unsure','Not sure')])})});return Object.freeze({...step,type:'driver-triage',interaction:'graph-driver-triage',questions,presentation:Object.freeze({memberFacingAsOneInteraction:true,compactMatrix:true,combineOptions:true,showDimensionLabels:true})})}
function graphSeverityInteraction(step){const questions=(step.nodeIds??[]).map(constructId=>{const label=memberLabel(constructId);return Object.freeze({id:`${GRAPH_SEVERITY_PREFIX}${constructId}`,constructId,text:`How much is ${label} affecting things right now?`,label,responseMode:'single',options:Object.freeze([option('minor','A little'),option('material','Somewhat'),option('major','A lot'),option('unsure','Not sure')])})});return Object.freeze({...step,type:'driver-triage',interaction:'graph-severity-triage',questions,presentation:Object.freeze({memberFacingAsOneInteraction:true,compactMatrix:true,combineOptions:true,showDimensionLabels:true})})}
export function createDiscoverySession(options={}){return Discovery.session(options)}
export function createDiscoverySessionFromHandoff(handoff={},options={}){const constructIds=[...new Set([...(handoff?.candidateConstructIds||handoff?.candidateConcerns||[]),...(options.constructIds||[])].filter(isConstructId))];return Discovery.session({...options,constructIds})}
export function nextDiscoveryStep(session){const step=Discovery.next(session);if(step.interaction==='compact-driver-relationship-screen')return unifiedBaselineDriverInteraction(step);if(step.type==='driver_triage')return graphDriverInteraction(step);if(step.type==='severity_triage')return graphSeverityInteraction(step);return step}
export function answerDiscoveryQuestion(session,question,answerIds){return Discovery.answer(session,question,answerIds)}
export function submitDiscoverySafetyConfirmation(session,confirmation){return Discovery.setSafetyContext(session,{},confirmation)}
export function answerDiscoveryInteraction(session,interaction,answersByQuestion={}){const questions=Array.isArray(interaction?.questions)?interaction.questions:[];if(interaction?.interaction==='unified-canonical-driver-triage'){const question=questions[0],raw=answersByQuestion[question?.id],selected=new Set(Array.isArray(raw)?raw:[raw].filter(Boolean));for(const selectedId of selected){const choice=question?.options?.find(x=>x.id===selectedId);if(!choice?.constructId||!choice.sources?.length)continue;const source=choice.sources[0];Discovery.answer(session,source.question,source.answerId)}return session}if(interaction?.interaction==='graph-driver-triage'){const selections={};for(const question of questions){const answer=answersByQuestion[question.id];if(answer===undefined||answer===null)continue;const value=Array.isArray(answer)?answer[0]:answer;selections[question.constructId]=value==='no'?'reject':value==='yes'?'accept':'unknown'}return Discovery.setDriverSelections(session,selections)}if(interaction?.interaction==='graph-severity-triage'){const responses={};const level={minor:.2,material:.55,major:.85};for(const question of questions){const answer=answersByQuestion[question.id];if(answer===undefined||answer===null)continue;const value=Array.isArray(answer)?answer[0]:answer;if(value==='unsure'){responses[question.constructId]={memberReportedUnknown:true};continue}const score=level[value];responses[question.constructId]={severity:score,frequency:score,functionalImpact:score,memberImportance:score}}return Discovery.setSeverityResponses(session,responses)}for(const question of questions){const answerIds=answersByQuestion[question.id];if(answerIds!==undefined&&answerIds!==null)Discovery.answer(session,question,answerIds)}return session}
export function submitDiscoveryDriverTriage(session,selections={}){return Discovery.setDriverSelections(session,selections)}
export function submitDiscoverySeverityTriage(session,responses={}){return Discovery.setSeverityResponses(session,responses)}
export function submitDiscoveryRelationshipEvidence(session,evidence={}){return Discovery.setRelationshipEvidence(session,evidence)}
export function submitDiscoveryTriage(session,importanceByConstruct){return Discovery.triage(session,importanceByConstruct)}
export function resolveDiscoveryConstruct(session,constructId,resolutionState,options={}){return Discovery.resolve(session,constructId,resolutionState,options)}
export function finishDiscovery(session){Discovery.complete(session);return discoveryOutput(session)}
export function discoveryOutput(session){const trace=Discovery.trace(session);const graphReady=trace.phase==='ready_for_prioritization'&&trace.orchestration?.readyForPrioritization===true;if(graphReady){const candidateIds=trace.orchestration.driverGraph.nodes.filter(x=>x.status==='supported'&&!x.excluded).map(x=>x.constructId);return Object.freeze({trace,handoff:Object.freeze({usable:true,candidateIds:Object.freeze(candidateIds),unresolvedConstructIds:Object.freeze([]),blockingConstructIds:Object.freeze([]),boundedUncertainty:false,driverGraph:trace.orchestration.driverGraph,driverDispositions:trace.orchestration.driverDispositions,rankedHypotheses:trace.orchestration.rankedHypotheses})})}const allowBoundedUncertainty=session?.incomplete===false,handoff=handoffAudit(trace.states||[],{allowBoundedUncertainty});return Object.freeze({trace,handoff:Object.freeze({usable:handoff.usable,candidateIds:Object.freeze([...handoff.candidateIds]),unresolvedConstructIds:Object.freeze(handoff.unresolved.map(x=>x.constructId)),blockingConstructIds:Object.freeze(handoff.blocking.map(x=>x.constructId)),boundedUncertainty:Boolean(handoff.boundedUncertainty)})})}
export function saveDiscoveryDraft(session){const serializable={...session,questionBank:undefined};sessionStorage.setItem(STORAGE_KEY,JSON.stringify(serializable));return session}
export function loadDiscoveryDraft(){const raw=sessionStorage.getItem(STORAGE_KEY);if(!raw)return null;try{return{...JSON.parse(raw),questionBank:Discovery.BANK}}catch{return null}}
export function clearDiscoveryDraft(){sessionStorage.removeItem(STORAGE_KEY)}
function normalizedImportance(s={}){const raw=s.memberImportance;if(raw===null||raw===undefined)return null;if(typeof raw==='number')return raw;const map={low:0,moderate:1,high:2,'very-high':3};return map[raw]??null}
const CONFIDENCE_ORDER=Object.freeze({UNKNOWN:0,LIMITED:1,MODERATE:2,WELL_SUPPORTED:3});
function qualitativeConfidence(s={}){const raw=s.qualitativeConfidence??s.evidenceConfidence??s.confidence??'UNKNOWN';const value=String(raw).trim().toUpperCase().replace(/[ -]+/g,'_');return Object.hasOwn(CONFIDENCE_ORDER,value)?value:'UNKNOWN'}
function evidenceSupport(confidence){if(confidence==='WELL_SUPPORTED')return'strong';if(confidence==='MODERATE')return'sufficient';if(confidence==='LIMITED')return'limited';return'none'}
export function discoveryPriorityCandidates(output={}){const graphNodes=output.handoff?.driverGraph?.nodes;if(Array.isArray(graphNodes)){const ranked=new Map((output.handoff?.rankedHypotheses||[]).map(x=>[x.constructId,x]));return graphNodes.filter(s=>s.status==='supported'&&!s.excluded).map(s=>{const hypothesis=ranked.get(s.constructId)||{};return Object.freeze({constructId:s.constructId,label:memberLabel(s.constructId),qualitativeConfidence:s.qualitativeConfidence||'MODERATE',evidenceSupport:s.evidenceSupport||'sufficient',memberImportance:s.memberImportance??s.triage?.memberImportance??null,materiality:s.materiality??null,leverage:hypothesis.score??hypothesis.leverage??null,leverageHypothesis:hypothesis,evidenceRefs:s.evidenceRefs||[],provenanceRefs:s.provenanceRefs||[],resolutionState:s.resolutionState||'sufficient',memberEmphasized:Boolean((s.memberImportance??s.triage?.memberImportance)!=null&&Number(s.memberImportance??s.triage?.memberImportance)>=.67),inferred:false,relationships:s.relationships||[],feasibility:s.feasibility||null})}).sort((a,b)=>Number(b.leverage??0)-Number(a.leverage??0)||Number(b.materiality??0)-Number(a.materiality??0)||a.constructId.localeCompare(b.constructId))}const states=output.trace?.states||[];return states.filter(s=>{if(['deferred','nonIssue','escalated'].includes(s.resolutionState)||s.excluded)return false;const confidence=qualitativeConfidence(s);return CONFIDENCE_ORDER[confidence]>=CONFIDENCE_ORDER.MODERATE}).map(s=>{const importance=normalizedImportance(s),confidence=qualitativeConfidence(s),constructId=s.constructId;return Object.freeze({constructId,label:memberLabel(constructId),qualitativeConfidence:confidence,evidenceSupport:evidenceSupport(confidence),memberImportance:importance,resolutionState:s.resolutionState,memberEmphasized:importance!==null&&importance>=2,inferred:importance===null&&confidence!=='UNKNOWN',evidenceRefs:s.evidenceRefs||[],relationships:s.relationships||[],feasibility:s.feasibility||null})}).sort((a,b)=>Number(b.memberImportance??-1)-Number(a.memberImportance??-1)||CONFIDENCE_ORDER[b.qualitativeConfidence]-CONFIDENCE_ORDER[a.qualitativeConfidence]||a.constructId.localeCompare(b.constructId))}