import * as Discovery from '../../intelligence/discovery/discovery-engine.js';
import LIBRARY from '../../intelligence/discovery/intervention-library.js';
import {rankInterventionCandidates} from '../../intelligence/discovery/intervention-selector.js';

const STORAGE_KEY='el8_onboarding_discovery_v3';
const INTERVENTION_CONCERN=Object.freeze({money_pressure:'money',physical_condition:'health',poor_sleep:'sleep',low_energy:'energy',low_focus:'focus',work_pressure:'work',work_instability:'work',high_stress:'stress',relationship_strain:'relationships',low_support:'support',home_instability:'home',low_direction:'direction'});
const interventionConcern=id=>INTERVENTION_CONCERN[id]||id;
export function discoveryOptionsFromBaselineHandoff(handoff={}){const concerns=[...new Set(handoff.candidateConcerns||[])].filter(Boolean);return Object.freeze({concernIds:concerns,baselineHandoff:handoff})}
export function createDiscoverySession(options={}){const s=Discovery.session(options);if(options.baselineHandoff){s.baselineHandoff=options.baselineHandoff;const priorities=options.baselineHandoff.signals?.priorityConcerns||[];if(priorities.length)Discovery.seedImportance(s,Object.fromEntries(s.concernIds.map(id=>[id,priorities.includes(id)?3:1])))}return s}
export function createDiscoverySessionFromHandoff(handoff={}){return createDiscoverySession(discoveryOptionsFromBaselineHandoff(handoff))}
export function nextDiscoveryStep(session){return Discovery.next(session)}
export function answerDiscoveryQuestion(session,question,answerIds){return Discovery.answer(session,question,answerIds)}
export function submitDiscoveryTriage(session,importanceByConcern){return Discovery.triage(session,importanceByConcern)}
export function submitDiscoveryPriority(session,concernIds){return Discovery.prioritize(session,concernIds)}
export function resolveDiscoveryConcern(session,concernId,resolutionState,options={}){return Discovery.resolve(session,concernId,resolutionState,options)}
export function finishDiscovery(session){Discovery.complete(session);return discoveryOutput(session)}
export function discoveryOutput(session){return Object.freeze({trace:Discovery.trace(session),plan:Discovery.memberPlan(session),baselineHandoff:session.baselineHandoff||null})}
export function saveDiscoveryDraft(session){const serializable={...session,questionBank:undefined};sessionStorage.setItem(STORAGE_KEY,JSON.stringify(serializable));return session}
export function loadDiscoveryDraft(){const raw=sessionStorage.getItem(STORAGE_KEY);if(!raw)return null;try{return{...JSON.parse(raw),questionBank:Discovery.BANK}}catch{return null}}
export function clearDiscoveryDraft(){sessionStorage.removeItem(STORAGE_KEY)}
function timeBudgetMinutes(handoff={}){const t=handoff.signals?.feasibility?.time;return t==='<5 min'?5:t==='5–15 min'?15:t==='15–30 min'?30:t==='>30 min'?60:20}
function effortBudget(handoff={}){const f=handoff.signals?.feasibility||{},load=f.overall_load,readiness=f.readiness,t=timeBudgetMinutes(handoff);if(t<=5||load==='Overwhelming'||readiness==='Not ready')return 1;if(t<=15||load==='Difficult'||readiness==='Somewhat ready')return 2;return 3}
function concernPriority(action,handoff={}){const ids=handoff.signals?.priorityConcerns||[];return ids.includes(action.concernId)?2:0}
function oneConstraintScore(action,c,handoff){if(c==='Cost'||c==='limited_budget')return action.costBand==='free'?2:-2;if(c==='Time'||c==='limited_time')return Number(action.estimatedMinutes||999)<=timeBudgetMinutes(handoff)?2:-2;if(['Accessibility','mobility_accessibility','pain_or_symptoms'].includes(c))return action.accessibility==='movement-dependent'?-3:1;if(c==='Professional guidance'||c==='professional_guidance')return action.professionalSupport==='possible'?1:0;if(c==='direct_contact_unsafe')return action.requiresDirectContact?-4:1;return 0}
function constraintScore(action,handoff={}){const raw=handoff.signals?.constraints,constraints=(Array.isArray(raw)?raw:raw?[raw]:[]).filter(c=>!['None','Prefer not to say'].includes(c));return constraints.reduce((score,c)=>score+oneConstraintScore(action,c,handoff),0)}
function timeFit(action,handoff={}){const m=Number(action.estimatedMinutes||15),budget=timeBudgetMinutes(handoff);if(m<=budget)return 4;if(m<=budget*1.5)return 1;return -3}
function scorePlanAction(action,handoff={}){const effort=Number(action.effort??2)<=effortBudget(handoff)?2:-1,evidence=Number(action.evidenceQuality??0),priority=concernPriority(action,handoff),constraints=constraintScore(action,handoff),time=timeFit(action,handoff),selected=action.memberSelected?1:0;return Object.freeze({total:time+effort+priority+constraints+evidence+selected,time,effort,priority,constraints,evidence,selected})}
function rankPlanActions(actions=[],handoff={}){return [...actions].map((a,index)=>({...a,fitScore:scorePlanAction(a,handoff),_index:index})).sort((a,b)=>b.fitScore.total-a.fitScore.total||a._index-b._index).map(({_index,...a})=>a)}
function normalizedImportance(s={}){const raw=s.memberImportance;if(raw===null||raw===undefined)return null;if(typeof raw==='number')return raw;const map={low:0,moderate:1,high:2,'very-high':3};return map[raw]??null}
function evidenceConfidence(s={}){return Number(s.evidenceConfidence??s.confidence??0)}
function fitHandoff(handoff={},state={}){const base=handoff.signals||{},fit=state.feasibility||{},values=fit.values||{};const constraints=[...(Array.isArray(base.constraints)?base.constraints:base.constraints?[base.constraints]:[]),...(fit.constraints||[])];const feasibility={...(base.feasibility||{}),...values};if(values.scheduleFlexibility==='low'&&!feasibility.time)feasibility.time='<5 min';if(values.costSensitivity==='high'&&!constraints.includes('limited_budget'))constraints.push('limited_budget');if(values.accessibilityNeeds&&!constraints.includes('mobility_accessibility'))constraints.push('mobility_accessibility');if(values.professionalGuidanceRequired&&!constraints.includes('professional_guidance'))constraints.push('professional_guidance');return{...handoff,signals:{...base,constraints:[...new Set(constraints)],feasibility}}}
export function discoveryPriorityCandidates(output={}){const states=output.trace?.states||[],focusById=new Map((output.plan?.focus||[]).map((x,index)=>[x.concernId,{...x,rank:index+1}]));return states.filter(s=>{if(['deferred','nonIssue','escalated'].includes(s.resolutionState)||s.excluded)return false;const importance=normalizedImportance(s),evidence=evidenceConfidence(s);return (importance!==null&&importance>0)||evidence>0}).map(s=>{const focus=focusById.get(s.concernId),importance=normalizedImportance(s),evidence=evidenceConfidence(s),memberEmphasized=importance!==null&&importance>=2;return Object.freeze({concernId:s.concernId,label:focus?.label||s.label||s.concernId,evidenceConfidence:focus?.evidenceConfidence??evidence,memberImportance:importance,memberSelected:Boolean(focus?.memberSelected||s.memberSelected),resolutionState:s.resolutionState,recommended:Boolean(focus),memberEmphasized,inferred:importance===null&&evidence>0,evidenceRefs:s.evidenceRefs||[],feasibility:s.feasibility||null,rank:focus?.rank??999})}).sort((a,b)=>Number(b.recommended)-Number(a.recommended)||Number(b.memberImportance??-1)-Number(a.memberImportance??-1)||Number(b.evidenceConfidence)-Number(a.evidenceConfidence)||a.concernId.localeCompare(b.concernId))}
function actionFromCandidate(c,state){return{...c,concernId:state.concernId,concernLabel:state.label||state.concernId,evidenceConfidence:evidenceConfidence(state),memberSelected:true,feasibilityUsed:state.feasibility||null}}
export function actionsForConfirmedPriorities(output={},confirmedPriorities=[],handoff={}){const wanted=[...new Set(confirmedPriorities)].slice(0,2),states=new Map((output.trace?.states||[]).map(s=>[s.concernId,s])),actions=[];for(const id of wanted){const state=states.get(id);if(!state)continue;const interventionId=interventionConcern(id),selectorState={...state,concernId:interventionId};const ranked=rankInterventionCandidates(selectorState,LIBRARY,{limit:4,maxPerIntent:2});if(ranked.type==='candidates'){const fit=fitHandoff(handoff,state);actions.push(...rankPlanActions(ranked.candidates.map(c=>actionFromCandidate(c,state)),fit))}}return actions.sort((a,b)=>b.fitScore.total-a.fitScore.total)}
export function initialPlanProposal(session,{reviewDays=7,confirmedPriorities=null}={}){const output=discoveryOutput(session),source=output.plan,handoff=session.baselineHandoff||{},confirmed=Array.isArray(confirmedPriorities)&&confirmedPriorities.length?[...new Set(confirmedPriorities)].slice(0,2):[],focus=confirmed.map(id=>{const state=(output.trace?.states||[]).find(s=>s.concernId===id),existing=source.focus.find(x=>x.concernId===id);return existing||state?{concernId:id,label:existing?.label||state?.label||id,evidenceConfidence:existing?.evidenceConfidence??evidenceConfidence(state),memberSelected:true,resolutionState:existing?.resolutionState||state?.resolutionState||'triaged',feasibility:state?.feasibility||null}:null}).filter(Boolean),actions=confirmed.length?actionsForConfirmedPriorities(output,confirmed,handoff):rankPlanActions(source.focus.flatMap(item=>item.actions.map(action=>({...action,concernId:item.concernId,concernLabel:item.label,evidenceConfidence:item.evidenceConfidence,memberSelected:item.memberSelected}))),handoff),budget=effortBudget(handoff);return Object.freeze({status:source.status,reviewDays:[7,14].includes(Number(reviewDays))?Number(reviewDays):7,uncertainty:source.uncertainty,explanation:source.explanation,focus,candidatePriorities:discoveryPriorityCandidates(output),candidateActions:actions,confirmedPriorities:confirmed,selectedActionIds:[],fitContext:Object.freeze({effortBudget:budget,timeBudgetMinutes:timeBudgetMinutes(handoff),memberPriority:handoff.signals?.priorityConcerns||[],constraints:handoff.signals?.constraints||[],feasibility:handoff.signals?.feasibility||{}})})}
