import test from'node:test';import assert from'node:assert/strict';import{initialPlanFromBaseline}from'./initial-plan-bridge.js';

test('baseline seeds Discovery but cannot select an intervention',()=>{const p=initialPlanFromBaseline({condition_baseline:{Financial:'Struggling',Physical:'Okay'},member_priority:'Financial',functional_impact:['Financial'],worsening:['Financial'],feasibility:{time:'5–15 min',overall_load:'Manageable'}});assert.equal(p.status,'requires_discovery_handoff');assert.equal(p.discoverySeed.concernId,'money');assert.equal(p.discoverySeed.dimension,'Financial');assert.equal(p.discoverySeed.memberPrioritySelected,true);assert.equal(p.candidateActions.length,0);assert.equal(p.selectedActionIds.length,0);assert.equal(p.confirmedPriorities.length,0);assert.equal(p.requiresDiscoveryHandoff,true);assert.equal(p.requiresPlanSpecificAssessment,false);assert.match(p.explanation,/before choosing an action/i)});

test('low capacity is passed forward without manufacturing a plan',()=>{const p=initialPlanFromBaseline({condition_baseline:{Physical:'Needs attention'},member_priority:'Physical',feasibility:{time:'<5 min',overall_load:'Difficult'}});assert.equal(p.capacity.maxConcurrentActions,1);assert.equal(p.capacity.mode,'micro');assert.equal(p.discoverySeed.feasibility.capacity,'low');assert.equal(p.candidateActions.length,0)});

test('unclear baseline asks for clarification instead of guessing',()=>{const p=initialPlanFromBaseline({condition_baseline:{Physical:'Okay',Emotional:'Okay'},member_priority:'No preference',functional_impact:['None'],worsening:['Unsure'],feasibility:{}});assert.equal(p.status,'needs_clarification');assert.equal(p.discoverySeed,null);assert.equal(p.candidateActions.length,0);assert.equal(p.requiresDiscoveryHandoff,false)});

test('baseline bridge never assigns synthetic evidence confidence',()=>{const p=initialPlanFromBaseline({condition_baseline:{Financial:'Struggling'},member_priority:'Financial',functional_impact:['Financial'],feasibility:{}});assert.ok(p.candidatePriorities.every(x=>x.evidenceConfidence===undefined));assert.equal(p.discoverySeed.evidenceConfidence,undefined)});

test('the obsolete hard-coded money check-in cannot reappear from baseline',()=>{const p=initialPlanFromBaseline({condition_baseline:{Financial:'Struggling'},member_priority:'Financial',functional_impact:['Financial'],feasibility:{}});assert.equal(p.selectedActionIds.length,0);assert.ok(!JSON.stringify(p).includes('2-minute money check-in'));assert.ok(!JSON.stringify(p).includes('money-baseline-log'))});
