import test from 'node:test';
import assert from 'node:assert/strict';
import {projectOnboardingMemberState} from './member-state-projection.js';
import {applyMemberPriorityDecision} from './member-state-priority-decision.js';

const now='2026-08-27T00:00:00.000Z';
function discovery(){return{trace:{states:[{concernId:'poor_sleep',evidenceRefs:['e:sleep']},{concernId:'money_pressure',evidenceRefs:['e:money']}]},baselineHandoff:{signals:{indicatorSignals:[{id:'sleep',dimension:'Physical',value:2},{id:'health',dimension:'Physical',value:4},{id:'money',dimension:'Financial',value:1},{id:'mood',dimension:'Emotional',value:3}],feasibility:{capacity:'low',overall_load:'Difficult',time:'<5 min'}}}}}

test('completed Discovery establishes immutable initial baseline and supported problems before Prioritization',()=>{const s=projectOnboardingMemberState({memberId:'member:test',discoveryOutput:discovery(),now});assert.equal(s.baseline.status,'ESTABLISHED');assert.equal(s.baseline.establishedAt,now);assert.equal(s.baseline.sourceRevision,0);assert.deepEqual(s.baseline.evidenceRefs,['e:sleep','e:money']);assert.deepEqual(s.problems.map(p=>[p.id,p.status]),[['problem:poor_sleep','SUPPORTED'],['problem:financial_strain','SUPPORTED']]);assert.deepEqual(s.evidence.map(e=>e.id),['e:sleep','e:money']);assert.deepEqual(s.priorities,[]);assert.equal(s.revision,0);assert.equal(s.engagementBurden.capacity,'low')});
test('completed Discovery projects qualitative dimension conditions into immutable baseline',()=>{const s=projectOnboardingMemberState({memberId:'member:test',discoveryOutput:discovery(),now});assert.equal(s.dimensions.physical.condition,'Attention');assert.equal(s.dimensions.financial.condition,'Attention');assert.equal(s.dimensions.emotional.condition,'Stable');assert.equal(s.dimensions.physical.updatedAt,now);assert.deepEqual(s.baseline.dimensionSnapshots,s.dimensions)});
test('multiple opening indicators use the most attention-requiring supported condition for a dimension',()=>{const s=projectOnboardingMemberState({memberId:'member:test',discoveryOutput:discovery(),now});assert.equal(s.dimensions.physical.condition,'Attention')});
test('Going well establishes Healthy rather than Thriving from a single opening signal',()=>{const d={trace:{states:[]},baselineHandoff:{signals:{indicatorSignals:[{id:'social',dimension:'Social',value:5}],feasibility:{}}}};const s=projectOnboardingMemberState({memberId:'member:test',discoveryOutput:d,now});assert.equal(s.dimensions.social.condition,'Healthy')});
test('legacy dimension evidence is fallback only when signal-native dimension evidence is absent',()=>{const d={trace:{states:[]},baselineHandoff:{signals:{indicatorSignals:[{id:'sleep',dimension:'Physical',value:4}],legacy:{dimensionSignals:[{dimension:'Physical',condition:'Struggling'},{dimension:'Social',condition:'Going well'},{dimension:'Spiritual',condition:'Very strong'}]},feasibility:{}}}};const s=projectOnboardingMemberState({memberId:'member:test',discoveryOutput:d,now});assert.equal(s.dimensions.physical.condition,'Healthy');assert.equal(s.dimensions.social.condition,'Healthy');assert.equal(s.dimensions.spiritual.condition,'Thriving')});
test('Member State does not infer capacity from manageability or time',()=>{const s=projectOnboardingMemberState({memberId:'member:test',discoveryOutput:{trace:{states:[]},baselineHandoff:{signals:{feasibility:{overall_load:'Overwhelming',time:'<5 min'}}}},now});assert.equal(s.engagementBurden.capacity,null);assert.equal(s.engagementBurden.manageability,'Overwhelming')});
test('member confirmation is a later canonical transition and does not establish or rewrite baseline',()=>{const baseline=projectOnboardingMemberState({memberId:'member:test',discoveryOutput:discovery(),now});const snapshot=structuredClone(baseline.baseline);const s=applyMemberPriorityDecision(baseline,['money_pressure','poor_sleep'],{at:'2026-08-27T00:05:00.000Z'});assert.deepEqual(s.priorities.map(p=>[p.id,p.problemId,p.status,p.rank]),[['priority:financial_strain','problem:financial_strain','ACCEPTED',1],['priority:poor_sleep','problem:poor_sleep','ACCEPTED',2]]);assert.equal(s.revision,1);assert.equal(s.history.at(-1).type,'PRIORITIES_UPDATED');assert.deepEqual(s.baseline,snapshot);assert.equal(baseline.priorities.length,0)});
test('Prioritization requires the completed Discovery baseline boundary',()=>{const baseline=projectOnboardingMemberState({memberId:'member:test',discoveryOutput:discovery(),now});baseline.baseline.status='NOT_ESTABLISHED';assert.throws(()=>applyMemberPriorityDecision(baseline,['poor_sleep'],{at:now}),/completed Discovery baseline/)});
test('priority confirmation cannot invent an unsupported problem',()=>{const baseline=projectOnboardingMemberState({memberId:'member:test',discoveryOutput:discovery(),now});assert.throws(()=>applyMemberPriorityDecision(baseline,['stress'],{at:now}),/supported problem/)});
test('projection accepts already canonical problem ids without inventing another namespace',()=>{const d={trace:{states:[{concernId:'problem:stress',evidenceRefs:['e:stress']}]},baselineHandoff:{signals:{feasibility:{}}}};const s=projectOnboardingMemberState({memberId:'member:test',discoveryOutput:d,now});assert.equal(s.problems[0].id,'problem:stress')});
test('obsolete Discovery output shapes cannot establish canonical Member State problems',()=>{for(const key of ['ranked','selected','priorityCandidates','candidates']){const s=projectOnboardingMemberState({memberId:'member:test',discoveryOutput:{[key]:[{concernId:'poor_sleep',evidenceRefs:['e:sleep']}],baselineHandoff:{signals:{feasibility:{capacity:'medium'}}}},now});assert.deepEqual(s.problems,[],key);assert.deepEqual(s.evidence,[],key);assert.deepEqual(s.baseline.evidenceRefs,[],key)}});
