import test from 'node:test';import assert from 'node:assert/strict';import{createDiscoveryFromSnapshot,discoveryPrioritizationInput,planningHandoffFromDiscovery,buildOnboardingPlan}from'./planning-pipeline.js';import{appendObservation,setResolution}from'../../intelligence/discovery/discovery-controller.js';
const handoff=(constructIds,priority=constructIds)=>({candidateConstructs:constructIds,signals:{priorityConstructs:priority,feasibility:{}},uncertainty:{requiresDiscoveryConfirmation:true}});
const establish=(s,id)=>{appendObservation(s,{concernId:id,questionId:`discovery-${id}`,effects:[{type:'evidence',target:id,polarity:'supports',strength:.9},{type:'importance',target:id,value:'high'}]});setResolution(s,id,'sufficient',{driverKnown:true});return s};
test('snapshot feasibility preserves uncertainty instead of defaulting to medium',()=>{const s=createDiscoveryFromSnapshot(handoff(['PHYSICAL_CONDITION']));assert.equal(s.facts.snapshotFeasibility.capacity,'unknown')});
test('legacy concern IDs cannot enter construct-state Discovery',()=>{assert.equal(createDiscoveryFromSnapshot(handoff(['money_pressure','poor_sleep'])),null)});
test('resolved construct becomes Prioritization candidate without translation',()=>{const s=establish(createDiscoveryFromSnapshot(handoff(['SLEEP_QUALITY'])),'SLEEP_QUALITY');const h=planningHandoffFromDiscovery(s,{memberStateRevision:2});assert.equal(h.prioritization.recommended[0].constructId,'SLEEP_QUALITY');assert.equal(h.prioritization.memberStateRevision,2)});
test('valid focus without a generic Action remains a Prioritization candidate',()=>{const s=establish(createDiscoveryFromSnapshot(handoff(['ENERGY_FUNCTION'])),'ENERGY_FUNCTION');const h=discoveryPrioritizationInput(s,{memberStateRevision:5});assert.deepEqual(h.candidates.map(x=>x.constructId),['ENERGY_FUNCTION']);assert.equal(h.candidates[0].planningContract.disposition,'conditional_action')});
test('unavailable Action does not suppress a valid focus upstream',()=>{const s=establish(createDiscoveryFromSnapshot(handoff(['RELATIONSHIP_STRAIN'])),'RELATIONSHIP_STRAIN');const h=discoveryPrioritizationInput(s,{memberStateRevision:6});assert.deepEqual(h.candidates.map(x=>x.constructId),['RELATIONSHIP_STRAIN']);assert.ok(h.candidates[0].planningContract)});
test('full onboarding chain requires member Focus confirmation before Planning',()=>{const s=establish(createDiscoveryFromSnapshot(handoff(['SLEEP_QUALITY'])),'SLEEP_QUALITY');const out=buildOnboardingPlan({session:s,memberStateRevision:3,focusDecisions:[{constructId:'SLEEP_QUALITY',decision:'accepted'}]});assert.equal(out.confirmation.accepted[0].constructId,'SLEEP_QUALITY');assert.equal(out.plan.status,'proposed');assert.ok(out.plan.proposedActions.length>=1);assert.ok(out.plan.proposedActions.every(x=>!('intervention_id'in x)&&!('problem_id'in x)))});
