import test from'node:test';import assert from'node:assert/strict';import{activateCanonicalOnboarding}from'./plan-activation-transaction.js';
const memberState={schemaVersion:'3.0.0',revision:2,activePlanRef:null};const next={schemaVersion:'3.0.0',revision:3,activePlanRef:{planId:'db-plan-1'},activeActionIds:['PHY-001']};const plan={status:'proposed'};const persistPlan=async()=>({id:'db-plan-1'});const applyPlan=(_base,_plan,{planId}={})=>{assert.equal(planId,'db-plan-1');return next};
test('persists canonical Plan before Member State activation then completes lifecycle',async()=>{const calls=[];const result=await activateCanonicalOnboarding({userId:'u1',memberState,plan,applyPlan,loadState:async()=>({revision:2,state:memberState}),persistPlan:async x=>{calls.push(['plan',x.userId]);return{id:'db-plan-1'}},persistState:async x=>{calls.push(['state',x.expectedRevision,x.state.revision]);return{revision:3,state:next}},completeOnboarding:async()=>calls.push(['complete'])});assert.equal(result,next);assert.deepEqual(calls,[['plan','u1'],['state',2,3],['complete']])});
test('same-session retry detects durable Plan ref and only retries completion',async()=>{const calls=[];const result=await activateCanonicalOnboarding({userId:'u1',memberState,plan,applyPlan:()=>{throw new Error('must not reapply')},loadState:async()=>({revision:3,state:next}),persistPlan:async()=>{throw new Error('must not persist plan')},persistState:async()=>{throw new Error('must not persist state')},completeOnboarding:async()=>calls.push('complete')});assert.equal(result,next);assert.deepEqual(calls,['complete'])});
test('creates initial v3 state before persisting and activating Plan',async()=>{const calls=[],initial={schemaVersion:'3.0.0',revision:0,activePlanRef:null},planned={schemaVersion:'3.0.0',revision:1,activePlanRef:{planId:'db-plan-1'}};await activateCanonicalOnboarding({userId:'u1',memberState:initial,plan,applyPlan:(_base,_plan,{planId})=>{assert.equal(planId,'db-plan-1');return planned},loadState:async()=>null,persistPlan:async()=>{calls.push(['plan']);return{id:'db-plan-1'}},persistState:async x=>{calls.push(['state',x.expectedRevision,x.state.revision]);return{revision:x.state.revision,state:x.state}},completeOnboarding:async()=>{}});assert.deepEqual(calls,[['state',-1,0],['plan'],['state',0,1]])});
test('verifies initial state persistence before attempting Plan persistence',async()=>{const initial={schemaVersion:'3.0.0',revision:0,activePlanRef:null};await assert.rejects(()=>activateCanonicalOnboarding({userId:'u1',memberState:initial,plan,applyPlan:()=>{throw new Error('must not apply')},loadState:async()=>null,persistPlan:async()=>{throw new Error('must not persist plan')},persistState:async()=>({revision:1,state:{revision:1}}),completeOnboarding:async()=>{}}),/Stored Member State revision mismatch/)});
test('rejects unrelated stored revision before Plan persistence',async()=>{await assert.rejects(()=>activateCanonicalOnboarding({userId:'u1',memberState,plan,applyPlan,loadState:async()=>({revision:4,state:{schemaVersion:'3.0.0',revision:4,activePlanRef:null}}),persistPlan,persistState:async()=>{},completeOnboarding:async()=>{}}),/revision conflict/)});
test('requires durable Plan ID before applying activation',async()=>{await assert.rejects(()=>activateCanonicalOnboarding({userId:'u1',memberState,plan,applyPlan:()=>{throw new Error('must not apply')},loadState:async()=>({revision:2,state:memberState}),persistPlan:async()=>({}),persistState:async()=>{},completeOnboarding:async()=>{}}),/Plan ID required/)});
test('applies Plan to durable state when caller snapshot has same revision but stale content',async()=>{const caller={schemaVersion:'3.0.0',revision:2,activePlanRef:null,focusDecisions:{SLEEP_QUALITY:{decision:'accepted'}}};const durable={...caller,focusDecisions:{...caller.focusDecisions,ACTIVITY_LEVEL:{decision:'accepted'}},memberContext:{capacity:'low'}};let appliedBase=null;const planned={...durable,revision:3,activePlanRef:{planId:'db-plan-1'}};await activateCanonicalOnboarding({userId:'u1',memberState:caller,plan,applyPlan:(base,_plan,{planId})=>{appliedBase=base;assert.equal(planId,'db-plan-1');return planned},loadState:async()=>({revision:2,state:durable}),persistPlan,persistState:async x=>{assert.equal(x.expectedRevision,2);assert.equal(x.state,planned);return{revision:3,state:planned}},completeOnboarding:async()=>{}});assert.equal(appliedBase,durable);assert.ok(appliedBase.focusDecisions.ACTIVITY_LEVEL);assert.equal(appliedBase.memberContext.capacity,'low')});
