import BANK from './canonical-bank.js';
const prefix=p=>Object.freeze(BANK.filter(q=>q.id.startsWith(p)));
export const GENERAL_QUESTIONS=prefix('GEN');
export const PHYSICAL_QUESTIONS=Object.freeze(BANK.filter(q=>q.id.startsWith('PHY')&&q.id!=='PHY500'));
export const EMOTIONAL_QUESTIONS=prefix('EMT');
export const FINANCIAL_QUESTIONS=prefix('FIN');
export const OCCUPATIONAL_QUESTIONS=prefix('OCC');
export const SOCIAL_QUESTIONS=prefix('SOC');
export const ENVIRONMENTAL_QUESTIONS=prefix('ENV');
export const INTELLECTUAL_QUESTIONS=prefix('INT');
export const SPIRITUAL_QUESTIONS=prefix('SPT');
export const CROSS_DIMENSIONAL_QUESTIONS=Object.freeze(BANK.filter(q=>q.id==='PHY500'||q.id.startsWith('XDM')));
export const CORE_QUESTIONS=Object.freeze([]);
