import BANK,{CANONICAL_DISCOVERY_QUESTION_BY_ID} from './canonical-bank.js';
export const DISCOVERY_QUESTIONS=BANK;
export const DISCOVERY_QUESTION_BY_ID=CANONICAL_DISCOVERY_QUESTION_BY_ID;
export default DISCOVERY_QUESTIONS;
