import { EMOTIONAL_QUESTION_BANK } from './emotional.js';
import { ENVIRONMENTAL_QUESTION_BANK } from './environmental.js';
import { FINANCIAL_QUESTION_BANK } from './financial.js';
import { GENERAL_QUESTION_BANK } from './general.js';
import { INTELLECTUAL_QUESTION_BANK } from './intellectual.js';
import { OCCUPATIONAL_QUESTION_BANK } from './occupational.js';
import { PHYSICAL_QUESTION_BANK } from './physical.js';
import { SAFETY_QUESTION_BANK } from './safety.js';
import { SOCIAL_QUESTION_BANK } from './social.js';
import { SPIRITUAL_QUESTION_BANK } from './spiritual.js';
import { CROSS_DIMENSIONAL_QUESTION_BANK } from './cross-dimensional.js';
export { QUESTION_BANK_COLUMNS } from './schema.js';

export const QUESTION_BANK = Object.freeze([
  ...EMOTIONAL_QUESTION_BANK,
  ...ENVIRONMENTAL_QUESTION_BANK,
  ...FINANCIAL_QUESTION_BANK,
  ...GENERAL_QUESTION_BANK,
  ...INTELLECTUAL_QUESTION_BANK,
  ...OCCUPATIONAL_QUESTION_BANK,
  ...PHYSICAL_QUESTION_BANK,
  ...SAFETY_QUESTION_BANK,
  ...SOCIAL_QUESTION_BANK,
  ...SPIRITUAL_QUESTION_BANK,
  ...CROSS_DIMENSIONAL_QUESTION_BANK,
]);

export {
  EMOTIONAL_QUESTION_BANK,
  ENVIRONMENTAL_QUESTION_BANK,
  FINANCIAL_QUESTION_BANK,
  GENERAL_QUESTION_BANK,
  INTELLECTUAL_QUESTION_BANK,
  OCCUPATIONAL_QUESTION_BANK,
  PHYSICAL_QUESTION_BANK,
  SAFETY_QUESTION_BANK,
  SOCIAL_QUESTION_BANK,
  SPIRITUAL_QUESTION_BANK,
  CROSS_DIMENSIONAL_QUESTION_BANK,
};
