import { Q } from './core.js';

// Social owns relationship strain, perceived support, companionship and isolation.
// Keep these constructs distinct: having people available, feeling supported, conflict,
// loneliness and ability to participate socially are related but not interchangeable.
// Feasibility answers describe member-reported constraints or preferences, not causes.
// These are EL8-authored hypothesis items informed by PROMIS social-health constructs;
// they are not PROMIS items and do not inherit PROMIS scoring or validation.
export const SOCIAL_QUESTIONS = Object.freeze([
  Q('R1', 'state-probe', 'During the past 7 days, how often did tension or conflict in a close relationship bother you?', ['relationship_strain'], [['never', 'Never', { relationship_strain: -0.65 }], ['rarely', 'Rarely', { relationship_strain: -0.25 }], ['sometimes', 'Sometimes', { relationship_strain: 0.3 }], ['often', 'Often', { relationship_strain: 0.65 }], ['always', 'Almost always', { relationship_strain: 0.8 }], ['na', 'Not applicable', {}], ['unsure', 'Not sure', {}]], 0.16),
  Q('R2', 'impact-probe', 'During the past 7 days, how much did relationship problems interfere with your usual activities or ability to focus?', ['relationship_strain'], [['none', 'Not at all', { relationship_strain: -0.35 }], ['little', 'A little', { relationship_strain: 0.15 }], ['some', 'Somewhat', { relationship_strain: 0.4 }], ['much', 'A lot', { relationship_strain: 0.7 }], ['na', 'Not applicable', {}], ['unsure', 'Not sure', {}]], 0.16),
  Q('R3', 'discriminator', 'What has been difficult in your close relationships lately? Select any that fit.', ['relationship_strain', 'low_support'], [['conflict', 'Conflict or repeated tension', { relationship_strain: 0.55 }], ['communication', 'Communication or feeling misunderstood', { relationship_strain: 0.4 }], ['trust', 'Trust or uncertainty about the relationship', { relationship_strain: 0.5 }], ['distance', 'Not enough contact or closeness', { low_support: 0.3 }], ['support', 'Not getting the support I need', { low_support: 0.55 }], ['boundaries', 'Maintaining boundaries or enough distance', { relationship_strain: 0.25 }], ['other', 'Something else', {}], ['none', 'Nothing significant', { relationship_strain: -0.35 }], ['unsure', 'Not sure', {}]], 0.2, 'multi'),
  Q('R4', 'feasibility-probe', 'If you wanted to improve or protect a relationship, what would EL8 need to account for? Select any that fit.', ['relationship_strain'], [['other_person', 'The other person may not want to participate', {}], ['safety', 'Direct contact or confrontation would not feel safe or appropriate', {}], ['distance', 'Distance or limited contact', {}], ['time', 'Limited time or conflicting schedules', { schedule_disruption: 0.08 }], ['boundaries', 'I need to maintain distance or boundaries', {}], ['not_change', 'I do not want to change this relationship right now', {}], ['none', 'No obvious limitation', {}], ['unsure', 'Not sure', {}]], 0.11, 'multi'),
  Q('S1', 'support-probe', 'If you needed emotional support right now, is there someone you could turn to?', ['low_support'], [['yes', 'Yes, reliably', { low_support: -0.65 }], ['maybe', 'Probably, but not reliably', { low_support: 0.2 }], ['no', 'Not really', { low_support: 0.7 }], ['prefer_not', 'I would rather not seek support right now', {}], ['unsure', 'Not sure', {}]], 0.14),
  Q('S2', 'isolation-probe', 'During the past 7 days, how often did you feel isolated or disconnected from other people?', ['lonely'], [['never', 'Never', { lonely: -0.65 }], ['rarely', 'Rarely', { lonely: -0.25 }], ['sometimes', 'Sometimes', { lonely: 0.3 }], ['often', 'Often', { lonely: 0.65 }], ['always', 'Almost always', { lonely: 0.8 }], ['unsure', 'Not sure', {}]], 0.16),
  Q('S3', 'support-discriminator', 'What kind of support or connection would be most useful right now?', ['low_support', 'lonely'], [['emotional', 'Someone who will listen or understand', { low_support: 0.35 }], ['practical', 'Practical help with something', { low_support: 0.3 }], ['advice', 'Advice or useful information', { low_support: 0.25 }], ['companionship', 'Someone to spend time or do things with', { lonely: 0.35 }], ['belonging', 'Feeling included in a group or community', { lonely: 0.4 }], ['none', 'I do not need more support or connection right now', { low_support: -0.4, lonely: -0.25 }], ['unsure', 'Not sure', {}]], 0.18),
  Q('S4', 'feasibility-probe', 'Which things, if any, currently limit access to support or social connection? Select any that fit.', ['low_support', 'lonely'], [['availability', 'The people I would turn to are not available', { low_support: 0.18 }], ['trust', 'I do not feel comfortable opening up', {}], ['time', 'Time or schedule', { schedule_disruption: 0.08 }], ['access', 'Distance, transportation, mobility, or access', {}], ['energy', 'I do not have much energy for social effort', { low_energy: 0.1 }], ['conflict', 'Conflict or tension makes contact difficult', { relationship_strain: 0.18 }], ['preference', 'I prefer more time alone right now', {}], ['none', 'Nothing obvious', {}], ['unsure', 'Not sure', {}]], 0.11, 'multi'),
]);
