// GENERATED FROM RECONCILED EL8 DRIVE AUTHORITY — 2026-09-01
// Canonical semantic Signal constructs.
// Do not hand-edit generated registry content; reconcile in Drive and regenerate.

export const SIGNALS = Object.freeze([
  {
    "Signal ID": "EMOTIONAL_STATE",
    "Signal": "Emotional state",
    "Primary Dimension": "Emotional",
    "Affected Dimensions": "Physical, Social, Occupational, Financial",
    "Definition": "Current overall emotional valence/distress.",
    "Temporal Sensitivity": "Daily",
    "Likely Causes": "Possible contributors/associations: stress, sleep, relationships, work, finances; none inferred without separate member evidence.",
    "Likely Consequences": "Possible associated outcomes: functioning, sleep, connection, motivation; no downstream construct is created from EMOTIONAL_STATE alone.",
    "Decision Relevance": "Determines whether deeper driver discrimination is warranted.",
    "Evidence Strength": "High",
    "Source IDs": "SRC000001,SRC000002",
    "Evidence Class": "Direct construct evidence",
    "Runtime / Effect Keys": "emotional state / distress effects; stress only when directly reported",
    "Direct Evidence Rule": "Only explicit current-state answers establish EMOTIONAL_STATE.",
    "Hypothesis / Relationship Rule": "Sleep, work, money, relationships and other links are hypotheses unless separately supported by member evidence.",
    "Feasibility / Constraint Rule": "Constraints may explain context but do not establish emotional state.",
    "System / Safety Boundary": "Severe emotional patterns may be Safety-relevant context only under governed deterministic rules; no risk score.",
    "Governed Mapping Status": "Mapped",
    "Reconciliation Notes": "EMOTIONAL_STATE is the canonical conceptual signal for emotional state. Question namespace and signal semantics are intentionally distinct; runtime/effect-key normalization remains an implementation task after the Drive design freeze.",
    "Audit Status": "Keep"
  },
  {
    "Signal ID": "PRESSURE_PATTERN",
    "Signal": "Pressure / stress pattern",
    "Primary Dimension": "Emotional",
    "Affected Dimensions": "Physical, Occupational, Financial, Social",
    "Definition": "Nature and source pattern of current pressure.",
    "Temporal Sensitivity": "Daily-weekly",
    "Likely Causes": "Possible contexts/contributors: workload, money, relationships, health, uncertainty; source answers remain member-reported hypotheses.",
    "Likely Consequences": "Possible associated outcomes: emotional state, sleep, functioning, coping; each requires separate direct evidence.",
    "Decision Relevance": "Discriminates which driver/context warrants follow-up evidence; any focus or intervention decision remains with the owning canonical stage.",
    "Evidence Strength": "High",
    "Source IDs": "SRC000001,SRC000006,SRC000007",
    "Evidence Class": "Direct construct + member-reported context",
    "Runtime / Effect Keys": "stress; work/money/people/support/home/health/sleep/energy associations",
    "Direct Evidence Rule": "Direct stress-state answer establishes pressure/stress evidence.",
    "Hypothesis / Relationship Rule": "Reported source/context answers create member hypotheses, not causal findings.",
    "Feasibility / Constraint Rule": "Fit barriers remain separate constraint evidence.",
    "System / Safety Boundary": "Contextual severity may trigger minimum Safety clarification only when governed criteria are met.",
    "Governed Mapping Status": "Mapped",
    "Reconciliation Notes": "Canonical stress construct. Runtime stress maps directly to PRESSURE_PATTERN; reported work, money, relationship, support, home, health, sleep and energy contexts remain member-reported associations unless independently established.",
    "Audit Status": "Keep"
  },
  {
    "Signal ID": "SLEEP_QUALITY",
    "Signal": "Sleep quality / restoration",
    "Primary Dimension": "Physical",
    "Affected Dimensions": "Emotional, Intellectual, Occupational",
    "Definition": "Whether sleep is adequate and restorative.",
    "Temporal Sensitivity": "Daily",
    "Likely Causes": "Possible contributors/associations: stress, schedule, environment, health, habits; none inferred from sleep state alone.",
    "Likely Consequences": "Possible associated outcomes: emotional wellbeing, focus, energy and performance; each requires separate direct evidence.",
    "Decision Relevance": "High-value bridge signal; poor sleep can justify driver investigation.",
    "Evidence Strength": "High",
    "Source IDs": "SRC000003,SRC000004",
    "Evidence Class": "Direct construct evidence",
    "Runtime / Effect Keys": "poor_sleep",
    "Direct Evidence Rule": "Explicit sleep-state answers establish SLEEP_QUALITY.",
    "Hypothesis / Relationship Rule": "stress, schedule, environment, activity and health links require member evidence plus Evidence Bank support.",
    "Feasibility / Constraint Rule": "Sleep feasibility/barriers are planning evidence, not sleep severity.",
    "System / Safety Boundary": "Poor sleep alone is not an acute Safety trigger.",
    "Governed Mapping Status": "Mapped",
    "Reconciliation Notes": "Use EVD000001/EVD000007/EVD000008/EVD000009/EVD000010 only as governed relationship priors.",
    "Audit Status": "Keep"
  },
  {
    "Signal ID": "ENERGY_FUNCTION",
    "Signal": "Energy / physical functioning",
    "Primary Dimension": "Physical",
    "Affected Dimensions": "Occupational, Intellectual, Emotional",
    "Definition": "Capacity to carry out intended daily activity.",
    "Temporal Sensitivity": "Daily",
    "Likely Causes": "Possible contributors/associations: sleep, illness/physical condition, activity, nutrition, emotional state; none inferred without separate evidence.",
    "Likely Consequences": "Possible associated outcomes: work functioning, focus and movement; ENERGY_FUNCTION alone does not establish them.",
    "Decision Relevance": "Distinguishes physical constraint from motivation, feasibility or competing-priority explanations without selecting the resulting focus.",
    "Evidence Strength": "High",
    "Source IDs": "SRC000001",
    "Evidence Class": "Direct construct evidence",
    "Runtime / Effect Keys": "low_energy",
    "Direct Evidence Rule": "Explicit energy/function answers establish ENERGY_FUNCTION.",
    "Hypothesis / Relationship Rule": "Sleep, activity, stress, health and schedule are possible contributors, never inferred causes from co-occurrence.",
    "Feasibility / Constraint Rule": "Energy constraints can govern action feasibility.",
    "System / Safety Boundary": "Low energy alone is not an emergency threshold.",
    "Governed Mapping Status": "Mapped",
    "Reconciliation Notes": "EVD000006 supports activity→energy average intervention effect; personalized confidence requires member evidence.",
    "Audit Status": "Keep"
  },
  {
    "Signal ID": "LONELINESS",
    "Signal": "Loneliness / belonging",
    "Primary Dimension": "Social",
    "Affected Dimensions": "Emotional",
    "Definition": "Subjective adequacy and quality of social connection, distinct from contact frequency.",
    "Temporal Sensitivity": "Daily-weekly",
    "Likely Causes": "Possible contexts/associations: objective isolation/contact, relationship quality and belonging; none substitutes for subjective loneliness evidence.",
    "Likely Consequences": "Possible associated outcomes: emotional wellbeing, sleep and broader health-related quality of life; each requires separate evidence.",
    "Decision Relevance": "Separates social exposure from meaningful connection.",
    "Evidence Strength": "High",
    "Source IDs": "SRC000005",
    "Evidence Class": "Direct construct evidence",
    "Runtime / Effect Keys": "lonely",
    "Direct Evidence Rule": "Only subjective loneliness/belonging answers establish LONELINESS.",
    "Hypothesis / Relationship Rule": "Contact frequency, relationship strain and low support remain separate constructs; low_support maps to SUPPORT_AVAILABILITY.",
    "Feasibility / Constraint Rule": "Preference/access constraints are separate from loneliness.",
    "System / Safety Boundary": "Isolation/loneliness may be contextual Safety information only after legitimate Safety activation; not proof of risk.",
    "Governed Mapping Status": "Mapped",
    "Reconciliation Notes": "Canonical loneliness construct. SUPPORT_AVAILABILITY now owns low_support; RELATIONSHIP_STRAIN owns relationship conflict/strain.",
    "Audit Status": "Keep"
  },
  {
    "Signal ID": "JOB_SECURITY",
    "Signal": "Work / income security",
    "Primary Dimension": "Occupational",
    "Affected Dimensions": "Financial, Emotional",
    "Definition": "Perceived stability of employment or productive income pathway.",
    "Temporal Sensitivity": "Weekly-event",
    "Likely Causes": "Possible contexts: unemployment, employment insecurity/precarity and organizational change; distinguish actual status from perceived security.",
    "Likely Consequences": "Possible associated outcomes: financial strain, emotional distress and Planning constraints; each remains separately evidenced.",
    "Decision Relevance": "Distinguishes progress problem from security threat.",
    "Evidence Strength": "High",
    "Source IDs": "SRC000006",
    "Evidence Class": "Direct construct evidence",
    "Runtime / Effect Keys": "work_instability; unemployment/employment insecurity variants",
    "Direct Evidence Rule": "Explicit employment/security answers establish JOB_SECURITY.",
    "Hypothesis / Relationship Rule": "Money/stress/direction links are separate hypotheses.",
    "Feasibility / Constraint Rule": "Schedule/fit/opportunity constraints are not security evidence.",
    "System / Safety Boundary": "No automatic Safety meaning.",
    "Governed Mapping Status": "Mapped",
    "Reconciliation Notes": "Canonical work/income-security construct. work_instability and explicit unemployment/employment-insecurity evidence map here; workload, fit, direction, opportunity and schedule remain separate evidence or constraints.",
    "Audit Status": "Keep"
  },
  {
    "Signal ID": "FINANCIAL_STRAIN",
    "Signal": "Financial strain",
    "Primary Dimension": "Financial",
    "Affected Dimensions": "Emotional, Occupational",
    "Definition": "Difficulty meeting needs/obligations and felt financial pressure.",
    "Temporal Sensitivity": "Daily-event",
    "Likely Causes": "Possible contributors/contexts: debt, low income, unexpected costs and instability; contributor identity does not itself add FINANCIAL_STRAIN severity.",
    "Likely Consequences": "Possible associated outcomes: emotional pressure, reduced perceived control and constrained choices; FINANCIAL_CONTROL and other constructs require separate evidence.",
    "Decision Relevance": "Tests whether financial strain is a plausible material driver requiring deeper evidence; any focus or stabilization action remains a governed downstream decision.",
    "Evidence Strength": "High",
    "Source IDs": "SRC000007",
    "Evidence Class": "Direct construct evidence",
    "Runtime / Effect Keys": "money_pressure",
    "Direct Evidence Rule": "Explicit Financial state or condition evidence may establish FINANCIAL_STRAIN, but the construct is composite rather than additive: subjective pressure (FIN001), required-expense coverage (FIN002), choice limitation (FIN004), payment urgency (FIN005), resilience (FIN006), and at-risk obligations (FIN007) are distinct facets. Multiple facets increase confidence/breadth and may affect urgency, but must not be blindly summed as independent severity increments.",
    "Hypothesis / Relationship Rule": "FIN003 contributor answers and cross-dimensional money mentions identify context or relationships only; they do not add FINANCIAL_STRAIN severity. JOB_SECURITY, EMOTIONAL_STATE, PHYSICAL_CONDITION, ENVIRONMENTAL_INTERFERENCE, HOUSING_STABILITY and other linked constructs require their own direct evidence.",
    "Feasibility / Constraint Rule": "Cost sensitivity, low-cost preferences, access barriers and other resource constraints may govern Planning fit without increasing FINANCIAL_STRAIN. A member can prefer a low-cost plan without being financially strained.",
    "System / Safety Boundary": "No automatic Safety meaning. At-risk housing, utilities, food, transport, healthcare or debt payments can change practical urgency and routing, but Safety confirmation remains governed separately.",
    "Governed Mapping Status": "Mapped",
    "Reconciliation Notes": "Reconciled 2026-08-30: FINANCIAL_STRAIN uses a facet-based composite architecture. FIN001/002/004/005/006/007 provide distinct direct Financial evidence; FIN003 is contributor/context evidence only. Repeated evidence across facets strengthens confidence and characterizes breadth/urgency without additive score inflation. Negative evidence on one facet cannot erase independently supported strain on another.",
    "Audit Status": "Keep"
  },
  {
    "Signal ID": "FINANCIAL_CONTROL",
    "Signal": "Financial control / agency",
    "Primary Dimension": "Financial",
    "Affected Dimensions": "Emotional",
    "Definition": "Perceived ability to understand and influence one's financial situation.",
    "Temporal Sensitivity": "Weekly",
    "Likely Causes": "Possible contexts: planning complexity, debt complexity and income predictability; none automatically establishes low perceived control.",
    "Likely Consequences": "Possible associated outcomes: coping, emotional distress and action readiness; each remains separately evidenced.",
    "Decision Relevance": "Separates objective constraint from actionable control gap.",
    "Evidence Strength": "Moderate-high",
    "Source IDs": "SRC000007",
    "Evidence Class": "Direct construct evidence",
    "Runtime / Effect Keys": "financial control / agency effects",
    "Direct Evidence Rule": "Only explicit perceived-control/agency answers establish FINANCIAL_CONTROL.",
    "Hypothesis / Relationship Rule": "Debt, income complexity and financial strain can explain context but do not automatically establish low control.",
    "Feasibility / Constraint Rule": "Objective money/time/access constraints remain separate feasibility evidence.",
    "System / Safety Boundary": "No automatic Safety meaning.",
    "Governed Mapping Status": "Mapped",
    "Reconciliation Notes": "Canonical financial-control construct. Keep perceived agency separate from FINANCIAL_STRAIN and from objective resource constraints.",
    "Audit Status": "Keep"
  },
  {
    "Signal ID": "ENVIRONMENTAL_INTERFERENCE",
    "Signal": "Environmental interference",
    "Primary Dimension": "Environmental",
    "Affected Dimensions": "Physical, Emotional, Social",
    "Definition": "Degree home or immediate surroundings interfere with usual daily functioning.",
    "Temporal Sensitivity": "Weekly-event",
    "Likely Causes": "Possible environmental factors: noise, crowding, privacy, physical conditions, access and location; factor identity is not interference severity.",
    "Likely Consequences": "Possible associated outcomes: activity, stress, sleep and connection; each linked construct requires separate direct evidence.",
    "Decision Relevance": "Identifies environmental interference as a potentially material driver while keeping housing stability and Safety separate.",
    "Evidence Strength": "Moderate-high",
    "Source IDs": "SRC000008",
    "Evidence Class": "Direct construct + factor-specific context",
    "Runtime / Effect Keys": "environmental_interference; environment factors",
    "Direct Evidence Rule": "Explicit Environmental interference evidence from ENV001 or equivalent direct environment-state evidence establishes ENVIRONMENTAL_INTERFERENCE. Factor-only answers identify conditions without automatically increasing severity.",
    "Hypothesis / Relationship Rule": "Sleep, stress, focus, activity and social spillover require both a specific Environmental factor and separate member evidence for the linked construct; contributor selections remain hypotheses.",
    "Feasibility / Constraint Rule": "Accessibility, transportation/location, modifiability and reliable-space barriers may be valid terminal Planning constraints without establishing greater ENVIRONMENTAL_INTERFERENCE.",
    "System / Safety Boundary": "ENV003 physical-safety answers are a separate contextual Safety class; Safety confirmation cannot be replaced by ordinary Environmental evidence.",
    "Governed Mapping Status": "Mapped",
    "Reconciliation Notes": "Reconciled 2026-08-31: ENVIRONMENTAL_INTERFERENCE is the governed interference construct. HOUSING_STABILITY is separate and must be established by its own direct evidence. Factor identity, feasibility/access constraints and contextual physical safety remain separate evidence classes.",
    "Audit Status": "Keep"
  },
  {
    "Signal ID": "HOUSING_STABILITY",
    "Signal": "Housing stability",
    "Primary Dimension": "Environmental",
    "Affected Dimensions": "Financial, Emotional",
    "Definition": "Security and continuity of the member's current housing in the near future.",
    "Temporal Sensitivity": "Weekly-event",
    "Likely Causes": "Possible contexts: affordability, tenancy or ownership uncertainty, temporary housing and other continuity threats; context alone does not establish severity.",
    "Likely Consequences": "Possible associated outcomes: financial pressure, emotional pressure and constrained choices; each linked construct requires separate direct evidence.",
    "Decision Relevance": "Separates housing continuity from general Environmental interference and from physical-safety context.",
    "Evidence Strength": "High",
    "Source IDs": "SRC000008",
    "Evidence Class": "Direct construct evidence",
    "Runtime / Effect Keys": "housing_stability",
    "Direct Evidence Rule": "Only explicit housing-security or continuity evidence from ENV004 or equivalent direct evidence establishes HOUSING_STABILITY.",
    "Hypothesis / Relationship Rule": "ENV002 housing-uncertainty factor identity may route clarification but does not duplicate ENV004 state evidence. Financial strain and Environmental interference require their own evidence.",
    "Feasibility / Constraint Rule": "Access, affordability and ability-to-change constraints can shape Planning without being treated as additional HOUSING_STABILITY severity.",
    "System / Safety Boundary": "Housing instability may change practical urgency, but acute Safety disposition remains governed separately.",
    "Governed Mapping Status": "Mapped",
    "Reconciliation Notes": "Added 2026-08-31 to align the Signals registry with the governed Environmental taxonomy and ENV004 direct housing-stability probe.",
    "Audit Status": "Keep"
  },
  {
    "Signal ID": "MEANING_PURPOSE",
    "Signal": "Meaning / purpose",
    "Primary Dimension": "Spiritual",
    "Affected Dimensions": "Emotional, Occupational",
    "Definition": "Sense that life and current activity have direction, significance or values alignment.",
    "Temporal Sensitivity": "Weekly-monthly",
    "Likely Causes": "Possible contexts: values alignment, roles, contribution and spirituality; these do not establish MEANING_PURPOSE without direct member evidence.",
    "Likely Consequences": "Possible associated outcomes: motivation, resilience and emotional wellbeing; each remains separately evidenced.",
    "Decision Relevance": "Distinguishes low mood/energy from loss of direction.",
    "Evidence Strength": "High",
    "Source IDs": "SRC000009",
    "Evidence Class": "Direct construct evidence",
    "Runtime / Effect Keys": "meaning / purpose effects; do not use lack_direction as a synonym",
    "Direct Evidence Rule": "Only explicit meaning, purpose, worthwhile-life or values-alignment answers establish MEANING_PURPOSE.",
    "Hypothesis / Relationship Rule": "Direction clarity is separate and maps to DIRECTION_CLARITY; work/focus uncertainty cannot establish meaning loss.",
    "Feasibility / Constraint Rule": "Time, money, energy, support and starting barriers remain fit constraints.",
    "System / Safety Boundary": "No automatic Safety meaning; low meaning/purpose is contextual wellness evidence unless a governed Safety trigger separately activates.",
    "Governed Mapping Status": "Mapped",
    "Reconciliation Notes": "Canonical meaning/purpose construct. SPT002-type meaning evidence belongs here; SPT001/SPT003 direction evidence belongs to DIRECTION_CLARITY.",
    "Audit Status": "Keep"
  },
  {
    "Signal ID": "COGNITIVE_ENGAGEMENT",
    "Signal": "Cognitive engagement",
    "Primary Dimension": "Intellectual",
    "Affected Dimensions": "Occupational, Emotional",
    "Definition": "Degree of learning, curiosity, challenge and mental engagement.",
    "Temporal Sensitivity": "Daily-weekly",
    "Likely Causes": "Possible contexts: opportunity, energy, interest and workload; candidate construct remains deferred until a distinct downstream use is validated.",
    "Likely Consequences": "Possible associated outcomes: growth, motivation and productive capacity; no downstream construct is created from engagement evidence alone.",
    "Decision Relevance": "Provides evidence about whether intellectual engagement appears underused, overloaded or adequately supported; downstream focus decisions remain governed.",
    "Evidence Strength": "Moderate",
    "Source IDs": "SRC000010",
    "Evidence Class": "Experimental / direct construct candidate",
    "Runtime / Effect Keys": "No direct effect for experimental engagement item",
    "Direct Evidence Rule": "Only explicit engagement/learning evidence may establish COGNITIVE_ENGAGEMENT once validated.",
    "Hypothesis / Relationship Rule": "Do not use engagement as explanation for low focus without separate evidence.",
    "Feasibility / Constraint Rule": "Opportunity/energy/time constraints are separate.",
    "System / Safety Boundary": "No automatic Safety meaning.",
    "Governed Mapping Status": "Experimental/deferred",
    "Reconciliation Notes": "Keep INT004 out of required Discovery sufficiency path.",
    "Audit Status": "Experimental/Deferred"
  },
  {
    "Signal ID": "RELATIONSHIP_STRAIN",
    "Signal": "Relationship strain",
    "Primary Dimension": "Social",
    "Affected Dimensions": "Emotional",
    "Definition": "Current strain, conflict, communication, trust, distance or boundary difficulty in a meaningful relationship.",
    "Temporal Sensitivity": "Daily-weekly",
    "Likely Causes": "Possible relationship contexts/drivers: conflict, communication, trust, distance, support mismatch and boundaries; these characterize strain but do not create other Social constructs.",
    "Likely Consequences": "Possible associated outcomes: stress, support needs and functioning; each requires separate evidence.",
    "Decision Relevance": "Separates relationship-specific strain from loneliness and support availability.",
    "Evidence Strength": "Member-direct; external relationship evidence pending",
    "Evidence Class": "Direct construct evidence",
    "Runtime / Effect Keys": "relationship_strain",
    "Direct Evidence Rule": "Explicit relationship-strain answers establish RELATIONSHIP_STRAIN.",
    "Hypothesis / Relationship Rule": "Loneliness/support/stress links remain distinct hypotheses.",
    "Feasibility / Constraint Rule": "Other-person, distance, boundaries, preference and safety constraints are fit/context evidence.",
    "System / Safety Boundary": "Unsafe-contact context may constrain recommendations; not automatically acute danger.",
    "Governed Mapping Status": "Mapped",
    "Reconciliation Notes": "Canonical conceptual signal. Preserve distinction from LONELINESS and SUPPORT_AVAILABILITY; runtime relationship_strain maps here.",
    "Audit Status": "Keep"
  },
  {
    "Signal ID": "SUPPORT_AVAILABILITY",
    "Signal": "Support availability / adequacy",
    "Primary Dimension": "Social",
    "Affected Dimensions": "Emotional, Occupational",
    "Definition": "Perceived availability and adequacy of practical or emotional support when wanted.",
    "Temporal Sensitivity": "Daily-weekly",
    "Likely Causes": "Possible contexts: access, trust, relationship quality, time and conflict; these do not establish support inadequacy unless the member directly reports it.",
    "Likely Consequences": "Possible associated outcomes: coping capacity, feasibility and connection; loneliness and relationship strain remain separate constructs.",
    "Decision Relevance": "Separates support availability from loneliness, contact frequency and relationship strain.",
    "Evidence Strength": "Member-direct; external evidence pending",
    "Evidence Class": "Direct construct evidence",
    "Runtime / Effect Keys": "low_support",
    "Direct Evidence Rule": "Explicit availability/adequacy answers establish SUPPORT_AVAILABILITY.",
    "Hypothesis / Relationship Rule": "Low support does not prove loneliness or relationship strain.",
    "Feasibility / Constraint Rule": "Trust, access, time, energy, conflict and preference are fit/context evidence.",
    "System / Safety Boundary": "No automatic Safety meaning; unsafe-contact constraints handled separately.",
    "Governed Mapping Status": "Mapped",
    "Reconciliation Notes": "Canonical conceptual signal. low_support maps here; keep support adequacy distinct from loneliness and relationship strain.",
    "Audit Status": "Keep"
  },
  {
    "Signal ID": "PHYSICAL_CONDITION",
    "Signal": "Physical condition / health burden",
    "Primary Dimension": "Physical",
    "Affected Dimensions": "Occupational, Emotional",
    "Definition": "Member-reported current physical health burden or condition affecting daily life.",
    "Temporal Sensitivity": "Daily-event",
    "Likely Causes": "Possible physical contexts: illness, symptoms, pain, injury or chronic condition as member-reported information; no diagnosis or causal inference.",
    "Likely Consequences": "Possible associated outcomes: function, energy, activity and feasibility; each remains separately evidenced.",
    "Decision Relevance": "Prevents generic physical-health evidence from collapsing into activity, body/weight or energy.",
    "Evidence Strength": "Member-direct; clinical inference prohibited",
    "Evidence Class": "Direct construct evidence",
    "Runtime / Effect Keys": "physical_condition",
    "Direct Evidence Rule": "Explicit current physical-condition answers establish PHYSICAL_CONDITION.",
    "Hypothesis / Relationship Rule": "Do not collapse into activity, body/weight or energy.",
    "Feasibility / Constraint Rule": "Professional-guidance/medical constraints are separate.",
    "System / Safety Boundary": "Ratings alone never establish medical emergency.",
    "Governed Mapping Status": "Mapped",
    "Reconciliation Notes": "Canonical conceptual signal. physical_condition maps here; keep separate from ACTIVITY_LEVEL, ENERGY_FUNCTION and body/weight constructs.",
    "Audit Status": "Keep"
  },
  {
    "Signal ID": "ACTIVITY_LEVEL",
    "Signal": "Physical activity / movement level",
    "Primary Dimension": "Physical",
    "Affected Dimensions": "Emotional, Sleep, Energy",
    "Definition": "Current level and consistency of intentional or routine physical movement.",
    "Temporal Sensitivity": "Daily-weekly",
    "Likely Causes": "Possible contexts: opportunity, physical condition, environment, energy and habit; barriers do not establish ACTIVITY_LEVEL severity.",
    "Likely Consequences": "Intervention evidence supports possible energy/sleep benefits on average, but ACTIVITY_LEVEL alone does not establish changes in either construct.",
    "Decision Relevance": "Supports activity-specific reasoning without treating inactivity as the cause of other problems.",
    "Evidence Strength": "High intervention evidence for selected outcomes",
    "Source IDs": "SRC000017,SRC000018",
    "Evidence Class": "Direct construct evidence",
    "Runtime / Effect Keys": "low_activity",
    "Direct Evidence Rule": "Explicit activity/movement answers establish ACTIVITY_LEVEL.",
    "Hypothesis / Relationship Rule": "Do not infer physical condition, energy or sleep from activity alone.",
    "Feasibility / Constraint Rule": "Feasibility/contraindication/professional guidance remain separate.",
    "System / Safety Boundary": "No automatic Safety meaning.",
    "Governed Mapping Status": "Mapped",
    "Reconciliation Notes": "Canonical conceptual signal. low_activity maps here; Evidence Bank relationships apply only when member evidence supports the relevant constructs.",
    "Audit Status": "Keep"
  },
  {
    "Signal ID": "FOCUS_FUNCTION",
    "Signal": "Focus / attention functioning",
    "Primary Dimension": "Intellectual",
    "Affected Dimensions": "Occupational, Emotional",
    "Definition": "Member-reported ability to sustain attention, concentrate and carry out cognitively demanding activity.",
    "Temporal Sensitivity": "Daily",
    "Likely Causes": "Possible contributors/associations: sleep, stress, environment, direction, activation and physical health; none inferred as the cause of focus difficulty.",
    "Likely Consequences": "Possible associated outcomes: work/study functioning and task completion; each requires separate evidence where represented as a construct.",
    "Decision Relevance": "Establishes focus as a direct construct; possible contributors remain hypotheses.",
    "Evidence Strength": "Moderate-high relationship evidence for sleep; moderate/domain-specific for stress",
    "Source IDs": "SRC000020,SRC000023",
    "Evidence Class": "Direct construct evidence",
    "Runtime / Effect Keys": "low_focus",
    "Direct Evidence Rule": "Explicit concentration/focus answers establish FOCUS_FUNCTION.",
    "Hypothesis / Relationship Rule": "Sleep/stress/direction/activation/environment links are member hypotheses; EVD000009 stronger than EVD000012.",
    "Feasibility / Constraint Rule": "Schedule/environment/energy constraints can affect fit.",
    "System / Safety Boundary": "No diagnostic cognitive inference.",
    "Governed Mapping Status": "Mapped",
    "Reconciliation Notes": "Canonical conceptual signal. low_focus maps here; sleep and stress relationships remain hypotheses governed by Evidence Bank support.",
    "Audit Status": "Keep"
  },
  {
    "Signal ID": "ACTIVATION",
    "Signal": "Action initiation / activation",
    "Primary Dimension": "Cross-dimensional",
    "Affected Dimensions": "Physical, Emotional, Intellectual, Occupational, Spiritual",
    "Definition": "Ability to begin intended actions once a direction or task is known.",
    "Temporal Sensitivity": "Daily",
    "Likely Causes": "Possible contexts: structure, energy, task clarity, friction and competing demands; none is inferred as the cause of activation difficulty.",
    "Likely Consequences": "Possible associated outcome: follow-through/progress; activation evidence does not manufacture another wellness construct.",
    "Decision Relevance": "Separates difficulty starting from low energy, low mood, focus problems or lack of direction.",
    "Evidence Strength": "Member-direct; external evidence pending",
    "Evidence Class": "Direct construct evidence",
    "Runtime / Effect Keys": "low_activation",
    "Direct Evidence Rule": "Explicit difficulty initiating action establishes ACTIVATION.",
    "Hypothesis / Relationship Rule": "Do not equate activation difficulty with low energy, depression or lack of direction.",
    "Feasibility / Constraint Rule": "Starting/time/structure barriers can be fit evidence.",
    "System / Safety Boundary": "No automatic Safety meaning.",
    "Governed Mapping Status": "Mapped",
    "Reconciliation Notes": "Canonical conceptual signal. low_activation maps here; keep it distinct from energy, emotional state, focus and direction.",
    "Audit Status": "Keep"
  },
  {
    "Signal ID": "SCHEDULE_DISRUPTION",
    "Signal": "Schedule / routine disruption",
    "Primary Dimension": "Cross-dimensional",
    "Affected Dimensions": "Physical, Occupational, Emotional",
    "Definition": "Instability or mismatch in routine/timing that materially affects daily functioning.",
    "Temporal Sensitivity": "Daily-weekly",
    "Likely Causes": "Possible contexts: work hours, caregiving, obligations and irregular routine; these can explain schedule disruption without creating downstream impairment.",
    "Likely Consequences": "Possible associated outcomes: sleep, energy, feasibility and work functioning; each requires separate evidence.",
    "Decision Relevance": "Captures schedule as a distinct context/constraint rather than automatically assigning downstream effects.",
    "Evidence Strength": "Member-direct; relationship evidence pending",
    "Evidence Class": "Direct construct/context evidence",
    "Runtime / Effect Keys": "schedule_disruption",
    "Direct Evidence Rule": "Explicit schedule/routine disruption establishes SCHEDULE_DISRUPTION.",
    "Hypothesis / Relationship Rule": "Sleep, energy and work effects require separate member support/evidence.",
    "Feasibility / Constraint Rule": "Schedule constraints are often Planning evidence.",
    "System / Safety Boundary": "No automatic Safety meaning.",
    "Governed Mapping Status": "Mapped",
    "Reconciliation Notes": "Canonical conceptual/context signal. schedule_disruption maps here; downstream sleep, energy or work effects require separate evidence.",
    "Audit Status": "Keep"
  },
  {
    "Signal ID": "BODY_WEIGHT_CONCERN",
    "Signal": "Body / weight concern",
    "Primary Dimension": "Physical",
    "Affected Dimensions": "Emotional",
    "Definition": "Member-reported concern or burden specifically related to weight or body composition, without implying illness, inactivity, or a need for weight change.",
    "Temporal Sensitivity": "Daily-weekly",
    "Likely Causes": "Possible member-described contexts: body/weight perception, goals, change or comfort; no body-size, illness or activity inference.",
    "Likely Consequences": "Possible relevance: attention, wellbeing or Planning when the member identifies it; no downstream construct is created automatically.",
    "Decision Relevance": "Keeps body/weight concern distinct from physical condition, activity level and energy; can justify targeted clarification only when decision-relevant.",
    "Evidence Strength": "Member-direct; external evidence pending",
    "Evidence Class": "Direct construct evidence",
    "Runtime / Effect Keys": "body_weight_concern",
    "Direct Evidence Rule": "Explicit body/weight concern answers establish BODY_WEIGHT_CONCERN.",
    "Hypothesis / Relationship Rule": "Do not infer PHYSICAL_CONDITION, ACTIVITY_LEVEL, ENERGY_FUNCTION, diagnosis, body-size status or a need for weight change from this construct.",
    "Feasibility / Constraint Rule": "Goals, preferences, professional guidance and action constraints remain Planning/fit evidence.",
    "System / Safety Boundary": "Body/weight concern alone has no automatic Safety or medical meaning.",
    "Governed Mapping Status": "Mapped",
    "Reconciliation Notes": "Added during 2026-08-30 reconciliation because body_weight_concern is an active direct Question Bank construct and must not remain an unmapped effect key.",
    "Audit Status": "Keep"
  },
  {
    "Signal ID": "VALUES_CLARITY",
    "Signal": "Values clarity",
    "Primary Dimension": "Spiritual",
    "Affected Dimensions": "Intellectual, Emotional",
    "Definition": "Clarity about what matters most when making choices, distinct from meaning/purpose and broad future direction.",
    "Temporal Sensitivity": "Weekly-monthly",
    "Likely Causes": "Possible contexts: competing values, uncertainty, role transition and unresolved tradeoffs; none establishes another construct without direct evidence.",
    "Likely Consequences": "Possible associated outcome: decision/prioritization uncertainty; DIRECTION_CLARITY and NEXT_STEP_CLARITY remain separate.",
    "Decision Relevance": "Discriminates values uncertainty from lack of purpose, broad direction uncertainty and action-initiation difficulty.",
    "Evidence Strength": "Member-direct; external evidence pending",
    "Evidence Class": "Direct discriminator / candidate construct",
    "Runtime / Effect Keys": "values_clarity",
    "Direct Evidence Rule": "Only explicit uncertainty about what matters in choices supports VALUES_CLARITY.",
    "Hypothesis / Relationship Rule": "May relate to DIRECTION_CLARITY but must not be treated as identical to lack_direction without separate evidence.",
    "Feasibility / Constraint Rule": "Time, money, energy, support and other barriers remain fit constraints.",
    "System / Safety Boundary": "No automatic Safety meaning.",
    "Governed Mapping Status": "Mapped — subconstruct",
    "Reconciliation Notes": "SPT003.04 currently supplies direct discriminator evidence. Retain as a distinct subconstruct unless later validation shows it should collapse into DIRECTION_CLARITY.",
    "Audit Status": "Keep / validate"
  },
  {
    "Signal ID": "NEXT_STEP_CLARITY",
    "Signal": "Next-step clarity",
    "Primary Dimension": "Spiritual / Intellectual",
    "Affected Dimensions": "Occupational",
    "Definition": "Clarity about what concrete next step to take when the member already knows what matters, distinct from activation/follow-through.",
    "Temporal Sensitivity": "Daily-weekly",
    "Likely Causes": "Possible contexts: planning ambiguity, option overload, insufficient information and unclear sequencing; these do not imply activation difficulty.",
    "Likely Consequences": "Possible associated outcome: delayed action selection; ACTIVATION, FOCUS_FUNCTION and DIRECTION_CLARITY require separate evidence.",
    "Decision Relevance": "Prevents a planning/clarity problem from being misclassified as LOW_ACTIVATION.",
    "Evidence Strength": "Member-direct; external evidence pending",
    "Evidence Class": "Direct discriminator / candidate construct",
    "Runtime / Effect Keys": "next_step_clarity",
    "Direct Evidence Rule": "Explicit 'know what matters but unsure what next step to take' evidence supports NEXT_STEP_CLARITY.",
    "Hypothesis / Relationship Rule": "Do not infer LOW_ACTIVATION, low energy, low focus or lack of broad direction from next-step uncertainty alone.",
    "Feasibility / Constraint Rule": "May terminate in Planning clarification without establishing another wellness impairment.",
    "System / Safety Boundary": "No automatic Safety meaning.",
    "Governed Mapping Status": "Mapped — subconstruct",
    "Reconciliation Notes": "SPT003.05 supplies direct discriminator evidence. Keep separate from ACTIVATION: not knowing the next step is not the same as being unable to start a known step.",
    "Audit Status": "Keep / validate"
  },
  {
    "Evidence Class": "Feasibility / constraint",
    "Runtime / Effect Keys": "constraints; professional guidance; preference/access/time/money/energy barriers",
    "Direct Evidence Rule": "Does not establish a wellness concern by itself.",
    "Hypothesis / Relationship Rule": "May explain why an intervention/focus is unsuitable without becoming a causal hypothesis.",
    "Feasibility / Constraint Rule": "Valid terminal fit evidence for Planning.",
    "System / Safety Boundary": "Explicit danger/unsafe-contact/medical-emergency content follows governed Safety boundary, not generic constraint scoring.",
    "Governed Mapping Status": "Cross-cutting class",
    "Reconciliation Notes": "Do not force every constraint into a conceptual wellness signal.",
    "Audit Status": "Keep class"
  },
  {
    "Evidence Class": "System control",
    "Runtime / Effect Keys": "positive_goal; positive_strength_area; handoff_confirmation; opt_out",
    "Direct Evidence Rule": "System-control evidence only; never wellness impairment evidence and never an ordinal construct state.",
    "Hypothesis / Relationship Rule": "Must not enter the population relationship graph as member health evidence or create causal hypotheses.",
    "Feasibility / Constraint Rule": "Can govern flow, preference, confirmation, correction and handoff without being scored as wellness evidence.",
    "System / Safety Boundary": "Never Safety evidence unless a separate governed Safety state exists.",
    "Governed Mapping Status": "Cross-cutting semantic class",
    "Reconciliation Notes": "Reconciled to current Question Bank semantics: positive goals/strengths, GEN900 confirmation and GEN901 opt-out are semantic system-control states, not numeric Signal Bank effects.",
    "Audit Status": "Keep class"
  },
  {
    "Signal ID": "DIRECTION_CLARITY",
    "Signal": "Direction clarity",
    "Primary Dimension": "Spiritual",
    "Affected Dimensions": "Intellectual, Occupational",
    "Definition": "Clarity about current priorities or broader direction, distinct from meaning/purpose, values clarity, next-step clarity and activation.",
    "Temporal Sensitivity": "Weekly-monthly",
    "Likely Causes": "Possible contexts: competing priorities, transition, uncertainty and insufficient reflection/information; discriminator answers identify the unresolved construct rather than adding severity.",
    "Likely Consequences": "Possible associated outcomes: priority uncertainty and Planning ambiguity; meaning, values, next-step clarity, focus and activation remain distinct.",
    "Decision Relevance": "Establishes broad direction as its own construct and determines whether a narrower direction discriminator is useful; does not itself select the focus.",
    "Evidence Strength": "Member-direct; external evidence pending",
    "Evidence Class": "Direct construct evidence + semantic discrimination",
    "Runtime / Effect Keys": "lack_direction; direction_discriminator variants",
    "Direct Evidence Rule": "SPT001-type explicit direction-state answers establish DIRECTION_CLARITY. SPT003 answers identify which direction-related construct is unresolved but are not additive DIRECTION_CLARITY severity.",
    "Hypothesis / Relationship Rule": "Meaning/purpose, values, next-step clarity, focus, work and activation remain distinct constructs or hypotheses unless separately supported.",
    "Feasibility / Constraint Rule": "Time, money, energy, support and access barriers are Planning/fit evidence rather than direction severity.",
    "System / Safety Boundary": "No automatic Safety meaning. Direction uncertainty alone does not activate Safety.",
    "Governed Mapping Status": "Mapped",
    "Reconciliation Notes": "Added during 2026-08-30 reconciliation to close a canonical mapping gap. SPT001 supplies direct direction state; SPT003 is a semantic discriminator and must not double-score the same direction fact.",
    "Audit Status": "Keep"
  },
  {
    "Evidence Class": "Safety confirmation state",
    "Runtime / Effect Keys": "safety_state; __safety_immediate_danger; __safety_uncertain; __safety_intent; __safety_current_self_harm_thoughts; __safety_can_stay_safe; __safety_cannot_stay_safe",
    "Direct Evidence Rule": "Only explicit governed Safety answers establish a categorical Safety state; no numeric wellness weight or risk score applies.",
    "Hypothesis / Relationship Rule": "Wellness/context indicators can justify approved clarification but cannot substitute for categorical Safety evidence or disposition.",
    "Feasibility / Constraint Rule": "Safety disposition may override ordinary feasibility/Planning; ordinary constraints do not themselves clear or quantify Safety.",
    "System / Safety Boundary": "Categorical Safety logic is independent of wellness encodings. A reassuring answer cannot independently clear an activated concern, and design-only SFT items require expert validation before external release.",
    "Governed Mapping Status": "Cross-cutting governed categorical class",
    "Reconciliation Notes": "Keep SFT namespace and safety_state semantics separate from wellness conceptual signals and ordinal construct encodings.",
    "Audit Status": "Validation required"
  }
]);
