import test from'node:test';import assert from'node:assert/strict';
import{createCrossDimensionalHypothesis,crossDimensionalHypothesisDecisionUsable,activeCrossDimensionalHypothesisRefs,memberRelationshipGraph}from'./cross-dimensional-hypothesis.js';

const base={hypothesisId:'sleep-pressure-1',relationshipId:'REL000008',fromConstructId:'SLEEP_QUALITY',toConstructId:'PRESSURE_PATTERN',proposition:'Recent sleep disruption may be contributing to the member’s current pressure pattern.',linkedConstructIds:['SLEEP_QUALITY','PRESSURE_PATTERN'],linkedDimensionIds:['physical','emotional'],evidenceRefs:['e:sleep-7d','e:pressure-7d'],evidenceAgainstRefs:['e:no-pattern-yet'],competingExplanationRefs:['h:financial-pressure'],sourceType:'discovery_synthesis',sourceRef:'discovery:session-1',confidence:'moderate',observedAt:'2026-08-25T12:00:00Z',revalidateAfter:'2026-09-08T12:00:00Z',expiresAt:'2026-09-22T12:00:00Z'};
const current=()=>createCrossDimensionalHypothesis(base);

test('bounded member relationship hypothesis is decision-usable while current and evidence-backed',()=>{assert.equal(crossDimensionalHypothesisDecisionUsable(current(),{now:'2026-09-02T12:00:00Z'}),true)});
test('stale member relationship hypothesis loses decision influence',()=>{assert.equal(crossDimensionalHypothesisDecisionUsable(current(),{now:'2026-09-09T12:00:00Z'}),false);assert.deepEqual(activeCrossDimensionalHypothesisRefs([current()],{now:'2026-09-09T12:00:00Z',acceptedFocusIds:['PRESSURE_PATTERN']}),[])});
test('relationship contributes context only when an already accepted Focus participates',()=>{assert.deepEqual(activeCrossDimensionalHypothesisRefs([current()],{now:'2026-09-02T12:00:00Z',acceptedFocusIds:['PRESSURE_PATTERN']}),['cross_dimension_hypothesis:sleep-pressure-1']);assert.deepEqual(activeCrossDimensionalHypothesisRefs([current()],{now:'2026-09-02T12:00:00Z',acceptedFocusIds:['FINANCIAL_STRAIN']}),[])});
test('unsupported relationship cannot be created',()=>{assert.throws(()=>createCrossDimensionalHypothesis({hypothesisId:'unsupported',proposition:'Unsupported relationship',linkedConstructIds:['SLEEP_QUALITY','PRESSURE_PATTERN'],linkedDimensionIds:['physical','emotional'],evidenceRefs:[],sourceType:'qa',sourceRef:'qa:1',observedAt:'2026-09-02T12:00:00Z',revalidateAfter:'2026-09-09T12:00:00Z'}),/evidenceRefs/) });
test('member edge must match an active canonical relationship and exact endpoints',()=>{assert.throws(()=>createCrossDimensionalHypothesis({...base,hypothesisId:'bad-edge',relationshipId:'REL000011',fromConstructId:'JOB_SECURITY',toConstructId:'EMOTIONAL_STATE',linkedConstructIds:['JOB_SECURITY','EMOTIONAL_STATE'],linkedDimensionIds:['occupational','emotional']}),/ACTIVE canonical relationship/);assert.throws(()=>createCrossDimensionalHypothesis({...base,hypothesisId:'bad-target',toConstructId:'EMOTIONAL_STATE',linkedConstructIds:['SLEEP_QUALITY','EMOTIONAL_STATE']}),/endpoints do not match/) });
test('member relationship graph preserves evidence for, evidence against and competing explanations',()=>{const graph=memberRelationshipGraph([current()],{now:'2026-09-02T12:00:00Z'});assert.equal(graph.edges.length,1);assert.equal(graph.edges[0].relationshipId,'REL000008');assert.deepEqual(graph.edges[0].evidenceRefs,['e:sleep-7d','e:pressure-7d']);assert.deepEqual(graph.edges[0].evidenceAgainstRefs,['e:no-pattern-yet']);assert.deepEqual(graph.edges[0].competingExplanationRefs,['h:financial-pressure'])});
