import test from'node:test';import assert from'node:assert/strict';
import{createCrossDimensionalHypothesis,crossDimensionalHypothesisDecisionUsable,activeCrossDimensionalHypothesisRefs}from'./cross-dimensional-hypothesis.js';

const current=()=>createCrossDimensionalHypothesis({hypothesisId:'sleep-pressure-1',proposition:'Recent sleep disruption may be contributing to the member’s current pressure pattern.',linkedConstructIds:['SLEEP_QUALITY','PRESSURE_PATTERN'],linkedDimensionIds:['physical','emotional'],evidenceRefs:['e:sleep-7d','e:pressure-7d'],sourceType:'discovery_synthesis',sourceRef:'discovery:session-1',confidence:'moderate',observedAt:'2026-08-25T12:00:00Z',revalidateAfter:'2026-09-08T12:00:00Z',expiresAt:'2026-09-22T12:00:00Z'});

test('bounded cross-dimensional hypothesis is decision-usable while current and evidence-backed',()=>{assert.equal(crossDimensionalHypothesisDecisionUsable(current(),{now:'2026-09-02T12:00:00Z'}),true)});
test('stale cross-dimensional hypothesis loses decision influence',()=>{assert.equal(crossDimensionalHypothesisDecisionUsable(current(),{now:'2026-09-09T12:00:00Z'}),false);assert.deepEqual(activeCrossDimensionalHypothesisRefs([current()],{now:'2026-09-09T12:00:00Z',acceptedFocusIds:['PRESSURE_PATTERN']}),[])});
test('relationship contributes context only when an already accepted Focus participates',()=>{assert.deepEqual(activeCrossDimensionalHypothesisRefs([current()],{now:'2026-09-02T12:00:00Z',acceptedFocusIds:['PRESSURE_PATTERN']}),['cross_dimension_hypothesis:sleep-pressure-1']);assert.deepEqual(activeCrossDimensionalHypothesisRefs([current()],{now:'2026-09-02T12:00:00Z',acceptedFocusIds:['FINANCIAL_STRAIN']}),[])});
test('unsupported relationship cannot be created',()=>{assert.throws(()=>createCrossDimensionalHypothesis({hypothesisId:'unsupported',proposition:'Unsupported relationship',linkedConstructIds:['SLEEP_QUALITY','PRESSURE_PATTERN'],linkedDimensionIds:['physical','emotional'],evidenceRefs:[],sourceType:'qa',sourceRef:'qa:1',observedAt:'2026-09-02T12:00:00Z',revalidateAfter:'2026-09-09T12:00:00Z'}),/evidenceRefs/) });
