// GENERATED FROM RECONCILED EL8 DRIVE AUTHORITY — 2026-09-01
// Canonical cross-system Evidence Bank.
// Do not hand-edit generated registry content; reconcile in Drive and regenerate.

export const EVIDENCE = Object.freeze([
  {
    "Evidence ID": "EVD000001",
    "From Construct / Signal": "SLEEP_QUALITY",
    "To Construct / Signal": "EMOTIONAL_STATE",
    "Dimensions": "Physical; Emotional",
    "Relationship / Claim": "Sleep disturbance and emotional health are linked in both directions.",
    "Directionality": "Bidirectional",
    "Evidence Type": "Systematic/longitudinal + intervention evidence",
    "Evidence Strength": "High",
    "Causality / Inference Level": "Association + temporal/intervention support; not individual causal proof",
    "Intervention Evidence": "Yes — evidence supports that improving sleep can improve some mental-health outcomes.",
    "Source IDs": "SRC000003; SRC000004; SRC000016",
    "EL8 Decision Use": "Use as a population prior only when SLEEP_QUALITY and EMOTIONAL_STATE are independently supported. Raise relationship-clarification or leverage-testing value only when the result can change focus or Planning.",
    "Allowed Member-facing Claim": "Research links sleep and emotional wellbeing. Because both are separately supported for you, EL8 can test whether they appear related and whether sleep is a useful leverage point.",
    "Prohibited / Guardrail": "Do not transfer severity between constructs, say sleep caused this member's emotional difficulty, or promise emotional improvement.",
    "Potential Spillover / QoL Areas": "Emotional wellbeing; stress/distress; broader quality of life where supported",
    "Member-specific Evidence Rule": "Strengthen only when repeated member data shows sleep changes precede or co-move with emotional outcomes; preserve alternative explanations.",
    "Status": "Active",
    "Audit Notes": "Candidate high-leverage relationship for Insights / focus confirmation."
  },
  {
    "Evidence ID": "EVD000002",
    "From Construct / Signal": "FINANCIAL_STRAIN",
    "To Construct / Signal": "EMOTIONAL_STATE",
    "Dimensions": "Financial; Emotional",
    "Relationship / Claim": "Financial strain is consistently associated with poorer emotional and broader health outcomes.",
    "Directionality": "Primarily Financial→Emotional; causal mechanism not assumed",
    "Evidence Type": "Systematic reviews; mostly observational",
    "Evidence Strength": "High association confidence",
    "Causality / Inference Level": "Population association; limited causal certainty",
    "Intervention Evidence": "Indirect/context dependent",
    "Source IDs": "SRC000007; SRC000011; SRC000014",
    "EL8 Decision Use": "Use as a population prior only when FINANCIAL_STRAIN and EMOTIONAL_STATE are independently supported; investigate the relationship only when it can change focus, urgency or Planning.",
    "Allowed Member-facing Claim": "Research consistently links financial strain with poorer emotional wellbeing. Because both are separately supported for you, EL8 can test whether financial strain appears relevant to your current pressure.",
    "Prohibited / Guardrail": "FINANCIAL_STRAIN and EMOTIONAL_STATE must each be independently established. Do not transfer severity, infer a single causal pathway, or promise emotional improvement from financial change.",
    "Potential Spillover / QoL Areas": "Emotional wellbeing; functioning; physical wellbeing; social needs",
    "Member-specific Evidence Rule": "Require member-specific co-occurrence and preferably longitudinal response before increasing personalized causal confidence.",
    "Status": "Active",
    "Audit Notes": "Useful for focus explanation but claim language must remain associative."
  },
  {
    "Evidence ID": "EVD000003",
    "From Construct / Signal": "JOB_SECURITY",
    "To Construct / Signal": "EMOTIONAL_STATE",
    "Dimensions": "Occupational; Emotional; Financial",
    "Relationship / Claim": "Employment insecurity/unemployment is associated with emotional distress.",
    "Directionality": "Primarily Occupational→Emotional",
    "Evidence Type": "Prospective meta-analytic evidence",
    "Evidence Strength": "High",
    "Causality / Inference Level": "Population temporal association; not individual causal proof",
    "Intervention Evidence": "Context dependent",
    "Source IDs": "SRC000006",
    "EL8 Decision Use": "Use as a population prior only when JOB_SECURITY and EMOTIONAL_STATE are independently supported; distinguish security/status from workload, fit, progress and direction before relationship clarification.",
    "Allowed Member-facing Claim": "Research links employment insecurity and unemployment with emotional distress. Because work security/status and emotional difficulty are separately supported for you, EL8 can test whether they appear related.",
    "Prohibited / Guardrail": "JOB_SECURITY and EMOTIONAL_STATE must each be independently established. Do not equate workload, dissatisfaction, unemployment and insecurity, or transfer severity between constructs.",
    "Potential Spillover / QoL Areas": "Emotional wellbeing; financial stability; occupational functioning",
    "Member-specific Evidence Rule": "Personal confidence rises only when the member identifies security as relevant and repeated evidence supports the pattern.",
    "Status": "Active",
    "Audit Notes": "Requires construct-specific occupational evidence."
  },
  {
    "Evidence ID": "EVD000004",
    "From Construct / Signal": "LONELINESS",
    "To Construct / Signal": "EMOTIONAL_STATE; physical-health/QoL outcome (contextual, no canonical Physical signal implied)",
    "Dimensions": "Social; Emotional; Physical",
    "Relationship / Claim": "Loneliness is associated with poorer mental and physical health-related quality of life.",
    "Directionality": "Bidirectional / feedback plausible",
    "Evidence Type": "Systematic reviews/meta-analyses; prospective evidence for broader social isolation risks",
    "Evidence Strength": "High association confidence",
    "Causality / Inference Level": "Association; direction and mechanisms vary",
    "Intervention Evidence": "Plausible; intervention effect depends on intervention and member context",
    "Source IDs": "SRC000005; SRC000012; SRC000013; SRC000015",
    "EL8 Decision Use": "Use EMOTIONAL_STATE as the canonical relationship target only when LONELINESS and EMOTIONAL_STATE are independently supported. Physical-health/QoL findings remain population context unless a separate canonical member construct is directly established; do not map them automatically to PHYSICAL_CONDITION. Do not substitute contact frequency, relationship strain or support availability for loneliness.",
    "Allowed Member-facing Claim": "Research links loneliness with poorer mental and physical quality of life. Where a separately established EL8 construct is relevant for you, EL8 can test whether changes in meaningful connection track with it.",
    "Prohibited / Guardrail": "Do not predict individual health risk, infer loneliness from low contact frequency, manufacture PHYSICAL_CONDITION or another construct from population QoL evidence, or transfer severity from loneliness.",
    "Potential Spillover / QoL Areas": "Emotional wellbeing; physical quality of life; sleep/activity where separately supported",
    "Member-specific Evidence Rule": "Track belonging separately from contact frequency. Personalize only to canonical member constructs independently established by direct evidence; physical QoL population evidence alone is not a member PHYSICAL_CONDITION state.",
    "Status": "Active",
    "Audit Notes": "Canonical target corrected: physical-health/QoL evidence is retained as population spillover context rather than a synthetic PHYSICAL_HEALTH signal. Loneliness ≠ objective isolation."
  },
  {
    "Evidence ID": "EVD000005",
    "From Construct / Signal": "ENVIRONMENTAL_INTERFERENCE",
    "To Construct / Signal": "SLEEP_QUALITY; ENERGY_FUNCTION; EMOTIONAL_STATE; ACTIVITY_LEVEL; LONELINESS (candidate targets only when independently supported)",
    "Dimensions": "Environmental; Physical; Emotional; Social",
    "Relationship / Claim": "Specific environmental factors such as noise, crowding, privacy, physical conditions and access can interfere with functioning and influence multiple wellbeing outcomes.",
    "Directionality": "Environmental→multiple; heterogeneous",
    "Evidence Type": "Systematic review evidence",
    "Evidence Strength": "Moderate-high",
    "Causality / Inference Level": "Context-dependent population evidence",
    "Intervention Evidence": "Depends on specific modifiable environmental factor",
    "Source IDs": "SRC000008",
    "EL8 Decision Use": "Use only after a specific Environmental factor and a governed linked member construct are independently supported. Candidate targets are SLEEP_QUALITY, ENERGY_FUNCTION, EMOTIONAL_STATE, ACTIVITY_LEVEL and LONELINESS; the population relationship is a prior, not evidence that all targets exist.",
    "Allowed Member-facing Claim": "Research suggests specific environmental factors can affect wellbeing. Because you reported a particular factor and a separately supported outcome, EL8 can account for that constraint and test whether they appear related.",
    "Prohibited / Guardrail": "Do not use an Environmental contributor or feasibility answer to manufacture ENVIRONMENTAL_INTERFERENCE severity or any downstream state. HOUSING_STABILITY requires separate direct evidence. Do not treat generic activity or connection labels as governed constructs; each target requires its own direct member evidence.",
    "Potential Spillover / QoL Areas": "Sleep; activity; stress/emotional wellbeing; social connection; energy",
    "Member-specific Evidence Rule": "Personalize only to the specific environmental factor the member reports and to governed target constructs independently established for that member; test outcomes after feasible changes.",
    "Status": "Active",
    "Audit Notes": "Reconciled 2026-08-31 to ENVIRONMENTAL_INTERFERENCE. HOUSING_STABILITY remains a separate governed construct rather than being bundled into this evidence relationship."
  },
  {
    "Evidence ID": "EVD000006",
    "From Construct / Signal": "ACTIVITY_LEVEL",
    "To Construct / Signal": "ENERGY_FUNCTION; FATIGUE; VITALITY",
    "Dimensions": "Physical",
    "Relationship / Claim": "Regular exercise can improve average energy/vitality and reduce fatigue.",
    "Directionality": "Activity intervention→energy/fatigue outcomes",
    "Evidence Type": "Meta-analysis of randomized trials",
    "Evidence Strength": "High intervention confidence for average effect; modest effect size",
    "Causality / Inference Level": "Intervention evidence supports causally interpretable average benefit within studied programs; individual response varies.",
    "Intervention Evidence": "Yes — small-to-moderate average improvements in energy/vitality and reductions in fatigue.",
    "Source IDs": "SRC000017",
    "EL8 Decision Use": "Use intervention evidence as a candidate leverage prior only when ACTIVITY_LEVEL and ENERGY_FUNCTION are independently supported and activity is feasible; Planning owns action selection.",
    "Allowed Member-facing Claim": "Research suggests regular exercise can improve energy and vitality on average. Because activity and energy are separately relevant for you, EL8 can test whether a feasible activity change helps your energy.",
    "Prohibited / Guardrail": "Do not infer low activity caused low energy/fatigue, transfer severity, prescribe activity despite contraindications, or promise a specific benefit.",
    "Potential Spillover / QoL Areas": "Energy; fatigue; vitality; physical functioning",
    "Member-specific Evidence Rule": "Track activity dose and subsequent energy/fatigue within the member; strengthen only if repeated changes align and competing explanations remain plausible.",
    "Status": "Active",
    "Audit Notes": "Intervention-backed relationship; Planning owns action selection and safety/feasibility constraints."
  },
  {
    "Evidence ID": "EVD000007",
    "From Construct / Signal": "ACTIVITY_LEVEL",
    "To Construct / Signal": "SLEEP_QUALITY",
    "Dimensions": "Physical",
    "Relationship / Claim": "Exercise interventions can improve sleep quality in adults on average.",
    "Directionality": "Activity intervention→sleep",
    "Evidence Type": "Systematic review / network meta-analysis",
    "Evidence Strength": "High intervention confidence; heterogeneous protocols",
    "Causality / Inference Level": "Intervention evidence supports an average causal effect; relevance to an individual's sleep driver is not automatic.",
    "Intervention Evidence": "Yes — exercise can improve sleep quality on average.",
    "Source IDs": "SRC000018",
    "EL8 Decision Use": "Use intervention evidence as a candidate leverage prior only when ACTIVITY_LEVEL and SLEEP_QUALITY are independently supported and activity is feasible; direct sleep drivers still govern.",
    "Allowed Member-facing Claim": "Research suggests physical activity can improve sleep quality on average. Because sleep and activity are separately relevant for you, EL8 can test whether a feasible activity change supports your sleep.",
    "Prohibited / Guardrail": "Do not infer inactivity caused poor sleep, create sleep impairment from activity evidence, or automatically prioritize activity over direct sleep drivers.",
    "Potential Spillover / QoL Areas": "Sleep quality; daytime functioning; potentially emotional wellbeing through separately supported pathways",
    "Member-specific Evidence Rule": "Track whether increased feasible activity precedes better sleep for this member; reduce confidence if no consistent pattern appears.",
    "Status": "Active",
    "Audit Notes": "Useful spillover explanation, but should not create a concern the member never raised."
  },
  {
    "Evidence ID": "EVD000008",
    "From Construct / Signal": "SLEEP_QUALITY",
    "To Construct / Signal": "PRESSURE_PATTERN",
    "Dimensions": "Physical; Emotional",
    "Relationship / Claim": "Sleep quality and perceived stress can form a reciprocal relationship in daily life.",
    "Directionality": "Likely bidirectional; subjective sleep→next-day stress has recent intensive-longitudinal support",
    "Evidence Type": "Systematic/longitudinal evidence + intensive longitudinal study",
    "Evidence Strength": "Moderate-high; member-level dynamics heterogeneous",
    "Causality / Inference Level": "Population and temporal evidence support a relationship, not individual causal proof.",
    "Intervention Evidence": "Indirect — improving sleep may affect stress for some people, but this row does not establish a guaranteed intervention effect.",
    "Source IDs": "SRC000003; SRC000004; SRC000019",
    "EL8 Decision Use": "When SLEEP_QUALITY and PRESSURE_PATTERN are independently supported, use population evidence to justify testing a member-specific relationship; neither construct selects or scores the other.",
    "Allowed Member-facing Claim": "Research suggests sleep and stress can reinforce each other. Because both are separately supported for you, EL8 can track whether they reliably move together before treating either as a leverage point.",
    "Prohibited / Guardrail": "Do not infer sleep caused stress or stress caused sleep difficulty, transfer severity, or promise improvement in either direction.",
    "Potential Spillover / QoL Areas": "Stress; emotional wellbeing; sleep quality; daytime functioning",
    "Member-specific Evidence Rule": "Strengthen only when repeated member observations show sleep and stress co-vary, preferably with temporal ordering; weaken if the pattern does not reproduce.",
    "Status": "Active",
    "Audit Notes": "Restored missing canonical evidence row. Path Audit already depended on EVD000008; restoration preserves identifier traceability instead of renumbering EVD000009–EVD000012."
  },
  {
    "Evidence ID": "EVD000009",
    "From Construct / Signal": "SLEEP_QUALITY; SLEEP_RESTRICTION",
    "To Construct / Signal": "FOCUS_FUNCTION",
    "Dimensions": "Physical; Intellectual",
    "Relationship / Claim": "Sleep disturbance and restriction are associated with impairments in attention and selected executive/cognitive functions.",
    "Directionality": "Sleep→cognitive functioning supported at population level; magnitude/domain varies",
    "Evidence Type": "Overview of systematic reviews/meta-analyses",
    "Evidence Strength": "Moderate-high",
    "Causality / Inference Level": "Population evidence supports functional effect, but does not identify sleep as the cause of an individual's focus problem.",
    "Intervention Evidence": "Indirect / condition-specific; this row is not evidence for a specific sleep treatment improving this member's focus.",
    "Source IDs": "SRC000020",
    "EL8 Decision Use": "Use as a population prior only when SLEEP_QUALITY and FOCUS_FUNCTION are independently supported; temporal/member-specific evidence may strengthen a leverage hypothesis but cannot create focus impairment.",
    "Allowed Member-facing Claim": "Research links sleep problems with attention and some executive functions. Because sleep and focus are separately relevant for you, EL8 can check whether better sleep is followed by clearer daytime focus.",
    "Prohibited / Guardrail": "Do not infer poor sleep caused focus difficulty, create FOCUS_FUNCTION impairment from sleep evidence, or promise cognitive improvement.",
    "Potential Spillover / QoL Areas": "Focus; attention; executive functioning; daytime performance",
    "Member-specific Evidence Rule": "Track whether better sleep reliably precedes better focus/attention for this member before increasing personalized confidence.",
    "Status": "Active",
    "Audit Notes": "Useful for Focus and Sleep mixed paths; preserve medical/sleep-disorder boundaries."
  },
  {
    "Evidence ID": "EVD000010",
    "From Construct / Signal": "LONELINESS",
    "To Construct / Signal": "SLEEP_QUALITY",
    "Dimensions": "Social; Physical",
    "Relationship / Claim": "Loneliness is associated with poorer subjective sleep quality and insomnia-type sleep disturbance, but not clearly with sleep duration.",
    "Directionality": "Association; direction uncertain",
    "Evidence Type": "Systematic review/meta-analysis",
    "Evidence Strength": "Moderate",
    "Causality / Inference Level": "Cross-sectional association with unresolved directionality/confounding",
    "Intervention Evidence": "No direct intervention inference from this evidence row",
    "Source IDs": "SRC000021",
    "EL8 Decision Use": "When LONELINESS and SLEEP_QUALITY are independently supported, use population evidence only to justify testing co-variation; direction and leverage remain uncertain.",
    "Allowed Member-facing Claim": "Research finds loneliness and sleep disturbance often occur together. Because both are separately relevant for you, EL8 can track whether changes in connection and sleep move together without assuming a causal direction.",
    "Prohibited / Guardrail": "Do not infer loneliness from low contact frequency, infer poor sleep from loneliness, transfer severity between constructs, or claim either caused the other.",
    "Potential Spillover / QoL Areas": "Social connection; sleep quality; emotional wellbeing through separately supported pathways",
    "Member-specific Evidence Rule": "Use repeated within-person observations to establish whether connection and sleep co-vary and whether either tends to precede the other.",
    "Status": "Active",
    "Audit Notes": "Keep loneliness distinct from objective social isolation/contact frequency."
  },
  {
    "Evidence ID": "EVD000011",
    "From Construct / Signal": "JOB_SECURITY",
    "To Construct / Signal": "EMOTIONAL_STATE",
    "Dimensions": "Occupational; Emotional; Financial",
    "Relationship / Claim": "Unemployment is associated with worse mental-health symptoms, while re-employment is associated with symptom improvement on average.",
    "Directionality": "Longitudinal Occupational→Emotional; re-employment improvement supported",
    "Evidence Type": "Systematic review/meta-analysis of prospective longitudinal studies",
    "Evidence Strength": "Moderate-high association; low GRADE certainty for causal inference",
    "Causality / Inference Level": "Temporal evidence strengthens inference but residual confounding and heterogeneity limit causal certainty.",
    "Intervention Evidence": "Some improvement inference for re-employment at population level; not a guaranteed individual mental-health effect.",
    "Source IDs": "SRC000006; SRC000022",
    "EL8 Decision Use": "Treat as additional evidence for the same canonical JOB_SECURITY→EMOTIONAL_STATE relationship represented by EVD000003, not as a second independent relationship. Use longitudinal/re-employment evidence to refine confidence and intervention interpretation only.",
    "Allowed Member-facing Claim": "Longitudinal research adds evidence that unemployment and re-employment can track with emotional distress at the population level. If work security/status and emotional difficulty are separately relevant for you, EL8 can track whether they move together.",
    "Prohibited / Guardrail": "Do not double-count EVD000003 and EVD000011, transfer severity to EMOTIONAL_STATE, treat employment status as the sole cause of distress, or promise that obtaining work will resolve it.",
    "Potential Spillover / QoL Areas": "Emotional wellbeing; financial stability; occupational functioning; daily structure",
    "Member-specific Evidence Rule": "Track whether changes in employment/security are followed by changes in distress and functioning; retain other drivers.",
    "Status": "Active",
    "Audit Notes": "Supporting evidence for EVD000003, not a separate member relationship. Preserves distinct longitudinal/re-employment evidence while preventing duplicate relationship counting."
  },
  {
    "Evidence ID": "EVD000012",
    "From Construct / Signal": "PRESSURE_PATTERN",
    "To Construct / Signal": "FOCUS_FUNCTION",
    "Dimensions": "Emotional; Intellectual",
    "Relationship / Claim": "Psychosocial stress can impair some executive-function performance, but cognitive effects are smaller and less uniform than broad 'stress hurts cognition' claims imply.",
    "Directionality": "Stress→selected executive functions; heterogeneous",
    "Evidence Type": "Meta-analysis",
    "Evidence Strength": "Moderate / domain-specific",
    "Causality / Inference Level": "Experimental population effect in selected tasks; insufficient for individual causal attribution.",
    "Intervention Evidence": "No direct intervention inference in this row",
    "Source IDs": "SRC000023",
    "EL8 Decision Use": "Use as a weaker population prior only when PRESSURE_PATTERN and FOCUS_FUNCTION are independently supported; prefer direct and member-specific evidence before treating stress as a leverage point.",
    "Allowed Member-facing Claim": "Research suggests stress can interfere with some executive functions. Because stress and focus are separately relevant for you, EL8 can check whether they reliably move together before treating stress as a leverage point.",
    "Prohibited / Guardrail": "Do not claim stress generally damages cognition, create FOCUS_FUNCTION impairment from stress evidence, transfer severity, or infer stress is the main cause of focus difficulty.",
    "Potential Spillover / QoL Areas": "Focus; planning; task control; cognitive functioning",
    "Member-specific Evidence Rule": "Require repeated member-level stress/focus association before using it as a personalized recommendation rationale.",
    "Status": "Active",
    "Audit Notes": "Deliberately cautious because the meta-analysis found weaker/mixed effects across cognitive domains."
  }
]);
