// GENERATED FROM RECONCILED EL8 DRIVE AUTHORITY — 2026-09-01
// Canonical Question registry.
// Do not hand-edit generated registry content; reconcile in Drive and regenerate.

export const QUESTIONS = Object.freeze([
  {
    "Question ID": "Q000001",
    "Sort Key": "1.0001",
    "Legacy ID": "GEN001",
    "Question": "Thinking about your life lately, what has been bothering you or making things harder? Select any that fit.",
    "Response Type": "Multi",
    "Role": "general",
    "Primary Dimension": "General",
    "Primary Construct": "General concern routing",
    "Prerequisite / Trigger": "Discovery start",
    "Scheduling / Stage": "Orient — entry only; transition as soon as routing evidence is sufficient",
    "Burden": "0.3",
    "Audit Status": "Keep",
    "Runtime Status": "Active",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Routing/salience only; answer-specific selections do not directly establish wellness severity.",
    "Variant Group": "OPENING_ISSUE_GATEWAY",
    "Source Sheet": "General",
    "Registry Notes": "Canonical opening issue gateway; permanent ID migrated from GEN001."
  },
  {
    "Question ID": "Q000002",
    "Sort Key": "1.0002",
    "Legacy ID": "GEN010",
    "Question": "Thinking about recent difficult days, what has most often made the day harder?",
    "Response Type": "Single",
    "Role": "orientation",
    "Primary Dimension": "General",
    "Primary Construct": "Difficult-day orientation",
    "Prerequisite / Trigger": "Orientation fallback / broader entry",
    "Scheduling / Stage": "Deferred fallback — outside canonical adaptive flow",
    "Burden": "0.14",
    "Audit Status": "Future candidate — fallback use unproven",
    "Runtime Status": "Deferred / fallback candidate",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Driver context only; no direct construct-severity establishment.",
    "Variant Group": "DIFFICULT_DAY_FALLBACK",
    "Source Sheet": "General",
    "Registry Notes": "Retained only as a future fallback candidate; not canonical runtime flow."
  },
  {
    "Question ID": "Q000003",
    "Sort Key": "1.0003",
    "Legacy ID": "GEN011",
    "Question": "Thinking about the past 7 days, which best describes your day-to-day routine?",
    "Response Type": "Single",
    "Role": "orientation",
    "Primary Dimension": "General",
    "Primary Construct": "Routine structure",
    "Prerequisite / Trigger": "Planning-context need only",
    "Scheduling / Stage": "Deferred Planning context — outside canonical Discovery flow",
    "Burden": "0.12",
    "Audit Status": "Future candidate — Planning context only",
    "Runtime Status": "Deferred / Planning-context candidate",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Planning context only; must not establish a wellness construct.",
    "Variant Group": "ROUTINE_CONTEXT",
    "Source Sheet": "General",
    "Registry Notes": "Defer from Discovery core; collect only if Planning needs this context."
  },
  {
    "Question ID": "Q000004",
    "Sort Key": "1.0004",
    "Legacy ID": "GEN012",
    "Question": "When life has been going well, what has most helped you keep going?",
    "Response Type": "Single",
    "Role": "orientation",
    "Primary Dimension": "General",
    "Primary Construct": "Protective strengths",
    "Prerequisite / Trigger": "Positive-path / protective-resource clarification",
    "Scheduling / Stage": "Adaptive Orient/positive context — optional fallback only",
    "Burden": "0.12",
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / positive-path strength fallback",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Protective-resource context only; strengths never subtract independent problem evidence.",
    "Variant Group": "PROTECTIVE_STRENGTH_FALLBACK",
    "Source Sheet": "General",
    "Registry Notes": "Optional strength fallback; ask only when it adds decision value."
  },
  {
    "Question ID": "Q000005",
    "Sort Key": "1.0005",
    "Legacy ID": "GEN100",
    "Question": "It sounds like things are generally going okay. What would make EL8 most useful to you right now?",
    "Response Type": "Single",
    "Role": "goal-probe",
    "Primary Dimension": "General",
    "Primary Construct": "Positive-path goal",
    "Prerequisite / Trigger": "GEN001.13 = well",
    "Scheduling / Stage": "Adaptive Narrow/goal definition — may directly support positive handoff",
    "Burden": "0.1",
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / positive path",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Defines requested positive-path use; clear goal may be sufficient for handoff without deficit searching.",
    "Variant Group": "POSITIVE_PATH_GOAL",
    "Source Sheet": "General",
    "Registry Notes": "Canonical positive-path goal probe; GEN101 optional only when strength/resource knowledge changes Planning."
  },
  {
    "Question ID": "Q000006",
    "Sort Key": "1.0006",
    "Legacy ID": "GEN101",
    "Question": "What is working well that you would most want to protect or build on?",
    "Response Type": "Single",
    "Role": "strength-probe",
    "Primary Dimension": "General",
    "Primary Construct": "Positive-path strength",
    "Prerequisite / Trigger": "Positive-path goal established AND strength would change handoff/Planning",
    "Scheduling / Stage": "Adaptive Deepen/Fit — optional positive-path strength only",
    "Burden": "0.1",
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / optional positive-path strength",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Member-identified resource context only; must not erase independently supported concerns.",
    "Variant Group": "POSITIVE_PATH_STRENGTH",
    "Source Sheet": "General",
    "Registry Notes": "Optional positive-path strength/resource probe; never required before a valid positive handoff."
  },
  {
    "Question ID": "Q000007",
    "Sort Key": "1.0007",
    "Legacy ID": "GEN200",
    "Question": "If one thing improved over the next 7 days, which change would help your daily life most?",
    "Response Type": "Single",
    "Role": "discriminator",
    "Primary Dimension": "General",
    "Primary Construct": "Near-term decision value",
    "Prerequisite / Trigger": "2+ independently supported concerns remain plausible AND primary focus/near-term priority is unresolved",
    "Scheduling / Stage": "Adaptive Narrow — priority tie-break only",
    "Burden": "0.3",
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / priority tie-break only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Changes priority/salience only, never construct severity.",
    "Variant Group": "PRIORITY_TIEBREAK_NEAR_TERM",
    "Source Sheet": "General",
    "Registry Notes": "Ask only when multiple supported concerns remain and existing evidence/preferences cannot select primary focus."
  },
  {
    "Question ID": "Q000008",
    "Sort Key": "1.0008",
    "Legacy ID": "GEN201",
    "Question": "Which best describes what seems connected to daily life feeling harder right now?",
    "Response Type": "Single",
    "Role": "discriminator",
    "Primary Dimension": "General",
    "Primary Construct": "Circumstance / functioning distinction",
    "Prerequisite / Trigger": "Broad unresolved evidence AND circumstance-vs-functioning distinction would change next direct probe or route",
    "Scheduling / Stage": "Adaptive Narrow — routing ambiguity only",
    "Burden": "0.2",
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / routing ambiguity only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Context/routing hypothesis only; specific constructs require direct evidence.",
    "Variant Group": "CONTEXT_ROUTING_DISCRIMINATOR",
    "Source Sheet": "General",
    "Registry Notes": "Skip when direct construct evidence already resolves the route."
  },
  {
    "Question ID": "Q000009",
    "Sort Key": "1.0009",
    "Legacy ID": "GEN202",
    "Question": "When this issue affects you, which area do you usually notice changing first?",
    "Response Type": "Single",
    "Role": "discriminator",
    "Primary Dimension": "General",
    "Primary Construct": "First-noticed interaction",
    "Prerequisite / Trigger": "Established issue with 2+ plausible linked areas AND first-noticed relationship would change focus, leverage, or Planning",
    "Scheduling / Stage": "Adaptive Deepen — relationship ambiguity only",
    "Burden": "0.25",
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / relationship ambiguity only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Member-reported interaction context only; not causality or severity.",
    "Variant Group": "INTERACTION_DISCRIMINATOR",
    "Source Sheet": "General",
    "Registry Notes": "Ask only when relationship information can change focus, leverage, or Planning."
  },
  {
    "Question ID": "Q000010",
    "Sort Key": "1.0010",
    "Legacy ID": "GEN204",
    "Question": "Thinking about the past 7 days, which area have you spent the most time worrying about or trying to deal with?",
    "Response Type": "Single",
    "Role": "discriminator",
    "Primary Dimension": "General",
    "Primary Construct": "Recent concern salience",
    "Prerequisite / Trigger": "2+ independently supported concerns remain plausible AND primary focus unresolved AND recent attention is most informative tie-break",
    "Scheduling / Stage": "Adaptive Narrow — alternative priority tie-break only",
    "Burden": "0.25",
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / priority tie-break alternative",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Recent attention/salience only; do not ask with GEN200 by default and never infer severity.",
    "Variant Group": "PRIORITY_TIEBREAK_RECENT_SALIENCE",
    "Source Sheet": "General",
    "Registry Notes": "Alternative to GEN200 when recent attention is the more informative tie-break."
  },
  {
    "Question ID": "Q000011",
    "Sort Key": "1.0011",
    "Legacy ID": "GEN300",
    "Question": "Your answers point in different directions. Which option best describes what you mean?",
    "Response Type": "Single",
    "Role": "contradiction",
    "Primary Dimension": "General",
    "Primary Construct": "Contradiction resolution",
    "Prerequisite / Trigger": "Detected material contradiction",
    "Scheduling / Stage": "Adaptive correction — only material contradiction",
    "Burden": "0.18",
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / correction",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Reconciles conflicting evidence; answer itself creates no new concern signal.",
    "Variant Group": "CONTRADICTION_CORRECTION",
    "Source Sheet": "General",
    "Registry Notes": "Canonical contradiction clarification; preserve context dependence where appropriate."
  },
  {
    "Question ID": "Q000012",
    "Sort Key": "1.0012",
    "Legacy ID": "GEN301",
    "Question": "Did EL8 misunderstand which area is making daily life harder?",
    "Response Type": "Single",
    "Role": "correction",
    "Primary Dimension": "General",
    "Primary Construct": "Concern correction",
    "Prerequisite / Trigger": "Suspected concern misclassification",
    "Scheduling / Stage": "Adaptive correction — only suspected scope misclassification",
    "Burden": "0.18",
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / correction",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Scope/priority correction only; must not erase independently supported evidence.",
    "Variant Group": "CONCERN_SCOPE_CORRECTION",
    "Source Sheet": "General",
    "Registry Notes": "Correction coverage includes work, money, relationships, support, home, direction, physical condition, energy, sleep, stress and focus."
  },
  {
    "Question ID": "Q000013",
    "Sort Key": "1.0013",
    "Legacy ID": "GEN400",
    "Question": "Thinking about the past 7 days, has anything made it meaningfully harder to do your usual daily activities?",
    "Response Type": "Single",
    "Role": "healthy-verification",
    "Primary Dimension": "General",
    "Primary Construct": "Functional impact verification",
    "Prerequisite / Trigger": "Positive/weak evidence AND recent functional interference genuinely unresolved AND answer would change deepen/prioritize/handoff",
    "Scheduling / Stage": "Adaptive sufficiency check — positive/weak-path impact ambiguity only",
    "Burden": "0.14",
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / positive-path impact ambiguity only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Contextual functional-impact verification only; cannot create, reduce or erase construct severity.",
    "Variant Group": "FUNCTIONAL_IMPACT_VERIFICATION",
    "Source Sheet": "General",
    "Registry Notes": "Optional discriminator, not a routine healthy-verification gate."
  },
  {
    "Question ID": "Q000014",
    "Sort Key": "1.0014",
    "Legacy ID": "GEN401",
    "Question": "Do the issues you selected feel manageable without additional help right now?",
    "Response Type": "Single",
    "Role": "healthy-verification",
    "Primary Dimension": "General",
    "Primary Construct": "Manageability verification",
    "Prerequisite / Trigger": "Supported issue(s) AND proposed Planning/support intensity unresolved AND manageability preference would change handoff",
    "Scheduling / Stage": "Adaptive Fit/handoff — support intensity only when unresolved",
    "Burden": "0.14",
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / support-intensity fit only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Planning/support-intensity context only; not wellness severity or Discovery sufficiency requirement.",
    "Variant Group": "MANAGEABILITY_PLANNING_FIT",
    "Source Sheet": "General",
    "Registry Notes": "Skip when handoff/support intensity is already clear."
  },
  {
    "Question ID": "Q000015",
    "Sort Key": "1.0015",
    "Legacy ID": "GEN900",
    "Question": "Before we move on, does this feel like an accurate enough picture of what you want EL8 to work from?",
    "Response Type": "Single",
    "Role": "handoff-validation",
    "Primary Dimension": "General",
    "Primary Construct": "Member-confirmed understanding",
    "Prerequisite / Trigger": "Semantic sufficiency reached AND substantive synthesis exists whose accuracy matters to next decision; no active Safety interrupt",
    "Scheduling / Stage": "Sufficient/Handoff — final synthesis confirmation only when substantive",
    "Burden": "0.08",
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / final synthesis confirmation",
    "Evidence Status": "Hypothesis",
    "Decision Use": "System-control confirmation; does not validate every inference as fact or add wellness severity.",
    "Variant Group": "HANDOFF_CONFIRMATION",
    "Source Sheet": "General",
    "Registry Notes": "Final synthesis confirmation only when substantive; positive/no-active-focus endpoints may complete without it."
  },
  {
    "Question ID": "Q000016",
    "Sort Key": "1.0016",
    "Legacy ID": "GEN901",
    "Question": "Do you want to answer more questions about this right now?",
    "Response Type": "Single",
    "Role": "opt-out",
    "Primary Dimension": "General",
    "Primary Construct": "Member burden / opt-out",
    "Prerequisite / Trigger": "Member requests pause/stop, burden evident, or controller offers optional continuation",
    "Scheduling / Stage": "Any point in adaptive Discovery — member-controlled continuation/opt-out",
    "Burden": "0.08",
    "Audit Status": "Keep",
    "Runtime Status": "Available / member-controlled system action",
    "Evidence Status": "Hypothesis",
    "Decision Use": "System-control state only; member can pause/stop optional Discovery without creating wellness evidence.",
    "Variant Group": "DISCOVERY_OPT_OUT",
    "Source Sheet": "General",
    "Registry Notes": "Treat as member-controlled action rather than routine assessment question; Safety process remains independently governed."
  },
  {
    "Question ID": "Q000017",
    "Sort Key": "2.0001",
    "Legacy ID": "PHY001",
    "Question": "Which physical-health areas, if any, would you like EL8 to understand better?",
    "Response Type": "Multi",
    "Role": "concern-scope",
    "Primary Dimension": "Physical",
    "Primary Construct": "Physical-health scope discrimination",
    "Prerequisite / Trigger": "Health concern; only when Physical scope remains ambiguous",
    "Scheduling / Stage": "Adaptive Narrow — scope discrimination only",
    "Burden": 0.28,
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / scope discrimination only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Route Physical scope only; no question-level construct severity.",
    "Variant Group": "PHYSICAL_SCOPE_DISCRIMINATOR",
    "Source Sheet": "Physical",
    "Registry Notes": "Skip when existing evidence already identifies the relevant Physical construct."
  },
  {
    "Question ID": "Q000018",
    "Sort Key": "2.0002",
    "Legacy ID": "PHY100",
    "Question": "In the past 7 days, how much have concerns specifically about your weight or body bothered you?",
    "Response Type": "Single",
    "Role": "state-probe",
    "Primary Dimension": "Physical",
    "Primary Construct": "Body / weight concern",
    "Prerequisite / Trigger": "Body/weight concern",
    "Scheduling / Stage": "Adaptive state evidence",
    "Burden": 0.17,
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / adaptive",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Direct body/weight concern only; distinct from physical condition and activity.",
    "Variant Group": "BODY_WEIGHT_CONCERN_STATE",
    "Source Sheet": "Physical",
    "Registry Notes": "Do not infer inactivity, illness or need for weight change."
  },
  {
    "Question ID": "Q000019",
    "Sort Key": "2.0003",
    "Legacy ID": "PHY101",
    "Question": "If EL8 suggested a physical-health action, what would it need to account for? Select any that fit.",
    "Response Type": "Multi",
    "Role": "feasibility-probe",
    "Primary Dimension": "Physical",
    "Primary Construct": "Physical action feasibility",
    "Prerequisite / Trigger": "Non-activity/cross-cutting Physical constraints materially affect plan fit",
    "Scheduling / Stage": "Adaptive Fit — non-activity/cross-cutting constraints only",
    "Burden": 0.1,
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / non-activity physical fit only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Planning constraints/accommodations only.",
    "Variant Group": "PHYSICAL_GENERAL_FEASIBILITY",
    "Source Sheet": "Physical",
    "Registry Notes": "Do not duplicate activity-specific feasibility."
  },
  {
    "Question ID": "Q000020",
    "Sort Key": "2.0004",
    "Legacy ID": "PHY200",
    "Question": "In the past 7 days, how would you rate your sleep overall?",
    "Response Type": "Single",
    "Role": "state-probe",
    "Primary Dimension": "Physical",
    "Primary Construct": "Sleep state",
    "Prerequisite / Trigger": "Sleep concern",
    "Scheduling / Stage": "Adaptive state evidence",
    "Burden": 0.16,
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / adaptive",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Canonical direct SLEEP_QUALITY state evidence.",
    "Variant Group": "SLEEP_STATE",
    "Source Sheet": "Physical",
    "Registry Notes": "May itself satisfy focused Sleep evidence."
  },
  {
    "Question ID": "Q000021",
    "Sort Key": "2.0005",
    "Legacy ID": "PHY201",
    "Question": "In the past 7 days, what seemed connected with times it was harder to sleep well? Select any that fit.",
    "Response Type": "Multi",
    "Role": "discriminator",
    "Primary Dimension": "Physical",
    "Primary Construct": "Sleep contributors",
    "Prerequisite / Trigger": "Direct sleep difficulty supported and contributor relationship changes decision",
    "Scheduling / Stage": "Adaptive discrimination — contributor relationship only",
    "Burden": 0.2,
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / contributor discrimination only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Relationship/context hypotheses only; direct sleep state remains authoritative.",
    "Variant Group": "SLEEP_CONTRIBUTOR_DISCRIMINATOR",
    "Source Sheet": "Physical",
    "Registry Notes": "Ordinary Sleep sufficiency must not require this."
  },
  {
    "Question ID": "Q000022",
    "Sort Key": "2.0006",
    "Legacy ID": "PHY202",
    "Question": "When you sleep better than usual, what—if anything—do you tend to notice the next day?",
    "Response Type": "Single",
    "Role": "confirmation",
    "Primary Dimension": "Physical",
    "Primary Construct": "Sleep relationship confirmation",
    "Prerequisite / Trigger": "Sleep relationship could change leverage/focus",
    "Scheduling / Stage": "Adaptive relationship confirmation only",
    "Burden": 0.18,
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / relationship confirmation only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Sleep-energy/focus relationship evidence only; no direct state effect.",
    "Variant Group": "SLEEP_RELATIONSHIP_CONFIRMATION",
    "Source Sheet": "Physical",
    "Registry Notes": "Optional; ordinary Sleep sufficiency must not depend on it."
  },
  {
    "Question ID": "Q000023",
    "Sort Key": "2.0007",
    "Legacy ID": "PHY300",
    "Question": "In the past 7 days, how would you rate your energy during the day?",
    "Response Type": "Single",
    "Role": "state-probe",
    "Primary Dimension": "Physical",
    "Primary Construct": "Energy state",
    "Prerequisite / Trigger": "Energy concern",
    "Scheduling / Stage": "Adaptive state evidence",
    "Burden": 0.16,
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / adaptive",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Canonical direct ENERGY_FUNCTION state evidence.",
    "Variant Group": "ENERGY_STATE",
    "Source Sheet": "Physical",
    "Registry Notes": "May itself satisfy focused Energy evidence."
  },
  {
    "Question ID": "Q000024",
    "Sort Key": "2.0008",
    "Legacy ID": "PHY301",
    "Question": "In the past 7 days, what seemed most connected with times you had low energy? Select any that fit.",
    "Response Type": "Multi",
    "Role": "discriminator",
    "Primary Dimension": "Physical",
    "Primary Construct": "Energy contributors",
    "Prerequisite / Trigger": "Direct low-energy evidence supported and contributor relationship changes decision",
    "Scheduling / Stage": "Adaptive discrimination — contributor relationship only",
    "Burden": 0.2,
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / contributor discrimination only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Relationship/context hypotheses only; direct Energy state remains authoritative.",
    "Variant Group": "ENERGY_CONTRIBUTOR_DISCRIMINATOR",
    "Source Sheet": "Physical",
    "Registry Notes": "Ordinary Energy sufficiency must not require this."
  },
  {
    "Question ID": "Q000025",
    "Sort Key": "2.0009",
    "Legacy ID": "PHY400",
    "Question": "In the past 7 days, on how many days were you physically active for at least a short period?",
    "Response Type": "Single",
    "Role": "state-probe",
    "Primary Dimension": "Physical",
    "Primary Construct": "Activity frequency",
    "Prerequisite / Trigger": "Activity concern",
    "Scheduling / Stage": "Adaptive state evidence",
    "Burden": 0.16,
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / adaptive",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Canonical ACTIVITY_LEVEL state evidence; duplicate direct probes reconcile rather than accumulate.",
    "Variant Group": "ACTIVITY_STATE",
    "Source Sheet": "Physical",
    "Registry Notes": "May itself satisfy Activity evidence."
  },
  {
    "Question ID": "Q000026",
    "Sort Key": "2.0010",
    "Legacy ID": "PHY401",
    "Question": "Which kinds of activity are practical for you right now? Select any that fit.",
    "Response Type": "Multi",
    "Role": "feasibility-probe",
    "Primary Dimension": "Physical",
    "Primary Construct": "Activity feasibility",
    "Prerequisite / Trigger": "Activity is plausible and type choice changes plan",
    "Scheduling / Stage": "Adaptive Fit — activity-type choice only",
    "Burden": 0.12,
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / activity-type fit only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Activity Planning-fit/preferences only; no ACTIVITY_LEVEL severity effect.",
    "Variant Group": "ACTIVITY_TYPE_FEASIBILITY",
    "Source Sheet": "Physical",
    "Registry Notes": "Do not ask routinely alongside barrier probe."
  },
  {
    "Question ID": "Q000027",
    "Sort Key": "2.0011",
    "Legacy ID": "PHY402",
    "Question": "What could make physical activity harder for you right now? Select any that fit.",
    "Response Type": "Multi",
    "Role": "feasibility-probe",
    "Primary Dimension": "Physical",
    "Primary Construct": "Activity barriers",
    "Prerequisite / Trigger": "Activity plausible and barriers could change feasibility, accommodation, Safety/professional boundary or Planning",
    "Scheduling / Stage": "Adaptive Fit — activity barriers/constraints only",
    "Burden": 0.12,
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / barrier-fit only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Planning-fit constraints/context; answer rules prevent parallel severity inference.",
    "Variant Group": "ACTIVITY_BARRIER_FEASIBILITY",
    "Source Sheet": "Physical",
    "Registry Notes": "Primary Activity barrier probe; do not pair with type probe by default."
  },
  {
    "Question ID": "Q000028",
    "Sort Key": "2.0012",
    "Legacy ID": "PHY500",
    "Question": "In the past 7 days, how often was it hard to start something you intended to do?",
    "Response Type": "Single",
    "Role": "state-probe",
    "Primary Dimension": "Cross-dimensional",
    "Primary Construct": "Activation",
    "Prerequisite / Trigger": "Activation independently supported or distinction from energy/focus/schedule/clarity changes decision",
    "Scheduling / Stage": "Adaptive clarification/state evidence only",
    "Burden": 0.17,
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / activation clarification only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Direct ACTIVATION state; distinct from energy, activity, focus and next-step clarity.",
    "Variant Group": "ACTIVATION_STATE",
    "Source Sheet": "Physical",
    "Registry Notes": "Cross-dimensional construct retained in Physical source family pending normalization."
  },
  {
    "Question ID": "Q000029",
    "Sort Key": "1.2001",
    "Legacy ID": "EMT001",
    "Question": "In the past 7 days, how often did you feel stressed or overwhelmed?",
    "Response Type": "Single",
    "Role": "state-probe",
    "Primary Dimension": "Emotional",
    "Primary Construct": "Stress state",
    "Prerequisite / Trigger": "Stress concern",
    "Scheduling / Stage": "Adaptive state evidence — may itself satisfy focused Stress evidence",
    "Burden": 0.16,
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / adaptive",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Establish PRESSURE_PATTERN state directly.",
    "Variant Group": "STRESS_STATE",
    "Source Sheet": "Emotional",
    "Registry Notes": "Canonical current-state evidence."
  },
  {
    "Question ID": "Q000030",
    "Sort Key": "1.2002",
    "Legacy ID": "EMT002",
    "Question": "In the past 7 days, when you felt stressed or overwhelmed, what was happening around those times? Select any that fit.",
    "Response Type": "Multi",
    "Role": "discriminator",
    "Primary Dimension": "Emotional",
    "Primary Construct": "Stress context",
    "Prerequisite / Trigger": "Stress concern",
    "Scheduling / Stage": "Adaptive discrimination — Stress context only when decision-relevant",
    "Burden": 0.2,
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / context discrimination only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Capture Stress-context relationships only; direct PRESSURE_PATTERN state and other domain states require separate direct evidence.",
    "Variant Group": "STRESS_CONTEXT",
    "Source Sheet": "Emotional",
    "Registry Notes": "Contributor selections are hypotheses/context and are not required for ordinary Stress sufficiency."
  },
  {
    "Question ID": "Q000031",
    "Sort Key": "1.2003",
    "Legacy ID": "EMT003",
    "Question": "About how long have stress or difficult emotions been noticeably affecting your daily life?",
    "Response Type": "Single",
    "Role": "deepening",
    "Primary Dimension": "Emotional",
    "Primary Construct": "Duration",
    "Prerequisite / Trigger": "Stress concern",
    "Scheduling / Stage": "Adaptive deepening — duration only when decision-relevant",
    "Burden": 0.12,
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / duration deepening only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Establish Stress duration/functional-duration facet without additive severity scoring.",
    "Variant Group": "STRESS_DURATION",
    "Source Sheet": "Emotional",
    "Registry Notes": "Ask only when persistence changes urgency, interpretation, or handoff."
  },
  {
    "Question ID": "Q000032",
    "Sort Key": "1.2004",
    "Legacy ID": "EMT004",
    "Question": "In the past 7 days, how much did stress or difficult emotions interfere with your usual daily activities?",
    "Response Type": "Single",
    "Role": "impact-probe",
    "Primary Dimension": "Emotional",
    "Primary Construct": "Stress impact",
    "Prerequisite / Trigger": "Stress concern",
    "Scheduling / Stage": "Adaptive deepening — impact only when decision-relevant",
    "Burden": 0.14,
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / impact deepening only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Establish PRESSURE_PATTERN impact facet; keep impact distinct from frequency and duration.",
    "Variant Group": "STRESS_IMPACT",
    "Source Sheet": "Emotional",
    "Registry Notes": "Not a mandatory second severity probe."
  },
  {
    "Question ID": "Q000033",
    "Sort Key": "1.2005",
    "Legacy ID": "EMT005",
    "Question": "In the past 7 days, what, if anything, seemed to make stressful periods easier to handle? Select any that fit.",
    "Response Type": "Multi",
    "Role": "support-probe",
    "Primary Dimension": "Emotional",
    "Primary Construct": "Existing supports",
    "Prerequisite / Trigger": "Stress concern",
    "Scheduling / Stage": "Adaptive Fit — coping/resources only when Planning changes",
    "Burden": 0.12,
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / fit-resource only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Capture coping/protective-resource context for Planning fit only; no direct wellness severity effect.",
    "Variant Group": "STRESS_PLAN_FIT",
    "Source Sheet": "Emotional",
    "Registry Notes": "Ask only when existing supports/resources materially change the plan."
  },
  {
    "Question ID": "Q000034",
    "Sort Key": "1.3001",
    "Legacy ID": "SOC001",
    "Question": "During the past 7 days, how often did tension or conflict in a close relationship bother you?",
    "Response Type": "Single",
    "Role": "state-probe",
    "Primary Dimension": "Social",
    "Primary Construct": "Relationship strain",
    "Prerequisite / Trigger": "Relationships concern",
    "Scheduling / Stage": "Adaptive state evidence — may itself satisfy focused Relationship evidence",
    "Burden": "0.16",
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / adaptive",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Establish RELATIONSHIP_STRAIN state when independently relevant",
    "Variant Group": "RELATIONSHIP_STRAIN_STATE",
    "Source Sheet": "Social",
    "Registry Notes": "Canonical state evidence; do not force further problem discovery after sufficient low-strain evidence"
  },
  {
    "Question ID": "Q000035",
    "Sort Key": "1.3002",
    "Legacy ID": "SOC002",
    "Question": "During the past 7 days, how much did relationship problems interfere with your usual activities or ability to focus?",
    "Response Type": "Single",
    "Role": "impact-probe",
    "Primary Dimension": "Social",
    "Primary Construct": "Relationship impact",
    "Prerequisite / Trigger": "Relationships concern",
    "Scheduling / Stage": "Adaptive deepening — impact only when decision-relevant",
    "Burden": "0.16",
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / impact deepening only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Clarify impact only when it changes priority, urgency, or Planning",
    "Variant Group": "RELATIONSHIP_IMPACT",
    "Source Sheet": "Social",
    "Registry Notes": "Impact is a distinct facet; no global subtraction from strain-frequency evidence"
  },
  {
    "Question ID": "Q000036",
    "Sort Key": "1.3003",
    "Legacy ID": "SOC003",
    "Question": "What has been difficult in your close relationships lately? Select any that fit.",
    "Response Type": "Multi",
    "Role": "discriminator",
    "Primary Dimension": "Social",
    "Primary Construct": "Relationship difficulty",
    "Prerequisite / Trigger": "Relationships concern",
    "Scheduling / Stage": "Adaptive discrimination — relationship type/context only when decision-relevant",
    "Burden": "0.2",
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / relationship discrimination only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Discriminate relationship context without adding severity",
    "Variant Group": "RELATIONSHIP_DRIVER_CONTEXT",
    "Source Sheet": "Social",
    "Registry Notes": "Ask only when type of difficulty can change focus, Safety clarification, or Planning"
  },
  {
    "Question ID": "Q000037",
    "Sort Key": "1.3004",
    "Legacy ID": "SOC004",
    "Question": "If you wanted to improve or protect a relationship, what would EL8 need to account for? Select any that fit.",
    "Response Type": "Multi",
    "Role": "feasibility-probe",
    "Primary Dimension": "Social",
    "Primary Construct": "Relationship feasibility",
    "Prerequisite / Trigger": "Relationships concern",
    "Scheduling / Stage": "Adaptive Fit / governed Safety constraint — only when action is being considered",
    "Burden": "0.11",
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / fit or safety-constraint only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Constrain relationship Planning without changing relationship-state truth",
    "Variant Group": "RELATIONSHIP_FEASIBILITY",
    "Source Sheet": "Social",
    "Registry Notes": "Planning-fit probe; boundaries, Safety and participation constraints only when action choice changes"
  },
  {
    "Question ID": "Q000038",
    "Sort Key": "1.3005",
    "Legacy ID": "SOC100",
    "Question": "If you needed emotional support right now, is there someone you could turn to?",
    "Response Type": "Single",
    "Role": "state-probe",
    "Primary Dimension": "Social",
    "Primary Construct": "Available support",
    "Prerequisite / Trigger": "Support concern",
    "Scheduling / Stage": "Adaptive state evidence — Support availability only when independently relevant",
    "Burden": "0.14",
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / support-availability state only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Establish SUPPORT_AVAILABILITY state independently from loneliness",
    "Variant Group": "SUPPORT_AVAILABILITY_STATE",
    "Source Sheet": "Social",
    "Registry Notes": "Do not automatically pair with loneliness; constructs are distinct"
  },
  {
    "Question ID": "Q000039",
    "Sort Key": "1.3006",
    "Legacy ID": "SOC101",
    "Question": "During the past 7 days, how often did you feel isolated or disconnected from other people?",
    "Response Type": "Single",
    "Role": "state-probe",
    "Primary Dimension": "Social",
    "Primary Construct": "Isolation / loneliness",
    "Prerequisite / Trigger": "Support concern",
    "Scheduling / Stage": "Adaptive state evidence — Loneliness only when independently relevant",
    "Burden": "0.16",
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / loneliness state only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Establish LONELINESS state independently from support availability",
    "Variant Group": "LONELINESS_STATE",
    "Source Sheet": "Social",
    "Registry Notes": "Do not infer loneliness from low support or low contact"
  },
  {
    "Question ID": "Q000040",
    "Sort Key": "1.3007",
    "Legacy ID": "SOC102",
    "Question": "What kind of support or connection would be most useful right now?",
    "Response Type": "Single",
    "Role": "discriminator",
    "Primary Dimension": "Social",
    "Primary Construct": "Desired support",
    "Prerequisite / Trigger": "Support concern",
    "Scheduling / Stage": "Adaptive Fit discrimination — desired support only when Planning changes",
    "Burden": "0.18",
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / support-fit discrimination only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Identify desired support/connection form for Planning only",
    "Variant Group": "SUPPORT_CONNECTION_PREFERENCE",
    "Source Sheet": "Social",
    "Registry Notes": "Preference does not establish support availability or loneliness severity"
  },
  {
    "Question ID": "Q000041",
    "Sort Key": "1.3008",
    "Legacy ID": "SOC103",
    "Question": "Which things, if any, currently limit access to support or social connection? Select any that fit.",
    "Response Type": "Multi",
    "Role": "feasibility-probe",
    "Primary Dimension": "Social",
    "Primary Construct": "Support feasibility",
    "Prerequisite / Trigger": "Support concern",
    "Scheduling / Stage": "Adaptive Fit — access constraints only when Planning changes",
    "Burden": "0.11",
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / support-access constraint only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Constrain support/connection Planning without inferring state severity",
    "Variant Group": "SUPPORT_ACCESS_FEASIBILITY",
    "Source Sheet": "Social",
    "Registry Notes": "Ask only when support action is plausible and access barriers change the plan"
  },
  {
    "Question ID": "Q000042",
    "Sort Key": "1.4001",
    "Legacy ID": "INT001",
    "Question": "Thinking about the past 7 days, how often was it hard to stay focused on something you needed or wanted to do?",
    "Response Type": "Single",
    "Role": "state-probe",
    "Primary Dimension": "Intellectual",
    "Primary Construct": "Focus state",
    "Prerequisite / Trigger": "Focus concern",
    "Scheduling / Stage": "Adaptive state evidence — may itself satisfy focused Focus evidence",
    "Burden": "0.16",
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / adaptive",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Establish FOCUS_FUNCTION state directly",
    "Variant Group": "FOCUS_STATE",
    "Source Sheet": "Intellectual",
    "Registry Notes": "Canonical focus state evidence"
  },
  {
    "Question ID": "Q000043",
    "Sort Key": "1.4002",
    "Legacy ID": "INT002",
    "Question": "Thinking about the past 7 days, how much did difficulty focusing interfere with things that mattered to you?",
    "Response Type": "Single",
    "Role": "impact-probe",
    "Primary Dimension": "Intellectual",
    "Primary Construct": "Focus impact",
    "Prerequisite / Trigger": "Focus concern",
    "Scheduling / Stage": "Adaptive deepening — impact only when decision-relevant",
    "Burden": "0.18",
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / impact deepening only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Establish focus-impact facet without subtracting from frequency evidence",
    "Variant Group": "FOCUS_IMPACT",
    "Source Sheet": "Intellectual",
    "Registry Notes": "Ask only when impact changes priority, urgency, or Planning"
  },
  {
    "Question ID": "Q000044",
    "Sort Key": "1.4003",
    "Legacy ID": "INT003",
    "Question": "When focusing was difficult in the past 7 days, what did you notice around those times? Select any that fit.",
    "Response Type": "Multi",
    "Role": "discriminator",
    "Primary Dimension": "Intellectual",
    "Primary Construct": "Focus contributors",
    "Prerequisite / Trigger": "Focus concern",
    "Scheduling / Stage": "Adaptive discrimination — contributor context only when decision-relevant",
    "Burden": "0.2",
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / contributor discrimination only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Capture member-observed contributor relationships without cross-construct severity inference",
    "Variant Group": "FOCUS_CONTRIBUTOR_DISCRIMINATOR",
    "Source Sheet": "Intellectual",
    "Registry Notes": "Do not ask alongside INT005 by default"
  },
  {
    "Question ID": "Q000045",
    "Sort Key": "1.4004",
    "Legacy ID": "INT004",
    "Question": "Thinking about the past 7 days, how often did you have a chance to do something that kept your mind interested or engaged?",
    "Response Type": "Single",
    "Role": "engagement-probe",
    "Primary Dimension": "Intellectual",
    "Primary Construct": "Cognitive engagement",
    "Prerequisite / Trigger": "Focus concern",
    "Scheduling / Stage": "Deferred — no canonical Discovery stage",
    "Burden": "0.1",
    "Audit Status": "Future candidate — downstream use required",
    "Runtime Status": "Deferred / future research candidate",
    "Evidence Status": "Hypothesis",
    "Decision Use": "No current governed downstream decision use",
    "Variant Group": "COGNITIVE_ENGAGEMENT_CANDIDATE",
    "Source Sheet": "Intellectual",
    "Registry Notes": "Preserve as future candidate; do not ask in canonical Discovery"
  },
  {
    "Question ID": "Q000046",
    "Sort Key": "1.4005",
    "Legacy ID": "INT005",
    "Question": "If you wanted to make focusing easier right now, what would need to be taken into account? Select any that fit.",
    "Response Type": "Multi",
    "Role": "feasibility-probe",
    "Primary Dimension": "Intellectual",
    "Primary Construct": "Focus feasibility",
    "Prerequisite / Trigger": "Focus concern",
    "Scheduling / Stage": "Adaptive Fit — Focus constraints only when Planning changes",
    "Burden": "0.11",
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / fit only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Constrain Focus Planning without cross-construct severity inference",
    "Variant Group": "FOCUS_FEASIBILITY",
    "Source Sheet": "Intellectual",
    "Registry Notes": "Prospective Planning-fit probe; do not pair with INT003 by default"
  },
  {
    "Question ID": "Q000047",
    "Sort Key": "1.5001",
    "Legacy ID": "OCC001",
    "Question": "Which situation are you mainly talking about?",
    "Response Type": "Single",
    "Role": "discriminator",
    "Primary Dimension": "Occupational",
    "Primary Construct": "Work / school context",
    "Prerequisite / Trigger": "Work concern",
    "Scheduling / Stage": "Adaptive Narrow — Occupational context only when unresolved",
    "Burden": 0.1,
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / occupational-context routing only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Establish work/school routing context without severity inference",
    "Variant Group": "OCCUPATIONAL_CONTEXT",
    "Source Sheet": "Occupational",
    "Registry Notes": "Skip when context is already explicit"
  },
  {
    "Question ID": "Q000048",
    "Sort Key": "1.5002",
    "Legacy ID": "OCC002",
    "Question": "Which best describes your work or school situation right now?",
    "Response Type": "Single",
    "Role": "state-probe",
    "Primary Dimension": "Occupational",
    "Primary Construct": "Work / school stability",
    "Prerequisite / Trigger": "Work concern",
    "Scheduling / Stage": "Adaptive state evidence — Occupational stability only when independently relevant",
    "Burden": 0.16,
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / occupational-stability state only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Establish JOB_SECURITY current state directly",
    "Variant Group": "OCCUPATIONAL_STABILITY_STATE",
    "Source Sheet": "Occupational",
    "Registry Notes": "Absence and insecurity remain distinct"
  },
  {
    "Question ID": "Q000049",
    "Sort Key": "1.5003",
    "Legacy ID": "OCC003",
    "Question": "In the past 4 weeks, how often did you worry about losing work, hours, a role, or another important source of work or school stability?",
    "Response Type": "Single",
    "Role": "state-probe",
    "Primary Dimension": "Occupational",
    "Primary Construct": "Stability worry",
    "Prerequisite / Trigger": "Work concern",
    "Scheduling / Stage": "Adaptive deepening — stability worry only when decision-relevant",
    "Burden": 0.18,
    "Audit Status": "Keep — optional conditional deepening",
    "Runtime Status": "Conditional / decision-relevant deepening only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Capture stability-worry facet without duplicating current-state evidence",
    "Variant Group": "OCCUPATIONAL_STABILITY_WORRY",
    "Source Sheet": "Occupational",
    "Registry Notes": "OCC002 remains authoritative for current stability"
  },
  {
    "Question ID": "Q000050",
    "Sort Key": "1.5004",
    "Legacy ID": "OCC004",
    "Question": "What seems connected to the work, school, or training difficulty you are experiencing right now? Select any that fit.",
    "Response Type": "Multi",
    "Role": "discriminator",
    "Primary Dimension": "Occupational",
    "Primary Construct": "Work / school difficulty",
    "Prerequisite / Trigger": "Work concern",
    "Scheduling / Stage": "Adaptive discrimination — Occupational contributor context only when decision-relevant",
    "Burden": 0.2,
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / contributor discrimination only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Capture contributor/context relationships without cross-construct severity inference",
    "Variant Group": "OCCUPATIONAL_CONTRIBUTOR_DISCRIMINATOR",
    "Source Sheet": "Occupational",
    "Registry Notes": "Do not pair with OCC006 by default"
  },
  {
    "Question ID": "Q000051",
    "Sort Key": "1.5005",
    "Legacy ID": "OCC005",
    "Question": "In the past 4 weeks, how often did work, school, training, or related responsibilities interfere with the time or energy you needed elsewhere?",
    "Response Type": "Single",
    "Role": "impact-probe",
    "Primary Dimension": "Occupational",
    "Primary Construct": "Work / school interference",
    "Prerequisite / Trigger": "Work concern",
    "Scheduling / Stage": "Adaptive deepening — role interference only when decision-relevant",
    "Burden": 0.16,
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / impact deepening only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Capture Occupational role-interference impact without Schedule/Stress severity inference",
    "Variant Group": "OCCUPATIONAL_ROLE_INTERFERENCE",
    "Source Sheet": "Occupational",
    "Registry Notes": "Impact facet only"
  },
  {
    "Question ID": "Q000052",
    "Sort Key": "1.5006",
    "Legacy ID": "OCC006",
    "Question": "What could limit your ability to improve your work, school, or training situation right now? Select any that fit.",
    "Response Type": "Multi",
    "Role": "feasibility-probe",
    "Primary Dimension": "Occupational",
    "Primary Construct": "Work / school feasibility",
    "Prerequisite / Trigger": "Work concern",
    "Scheduling / Stage": "Adaptive Fit — Occupational constraints only when Planning changes",
    "Burden": 0.12,
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / fit only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Constrain Occupational Planning without cross-construct severity inference",
    "Variant Group": "OCCUPATIONAL_FEASIBILITY",
    "Source Sheet": "Occupational",
    "Registry Notes": "Prospective Planning-fit probe"
  },
  {
    "Question ID": "Q000053",
    "Sort Key": "1.5007",
    "Legacy ID": "OCC007",
    "Question": "Because you said you currently have no income, what factors are contributing to that right now? Select any that apply.",
    "Response Type": "Multi",
    "Role": "driver-discriminator",
    "Primary Dimension": "Occupational",
    "Primary Construct": "No-income occupational drivers",
    "Prerequisite / Trigger": "No-income evidence",
    "Scheduling / Stage": "Adaptive discrimination — no-income contributors only when decision-relevant",
    "Burden": 0.12,
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / no-income discrimination only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Explain no-income Occupational context without duplicate severity",
    "Variant Group": "NO_INCOME_OCCUPATIONAL_DRIVERS",
    "Source Sheet": "Occupational",
    "Registry Notes": "Requires explicit no-income evidence"
  },
  {
    "Question ID": "Q000054",
    "Sort Key": "1.5008",
    "Legacy ID": "OCC100",
    "Question": "How much control do you usually have over when you work, study, or handle your main daily responsibilities?",
    "Response Type": "Single",
    "Role": "control-probe",
    "Primary Dimension": "Occupational",
    "Primary Construct": "Schedule control",
    "Prerequisite / Trigger": "Schedule concern",
    "Scheduling / Stage": "Adaptive Fit — schedule control only when Planning changes",
    "Burden": 0.16,
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / schedule-control fit only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Capture schedule-control resource/constraint for Planning fit",
    "Variant Group": "SCHEDULE_CONTROL",
    "Source Sheet": "Occupational",
    "Registry Notes": "High control does not negate schedule interference"
  },
  {
    "Question ID": "Q000055",
    "Sort Key": "1.5009",
    "Legacy ID": "OCC101",
    "Question": "In the past 7 days, how often did your schedule interfere with sleep, regular meals, or another routine that matters to you?",
    "Response Type": "Single",
    "Role": "impact-probe",
    "Primary Dimension": "Occupational",
    "Primary Construct": "Schedule interference",
    "Prerequisite / Trigger": "Schedule concern",
    "Scheduling / Stage": "Adaptive state/deepening evidence — Schedule interference only when independently relevant",
    "Burden": 0.16,
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / schedule deepening only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Establish SCHEDULE_DISRUPTION interference facet directly",
    "Variant Group": "SCHEDULE_INTERFERENCE",
    "Source Sheet": "Occupational",
    "Registry Notes": "Negative answer is facet-specific only"
  },
  {
    "Question ID": "Q000056",
    "Sort Key": "1.6001",
    "Legacy ID": "FIN001",
    "Question": "During the past 30 days, how often have you felt worried or under pressure because of money?",
    "Response Type": "Single",
    "Role": "state-probe",
    "Primary Dimension": "Financial",
    "Primary Construct": "Money pressure",
    "Prerequisite / Trigger": "Money concern",
    "Scheduling / Stage": "Adaptive state evidence — typically Narrow/Deepen; may itself satisfy focused evidence",
    "Burden": 0.18,
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / adaptive",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Establish subjective FINANCIAL_STRAIN state directly",
    "Variant Group": "MONEY_PRESSURE_STATE"
  },
  {
    "Question ID": "Q000057",
    "Sort Key": "1.6002",
    "Legacy ID": "FIN002",
    "Question": "Right now, how well are you able to cover your regular required expenses?",
    "Response Type": "Single",
    "Role": "condition-probe",
    "Primary Dimension": "Financial",
    "Primary Construct": "Expense coverage",
    "Prerequisite / Trigger": "Money concern",
    "Scheduling / Stage": "Adaptive clarification — only when expense coverage changes the decision",
    "Burden": 0.18,
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / expense-coverage clarification only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Establish required-expense coverage facet without blind additive scoring",
    "Variant Group": "EXPENSE_COVERAGE"
  },
  {
    "Question ID": "Q000058",
    "Sort Key": "1.6003",
    "Legacy ID": "FIN003",
    "Question": "Which parts of your current financial situation seem connected to the money pressure you are experiencing? Select any that fit.",
    "Response Type": "Multi",
    "Role": "concern-scope",
    "Primary Dimension": "Financial",
    "Primary Construct": "Financial contributors",
    "Prerequisite / Trigger": "Money concern",
    "Scheduling / Stage": "Adaptive discrimination — only when contributor identity changes the decision",
    "Burden": 0.24,
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / contributor discrimination only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Capture Financial contributor/context without adding severity",
    "Variant Group": "FINANCIAL_CONTRIBUTOR_CONTEXT"
  },
  {
    "Question ID": "Q000059",
    "Sort Key": "1.6004",
    "Legacy ID": "FIN004",
    "Question": "During the past 30 days, how much has your financial situation limited choices that matter to you?",
    "Response Type": "Single",
    "Role": "impact-probe",
    "Primary Dimension": "Financial",
    "Primary Construct": "Financial impact",
    "Prerequisite / Trigger": "Money concern",
    "Scheduling / Stage": "Adaptive deepening — only when impact changes the decision",
    "Burden": 0.18,
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / impact deepening only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Establish choice-limitation impact facet",
    "Variant Group": "FINANCIAL_IMPACT"
  },
  {
    "Question ID": "Q000060",
    "Sort Key": "1.6005",
    "Legacy ID": "FIN005",
    "Question": "Which best describes your required payments over the next 30 days?",
    "Response Type": "Single",
    "Role": "urgency-probe",
    "Primary Dimension": "Financial",
    "Primary Construct": "Payment urgency",
    "Prerequisite / Trigger": "Money concern",
    "Scheduling / Stage": "Adaptive deepening — only when near-term urgency changes the decision",
    "Burden": 0.14,
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / urgency deepening only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Establish near-term payment-risk facet",
    "Variant Group": "PAYMENT_URGENCY"
  },
  {
    "Question ID": "Q000061",
    "Sort Key": "1.6006",
    "Legacy ID": "FIN006",
    "Question": "If an unexpected necessary expense came up today, how able would you be to cover it without missing other required payments?",
    "Response Type": "Single",
    "Role": "resilience-probe",
    "Primary Dimension": "Financial",
    "Primary Construct": "Financial resilience",
    "Prerequisite / Trigger": "Money concern",
    "Scheduling / Stage": "Adaptive deepening — only when resilience changes the decision",
    "Burden": 0.14,
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / resilience deepening only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Establish unexpected-expense resilience facet",
    "Variant Group": "FINANCIAL_RESILIENCE"
  },
  {
    "Question ID": "Q000062",
    "Sort Key": "1.6007",
    "Legacy ID": "FIN007",
    "Question": "Which required expenses are currently difficult to cover or at risk of being missed? Select any that fit.",
    "Response Type": "Multi",
    "Role": "obligation-probe",
    "Primary Dimension": "Financial",
    "Primary Construct": "At-risk obligations",
    "Prerequisite / Trigger": "Money concern",
    "Scheduling / Stage": "Adaptive discrimination — only when obligation identity changes the decision",
    "Burden": 0.2,
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / obligation discrimination only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Identify at-risk obligations without manufacturing downstream conditions",
    "Variant Group": "AT_RISK_OBLIGATIONS"
  },
  {
    "Question ID": "Q000063",
    "Sort Key": "1.6008",
    "Legacy ID": "FIN008",
    "Question": "How clearly do you know what money is coming in, what is due, and what is available right now?",
    "Response Type": "Single",
    "Role": "visibility-probe",
    "Primary Dimension": "Financial",
    "Primary Construct": "Financial visibility",
    "Prerequisite / Trigger": "Money concern",
    "Scheduling / Stage": "Deferred — no canonical Discovery stage",
    "Burden": 0.1,
    "Audit Status": "Future candidate — downstream use required",
    "Runtime Status": "Deferred / future research candidate",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Preserve for future governed budgeting/cash-flow action only",
    "Variant Group": "FINANCIAL_VISIBILITY"
  },
  {
    "Question ID": "Q000064",
    "Sort Key": "1.6009",
    "Legacy ID": "FIN009",
    "Question": "If EL8 suggested a money-related next step, what would it need to account for? Select any that fit.",
    "Response Type": "Multi",
    "Role": "feasibility-probe",
    "Primary Dimension": "Financial",
    "Primary Construct": "Action feasibility",
    "Prerequisite / Trigger": "Money concern",
    "Scheduling / Stage": "Adaptive Fit — only when constraints change Planning",
    "Burden": 0.1,
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / fit only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Capture Financial Planning constraints without severity inference",
    "Variant Group": "FINANCIAL_PLAN_FIT"
  },
  {
    "Question ID": "Q000065",
    "Sort Key": "1.7001",
    "Legacy ID": "ENV001",
    "Question": "Over the past 7 days, how often did something about your home or immediate surroundings interfere with your usual daily activities?",
    "Response Type": "Single",
    "Role": "state-probe",
    "Primary Dimension": "Environmental",
    "Primary Construct": "Home interference",
    "Prerequisite / Trigger": "Home concern",
    "Scheduling / Stage": "Adaptive state evidence — Environmental interference only when relevant",
    "Burden": "0.18",
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / environmental-interference state only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Establish ENVIRONMENTAL_INTERFERENCE state only",
    "Variant Group": "ENVIRONMENTAL_INTERFERENCE",
    "Source Sheet": "Environmental",
    "Registry Notes": "Do not substitute for housing stability or Safety evidence"
  },
  {
    "Question ID": "Q000066",
    "Sort Key": "1.7002",
    "Legacy ID": "ENV002",
    "Question": "Which conditions, if any, seemed connected with times daily life was harder recently? Select any that fit.",
    "Response Type": "Multi",
    "Role": "discriminator",
    "Primary Dimension": "Environmental",
    "Primary Construct": "Home conditions",
    "Prerequisite / Trigger": "Home concern",
    "Scheduling / Stage": "Adaptive discrimination — factor identity only when decision-relevant",
    "Burden": "0.2",
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / factor discrimination only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Identify Environmental factors without adding severity",
    "Variant Group": "ENVIRONMENTAL_FACTORS",
    "Source Sheet": "Environmental",
    "Registry Notes": "Cross-dimensional answers route clarification only"
  },
  {
    "Question ID": "Q000067",
    "Sort Key": "1.7003",
    "Legacy ID": "ENV003",
    "Question": "Do you currently feel physically safe where you live?",
    "Response Type": "Single",
    "Role": "safety-probe",
    "Primary Dimension": "Environmental",
    "Primary Construct": "Home safety",
    "Prerequisite / Trigger": "Relevant home/environment concern or evidence raises physical-safety ambiguity under approved Safety trigger rules",
    "Scheduling / Stage": "Governed Safety clarification — only after approved contextual trigger",
    "Burden": "0.2",
    "Audit Status": "Keep — governance validation required",
    "Runtime Status": "Conditional / governed safety trigger only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Contextual Safety evidence; governed minimum clarification when triggered",
    "Variant Group": "CONTEXTUAL_HOME_SAFETY",
    "Source Sheet": "Environmental",
    "Registry Notes": "Not a universal Environmental question; Safety disposition remains separately governed"
  },
  {
    "Question ID": "Q000068",
    "Sort Key": "1.7004",
    "Legacy ID": "ENV004",
    "Question": "How secure is your current housing for the near future?",
    "Response Type": "Single",
    "Role": "stability-probe",
    "Primary Dimension": "Environmental",
    "Primary Construct": "Housing stability",
    "Prerequisite / Trigger": "Home concern",
    "Scheduling / Stage": "Adaptive state evidence — Housing stability only when independently relevant",
    "Burden": "0.18",
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / housing-stability state only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Establish HOUSING_STABILITY state only",
    "Variant Group": "HOUSING_STABILITY",
    "Source Sheet": "Environmental",
    "Registry Notes": "Does not erase interference or Safety evidence"
  },
  {
    "Question ID": "Q000069",
    "Sort Key": "1.7005",
    "Legacy ID": "ENV005",
    "Question": "For the environmental difficulty that matters most, how much can you realistically change yourself right now?",
    "Response Type": "Single",
    "Role": "feasibility-probe",
    "Primary Dimension": "Environmental",
    "Primary Construct": "Environmental feasibility",
    "Prerequisite / Trigger": "Home concern",
    "Scheduling / Stage": "Adaptive Fit — environmental agency/feasibility only when Planning changes",
    "Burden": "0.12",
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / fit only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Capture Environmental Planning feasibility without severity inference",
    "Variant Group": "ENVIRONMENTAL_PLAN_FIT",
    "Source Sheet": "Environmental",
    "Registry Notes": "Planning-fit only"
  },
  {
    "Question ID": "Q000070",
    "Sort Key": "1.8001",
    "Legacy ID": "SPT001",
    "Question": "Thinking about your life as a whole, how clear is your sense of direction?",
    "Response Type": "Single",
    "Role": "state-probe",
    "Primary Dimension": "Spiritual",
    "Primary Construct": "Direction clarity",
    "Prerequisite / Trigger": "Direction concern",
    "Scheduling / Stage": "Adaptive state evidence — Direction only when independently relevant",
    "Burden": 0.18,
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / direction-state only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Establish DIRECTION_CLARITY state only when distinction changes focus or Planning",
    "Variant Group": "DIRECTION_CLARITY",
    "Source Sheet": "Spiritual",
    "Registry Notes": "Do not automatically pair with SPT002"
  },
  {
    "Question ID": "Q000071",
    "Sort Key": "1.8002",
    "Legacy ID": "SPT002",
    "Question": "Thinking about your life as a whole, how much does what you do feel meaningful or worthwhile to you?",
    "Response Type": "Single",
    "Role": "state-probe",
    "Primary Dimension": "Spiritual",
    "Primary Construct": "Meaning / purpose",
    "Prerequisite / Trigger": "Meaning/purpose concern",
    "Scheduling / Stage": "Adaptive state evidence — Meaning only when independently relevant",
    "Burden": 0.18,
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / meaning-state only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Establish MEANING_PURPOSE state independently from direction clarity",
    "Variant Group": "MEANING_PURPOSE",
    "Source Sheet": "Spiritual",
    "Registry Notes": "No automatic Safety implication; do not automatically ask both state probes"
  },
  {
    "Question ID": "Q000072",
    "Sort Key": "1.8003",
    "Legacy ID": "SPT003",
    "Question": "If something feels unclear or missing, which description fits best right now?",
    "Response Type": "Single",
    "Role": "discriminator",
    "Primary Dimension": "Spiritual",
    "Primary Construct": "Direction discriminator",
    "Prerequisite / Trigger": "Direction concern",
    "Scheduling / Stage": "Adaptive discrimination — only when Direction/Meaning/Values/Next-step ambiguity matters",
    "Burden": 0.16,
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / direction discrimination only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Distinguish direction, meaning, values, or next-step ambiguity without additive severity",
    "Variant Group": "DIRECTION_DISCRIMINATOR",
    "Source Sheet": "Spiritual",
    "Registry Notes": "Do not require when direct state evidence is already decision-sufficient"
  },
  {
    "Question ID": "Q000073",
    "Sort Key": "1.8004",
    "Legacy ID": "SPT004",
    "Question": "If you wanted to act on something important to you, which things would EL8 need to account for right now? Select any that fit.",
    "Response Type": "Multi",
    "Role": "feasibility-probe",
    "Primary Dimension": "Spiritual",
    "Primary Construct": "Purpose/action feasibility",
    "Prerequisite / Trigger": "Direction concern",
    "Scheduling / Stage": "Adaptive Fit — purpose/action constraints only when Planning changes",
    "Burden": 0.1,
    "Audit Status": "Keep",
    "Runtime Status": "Conditional / fit only",
    "Evidence Status": "Hypothesis",
    "Decision Use": "Capture purpose/action Planning-fit constraints without cross-dimensional severity inference",
    "Variant Group": "PURPOSE_ACTION_PLAN_FIT",
    "Source Sheet": "Spiritual",
    "Registry Notes": "Not required for Direction/Meaning state sufficiency"
  },
  {
    "Question ID": "Q000074",
    "Sort Key": "1.9001",
    "Legacy ID": "SFT000",
    "Question": "Before we continue, are you in immediate danger right now?",
    "Response Type": "Single",
    "Role": "safety-confirmation",
    "Primary Dimension": "Safety",
    "Primary Construct": "Immediate danger confirmation",
    "Prerequisite / Trigger": "Safety contextual trigger",
    "Scheduling / Stage": "Design-only governed Safety pathway — outside ordinary Discovery stages",
    "Burden": 0.08,
    "Audit Status": "Design candidate — expert validation required",
    "Runtime Status": "Design-only / expert validation required",
    "Evidence Status": "Expert validation required",
    "Decision Use": "Categorical Safety confirmation only; never wellness scoring",
    "Variant Group": "IMMEDIATE_DANGER_CONFIRMATION",
    "Source Sheet": "Safety",
    "Registry Notes": "EL8-authored wording is not a validated suicide screener; do not expose externally before qualified expert/validated-screening review"
  },
  {
    "Question ID": "Q000075",
    "Sort Key": "1.9002",
    "Legacy ID": "SFT001",
    "Question": "Are you thinking about seriously harming yourself or ending your life right now, and do you intend to act on those thoughts?",
    "Response Type": "Single",
    "Role": "safety-confirmation",
    "Primary Dimension": "Safety",
    "Primary Construct": "Current self-harm thoughts and intent",
    "Prerequisite / Trigger": "Safety contextual trigger",
    "Scheduling / Stage": "Design-only governed Safety pathway — outside ordinary Discovery stages",
    "Burden": 0.08,
    "Audit Status": "Design candidate — expert validation required",
    "Runtime Status": "Design-only / expert validation required",
    "Evidence Status": "Expert validation required",
    "Decision Use": "Categorical Safety evidence only; parent wording combines thoughts and intent and requires validated architecture",
    "Variant Group": "CURRENT_SELF_HARM_THOUGHTS_INTENT",
    "Source Sheet": "Safety",
    "Registry Notes": "Do not expose or operationalize externally before qualified expert/validated-screening review"
  },
  {
    "Question ID": "Q000076",
    "Sort Key": "1.9003",
    "Legacy ID": "SFT002",
    "Question": "Do you feel able to keep yourself safe right now?",
    "Response Type": "Single",
    "Role": "safety-confirmation",
    "Primary Dimension": "Safety",
    "Primary Construct": "Ability to stay safe",
    "Prerequisite / Trigger": "Safety contextual trigger",
    "Scheduling / Stage": "Design-only governed Safety pathway — outside ordinary Discovery stages",
    "Burden": 0.08,
    "Audit Status": "Design candidate — expert validation required",
    "Runtime Status": "Design-only / expert validation required",
    "Evidence Status": "Expert validation required",
    "Decision Use": "Categorical Safety evidence; reported ability to stay safe is not an independent clearance rule",
    "Variant Group": "ABILITY_TO_STAY_SAFE",
    "Source Sheet": "Safety",
    "Registry Notes": "Validate wording, role and disposition with qualified expertise before external use"
  }
]);
