import assert from 'node:assert/strict';
import { ACTIONS } from './index.js';
import { ALL_QUESTIONS, ALL_ANSWERS, ALL_EFFECTS, QUESTION_BY_ID, ANSWER_BY_ID, ACTION_BY_ID, migrateLegacyRegistryId, getQuestion, getAnswer, getAnswersForQuestion, getEffectsForAnswer } from './registry.js';

assert.equal(Object.keys(QUESTION_BY_ID).length, ALL_QUESTIONS.length);
assert.equal(Object.keys(ANSWER_BY_ID).length, ALL_ANSWERS.length);
assert.equal(Object.keys(ACTION_BY_ID).length, ACTIONS.length);
assert.equal(ALL_QUESTIONS.length, 97);
assert.equal(ALL_ANSWERS.length, 593);
assert.equal(ALL_EFFECTS.length, 482);
assert.equal(ACTIONS.length, 41);
assert.equal(migrateLegacyRegistryId('GEN001'), 'Q000001');
assert.equal(migrateLegacyRegistryId('GEN001.01'), 'A000001');
assert.equal(getQuestion('GEN001'), null, 'canonical runtime must not silently accept legacy question aliases');
assert.equal(getAnswer('GEN001.01'), null, 'canonical runtime must not silently accept legacy answer aliases');
assert.equal(getQuestion(migrateLegacyRegistryId('GEN001'))?.['Question ID'], 'Q000001');
assert.equal(getAnswersForQuestion('Q000001').length, 14);
assert.equal(getEffectsForAnswer('A000001').length, 0, 'general routing answers must not fabricate Effects');
assert.ok(getEffectsForAnswer('A000109').length > 0);
assert.ok(QUESTION_BY_ID.Q000077, 'orientation baseline must be present');
assert.ok(QUESTION_BY_ID.Q000092, 'all eight baseline driver discriminators must be present');
assert.ok(QUESTION_BY_ID.Q000097, 'direct state probes must be present');
// Exact canonical parentage replaces the former repository-only ID allocation.
assert.equal(ANSWER_BY_ID.A000592['Parent Question ID'],'Q000097');
assert.equal(ANSWER_BY_ID.A000574['Parent Question ID'],'Q000094');
assert.equal(ANSWER_BY_ID.A000568['Parent Question ID'],'Q000092');
for(const id of ['A000605','A000629','A000630','A000654'])assert.equal(getAnswer(id),null);
for(const answer of ALL_ANSWERS)assert.ok(QUESTION_BY_ID[answer['Parent Question ID']],answer['Answer ID']);
for(const effect of ALL_EFFECTS)assert.ok(ANSWER_BY_ID[effect['Answer ID']],effect['Effect ID']);
assert.equal(new Set(ALL_EFFECTS.map(e=>e['Effect ID'])).size,ALL_EFFECTS.length,'effect identities must be unique');
assert.ok(ACTION_BY_ID.ACT000001);
console.log('registry runtime adapter: PASS');
