// GENERATED FROM RECONCILED EL8 DRIVE AUTHORITY — 2026-09-03
// Canonical population relationship graph. Retired IDs remain non-executable.
// Member-specific edges are instantiated separately; population relationships are priors, not member causal truth.
// Do not hand-edit generated registry content; reconcile in Drive and regenerate.

export const RELATIONSHIPS = Object.freeze([
  {
    "Relationship ID":"REL000001","From Signal / Dimension":"SLEEP_QUALITY","To Signal / Dimension":"EMOTIONAL_STATE","Direction":"Bidirectional","Evidence Strength":"High","Source IDs":"SRC000003,SRC000004","Status":"ACTIVE","Relationship Type":"Reciprocal association / candidate feedback loop","Edge Instantiation Rule":"Instantiate a member edge only when both endpoint Signals are independently supported and member evidence makes the relationship decision-relevant. Preserve reciprocal direction unless member evidence discriminates it.","Directional Leverage Eligibility":"Conditional. Either direction may become a leverage candidate only with member-specific directional support plus modifiability/feasibility and meaningful downstream decision value."
  },
  {
    "Relationship ID":"REL000002","From Signal / Dimension":"FINANCIAL_STRAIN","To Signal / Dimension":"EMOTIONAL_STATE","Direction":"Primarily Financial→Emotional","Evidence Strength":"High","Source IDs":"SRC000007","Status":"ACTIVE","Relationship Type":"Directed candidate contributor relationship","Edge Instantiation Rule":"Instantiate only when FINANCIAL_STRAIN and EMOTIONAL_STATE are independently supported and member evidence makes a Financial→Emotional hypothesis material to a decision.","Directional Leverage Eligibility":"Eligible Financial→Emotional only when member evidence supports Financial strain/control as an upstream modifiable contributor, competing explanations are retained, and targeting Financial can plausibly change more than the direct Financial outcome."
  },
  {
    "Relationship ID":"REL000003","From Signal / Dimension":"JOB_SECURITY","To Signal / Dimension":"EMOTIONAL_STATE","Direction":"Primarily Occupational→Emotional","Evidence Strength":"High","Source IDs":"SRC000006,SRC000022","Status":"ACTIVE — CANONICAL JOB_SECURITY→EMOTIONAL_STATE","Relationship Type":"Directed candidate contributor relationship","Edge Instantiation Rule":"Instantiate only when JOB_SECURITY and EMOTIONAL_STATE are independently supported and security/status—not workload, fit or direction—is the member-specific occupational factor under consideration.","Directional Leverage Eligibility":"Eligible Occupational→Emotional when member evidence supports temporal/material relevance and an in-scope modifiable pathway exists; otherwise context/monitoring only."
  },
  {
    "Relationship ID":"REL000004","From Signal / Dimension":"LONELINESS","To Signal / Dimension":"EMOTIONAL_STATE","Direction":"Bidirectional/feedback","Evidence Strength":"High","Source IDs":"SRC000005","Status":"ACTIVE","Relationship Type":"Reciprocal association / candidate feedback loop","Edge Instantiation Rule":"Instantiate only when LONELINESS and EMOTIONAL_STATE are independently supported; preserve subjective loneliness semantics and reciprocal uncertainty.","Directional Leverage Eligibility":"Directional leverage only after member-specific direction and a feasible target are supported; otherwise association/monitoring."
  },
  {
    "Relationship ID":"REL000005","From Signal / Dimension":"ENVIRONMENTAL_INTERFERENCE","To Signal / Dimension":"SLEEP_QUALITY,ENERGY_FUNCTION,EMOTIONAL_STATE,ACTIVITY_LEVEL,LONELINESS","Direction":"Environmental→specific linked construct when member-supported","Evidence Strength":"Moderate-high","Source IDs":"SRC000008","Status":"ACTIVE","Relationship Type":"Contextual directed candidate contributor relationship","Edge Instantiation Rule":"For each member, instantiate one specific edge per independently supported target endpoint and specific environmental factor. Never instantiate the comma-separated target set as one omnibus member edge.","Directional Leverage Eligibility":"Eligible Environmental→target only when the specific factor is plausibly modifiable, the target is independently supported, and member evidence makes the relationship materially decision-relevant."
  },
  {
    "Relationship ID":"REL000006","From Signal / Dimension":"ACTIVITY_LEVEL","To Signal / Dimension":"ENERGY_FUNCTION","Direction":"Activity→Energy/Vitality","Evidence Strength":"High","Source IDs":"SRC000017","Status":"ACTIVE","Relationship Type":"Directed intervention-responsive candidate relationship","Edge Instantiation Rule":"Instantiate when ACTIVITY_LEVEL and ENERGY_FUNCTION are independently supported and activity is feasible/safe; member evidence must make energy response relevant to the decision.","Directional Leverage Eligibility":"Eligible Activity→Energy candidate because intervention evidence supports average direction, but only when activity is a legitimate modifiable target and competing energy drivers do not dominate."
  },
  {
    "Relationship ID":"REL000007","From Signal / Dimension":"ACTIVITY_LEVEL","To Signal / Dimension":"SLEEP_QUALITY","Direction":"Activity→Sleep","Evidence Strength":"High","Source IDs":"SRC000018","Status":"ACTIVE","Relationship Type":"Directed intervention-responsive candidate relationship","Edge Instantiation Rule":"Instantiate when ACTIVITY_LEVEL and SLEEP_QUALITY are independently supported, activity is feasible/safe and sleep response is decision-relevant.","Directional Leverage Eligibility":"Eligible Activity→Sleep candidate with intervention evidence, but direct sleep drivers and member fit can outrank it."
  },
  {
    "Relationship ID":"REL000008","From Signal / Dimension":"SLEEP_QUALITY","To Signal / Dimension":"PRESSURE_PATTERN","Direction":"Likely bidirectional","Evidence Strength":"Moderate-high","Source IDs":"SRC000003,SRC000004,SRC000019","Status":"ACTIVE","Relationship Type":"Reciprocal association / candidate feedback loop","Edge Instantiation Rule":"Instantiate only when SLEEP_QUALITY and PRESSURE_PATTERN are independently supported and the relationship can affect discrimination, leverage, monitoring or Review. Preserve reciprocal uncertainty by default.","Directional Leverage Eligibility":"Either direction conditionally eligible only after member temporal evidence, modifiability and competing explanations support it. Reciprocal association alone is insufficient to name a primary upstream driver."
  },
  {
    "Relationship ID":"REL000009","From Signal / Dimension":"SLEEP_QUALITY","To Signal / Dimension":"FOCUS_FUNCTION","Direction":"Sleep→Focus","Evidence Strength":"Moderate-high","Source IDs":"SRC000020","Status":"ACTIVE","Relationship Type":"Directed candidate functional relationship","Edge Instantiation Rule":"Instantiate when SLEEP_QUALITY and FOCUS_FUNCTION are independently supported and sleep-related focus response is decision-relevant.","Directional Leverage Eligibility":"Eligible Sleep→Focus only with member-specific temporal support and a modifiable sleep target; population evidence alone is insufficient for core ordering."
  },
  {
    "Relationship ID":"REL000010","From Signal / Dimension":"LONELINESS","To Signal / Dimension":"SLEEP_QUALITY","Direction":"Association; direction uncertain","Evidence Strength":"Moderate","Source IDs":"SRC000021","Status":"ACTIVE","Relationship Type":"Association / uncertain direction","Edge Instantiation Rule":"Instantiate when LONELINESS and SLEEP_QUALITY are independently supported and co-variation is worth testing; direction remains unset unless stronger member evidence emerges.","Directional Leverage Eligibility":"Not directionally leverage-eligible from population evidence alone. Requires additional member evidence that discriminates direction plus modifiability/decision value."
  },
  {
    "Relationship ID":"REL000011","From Signal / Dimension":"JOB_SECURITY","To Signal / Dimension":"EMOTIONAL_STATE","Direction":"Occupational security/status→Emotional","Evidence Strength":"Moderate-high","Source IDs":"SRC000006,SRC000022","Status":"RETIRED — DUPLICATE OF REL000003","Relationship Type":"Retired duplicate","Edge Instantiation Rule":"Never instantiate.","Directional Leverage Eligibility":"Not eligible."
  },
  {
    "Relationship ID":"REL000012","From Signal / Dimension":"PRESSURE_PATTERN","To Signal / Dimension":"FOCUS_FUNCTION","Direction":"Stress→selected focus/executive functions","Evidence Strength":"Moderate","Source IDs":"SRC000023","Status":"ACTIVE","Relationship Type":"Directed candidate functional relationship","Edge Instantiation Rule":"Instantiate when PRESSURE_PATTERN and FOCUS_FUNCTION are independently supported and the weaker population prior is decision-relevant.","Directional Leverage Eligibility":"Conditionally eligible Pressure→Focus only with repeated member-level support and after stronger/direct alternatives are considered."
  },
  {
    "Relationship ID":"REL000013","From Signal / Dimension":"FINANCIAL_STRAIN","To Signal / Dimension":"PRESSURE_PATTERN","Direction":"Primarily Financial→Pressure candidate contributor","Mechanism":"Financial hardship can contribute to perceived pressure through worry, appraisal, uncertainty and related psychological mechanisms; individual pathways vary.","Evidence Strength":"Moderate-high","Source IDs":"SRC000007,SRC000014,SRC000032,SRC000080","EL8 Use":"Use only when FINANCIAL_STRAIN and PRESSURE_PATTERN are independently supported and testing the relationship can change Prioritization, Planning, downstream monitoring or Review. This edge may participate in a mediated Financial→Pressure→Sleep hypothesis only with a separately instantiated Pressure↔Sleep edge.","Claim Guardrail":"Do not infer either endpoint from the other, declare finances the root cause from co-occurrence, promise pressure reduction from a Financial intervention, or infer a direct Financial→Sleep relationship.","Status":"ACTIVE","Relationship Type":"Directed candidate contributor / mediator-entry relationship","Conditions / Moderators":"FINANCIAL_STRAIN and PRESSURE_PATTERN independently supported; Financial factor current/material; relationship decision-relevant; distinguish objective hardship, subjective strain, control and broader emotional state.","Competing / Reverse Explanations":"Work insecurity, relationship/health burden, other stressors; pressure affecting financial behavior/appraisal; shared structural constraints; dispositional/contextual appraisal differences.","Member Evidence Strengthens":"Member reports financial strain preceding pressure/worry; repeated Financial changes co-vary with pressure; direct Financial target improves followed by expected pressure reduction.","Member Evidence Weakens":"Pressure changes independently; Financial target improves without pressure response; reverse timing; another driver better explains pressure.","Temporal Expectation":"No universal lag. Review direct Financial target and pressure trajectory separately over the governed Intervention window.","Decision Uses":"Discovery driver discrimination; Prioritization leverage; Planning core-intervention rationale; downstream pressure monitoring; mediated-path testing; Review relationship learning.","Edge Instantiation Rule":"Instantiate only when both endpoints are independently supported and member evidence makes a Financial→Pressure hypothesis materially decision-relevant.","Directional Leverage Eligibility":"Conditionally eligible Financial→Pressure when member evidence supports temporal/material relevance, Financial target is plausibly modifiable/in scope, and competing explanations remain represented."
  }
]);
