// GENERATED FROM RECONCILED EL8 DRIVE AUTHORITY — 2026-09-01
// Canonical relationship graph. Retired IDs remain non-executable.
// Do not hand-edit generated registry content; reconcile in Drive and regenerate.

export const RELATIONSHIPS = Object.freeze([
  {
    "Relationship ID": "REL000001",
    "From Signal / Dimension": "SLEEP_QUALITY",
    "To Signal / Dimension": "EMOTIONAL_STATE",
    "Direction": "Bidirectional",
    "Mechanism": "Sleep disturbance can worsen emotional health; emotional distress can disrupt sleep.",
    "Evidence Strength": "High",
    "Source IDs": "SRC000003,SRC000004",
    "EL8 Use": "Population evidence raises the value of member-specific relationship clarification only when SLEEP_QUALITY and EMOTIONAL_STATE are independently supported; never transfer severity or select the focus automatically.",
    "Member-facing Claim Tier": "Tier 2 — evidence-backed association + intervention evidence",
    "Improvement Inference": "Supported: improving sleep may improve some mental-health outcomes; individual spillover is not guaranteed.",
    "Claim Guardrail": "Do not say sleep caused this member's emotional difficulty without longitudinal/member-specific evidence.",
    "Insight / Confirmation Template": "Research links sleep and emotional health in both directions. Because your answers also point to sleep difficulty, sleep may be a useful focus. Improving it may also help emotional wellbeing, but EL8 will check whether that happens for you.",
    "Status": "ACTIVE"
  },
  {
    "Relationship ID": "REL000002",
    "From Signal / Dimension": "FINANCIAL_STRAIN",
    "To Signal / Dimension": "EMOTIONAL_STATE",
    "Direction": "Primarily Financial→Emotional",
    "Mechanism": "Financial strain, debt pressure and reduced financial control are associated with greater emotional distress; the member-specific pathway remains unproven.",
    "Evidence Strength": "High",
    "Source IDs": "SRC000007",
    "EL8 Use": "Use as a population prior only when FINANCIAL_STRAIN and EMOTIONAL_STATE are independently supported; investigate a Financial→Emotional relationship only if it can change focus, urgency or Planning.",
    "Member-facing Claim Tier": "Tier 3 — strong population association",
    "Improvement Inference": "Plausible, not established here: reducing financial strain may improve wellbeing, but effects depend on what can actually change.",
    "Claim Guardrail": "FINANCIAL_STRAIN and EMOTIONAL_STATE must each be independently established. Do not transfer severity, infer a single causal pathway, or promise emotional improvement from financial change.",
    "Insight / Confirmation Template": "Research links financial strain with poorer emotional wellbeing. Because your answers separately point to financial strain and emotional difficulty, EL8 can test whether they appear related for you without assuming one caused the other.",
    "Status": "ACTIVE"
  },
  {
    "Relationship ID": "REL000003",
    "From Signal / Dimension": "JOB_SECURITY",
    "To Signal / Dimension": "EMOTIONAL_STATE",
    "Direction": "Primarily Occupational→Emotional",
    "Mechanism": "Unemployment and employment insecurity are associated with greater psychological distress; longitudinal evidence also supports average improvement after re-employment. Member-specific direction and magnitude remain uncertain.",
    "Evidence Strength": "High",
    "Source IDs": "SRC000006,SRC000022",
    "EL8 Use": "Use as a population prior only when JOB_SECURITY and EMOTIONAL_STATE are independently supported; distinguish security from workload, fit, progress and direction before relationship clarification.",
    "Member-facing Claim Tier": "Tier 3 — strong population association",
    "Improvement Inference": "Plausible: improving employment security or reducing insecurity may reduce distress; individual effect uncertain.",
    "Claim Guardrail": "Do not equate work dissatisfaction, workload, unemployment and job insecurity.",
    "Insight / Confirmation Template": "Research links employment insecurity with emotional distress. Your answers suggest security may matter here, so EL8 recommends clarifying that driver before choosing an action.",
    "Status": "ACTIVE — CANONICAL JOB_SECURITY→EMOTIONAL_STATE"
  },
  {
    "Relationship ID": "REL000004",
    "From Signal / Dimension": "LONELINESS",
    "To Signal / Dimension": "EMOTIONAL_STATE",
    "Direction": "Bidirectional/feedback",
    "Mechanism": "Low belonging can worsen emotional health; distress can reduce connection.",
    "Evidence Strength": "High",
    "Source IDs": "SRC000005",
    "EL8 Use": "Use as a population prior only when LONELINESS and EMOTIONAL_STATE are independently supported; do not substitute contact frequency, relationship strain or support availability.",
    "Member-facing Claim Tier": "Tier 3 — strong population association",
    "Improvement Inference": "Plausible: improving meaningful connection may improve wellbeing; magnitude and direction vary.",
    "Claim Guardrail": "Keep loneliness (subjective) separate from social isolation/contact frequency (objective). Avoid causal certainty.",
    "Insight / Confirmation Template": "Loneliness is associated with poorer mental and physical quality of life. If connection is a priority for you, improving meaningful support may have benefits beyond the Social dimension; EL8 will track whether those benefits appear for you.",
    "Status": "ACTIVE"
  },
  {
    "Relationship ID": "REL000005",
    "From Signal / Dimension": "ENVIRONMENTAL_INTERFERENCE",
    "To Signal / Dimension": "SLEEP_QUALITY,ENERGY_FUNCTION,EMOTIONAL_STATE,ACTIVITY_LEVEL,LONELINESS",
    "Direction": "Environmental→specific linked construct when member-supported",
    "Mechanism": "Specific reported environmental factors can contribute to Environmental interference and may relate to sleep, energy, emotional wellbeing, activity or social connection; each linked member construct remains independently evidenced.",
    "Evidence Strength": "Moderate-high",
    "Source IDs": "SRC000008",
    "EL8 Use": "Use only when ENVIRONMENTAL_INTERFERENCE is directly supported, a specific Environmental factor is identified, and the linked member construct is separately supported. Treat the population relationship as a prior; member-specific linkage remains a hypothesis unless confirmed by member evidence.",
    "Member-facing Claim Tier": "Tier 4 — moderate evidence / context-dependent",
    "Improvement Inference": "Plausible: changing a relevant environmental constraint may improve the separately evidenced linked outcome; individual effect must be observed.",
    "Claim Guardrail": "Do not use an Environmental contributor/feasibility answer to manufacture ENVIRONMENTAL_INTERFERENCE severity or any downstream state. ENV001 governs Environmental interference; ENV004 separately governs HOUSING_STABILITY; each linked construct requires its own direct evidence.",
    "Insight / Confirmation Template": "Your answers separately point to environmental interference and another affected area. EL8 can test whether the specific environmental factor appears related while tracking whether changes actually improve the outcome for you.",
    "Status": "ACTIVE"
  },
  {
    "Relationship ID": "REL000006",
    "From Signal / Dimension": "ACTIVITY_LEVEL",
    "To Signal / Dimension": "ENERGY_FUNCTION",
    "Direction": "Activity→Energy/Vitality",
    "Mechanism": "Regular exercise can improve average energy/vitality and reduce fatigue; individual response varies.",
    "Evidence Strength": "High",
    "Source IDs": "SRC000017",
    "EL8 Use": "Use intervention evidence as a candidate leverage prior only when ACTIVITY_LEVEL and ENERGY_FUNCTION are independently supported and activity is feasible; no severity transfer.",
    "Member-facing Claim Tier": "Tier 2 — evidence-backed intervention relationship",
    "Improvement Inference": "Supported on average: regular exercise can modestly improve energy/vitality and reduce fatigue; individual benefit is not guaranteed.",
    "Claim Guardrail": "Do not infer that low activity caused low energy, create LOW_ENERGY from activity evidence, or recommend activity despite contraindications or poor fit.",
    "Insight / Confirmation Template": "Research suggests regular activity can improve energy on average. Since activity and energy both came up for you, EL8 can test whether a feasible activity change helps your energy.",
    "Status": "ACTIVE"
  },
  {
    "Relationship ID": "REL000007",
    "From Signal / Dimension": "ACTIVITY_LEVEL",
    "To Signal / Dimension": "SLEEP_QUALITY",
    "Direction": "Activity→Sleep",
    "Mechanism": "Exercise interventions can improve sleep quality on average, but the relevant activity type, dose and member fit vary.",
    "Evidence Strength": "High",
    "Source IDs": "SRC000018",
    "EL8 Use": "Use intervention evidence as a candidate leverage prior only when ACTIVITY_LEVEL and SLEEP_QUALITY are independently supported and activity is feasible; direct sleep drivers still govern.",
    "Member-facing Claim Tier": "Tier 2 — evidence-backed intervention relationship",
    "Improvement Inference": "Supported on average: physical activity can improve sleep quality; individual benefit is not guaranteed.",
    "Claim Guardrail": "Do not infer inactivity caused poor sleep, create SLEEP_QUALITY impairment from activity evidence, or automatically prioritize activity over direct sleep drivers.",
    "Insight / Confirmation Template": "Research suggests physical activity can improve sleep quality. Since sleep and activity both came up for you, EL8 can test whether a feasible activity change supports your sleep.",
    "Status": "ACTIVE"
  },
  {
    "Relationship ID": "REL000008",
    "From Signal / Dimension": "SLEEP_QUALITY",
    "To Signal / Dimension": "PRESSURE_PATTERN",
    "Direction": "Likely bidirectional",
    "Mechanism": "Sleep quality and perceived stress can reinforce each other, with substantial member-level variation.",
    "Evidence Strength": "Moderate-high",
    "Source IDs": "SRC000003,SRC000004,SRC000019",
    "EL8 Use": "When SLEEP_QUALITY and PRESSURE_PATTERN are independently supported, population evidence justifies testing a member-specific relationship; neither construct selects or scores the other.",
    "Member-facing Claim Tier": "Tier 3 — evidence-backed association / temporal support",
    "Improvement Inference": "Plausible: improving sleep may reduce stress for some people, but this relationship does not guarantee improvement in either direction.",
    "Claim Guardrail": "Do not infer sleep caused stress or stress caused sleep difficulty. Neither construct may manufacture the other without direct member evidence.",
    "Insight / Confirmation Template": "Research suggests sleep and stress can reinforce each other. Since both came up for you, EL8 can track whether changes in one reliably accompany changes in the other.",
    "Status": "ACTIVE"
  },
  {
    "Relationship ID": "REL000009",
    "From Signal / Dimension": "SLEEP_QUALITY",
    "To Signal / Dimension": "FOCUS_FUNCTION",
    "Direction": "Sleep→Focus",
    "Mechanism": "Sleep disturbance and restriction are associated with impairments in attention and selected executive functions.",
    "Evidence Strength": "Moderate-high",
    "Source IDs": "SRC000020",
    "EL8 Use": "Use as a population prior only when SLEEP_QUALITY and FOCUS_FUNCTION are independently supported; temporal/member-specific evidence may strengthen a leverage hypothesis but cannot create focus impairment.",
    "Member-facing Claim Tier": "Tier 3 — evidence-backed functional association",
    "Improvement Inference": "Plausible: better sleep may support attention/focus, but this row does not establish a guaranteed treatment effect for the member.",
    "Claim Guardrail": "Do not infer poor sleep caused focus difficulty or create FOCUS_FUNCTION impairment from sleep evidence alone.",
    "Insight / Confirmation Template": "Research links sleep problems with attention and some executive functions. Since sleep and focus both came up for you, EL8 can check whether better sleep is followed by clearer daytime focus.",
    "Status": "ACTIVE"
  },
  {
    "Relationship ID": "REL000010",
    "From Signal / Dimension": "LONELINESS",
    "To Signal / Dimension": "SLEEP_QUALITY",
    "Direction": "Association; direction uncertain",
    "Mechanism": "Loneliness is associated with poorer subjective sleep quality and insomnia-type disturbance; direction and mechanisms remain uncertain.",
    "Evidence Strength": "Moderate",
    "Source IDs": "SRC000021",
    "EL8 Use": "When LONELINESS and SLEEP_QUALITY are independently supported, use population evidence only to justify testing co-variation; direction and leverage remain uncertain.",
    "Member-facing Claim Tier": "Tier 4 — moderate evidence / association",
    "Improvement Inference": "No direct improvement inference: changing connection may or may not change sleep and vice versa.",
    "Claim Guardrail": "Do not infer loneliness from low contact frequency, infer poor sleep from loneliness, transfer severity between constructs, or claim either caused the other.",
    "Insight / Confirmation Template": "Research finds loneliness and sleep disturbance often occur together. Since both are separately relevant for you, EL8 can track whether changes in connection and sleep move together without assuming a causal direction.",
    "Status": "ACTIVE"
  },
  {
    "Relationship ID": "REL000011",
    "From Signal / Dimension": "JOB_SECURITY",
    "To Signal / Dimension": "EMOTIONAL_STATE",
    "Direction": "Occupational security/status→Emotional",
    "Mechanism": "Unemployment and employment insecurity are associated with greater psychological distress; re-employment is associated with improvement on average.",
    "Evidence Strength": "Moderate-high",
    "Source IDs": "SRC000006,SRC000022",
    "EL8 Use": "Retired duplicate. Preserve permanent ID and provenance only; runtime/design logic must use REL000003 as the single canonical JOB_SECURITY→EMOTIONAL_STATE relationship. SRC000022 evidence has been consolidated into REL000003.",
    "Member-facing Claim Tier": "Tier 3 — longitudinal population association",
    "Improvement Inference": "Plausible on average: re-employment or improved security may reduce distress; individual effect is uncertain.",
    "Claim Guardrail": "JOB_SECURITY must be independently established. REL000003 and REL000011 represent overlapping evidence for the same canonical relationship and must not be double-counted; no severity transfer or guaranteed benefit from re-employment.",
    "Insight / Confirmation Template": "Research links unemployment and employment insecurity with greater distress. If your answers independently support work security and emotional difficulty, EL8 can track whether changes in work security are followed by changes in wellbeing.",
    "Status": "RETIRED — DUPLICATE OF REL000003"
  },
  {
    "Relationship ID": "REL000012",
    "From Signal / Dimension": "PRESSURE_PATTERN",
    "To Signal / Dimension": "FOCUS_FUNCTION",
    "Direction": "Stress→selected focus/executive functions",
    "Mechanism": "Psychosocial stress can impair some executive-function performance, but effects are smaller and less uniform than broad stress-cognition claims imply.",
    "Evidence Strength": "Moderate",
    "Source IDs": "SRC000023",
    "EL8 Use": "Use as a weaker population prior only when PRESSURE_PATTERN and FOCUS_FUNCTION are independently supported; prefer direct and member-specific evidence before treating stress as a leverage point.",
    "Member-facing Claim Tier": "Tier 4 — moderate / domain-specific evidence",
    "Improvement Inference": "No direct improvement inference from this relationship alone.",
    "Claim Guardrail": "Do not claim stress generally damages cognition or infer that stress is the main cause of a member's focus difficulty.",
    "Insight / Confirmation Template": "Stress can interfere with some executive functions. Since stress and focus both came up for you, EL8 can check whether they reliably move together before treating stress as a leverage point.",
    "Status": "ACTIVE"
  }
]);
