// EL8 Prioritization.
// Conscious authority: governed comparative reasoning over Discovery-supported candidates.
// Subcon: quantitative ranking is retained as a non-authoritative shadow diagnostic.
import { UNKNOWN, discoveryToPrioritization, prioritizationToFocusConfirmation } from '../contracts/capability-boundaries.js';
import {memberRelationshipGraph} from '../state/cross-dimensional-hypothesis.js';
export const PRIORITIZATION_SCHEMA_VERSION='2.2.0';
export const PRIORITY_FACTOR_KEYS=Object.freeze(['urgency','materiality','memberImportance','leverage','readiness']);
export const PRIORITIZATION_OUTCOME=Object.freeze({CLEAR_DOMINANCE:'CLEAR_DOMINANCE',NEAR_EQUIVALENT:'NEAR_EQUIVALENT',DEEPEN_FOR_DISCRIMINATOR:'DEEPEN_FOR_DISCRIMINATOR',PORTFOLIO:'PORTFOLIO'});
const FACTOR_WEIGHT=Object.freeze({urgency:1,materiality:1,memberImportance:1,leverage:.75,readiness:.5});
const CONFIDENCE_VALUE=Object.freeze({limited:.45,moderate:.7,high:.9});
function clamp01(value){const n=Number(value);return Number.isFinite(n)?Math.max(0,Math.min(1,n)):UNKNOWN}
function suppliedFactor(decisionFactors,constructId,key){const value=decisionFactors?.[constructId]?.[key]??decisionFactors?.[key]?.[constructId];return value==null?UNKNOWN:clamp01(value)}
function leverageFromMemberGraph(constructId,graph){const outgoing=graph.edges.filter(edge=>edge.fromConstructId===constructId);if(!outgoing.length)return UNKNOWN;const supported=outgoing.map(edge=>CONFIDENCE_VALUE[edge.confidence]??0).filter(Boolean);return supported.length?clamp01(Math.max(...supported)):UNKNOWN}
function profile(candidate,decisionFactors,graph){const factors={};for(const key of PRIORITY_FACTOR_KEYS){const explicit=suppliedFactor(decisionFactors,candidate.constructId,key),candidateValue=candidate.factors?.[key];if(key==='leverage'){factors[key]=leverageFromMemberGraph(candidate.constructId,graph);continue}factors[key]=explicit!==UNKNOWN?explicit:(candidateValue==null?UNKNOWN:clamp01(candidateValue))}return factors}
function shadowScore(p){let weighted=0,weights=0;for(const key of PRIORITY_FACTOR_KEYS){if(p[key]===UNKNOWN)continue;const w=FACTOR_WEIGHT[key];weighted+=p[key]*w;weights+=w}return weights?weighted/weights:null}
function governedEvidence(p){const known=PRIORITY_FACTOR_KEYS.filter(k=>p[k]!==UNKNOWN);const high=known.filter(k=>p[k]>=.7);const material=known.filter(k=>p[k]>=.5);return{knownCount:known.length,highCount:high.length,materialCount:material.length,memberImportance:p.memberImportance===UNKNOWN?null:p.memberImportance,urgency:p.urgency===UNKNOWN?null:p.urgency}}
function compareGoverned(a,b){const ae=governedEvidence(a.profile),be=governedEvidence(b.profile);if(be.highCount!==ae.highCount)return be.highCount-ae.highCount;if(be.materialCount!==ae.materialCount)return be.materialCount-ae.materialCount;if(be.knownCount!==ae.knownCount)return be.knownCount-ae.knownCount;return a.candidate.constructId.localeCompare(b.candidate.constructId)}
function rationaleCodes(p){const codes=['discovery_supported'];if(p.memberImportance!==UNKNOWN&&p.memberImportance>=.7)codes.push('member_importance');if(p.urgency!==UNKNOWN&&p.urgency>=.7)codes.push('high_urgency');if(p.materiality!==UNKNOWN&&p.materiality>=.7)codes.push('high_materiality');if(p.leverage!==UNKNOWN&&p.leverage>=.7)codes.push('member_relationship_leverage');if(p.readiness!==UNKNOWN&&p.readiness>=.7)codes.push('member_readiness');if(PRIORITY_FACTOR_KEYS.some(key=>p[key]===UNKNOWN))codes.push('ranking_uncertainty_present');return codes}
function nearEquivalent(a,b){if(!a||!b)return false;const ae=governedEvidence(a.profile),be=governedEvidence(b.profile);return ae.highCount===be.highCount&&ae.materialCount===be.materialCount&&Math.abs((ae.memberImportance??.5)-(be.memberImportance??.5))<.2&&Math.abs((ae.urgency??.5)-(be.urgency??.5))<.2&&Math.abs((a.profile.leverage===UNKNOWN?.5:a.profile.leverage)-(b.profile.leverage===UNKNOWN?.5:b.profile.leverage))<.2}
function materiallyDominates(a,b){if(!a||!b)return false;const ae=governedEvidence(a.profile),be=governedEvidence(b.profile);const leverageAdvantage=a.profile.leverage!==UNKNOWN&&b.profile.leverage!==UNKNOWN&&a.profile.leverage-b.profile.leverage>=.2;const evidenceAdvantage=ae.highCount>be.highCount&&ae.materialCount>=be.materialCount;const urgencyAdvantage=ae.urgency!=null&&be.urgency!=null&&ae.urgency-be.urgency>=.3;const importanceAdvantage=ae.memberImportance!=null&&be.memberImportance!=null&&ae.memberImportance-be.memberImportance>=.3;return leverageAdvantage||evidenceAdvantage||urgencyAdvantage||importanceAdvantage}
function hasBoundedDiscriminator(a,b){if(!a||!b)return false;const unknownA=PRIORITY_FACTOR_KEYS.filter(k=>a.profile[k]===UNKNOWN),unknownB=PRIORITY_FACTOR_KEYS.filter(k=>b.profile[k]===UNKNOWN);return unknownA.length+unknownB.length===1}
function distinctPortfolioJustified(governed,decisionFactors){if(governed.length<2)return false;const requested=governed.filter(x=>decisionFactors?.[x.candidate.constructId]?.portfolio===true);return requested.length>=2}
function disposition(governed,decisionFactors){if(governed.length<=1)return PRIORITIZATION_OUTCOME.CLEAR_DOMINANCE;if(materiallyDominates(governed[0],governed[1]))return PRIORITIZATION_OUTCOME.CLEAR_DOMINANCE;if(nearEquivalent(governed[0],governed[1]))return PRIORITIZATION_OUTCOME.NEAR_EQUIVALENT;if(hasBoundedDiscriminator(governed[0],governed[1]))return PRIORITIZATION_OUTCOME.DEEPEN_FOR_DISCRIMINATOR;if(distinctPortfolioJustified(governed,decisionFactors))return PRIORITIZATION_OUTCOME.PORTFOLIO;return PRIORITIZATION_OUTCOME.NEAR_EQUIVALENT}
export function prioritizeCandidates(input,{safetyDisposition=null,decisionFactors={},relationshipHypotheses=[],now=new Date().toISOString()}={}){
 const governedInput=discoveryToPrioritization(input);const blocked=['pause_ordinary_flow','escalate'].includes(safetyDisposition?.disposition??governedInput.safetyDisposition);
 if(blocked)return{schemaVersion:PRIORITIZATION_SCHEMA_VERSION,memberStateRevision:governedInput.memberStateRevision,createdAt:now,blockedBySafety:true,decisionOutcome:null,recommended:[],alternatives:[],rationaleCodes:['safety_override'],relationshipTrace:[],shadow:null};
 const graph=memberRelationshipGraph(relationshipHypotheses,{now});
 const prepared=governedInput.candidates.map(candidate=>{const p=profile(candidate,decisionFactors,graph);return{candidate:Object.freeze({constructId:candidate.constructId,evidenceRefs:[...(candidate.evidenceRefs??[])],factors:Object.freeze({...p}),eligibility:'eligible'}),profile:p,shadowScore:shadowScore(p)}});
 const governed=[...prepared].sort(compareGoverned);const shadow=[...prepared].sort((a,b)=>(b.shadowScore??-1)-(a.shadowScore??-1)||a.candidate.constructId.localeCompare(b.candidate.constructId));const decisionOutcome=disposition(governed,decisionFactors);
 const rankedItems=governed.map(({candidate,profile:p},index)=>Object.freeze({constructId:candidate.constructId,rank:index+1,evidenceRefs:[...candidate.evidenceRefs],factors:p,rationaleCodes:[...rationaleCodes(p),...(decisionOutcome===PRIORITIZATION_OUTCOME.NEAR_EQUIVALENT&&index<2?['near_equivalent_member_preference']:[])]}));
 let recommended=[],alternatives=[...rankedItems];
 if(decisionOutcome===PRIORITIZATION_OUTCOME.CLEAR_DOMINANCE&&rankedItems.length){recommended=[rankedItems[0]];alternatives=rankedItems.slice(1)}
 else if(decisionOutcome===PRIORITIZATION_OUTCOME.PORTFOLIO){recommended=rankedItems.filter(x=>decisionFactors?.[x.constructId]?.portfolio===true);alternatives=rankedItems.filter(x=>!recommended.some(r=>r.constructId===x.constructId))}
 const boundary=prioritizationToFocusConfirmation({memberStateRevision:governedInput.memberStateRevision,recommended,alternatives,rationaleRefs:[]});
 const outcomeCode={CLEAR_DOMINANCE:'clear_dominance',NEAR_EQUIVALENT:'member_preference_discriminator',DEEPEN_FOR_DISCRIMINATOR:'deepen_for_discriminator',PORTFOLIO:'smallest_useful_portfolio'}[decisionOutcome];
 return{schemaVersion:PRIORITIZATION_SCHEMA_VERSION,memberStateRevision:governedInput.memberStateRevision,createdAt:now,blockedBySafety:false,decisionOutcome,recommended:boundary.recommended,alternatives:boundary.alternatives,rationaleCodes:['governed_comparative_reasoning',outcomeCode],relationshipTrace:graph.edges.map(edge=>Object.freeze({relationshipId:edge.relationshipId,memberEdgeId:edge.edgeId,fromConstructId:edge.fromConstructId,toConstructId:edge.toConstructId,confidence:edge.confidence})),shadow:Object.freeze({role:'Subcon',authoritative:false,model:'weighted_priority_v1',ranking:shadow.map((x,index)=>Object.freeze({constructId:x.candidate.constructId,rank:index+1,score:x.shadowScore}))})};
}
