// EL8 Prioritization.
// Conscious authority: governed comparative reasoning over Discovery-supported candidates.
// Subcon: quantitative ranking is retained as a non-authoritative shadow diagnostic.
import { UNKNOWN, createPriorityCandidate } from '../contracts/intelligence-contracts.js';
import { discoveryToPrioritization, prioritizationToFocusConfirmation } from '../contracts/capability-boundaries.js';
export const PRIORITIZATION_SCHEMA_VERSION='2.1.0';
export const PRIORITY_FACTOR_KEYS=Object.freeze(['urgency','materiality','memberImportance','leverage','readiness']);
const FACTOR_WEIGHT=Object.freeze({urgency:1,materiality:1,memberImportance:1,leverage:.75,readiness:.5});
function clamp01(value){const n=Number(value);return Number.isFinite(n)?Math.max(0,Math.min(1,n)):UNKNOWN}
function suppliedFactor(decisionFactors,constructId,key){const value=decisionFactors?.[constructId]?.[key]??decisionFactors?.[key]?.[constructId];return value==null?UNKNOWN:clamp01(value)}
function profile(candidate,decisionFactors){const factors={};for(const key of PRIORITY_FACTOR_KEYS){const explicit=suppliedFactor(decisionFactors,candidate.constructId,key),candidateValue=candidate.factors?.[key];factors[key]=explicit!==UNKNOWN?explicit:(candidateValue==null?UNKNOWN:clamp01(candidateValue))}return factors}
function shadowScore(p){let weighted=0,weights=0;for(const key of PRIORITY_FACTOR_KEYS){if(p[key]===UNKNOWN)continue;const w=FACTOR_WEIGHT[key];weighted+=p[key]*w;weights+=w}return weights?weighted/weights:null}
function governedEvidence(p){const known=PRIORITY_FACTOR_KEYS.filter(k=>p[k]!==UNKNOWN);const high=known.filter(k=>p[k]>=.7);const material=known.filter(k=>p[k]>=.5);return{knownCount:known.length,highCount:high.length,materialCount:material.length,memberImportance:p.memberImportance===UNKNOWN?null:p.memberImportance,urgency:p.urgency===UNKNOWN?null:p.urgency}}
function compareGoverned(a,b){const ae=governedEvidence(a.profile),be=governedEvidence(b.profile);if(be.highCount!==ae.highCount)return be.highCount-ae.highCount;if(be.materialCount!==ae.materialCount)return be.materialCount-ae.materialCount;if(be.knownCount!==ae.knownCount)return be.knownCount-ae.knownCount;return a.candidate.constructId.localeCompare(b.candidate.constructId)}
function rationaleCodes(p){const codes=['discovery_supported'];if(p.memberImportance!==UNKNOWN&&p.memberImportance>=.7)codes.push('member_importance');if(p.urgency!==UNKNOWN&&p.urgency>=.7)codes.push('high_urgency');if(p.materiality!==UNKNOWN&&p.materiality>=.7)codes.push('high_materiality');if(p.leverage!==UNKNOWN&&p.leverage>=.7)codes.push('shared_contributor_leverage');if(p.readiness!==UNKNOWN&&p.readiness>=.7)codes.push('member_readiness');if(PRIORITY_FACTOR_KEYS.some(key=>p[key]===UNKNOWN))codes.push('ranking_uncertainty_present');return codes}
function nearEquivalent(a,b){if(!a||!b)return false;const ae=governedEvidence(a.profile),be=governedEvidence(b.profile);return ae.highCount===be.highCount&&ae.materialCount===be.materialCount&&Math.abs((ae.memberImportance??.5)-(be.memberImportance??.5))<.2&&Math.abs((ae.urgency??.5)-(be.urgency??.5))<.2}
export function prioritizeCandidates(input,{safetyDisposition=null,decisionFactors={},now=new Date().toISOString()}={}){
 const governedInput=discoveryToPrioritization(input);const blocked=['pause_ordinary_flow','escalate'].includes(safetyDisposition?.disposition??governedInput.safetyDisposition);
 if(blocked)return{schemaVersion:PRIORITIZATION_SCHEMA_VERSION,memberStateRevision:governedInput.memberStateRevision,createdAt:now,blockedBySafety:true,recommended:[],alternatives:[],rationaleCodes:['safety_override'],shadow:null};
 const prepared=governedInput.candidates.map(candidate=>{const p=profile(candidate,decisionFactors);return{candidate:createPriorityCandidate({constructId:candidate.constructId,evidenceRefs:candidate.evidenceRefs??[],factors:p,eligibility:'eligible'}),profile:p,shadowScore:shadowScore(p)}});
 const governed=[...prepared].sort(compareGoverned);const shadow=[...prepared].sort((a,b)=>(b.shadowScore??-1)-(a.shadowScore??-1)||a.candidate.constructId.localeCompare(b.candidate.constructId));
 const memberChoiceUseful=nearEquivalent(governed[0],governed[1]);
 const rankedItems=governed.map(({candidate,profile:p},index)=>Object.freeze({constructId:candidate.constructId,rank:index+1,evidenceRefs:[...candidate.evidenceRefs],factors:p,rationaleCodes:[...rationaleCodes(p),...(memberChoiceUseful&&index<2?['near_equivalent_member_preference']:[])]}));
 const boundary=prioritizationToFocusConfirmation({memberStateRevision:governedInput.memberStateRevision,recommended:rankedItems,alternatives:[],rationaleRefs:[]});
 return{schemaVersion:PRIORITIZATION_SCHEMA_VERSION,memberStateRevision:governedInput.memberStateRevision,createdAt:now,blockedBySafety:false,recommended:boundary.recommended,alternatives:boundary.alternatives,rationaleCodes:['governed_comparative_reasoning',...(memberChoiceUseful?['member_preference_discriminator']:[])],shadow:Object.freeze({role:'Subcon',authoritative:false,model:'weighted_priority_v1',ranking:shadow.map((x,index)=>Object.freeze({constructId:x.candidate.constructId,rank:index+1,score:x.shadowScore}))})};
}
