// EL8 Prioritization.
// Conscious authority: governed comparative reasoning over Discovery-supported candidates.
// Subcon: quantitative ranking is retained as a non-authoritative shadow diagnostic.
import { UNKNOWN, discoveryToPrioritization, prioritizationToFocusConfirmation } from '../contracts/capability-boundaries.js';
import {memberRelationshipGraph} from '../state/cross-dimensional-hypothesis.js';
export const PRIORITIZATION_SCHEMA_VERSION='2.2.0';
export const PRIORITY_FACTOR_KEYS=Object.freeze(['urgency','materiality','memberImportance','leverage','readiness']);
const FACTOR_WEIGHT=Object.freeze({urgency:1,materiality:1,memberImportance:1,leverage:.75,readiness:.5});
const CONFIDENCE_VALUE=Object.freeze({limited:.45,moderate:.7,high:.9});
function clamp01(value){const n=Number(value);return Number.isFinite(n)?Math.max(0,Math.min(1,n)):UNKNOWN}
function suppliedFactor(decisionFactors,constructId,key){const value=decisionFactors?.[constructId]?.[key]??decisionFactors?.[key]?.[constructId];return value==null?UNKNOWN:clamp01(value)}
function leverageFromMemberGraph(constructId,graph){const outgoing=graph.edges.filter(edge=>edge.fromConstructId===constructId);if(!outgoing.length)return UNKNOWN;const supported=outgoing.map(edge=>CONFIDENCE_VALUE[edge.confidence]??0).filter(Boolean);if(!supported.length)return UNKNOWN;const breadth=Math.min(.1*(new Set(outgoing.map(edge=>edge.toConstructId)).size-1),.2);return clamp01(Math.max(...supported)+breadth)}
function profile(candidate,decisionFactors,graph){const factors={};for(const key of PRIORITY_FACTOR_KEYS){const explicit=suppliedFactor(decisionFactors,candidate.constructId,key),candidateValue=candidate.factors?.[key];if(key==='leverage'){factors[key]=leverageFromMemberGraph(candidate.constructId,graph);continue}factors[key]=explicit!==UNKNOWN?explicit:(candidateValue==null?UNKNOWN:clamp01(candidateValue))}return factors}
function shadowScore(p){let weighted=0,weights=0;for(const key of PRIORITY_FACTOR_KEYS){if(p[key]===UNKNOWN)continue;const w=FACTOR_WEIGHT[key];weighted+=p[key]*w;weights+=w}return weights?weighted/weights:null}
function governedEvidence(p){const known=PRIORITY_FACTOR_KEYS.filter(k=>p[k]!==UNKNOWN);const high=known.filter(k=>p[k]>=.7);const material=known.filter(k=>p[k]>=.5);return{knownCount:known.length,highCount:high.length,materialCount:material.length,memberImportance:p.memberImportance===UNKNOWN?null:p.memberImportance,urgency:p.urgency===UNKNOWN?null:p.urgency}}
function compareGoverned(a,b){const ae=governedEvidence(a.profile),be=governedEvidence(b.profile);if(be.highCount!==ae.highCount)return be.highCount-ae.highCount;if(be.materialCount!==ae.materialCount)return be.materialCount-ae.materialCount;if(be.knownCount!==ae.knownCount)return be.knownCount-ae.knownCount;return a.candidate.constructId.localeCompare(b.candidate.constructId)}
function rationaleCodes(p){const codes=['discovery_supported'];if(p.memberImportance!==UNKNOWN&&p.memberImportance>=.7)codes.push('member_importance');if(p.urgency!==UNKNOWN&&p.urgency>=.7)codes.push('high_urgency');if(p.materiality!==UNKNOWN&&p.materiality>=.7)codes.push('high_materiality');if(p.leverage!==UNKNOWN&&p.leverage>=.7)codes.push('member_relationship_leverage');if(p.readiness!==UNKNOWN&&p.readiness>=.7)codes.push('member_readiness');if(PRIORITY_FACTOR_KEYS.some(key=>p[key]===UNKNOWN))codes.push('ranking_uncertainty_present');return codes}
function nearEquivalent(a,b){if(!a||!b)return false;const ae=governedEvidence(a.profile),be=governedEvidence(b.profile);return ae.highCount===be.highCount&&ae.materialCount===be.materialCount&&Math.abs((ae.memberImportance??.5)-(be.memberImportance??.5))<.2&&Math.abs((ae.urgency??.5)-(be.urgency??.5))<.2}
export function prioritizeCandidates(input,{safetyDisposition=null,decisionFactors={},relationshipHypotheses=[],now=new Date().toISOString()}={}){
 const governedInput=discoveryToPrioritization(input);const blocked=['pause_ordinary_flow','escalate'].includes(safetyDisposition?.disposition??governedInput.safetyDisposition);
 if(blocked)return{schemaVersion:PRIORITIZATION_SCHEMA_VERSION,memberStateRevision:governedInput.memberStateRevision,createdAt:now,blockedBySafety:true,recommended:[],alternatives:[],rationaleCodes:['safety_override'],relationshipTrace:[],shadow:null};
 const graph=memberRelationshipGraph(relationshipHypotheses,{now});
 const prepared=governedInput.candidates.map(candidate=>{const p=profile(candidate,decisionFactors,graph);return{candidate:Object.freeze({constructId:candidate.constructId,evidenceRefs:[...(candidate.evidenceRefs??[])],factors:Object.freeze({...p}),eligibility:'eligible'}),profile:p,shadowScore:shadowScore(p)}});
 const governed=[...prepared].sort(compareGoverned);const shadow=[...prepared].sort((a,b)=>(b.shadowScore??-1)-(a.shadowScore??-1)||a.candidate.constructId.localeCompare(b.candidate.constructId));
 const memberChoiceUseful=nearEquivalent(governed[0],governed[1]);
 const rankedItems=governed.map(({candidate,profile:p},index)=>Object.freeze({constructId:candidate.constructId,rank:index+1,evidenceRefs:[...candidate.evidenceRefs],factors:p,rationaleCodes:[...rationaleCodes(p),...(memberChoiceUseful&&index<2?['near_equivalent_member_preference']:[])]}));
 // Default to the smallest useful recommendation: one Focus. Multiple plausible upstream drivers
 // remain alternatives unless incremental value, dependency/synergy and member capacity justify more.
 const recommended=rankedItems.length?[rankedItems[0]]:[];const alternatives=rankedItems.slice(1);
 const boundary=prioritizationToFocusConfirmation({memberStateRevision:governedInput.memberStateRevision,recommended,alternatives,rationaleRefs:[]});
 return{schemaVersion:PRIORITIZATION_SCHEMA_VERSION,memberStateRevision:governedInput.memberStateRevision,createdAt:now,blockedBySafety:false,recommended:boundary.recommended,alternatives:boundary.alternatives,rationaleCodes:['governed_comparative_reasoning','smallest_useful_focus_set',...(memberChoiceUseful?['member_preference_discriminator']:[])],relationshipTrace:graph.edges.map(edge=>Object.freeze({relationshipId:edge.relationshipId,memberEdgeId:edge.edgeId,fromConstructId:edge.fromConstructId,toConstructId:edge.toConstructId,confidence:edge.confidence})),shadow:Object.freeze({role:'Subcon',authoritative:false,model:'weighted_priority_v1',ranking:shadow.map((x,index)=>Object.freeze({constructId:x.candidate.constructId,rank:index+1,score:x.shadowScore}))})};
}
