const I=(id,concernId,intent,title,mechanism,expectedOutcome,measurement,effort=2,timeHorizon='7-days',extra={})=>Object.freeze({id,concernId,intent,title,mechanism,expectedOutcome,measurement,effort,timeHorizon,...extra});
export const INTERVENTION_LIBRARY=Object.freeze([
I('money_stabilize_snapshot','money','stabilize','Capture the immediate financial picture','visibility','Know the most urgent financial pressure and near-term consequence','Record the pressure, amount/timing if known, and consequence',1),
I('money_resolve_step','money','resolve','Take one financial pressure-reducing step','barrier-resolution','Reduce one immediate financial pressure','Complete and record one concrete action',2),
I('money_build_week','money','build','Set a seven-day spending boundary','structure','Improve short-term control over discretionary spending','Define the boundary and track adherence for seven days',2),
I('money_learn_driver','money','learn','Identify what is driving the money pressure','driver-identification','Clarify the main source of current financial strain','Complete a structured follow-up identifying income, debt, spending, timing, or another driver',1),
I('work_stabilize_next','work','stabilize','Protect the next necessary work or income step','immediate-continuity','Prevent near-term work/income deterioration','Identify and complete the most time-sensitive work/income action',2),
I('work_resolve_barrier','work','resolve','Address the main work barrier','barrier-resolution','Reduce the identified obstacle to work or income','Complete one action directly targeting the barrier',2),
I('work_build_pipeline','work','build','Build a small opportunity pipeline','opportunity-structure','Increase actionable work/income opportunities','Add or advance three realistic opportunities',3),
I('work_learn_barrier','work','learn','Clarify what is blocking progress','driver-identification','Identify the dominant work/income barrier','Complete a structured barrier check',1),
I('energy_stabilize_basics','energy','stabilize','Protect basic energy inputs today','basic-stability','Reduce avoidable short-term energy depletion','Complete one appropriate basic recovery action and record the result',1),
I('energy_resolve_drag','energy','resolve','Address one known energy drain','barrier-resolution','Reduce one identified contributor to low energy','Complete one action against the identified drain',2),
I('energy_build_movement','energy','build','Add manageable intentional movement','activation','Build a repeatable activity baseline','Complete and record one manageable movement period',2),
I('energy_learn_pattern','energy','learn','Track energy with sleep and activity','pattern-identification','Clarify when low energy occurs and what travels with it','Record energy, sleep and movement for the follow-up period',1),
I('sleep_stabilize_anchor','sleep','stabilize','Protect one sleep anchor','rhythm-stability','Reduce immediate schedule variability','Keep one realistic sleep or wake anchor',2),
I('sleep_resolve_barrier','sleep','resolve','Remove one identified sleep barrier','barrier-resolution','Reduce a known obstacle to sleep','Complete one change targeting the identified barrier',2),
I('sleep_build_log','sleep','build','Build a simple sleep routine','routine-building','Create a repeatable pre-sleep or wake routine','Follow the chosen routine and record adherence',2),
I('sleep_learn_log','sleep','learn','Track sleep timing and quality','pattern-identification','Clarify the sleep pattern before making stronger assumptions','Record sleep start, end and optional quality',1),
I('stress_stabilize_contain','stress','stabilize','Contain the strongest current stressor','load-reduction','Reduce immediate stress load','Take one practical containment or recovery action',1),
I('stress_resolve_stressor','stress','resolve','Address one controllable stressor','barrier-resolution','Reduce a specific source of stress','Complete one action that changes the stressor itself',2),
I('stress_build_recovery','stress','build','Create a repeatable recovery block','recovery-capacity','Improve ability to recover from routine stress','Complete a short planned recovery block on agreed days',2),
I('stress_learn_pattern','stress','learn','Map the strongest stress period','pattern-identification','Clarify triggers and context','Record trigger, intensity and context once daily',1),
I('relationships_stabilize_boundary','relationships','stabilize','Protect one immediate relationship boundary','harm-reduction','Reduce immediate interpersonal strain','Identify and apply one appropriate short-term boundary',2),
I('relationships_resolve_conversation','relationships','resolve','Take one appropriate communication step','communication','Improve one specific unresolved relationship issue','Complete one suitable conversation or message and record outcome',2),
I('relationships_build_connection','relationships','build','Build one positive connection habit','connection-building','Increase constructive relationship contact','Complete one intentional positive connection action',2),
I('relationships_learn_issue','relationships','learn','Clarify the main relationship issue','driver-identification','Identify what is actually creating the strain','Complete a structured issue/need/boundary check',1),
I('support_stabilize_contact','support','stabilize','Identify someone you can contact if needed','support-access','Ensure near-term access to appropriate support','Identify and record one realistic support contact/resource',1),
I('support_resolve_gap','support','resolve','Close one support gap','support-access','Increase usable support for a specific need','Contact or activate one appropriate support resource',2),
I('support_build_connection','support','build','Schedule one meaningful connection','connection-building','Increase regular social support','Arrange one realistic connection during the review period',2),
I('support_learn_map','support','learn','Map your available support','resource-mapping','Clarify which support exists for which needs','Complete a structured support map',1),
I('focus_stabilize_protect','focus','stabilize','Protect one necessary focus period','distraction-control','Complete one immediate priority despite focus difficulty','Use one short distraction-reduced block',1),
I('focus_resolve_distraction','focus','resolve','Remove one major distraction','barrier-resolution','Reduce a known focus barrier','Change or remove one identified distraction',2),
I('focus_build_block','focus','build','Build a repeatable focus block','attention-routine','Increase repeatable focused work','Complete one planned focus block and record duration',2),
I('focus_learn_context','focus','learn','Track when focus works and fails','pattern-identification','Clarify the conditions associated with focus','Record one effective or difficult focus period and context',1),
I('direction_resolve_choice','direction','resolve','Choose one near-term direction to test','decision','Reduce paralysis around direction','Select one realistic path for a small test',2),
I('direction_build_test','direction','build','Run one small direction experiment','experimentation','Gain real-world information about a possible path','Complete one small test and record what it taught you',2),
I('direction_learn_values','direction','learn','Clarify what matters most right now','values-clarification','Identify criteria for choosing direction','Complete a structured values/outcomes check',1),
I('home_stabilize_immediate','home','stabilize','Take the next housing stability step','immediate-stability','Reduce immediate home instability','Complete the most time-sensitive appropriate housing action',2,'immediate'),
I('home_resolve_barrier','home','resolve','Address the main home barrier','barrier-resolution','Reduce one identified home/environment problem','Complete one action targeting the barrier',2),
I('home_build_environment','home','build','Improve one repeatable home condition','environment-design','Make the environment more supportive of daily functioning','Implement and maintain one practical environmental change',2),
I('home_learn_issue','home','learn','Clarify how the home issue affects daily life','driver-identification','Identify the most consequential home barrier','Complete a structured home-impact check',1)
]);
export default INTERVENTION_LIBRARY;
