// Extracted from the legacy Focus Clarification module.
// These questions resolve uncertainty; they do not independently assign a plan.
export const clarificationQuestions = [
  {
    id: 'clarify_biggest_difference_v1',
    dimension: null,
    secondary_dimensions: [],
    signal: 'member_perceived_leverage',
    prompt: 'Which area would make the biggest positive difference in the next 30 days?',
    response_type: 'dynamic_dimension_choice',
    options_source: 'candidate_dimensions',
    fallback_options: ['Still unsure'],
    information_value: 5,
    burden: 1,
    actionability: 5,
    triggers: ['priority_tie', 'multiple_plausible_focuses'],
    dependencies: ['candidate_dimensions>=2'],
    cooldown_days: 14,
    stale_after_days: 30,
    safety_relevant: false,
    source: 'legacy focus-clarification'
  },
  {
    id: 'clarify_practicality_v1',
    dimension: null,
    secondary_dimensions: [],
    signal: 'member_perceived_feasibility',
    prompt: 'Which area feels most practical for you to work on right now?',
    response_type: 'dynamic_dimension_choice',
    options_source: 'candidate_dimensions',
    fallback_options: ['Still unsure'],
    information_value: 4,
    burden: 1,
    actionability: 5,
    triggers: ['priority_tie', 'feasibility_uncertain'],
    dependencies: ['candidate_dimensions>=2'],
    cooldown_days: 14,
    stale_after_days: 30,
    safety_relevant: false,
    source: 'legacy focus-clarification'
  },
  {
    id: 'clarify_upstream_leverage_v1',
    dimension: null,
    secondary_dimensions: [],
    signal: 'member_perceived_upstream_leverage',
    prompt: 'If one area improved first, which would make the other possible focus areas easier to improve?',
    response_type: 'dynamic_dimension_choice',
    options_source: 'candidate_dimensions',
    fallback_options: ['Still unsure'],
    information_value: 5,
    burden: 1,
    actionability: 5,
    triggers: ['priority_tie', 'upstream_relationship_uncertain'],
    dependencies: ['candidate_dimensions>=2'],
    cooldown_days: 14,
    stale_after_days: 30,
    safety_relevant: false,
    source: 'legacy focus-clarification'
  }
];
