// Extracted from Emotional Deepening v1.1.
// Evidence only: plan construction belongs to central EL8 intelligence.
export const emotionalQuestions = [
  {id:'emo_pressure_pattern_v1',dimension:'Emotional',secondary_dimensions:[],signal:'pressure_pattern',prompt:'What best describes the pressure right now?',response_type:'single_choice',options:['Stress / overwhelm','Anxiety / worry','Low mood','Anger / irritability','Grief / loss','Loneliness / disconnection','Relationship strain','Motivation / emotional exhaustion','Something else / mixed'],information_value:5,burden:1,actionability:4,triggers:['emotional_priority','emotional_uncertainty','member_requests_deepening'],dependencies:[],cooldown_days:14,stale_after_days:30,safety_relevant:false,source:'EMO-DEEP-001 v1.1'},
  {id:'emo_duration_v1',dimension:'Emotional',secondary_dimensions:[],signal:'duration',prompt:'How long has this been materially affecting you?',response_type:'single_choice',options:['Days','A few weeks','1–3 months','More than 3 months'],information_value:4,burden:1,actionability:3,triggers:['emotional_pressure_identified'],dependencies:['emo_pressure_pattern_v1'],cooldown_days:30,stale_after_days:60,safety_relevant:false,source:'EMO-DEEP-001 v1.1'},
  {id:'emo_functioning_v1',dimension:'Emotional',secondary_dimensions:['Occupational','Physical','Social'],signal:'functional_interference',prompt:'How much is it interfering with ordinary daily functioning?',response_type:'ordered_scale',options:['Mild — noticeable but manageable','Moderate — disrupting some routines','High — disrupting several important routines'],information_value:5,burden:1,actionability:5,triggers:['emotional_pressure_identified','conflicting_emotional_signals'],dependencies:[],cooldown_days:7,stale_after_days:14,safety_relevant:true,source:'EMO-DEEP-001 v1.1'},
  {id:'emo_helps_v1',dimension:'Emotional',secondary_dimensions:['Physical','Social','Spiritual'],signal:'helpful_supports',prompt:'What tends to help, even a little?',response_type:'single_choice',options:['Rest / recovery time','Movement / being outside','Talking with someone I trust','Structure / reducing demands','Reflection / calming practice','Nothing clearly helps yet'],information_value:3,burden:1,actionability:5,triggers:['emotional_action_needed'],dependencies:[],cooldown_days:14,stale_after_days:30,safety_relevant:false,source:'EMO-DEEP-001 v1.1'},
  {id:'emo_professional_support_v1',dimension:'Emotional',secondary_dimensions:[],signal:'professional_support_context',prompt:'Are you already getting professional support for this?',response_type:'single_choice',options:['Yes','No','Prefer not to say'],information_value:3,burden:1,actionability:3,triggers:['material_emotional_interference'],dependencies:[],cooldown_days:30,stale_after_days:60,safety_relevant:true,source:'EMO-DEEP-001 v1.1'},
  {id:'emo_workable_next_step_v1',dimension:'Emotional',secondary_dimensions:[],signal:'member_feasibility_preference',prompt:'What feels most workable for the next week?',response_type:'single_choice',options:['Protect recovery time','Reduce one source of overload','Reconnect with someone supportive','Restore one basic routine','Track the pattern before changing more'],information_value:4,burden:1,actionability:5,triggers:['emotional_plan_choice_uncertain'],dependencies:[],cooldown_days:7,stale_after_days:14,safety_relevant:false,source:'EMO-DEEP-001 v1.1'}
];
