// Extracted from Financial Deepening v1.0.
// Evidence only: objectives/pathways are selected by central EL8 intelligence.
const q=(id,signal,prompt,options,iv,burden,actionability,triggers=[],dependencies=[],cooldown_days=14,stale_after_days=30)=>({id,dimension:'Financial',secondary_dimensions:[],signal,prompt,response_type:'single_choice',options,information_value:iv,burden,actionability,triggers,dependencies,cooldown_days,stale_after_days,safety_relevant:false,source:'FIN-DEEP-001 v1.0'});
export const financialQuestions=[
q('fin_income_stability_v1','income_stability','How stable is your income right now?',['Stable','Mostly stable','Irregular / variable','No reliable income'],5,1,5,['financial_priority','income_uncertainty'],[],14,30),
q('fin_cashflow_v1','cashflow_after_essentials','After essentials, how is cash flow usually landing?',['Positive','Roughly even','Often short','Significantly short','Unsure'],5,1,5,['financial_priority','cashflow_uncertainty'],[],7,14),
q('fin_near_term_pressure_v1','near_term_pressure','How much near-term financial pressure is there?',['None','Manageable','At risk of missing obligations','Already behind'],5,1,5,['financial_pressure_possible'],[],7,14),
{id:'fin_obligations_v1',dimension:'Financial',secondary_dimensions:['Physical','Environmental'],signal:'essential_obligation_pressure',prompt:'Which required expenses are currently difficult or at risk?',response_type:'multi_choice',options:['Housing risk','Utilities risk','Food affordability','Transportation affordability','Medication / healthcare affordability','Debt / minimum payments difficult','Other required obligation','Voluntary support to partner / family / other','None'],information_value:5,burden:2,actionability:5,triggers:['financial_pressure_confirmed'],dependencies:['fin_near_term_pressure_v1'],cooldown_days:14,stale_after_days:30,safety_relevant:false,source:'FIN-DEEP-001 v1.0'},
q('fin_debt_status_v1','debt_status','How would you describe your debt-payment situation?',['None','Manageable','Difficult but current','At risk of missing payments','Behind / defaulted'],5,1,5,['debt_relevant','financial_priority'],[],14,30),
q('fin_obligation_coverage_v1','obligation_coverage','How reliably can required obligations be covered?',['Easily covered','Usually covered','Difficult to cover','Cannot reliably cover'],5,1,5,['financial_pressure_confirmed'],[],7,14),
q('fin_runway_v1','liquid_runway','About how much emergency breathing room do you have in liquid cash?',['3+ months','1–3 months','Less than 1 month','Little or none','Unsure'],5,1,5,['runway_unknown','financial_priority'],[],14,30),
q('fin_spending_flex_v1','nonessential_spending_flexibility','How much room is there to reduce non-essential spending?',['Already near minimum','Limited, some cuts possible','Moderate room to cut','Substantial room to cut','Unsure'],4,1,5,['cashflow_pressure','spending_leverage_uncertain'],[],14,30),
q('fin_pausable_expense_v1','pausable_expense','Is there a large non-essential expense that could realistically be paused?',['Yes','No','Unsure'],3,1,5,['cashflow_pressure'],[],14,30),
q('fin_spending_control_v1','spending_control','Do spending habits ever feel hard to control?',['No','Sometimes','Often','Prefer not to say'],3,1,4,['spending_pattern_relevant'],[],14,30),
q('fin_income_path_v1','income_path','What is the most realistic 1–3 month income path?',['Increase current work','Find new employment','Freelance / gig / contract','Build or grow business','Sell assets / one-time cash','Multiple paths','No realistic path','Unsure'],5,2,5,['income_increase_needed'],[],14,30),
q('fin_income_readiness_v1','income_path_readiness','How ready are you to act on that income path?',['Ready now','Mostly ready','Significant preparation needed','Not ready'],4,1,5,['income_path_selected'],['fin_income_path_v1'],7,14),
q('fin_income_urgency_v1','income_urgency','How soon does income need to improve?',['Days','Weeks','1–3 months','No immediate urgency'],5,1,5,['income_increase_needed'],[],7,14),
{id:'fin_contingency_sources_v1',dimension:'Financial',secondary_dimensions:['Social'],signal:'contingency_sources',prompt:'What resources could realistically help if the financial picture worsened?',response_type:'multi_choice',options:['Family','Partner','Friends','Government / community benefits','Insurance','Borrowing / credit','Saleable assets','Other','None','Unsure','Prefer not to say'],information_value:3,burden:2,actionability:4,triggers:['financial_resilience_uncertain','high_financial_pressure'],dependencies:[],cooldown_days:30,stale_after_days:60,safety_relevant:false,source:'FIN-DEEP-001 v1.0'},
q('fin_visibility_v1','financial_visibility','How clear is your current financial picture?',['Very clear','Mostly clear','Broad picture only','Poorly known','Unsure'],4,1,5,['financial_priority','data_quality_uncertain'],[],14,30),
q('fin_goal_v1','member_financial_goal','What financial objective matters most right now?',['Protect essentials / payments','Reduce spending','Increase income','Reduce debt','Preserve / build emergency cash','Build budget / visibility','Let EL8 recommend'],4,1,5,['financial_plan_choice_uncertain'],[],14,30),
q('fin_expected_change_v1','expected_near_term_change','Is a major financial change expected in the next 1–3 months?',['Large required expense','Payment increase','Income / support loss','Major purchase / commitment','Expected money coming in','Multiple','None known','Unsure'],4,1,4,['financial_forecast_relevant'],[],14,30),
q('fin_tightness_v1','available_cash_tightness','After near-term obligations, how much room is left for surprises?',['Comfortable','Adequate but protect','Tight — little room for surprises','Critically low','Unsure'],5,1,5,['financial_priority','cash_buffer_uncertain'],[],7,14)
];
