'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const{openMemberStateSession,persistMemberStateSession}=require('./member-state-session');
const{commitDiscoveryHandoff}=require('../../intelligence/member-state/discovery-handoff');
const{applyMemberStateUpdate}=require('../../intelligence/member-state/member-state-update');
const{projectPlanningInput}=require('../../intelligence/member-state/planning-projection');
const at='2026-08-27T20:00:00.000Z';
function fakeSupabase(){let row=null;return{from(name){assert.equal(name,'el8_member_state');return{select(){return{maybeSingle:async()=>({data:row?structuredClone(row):null,error:null})}}}},async rpc(name,args){assert.equal(name,'save_el8_member_state');if(row&&row.revision!==args.expected_revision)return{data:null,error:new Error('member state revision conflict')};if(!row&&args.expected_revision!==-1)return{data:null,error:new Error('member state revision conflict')};row={schema_version:args.next_state.schemaVersion,revision:args.next_state.revision,state:structuredClone(args.next_state)};return{data:structuredClone(row),error:null}}}}
function transition(s,type,payload,source){return applyMemberStateUpdate(s,{type,payload,source,at,expectedRevision:s.revision})}
test('authenticated member survives Discovery/Baseline save and reload into Planning',async()=>{const supabase=fakeSupabase(),session={user:{id:'auth-user-1'}};let opened=await openMemberStateSession({supabase,session,now:at});assert.equal(opened.state.revision,0);let s=commitDiscoveryHandoff(opened.state,{at,evidence:[{id:'e1',provenance:'DISCOVERY',recordedAt:at}],dimensions:[{dimension:'physical',condition:'NEEDS_ATTENTION',confidence:.9,evidenceRefs:['e1']}],establishBaseline:true});while(opened.state.revision<s.revision){const event=s.history.find(h=>h.revision===opened.state.revision+1);const targetRevision=event.revision;const snapshot=structuredClone(s);snapshot.revision=targetRevision;snapshot.history=s.history.filter(h=>h.revision<=targetRevision);if(targetRevision<s.revision){continue}await persistMemberStateSession({supabase,session,previousState:opened.state,nextState:s});opened={memberId:session.user.id,state:s}}const baseline=structuredClone(s.baseline);const reloaded=await openMemberStateSession({supabase,session,now:'2026-08-28T10:00:00.000Z'});assert.deepEqual(reloaded.state.baseline,baseline);s=transition(reloaded.state,'PROBLEM_UPDATED',{id:'problem:activity',status:'SUPPORTED',evidenceRefs:['e1']},'discovery');s=transition(s,'PRIORITY_UPDATED',{id:'priority:activity',problemId:'problem:activity',status:'ACCEPTED',rank:1,memberDecisionAt:at,evidenceRefs:['e1']},'member');const planning=projectPlanningInput(s);assert.deepEqual(planning.confirmedPriorityIds,['priority:activity']);assert.equal(planning.problems[0].problemId,'problem:activity');assert.deepEqual(s.baseline,baseline)});
test('session boundary rejects a state belonging to another member',async()=>{const supabase=fakeSupabase(),a={user:{id:'a'}},b={user:{id:'b'}};const opened=await openMemberStateSession({supabase,session:a,now:at});const next=transition(opened.state,'PROFILE_UPDATED',{goals:['sleep']},'member');await assert.rejects(()=>persistMemberStateSession({supabase,session:b,previousState:opened.state,nextState:next}),/identity mismatch/)});
