'use strict';
const assert=require('node:assert/strict');const test=require('node:test');
const{createMemberState}=require('./member-state');const{applyMemberStateUpdate}=require('./member-state-update');const{projectPrioritizationCandidates}=require('./prioritization-adapter');const{applyPrioritizationResult,recordPriorityDecision}=require('./prioritization-result-adapter');const{projectPlanningInput}=require('./planning-adapter');const{applyReviewResult}=require('./review-result-adapter');
const at='2026-08-27T21:30:00.000Z';
function w(s,type,payload){return applyMemberStateUpdate(s,{type,payload,source:'qa.matrix',at,expectedRevision:s.revision})}
function supported(){let s=createMemberState({memberId:'QA-MATRIX',now:at});return w(s,'PROBLEM_UPDATED',{id:'problem:sleep',status:'SUPPORTED',evidenceRefs:['e1']})}
function active(){let s=supported();s=w(s,'PRIORITY_UPDATED',{id:'priority:sleep',problemId:'problem:sleep',status:'ACCEPTED',memberDecisionAt:at});return w(s,'PLAN_UPDATED',{planId:'plan:matrix',status:'ACTIVE',interventions:[{id:'I1',priorityId:'priority:sleep',problemId:'problem:sleep'}]})}
function review(s,decision){return{memberStateRevision:s.revision,planId:'plan:matrix',interventionIds:['I1'],decision:{decision,reason:`qa_${decision}`,evidenceUsed:{adherence:'high',outcome:'unchanged',burden:'low',evidenceRefs:['r1']},requiresDiscovery:decision==='reassess',requiresPlanning:['simplify','replace'].includes(decision),continueCurrent:['keep','deepen'].includes(decision),pausePlan:['disengaged','safety_hold'].includes(decision)}}}
for(const [decision,status,constraint] of [['keep','ACTIVE',null],['deepen','REVIEW_DEEPENING',null],['simplify','REPLAN_REQUIRED','reduce_burden'],['replace','REPLAN_REQUIRED','different_intervention'],['reassess','REASSESS_REQUIRED',null],['disengaged','PAUSED',null],['safety_hold','PAUSED',null]])test(`review ${decision} routes canonically`,()=>{const s=active();const x=applyReviewResult(s,review(s,decision),{at});assert.equal(x.state.activePlan.status,status);assert.equal(x.state.learning.at(-1).disposition,decision);if(constraint)assert.equal(x.state.activePlan.adaptationRequest.constraint,constraint)});
test('unresolved Discovery problem never enters Prioritization',()=>{let s=createMemberState({memberId:'QA'});s=w(s,'PROBLEM_UPDATED',{id:'problem:sleep',status:'UNRESOLVED',confidence:1});assert.equal(projectPrioritizationCandidates(s).candidates.length,0)});
test('member rejection prevents Planning entry',()=>{let s=supported();s=w(s,'PRIORITY_UPDATED',{id:'priority:sleep',problemId:'problem:sleep',status:'RECOMMENDED'});s=recordPriorityDecision(s,{priorityId:'priority:sleep',decision:'REJECTED',at,source:'qa.member'});assert.equal(projectPlanningInput(s).confirmedPriorityIds.length,0)});
test('stale Prioritization result is rejected after state changes',()=>{let s=supported();const result={memberStateRevision:s.revision,blockedBySafety:false,priorityItems:[{priorityId:'priority:sleep',problemId:'problem:sleep'}]};s=w(s,'PROFILE_UPDATED',{goals:['changed']});assert.throws(()=>applyPrioritizationResult(s,result,{at}),/revision conflict/)});
test('capacity throttle is carried into Planning boundary',()=>{let s=supported();s=w(s,'PRIORITY_UPDATED',{id:'priority:sleep',problemId:'problem:sleep',status:'ACCEPTED',memberDecisionAt:at});s=w(s,'ENGAGEMENT_BURDEN_UPDATED',{capacity:'low',manageability:'difficult',throttle:{active:true,reason:'qa_friction'}});const x=projectPlanningInput(s);assert.equal(x.constraints.throttle.active,true);assert.equal(x.constraints.capacity,'low')});
