'use strict';
const assert=require('node:assert/strict');const test=require('node:test');
const{createMemberState}=require('./member-state');const{applyMemberStateUpdate}=require('./member-state-update');const{projectPlanningInput}=require('./planning-adapter');
const at='2026-08-27T22:00:00.000Z';
function w(s,type,payload){return applyMemberStateUpdate(s,{type,payload,source:'qa.reduction',at,expectedRevision:s.revision})}
function accepted(){let s=createMemberState({memberId:'QA-REDUCTION',now:at});s=w(s,'PROBLEM_UPDATED',{id:'problem:movement',status:'SUPPORTED',evidenceRefs:['e:movement']});return w(s,'PRIORITY_UPDATED',{id:'priority:movement',problemId:'problem:movement',status:'ACCEPTED',memberDecisionAt:at})}

test('Planning preserves member capacity and profile constraints',()=>{let s=accepted();s=w(s,'PROFILE_UPDATED',{constraints:['time','money']});s=w(s,'ENGAGEMENT_BURDEN_UPDATED',{capacity:'low',manageability:'difficult',throttle:{active:true,reason:'member_friction'}});const x=projectPlanningInput(s);assert.deepEqual(x.constraints.profile,['time','money']);assert.equal(x.constraints.capacity,'low');assert.equal(x.constraints.manageability,'difficult');assert.equal(x.constraints.throttle.active,true)});
test('Planning rejects unaccepted requested focus',()=>{const s=accepted();assert.throws(()=>projectPlanningInput(s,{priorityIds:['priority:other']}),/accepted member priorities/)});
test('Planning carries prior learning into replanning',()=>{let s=accepted();s=w(s,'LEARNING_RECORDED',{id:'learning:movement:1',problemId:'problem:movement',priorityId:'priority:movement',disposition:'replace',evidenceRefs:['review:1']});const x=projectPlanningInput(s);assert.equal(x.problems[0].priorLearning.at(-1).disposition,'replace')});
test('withdrawing an accepted priority removes its active intervention',()=>{let s=accepted();s=w(s,'PLAN_UPDATED',{planId:'plan:1',status:'ACTIVE',interventions:[{id:'I1',priorityId:'priority:movement',problemId:'problem:movement'}]});s=w(s,'PRIORITY_UPDATED',{id:'priority:movement',status:'REJECTED',memberDecisionAt:at});assert.equal(s.activePlan.interventions.length,0);assert.equal(s.activePlan.status,'PAUSED');assert.equal(s.activePlan.reconciliation.reason,'MEMBER_PRIORITY_WITHDRAWN');assert.deepEqual(s.activePlan.reconciliation.interventionIds,['I1'])});
test('withdrawing one focus forces replanning while preserving other active work',()=>{let s=accepted();s=w(s,'PROBLEM_UPDATED',{id:'problem:sleep',status:'SUPPORTED',evidenceRefs:['e:sleep']});s=w(s,'PRIORITY_UPDATED',{id:'priority:sleep',problemId:'problem:sleep',status:'ACCEPTED',memberDecisionAt:at});s=w(s,'PLAN_UPDATED',{planId:'plan:2',status:'ACTIVE',interventions:[{id:'I1',priorityId:'priority:movement',problemId:'problem:movement'},{id:'I2',priorityId:'priority:sleep',problemId:'problem:sleep'}]});s=w(s,'PRIORITY_UPDATED',{id:'priority:movement',status:'POSTPONED',memberDecisionAt:at});assert.deepEqual(s.activePlan.interventions.map(i=>i.id),['I2']);assert.equal(s.activePlan.status,'REPLAN_REQUIRED')});
