'use strict';
const assert=require('node:assert/strict');const test=require('node:test');
const{createMemberState}=require('./member-state');const{projectDiscoveryTrace}=require('./discovery-projection');const{applyDiscoveryResult}=require('./discovery-adapter');
const at='2026-08-27T16:00:00.000Z';
function trace(){return{observations:[{id:'obs-1',questionId:'q-sleep',concernId:'sleep_disruption',answerValue:'often',timestamp:at,effects:[{type:'evidence',target:'sleep_disruption',polarity:'supports',strength:.8},{type:'relationship',from:'occupational',to:'emotional',confidence:.6}]}],states:[{concernId:'sleep_disruption',evidenceConfidence:.8,excluded:false,temporality:'current',resolutionState:'sufficient'}],plan:{activeConcerns:['sleep_disruption']},memberPlan:{actions:['legacy-action']}}}
test('legacy Discovery projects explicit sufficient resolution into supported problem',()=>{const s=createMemberState({memberId:'T0001',now:at});const projected=projectDiscoveryTrace(trace(),{memberStateRevision:s.revision,at,revalidationPolicy:'relationship-v1'});const n=applyDiscoveryResult(s,projected,{at,source:'discovery.legacy-projection'});assert.equal(n.problems[0].status,'SUPPORTED');assert.equal(n.problems[0].discoveryResolution,'sufficient');assert.equal(n.priorities.length,0);assert.equal(n.activePlan.interventions.length,0)});
test('numeric confidence alone can never establish a supported problem',()=>{const t={observations:[],states:[{concernId:'sleep',evidenceConfidence:1,excluded:false,temporality:'current'}]};const p=projectDiscoveryTrace(t,{memberStateRevision:0,at});assert.equal(p.problemUpdates[0].status,'UNRESOLVED');assert.equal(p.problemUpdates[0].confidence,1)});
test('explicit sufficiency may support a problem without a magic confidence cutoff',()=>{const t={observations:[],states:[{concernId:'sleep',evidenceConfidence:.2,excluded:false,resolutionState:'sufficient'}]};const p=projectDiscoveryTrace(t,{memberStateRevision:0,at});assert.equal(p.problemUpdates[0].status,'SUPPORTED');assert.equal(p.problemUpdates[0].confidence,.2)});
test('deferred and escalated Discovery states remain distinct',()=>{const t={observations:[],states:[{concernId:'sleep',resolutionState:'deferred'},{concernId:'safety',resolutionState:'escalated'}]};const p=projectDiscoveryTrace(t,{memberStateRevision:0,at});assert.deepEqual(p.problemUpdates.map(x=>x.status),['DEFERRED','ESCALATED'])});
test('legacy plan/memberPlan fields are not projected across the canonical boundary',()=>{const p=projectDiscoveryTrace(trace(),{memberStateRevision:0,at});assert.equal('plan'in p,false);assert.equal('memberPlan'in p,false);assert.equal('recommendedPriorities'in p,false);assert.equal('interventions'in p,false)});
test('co-occurring concerns do not create causal hypotheses without explicit relationship evidence',()=>{const t={observations:[{id:'o1',questionId:'q1',concernId:'sleep',timestamp:at,effects:[]},{id:'o2',questionId:'q2',concernId:'money',timestamp:at,effects:[]}],states:[{concernId:'sleep',evidenceConfidence:.5},{concernId:'money',evidenceConfidence:.5}]};const p=projectDiscoveryTrace(t,{memberStateRevision:0,at});assert.equal(p.hypothesisUpdates.length,0)});
test('contradicted legacy concern remains a problem conclusion rather than disappearing',()=>{const t={observations:[],states:[{concernId:'sleep',evidenceConfidence:0,excluded:true,temporality:'current'}]};const p=projectDiscoveryTrace(t,{memberStateRevision:0,at});assert.equal(p.problemUpdates[0].status,'CONTRADICTED')});
