'use strict';

/** EL8 Canonical Member State v1. Durable member truth enters through explicit updates. */
const MEMBER_STATE_VERSION='1.0.0';
const DIMENSIONS=Object.freeze(['physical','emotional','social','intellectual','spiritual','occupational','financial','environmental']);
const DIMENSION_SCOPE=Object.freeze(['FOCUS','MONITORED','REFERRED','PAUSED']);
const PRIORITY_STATUS=Object.freeze(['RECOMMENDED','ACCEPTED','REJECTED','POSTPONED','PAUSED','COMPLETED']);
const INTERVENTION_STATUS=Object.freeze(['PROPOSED','ACCEPTED','IN_PROGRESS','COMPLETED','MODIFIED','PAUSED','DISCONTINUED']);
const HYPOTHESIS_STATUS=Object.freeze(['SUSPECTED','SUPPORTED','MEMBER_CONFIRMED','EXTERNALLY_ESTABLISHED','CONTRADICTED','STALE','ARCHIVED']);
const CONSIDERATION_STATUS=Object.freeze(['SAVED','CONSIDERING','DISMISSED','PROPOSED_FOR_PLAN','MOVED_TO_PLAN']);
function createDimensionState(){return{scope:'MONITORED',condition:null,confidence:null,evidenceRefs:[],updatedAt:null}}
function createMemberState({memberId,now=new Date().toISOString()}={}){if(!memberId||typeof memberId!=='string')throw new TypeError('memberId is required');return{schemaVersion:MEMBER_STATE_VERSION,memberId,revision:0,createdAt:now,updatedAt:now,profile:{goals:[],preferences:{},constraints:[],accessibilityNeeds:[],consent:{},permissions:{}},dimensions:Object.fromEntries(DIMENSIONS.map(d=>[d,createDimensionState()])),baseline:{status:'NOT_ESTABLISHED',establishedAt:null,sourceRevision:null,dimensionSnapshots:{},evidenceRefs:[]},evidence:[],problems:[],hypotheses:[],priorities:[],activePlan:{planId:null,status:null,interventions:[],reviewDueAt:null,activatedAt:null,updatedAt:null},engagementBurden:{capacity:null,manageability:null,adherenceTrend:null,skippedRequests:[],deferrals:[],trackingBurden:null,interventionBurden:null,disengagementSignals:[],throttle:{active:false,policyVersion:null,reasonCodes:[],activatedAt:null},updatedAt:null},considerations:[],learning:[],safety:{disposition:'ORDINARY_FLOW',unresolvedConstraints:[],policyVersion:null,updatedAt:null},history:[]}}
function assertMemberState(state){if(!state||typeof state!=='object')throw new TypeError('member state must be an object');if(state.schemaVersion!==MEMBER_STATE_VERSION)throw new Error(`unsupported member state schema: ${state.schemaVersion}`);if(!state.memberId)throw new Error('memberId is required');for(const d of DIMENSIONS){if(!state.dimensions?.[d])throw new Error(`missing dimension state: ${d}`);if(!DIMENSION_SCOPE.includes(state.dimensions[d].scope))throw new Error(`invalid dimension scope: ${d}`)}if(!state.baseline||!['NOT_ESTABLISHED','ESTABLISHED'].includes(state.baseline.status))throw new Error('invalid baseline state');for(const k of['evidence','problems','hypotheses','priorities','considerations','learning','history'])if(!Array.isArray(state[k]))throw new Error(`${k} must be an array`);return state}
module.exports={MEMBER_STATE_VERSION,DIMENSIONS,DIMENSION_SCOPE,PRIORITY_STATUS,INTERVENTION_STATUS,HYPOTHESIS_STATUS,CONSIDERATION_STATUS,createMemberState,assertMemberState};
