'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const{createMemberState}=require('./member-state');const{applyMemberStateUpdate}=require('./member-state-update');const{projectPlanningInput}=require('./planning-projection');
const at='2026-08-27T16:00:00.000Z';function update(s,type,payload,source='test'){return applyMemberStateUpdate(s,{type,payload,expectedRevision:s.revision,at,source})}
function acceptedState(){let s=createMemberState({memberId:'TQA',now:at});s=update(s,'EVIDENCE_RECORDED',{id:'e1',provenance:'QA',recordedAt:at});s=update(s,'PROBLEM_UPDATED',{id:'problem:low_activity',status:'SUPPORTED',evidenceRefs:['e1']});s=update(s,'PRIORITY_UPDATED',{id:'priority:p1',problemId:'problem:low_activity',status:'ACCEPTED',memberDecisionAt:at,evidenceRefs:['e1'],rank:1});return s}
test('projects only accepted priority problems into Planning',()=>{let s=acceptedState();s=update(s,'PROBLEM_UPDATED',{id:'problem:poor_sleep',status:'SUPPORTED',evidenceRefs:['e1']});s=update(s,'PRIORITY_UPDATED',{id:'priority:p2',problemId:'problem:poor_sleep',status:'RECOMMENDED',evidenceRefs:['e1'],rank:2});const x=projectPlanningInput(s);assert.equal(x.memberStateRevision,s.revision);assert.deepEqual(x.confirmedPriorityIds,['priority:p1']);assert.deepEqual(x.problems.map(p=>p.problemId),['problem:low_activity'])});
test('projects capacity throttle and Safety as Planning constraints',()=>{let s=acceptedState();s=update(s,'ENGAGEMENT_BURDEN_UPDATED',{capacity:'low'});s=update(s,'CAPACITY_THROTTLE_UPDATED',{active:true,policyVersion:'1',reasonCodes:['friction']});s=update(s,'SAFETY_UPDATED',{disposition:'HUMAN_REVIEW',unresolvedConstraints:['safety:qa'],policyVersion:'1'});const x=projectPlanningInput(s);assert.equal(x.constraints.capacity,'low');assert.equal(x.constraints.throttle.active,true);assert.equal(x.constraints.safety.disposition,'HUMAN_REVIEW')});
test('does not infer an unaccepted priority from a problem',()=>{let s=createMemberState({memberId:'TQA',now:at});s=update(s,'PROBLEM_UPDATED',{id:'problem:low_activity',status:'SUPPORTED',evidenceRefs:[]});const x=projectPlanningInput(s);assert.deepEqual(x.confirmedPriorityIds,[]);assert.deepEqual(x.problems,[])});
test('later Prioritization rerank creates a new revision and changes only prospective Planning order',()=>{let s=acceptedState();s=update(s,'PROBLEM_UPDATED',{id:'problem:poor_sleep',status:'SUPPORTED',evidenceRefs:['e1']});s=update(s,'PRIORITY_UPDATED',{id:'priority:p2',problemId:'problem:poor_sleep',status:'ACCEPTED',memberDecisionAt:at,evidenceRefs:['e1'],rank:2});const before=projectPlanningInput(s),beforeRevision=s.revision,beforeHistory=JSON.parse(JSON.stringify(s.history));assert.deepEqual(before.confirmedPriorityIds,['priority:p1','priority:p2']);s=update(s,'PRIORITY_UPDATED',{id:'priority:p1',rank:2},'prioritization.rerank');s=update(s,'PRIORITY_UPDATED',{id:'priority:p2',rank:1},'prioritization.rerank');const after=projectPlanningInput(s);assert.equal(s.revision,beforeRevision+2);assert.deepEqual(after.confirmedPriorityIds,['priority:p2','priority:p1']);assert.deepEqual(after.priorityOrder,[{priorityId:'priority:p2',rank:1},{priorityId:'priority:p1',rank:2}]);assert.deepEqual(before.confirmedPriorityIds,['priority:p1','priority:p2']);assert.deepEqual(s.history.slice(0,beforeHistory.length),beforeHistory);assert.equal(s.history.at(-1).source,'prioritization.rerank');assert.equal(after.memberStateRevision,s.revision)});
test('reranking preserves acceptance and member decision provenance',()=>{let s=acceptedState();const decisionAt=s.priorities[0].memberDecisionAt;s=update(s,'PRIORITY_UPDATED',{id:'priority:p1',rank:3},'prioritization.rerank');assert.equal(s.priorities[0].status,'ACCEPTED');assert.equal(s.priorities[0].memberDecisionAt,decisionAt);assert.equal(s.priorities[0].rank,3)});
