'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const{createMemberState}=require('./member-state');const{applyMemberStateUpdate}=require('./member-state-update');const{projectPlanningInput}=require('./planning-projection');
const at='2026-08-27T16:00:00.000Z';function update(s,type,payload,source='test'){return applyMemberStateUpdate(s,{type,payload,expectedRevision:s.revision,at,source})}
function acceptedState(){let s=createMemberState({memberId:'TQA',now:at});s=update(s,'EVIDENCE_RECORDED',{id:'e1',provenance:'QA',recordedAt:at});s=update(s,'PROBLEM_UPDATED',{id:'problem:low_activity',status:'SUPPORTED',evidenceRefs:['e1']});s=update(s,'PRIORITY_UPDATED',{id:'priority:p1',problemId:'problem:low_activity',status:'ACCEPTED',memberDecisionAt:at,evidenceRefs:['e1'],rank:1});return s}
test('projects only accepted priority problems into Planning',()=>{let s=acceptedState();s=update(s,'PROBLEM_UPDATED',{id:'problem:poor_sleep',status:'SUPPORTED',evidenceRefs:['e1']});s=update(s,'PRIORITY_UPDATED',{id:'priority:p2',problemId:'problem:poor_sleep',status:'RECOMMENDED',evidenceRefs:['e1'],rank:2});const x=projectPlanningInput(s);assert.deepEqual(x.confirmedPriorityIds,['priority:p1']);assert.deepEqual(x.problems.map(p=>p.problemId),['problem:low_activity'])});
test('projects capacity throttle and Safety as Planning constraints',()=>{let s=acceptedState();s=update(s,'ENGAGEMENT_BURDEN_UPDATED',{capacity:'low'});s=update(s,'CAPACITY_THROTTLE_UPDATED',{active:true,policyVersion:'1',reasonCodes:['friction']});s=update(s,'SAFETY_UPDATED',{disposition:'HUMAN_REVIEW',unresolvedConstraints:['safety:qa'],policyVersion:'1'});const x=projectPlanningInput(s);assert.equal(x.constraints.capacity,'low');assert.equal(x.constraints.throttle.active,true);assert.equal(x.constraints.safety.disposition,'HUMAN_REVIEW')});
test('does not infer an unaccepted priority from a problem',()=>{let s=createMemberState({memberId:'TQA',now:at});s=update(s,'PROBLEM_UPDATED',{id:'problem:low_activity',status:'SUPPORTED',evidenceRefs:[]});assert.deepEqual(projectPlanningInput(s).confirmedPriorityIds,[])});
test('later Prioritization rerank changes prospective Planning order',()=>{let s=acceptedState();s=update(s,'PROBLEM_UPDATED',{id:'problem:poor_sleep',status:'SUPPORTED',evidenceRefs:['e1']});s=update(s,'PRIORITY_UPDATED',{id:'priority:p2',problemId:'problem:poor_sleep',status:'ACCEPTED',memberDecisionAt:at,evidenceRefs:['e1'],rank:2});s=update(s,'PRIORITY_UPDATED',{id:'priority:p1',rank:2},'prioritization.rerank');s=update(s,'PRIORITY_UPDATED',{id:'priority:p2',rank:1},'prioritization.rerank');assert.deepEqual(projectPlanningInput(s).confirmedPriorityIds,['priority:p2','priority:p1'])});
test('withdrawal removes authorization from both active plan and next Planning projection',()=>{let s=acceptedState();s=update(s,'PROBLEM_UPDATED',{id:'problem:poor_sleep',status:'SUPPORTED',evidenceRefs:['e1']});s=update(s,'PRIORITY_UPDATED',{id:'priority:p2',problemId:'problem:poor_sleep',status:'ACCEPTED',memberDecisionAt:at,evidenceRefs:['e1'],rank:2});s=update(s,'PLAN_UPDATED',{planId:'plan:1',status:'ACTIVE',interventions:[{id:'i1',priorityId:'priority:p1'},{id:'i2',priorityId:'priority:p2'}]},'planning');s=update(s,'PRIORITY_UPDATED',{id:'priority:p1',status:'PAUSED',memberDecisionAt:at},'member');const x=projectPlanningInput(s);assert.deepEqual(s.activePlan.interventions.map(i=>i.id),['i2']);assert.equal(s.activePlan.status,'REPLAN_REQUIRED');assert.deepEqual(x.confirmedPriorityIds,['priority:p2']);assert.deepEqual(x.problems.map(p=>p.priorityId),['priority:p2']);assert.equal(x.confirmedPriorityIds.includes('priority:p1'),false)});
test('reacceptance restores prospective Planning authorization without resurrecting old intervention',()=>{let s=acceptedState();s=update(s,'PLAN_UPDATED',{planId:'plan:1',status:'ACTIVE',interventions:[{id:'i1',priorityId:'priority:p1'}]},'planning');s=update(s,'PRIORITY_UPDATED',{id:'priority:p1',status:'PAUSED',memberDecisionAt:at},'member');assert.deepEqual(s.activePlan.interventions,[]);const historyAtPause=s.history.length;s=applyMemberStateUpdate(s,{type:'PRIORITY_UPDATED',payload:{id:'priority:p1',status:'ACCEPTED',memberDecisionAt:'2026-08-28T16:00:00.000Z'},source:'member',at:'2026-08-28T16:00:00.000Z',expectedRevision:s.revision});const x=projectPlanningInput(s);assert.deepEqual(x.confirmedPriorityIds,['priority:p1']);assert.deepEqual(x.problems.map(p=>p.priorityId),['priority:p1']);assert.deepEqual(s.activePlan.interventions,[]);assert.equal(s.activePlan.status,'PAUSED');assert.equal(s.history.length,historyAtPause+1);assert.equal(s.priorities.find(p=>p.id==='priority:p1').memberDecisionAt,'2026-08-28T16:00:00.000Z')});
