'use strict';
const assert=require('node:assert/strict');const test=require('node:test');
const{createMemberState}=require('./member-state');const{applyMemberStateUpdate}=require('./member-state-update');const{projectPlanningInput}=require('./planning-adapter');
const at='2026-08-27T19:00:00.000Z';
function write(s,type,payload){return applyMemberStateUpdate(s,{type,payload,source:'qa',at,expectedRevision:s.revision})}
function setup(status='ACCEPTED'){let s=createMemberState({memberId:'T0001',now:at});s=write(s,'PROBLEM_UPDATED',{id:'problem:sleep',status:'SUPPORTED',evidenceRefs:['e1']});s=write(s,'PRIORITY_UPDATED',{id:'priority:sleep',problemId:'problem:sleep',status:status,...(status==='ACCEPTED'?{memberDecisionAt:at}:{})});return s}
test('Planning receives only explicitly accepted priorities',()=>{const x=projectPlanningInput(setup());assert.deepEqual(x.confirmedPriorityIds,['priority:sleep']);assert.equal(x.problems[0].problemId,'problem:sleep');assert.equal(x.memberChoice.mode,'EXPLICIT_ACCEPTANCE')});
test('recommended priority cannot cross into Planning',()=>{const s=setup('RECOMMENDED');assert.equal(projectPlanningInput(s).confirmedPriorityIds.length,0);assert.throws(()=>projectPlanningInput(s,{priorityIds:['priority:sleep']}),/requires accepted member priorities/)});
test('Planning receives constraints and learning but does not own problem establishment',()=>{let s=setup();s=write(s,'ENGAGEMENT_BURDEN_UPDATED',{capacity:'low',manageability:'difficult'});s=write(s,'LEARNING_RECORDED',{id:'l1',problemId:'problem:sleep',learnedAt:at,evidenceRefs:['e1'],outcome:'high_burden'});const x=projectPlanningInput(s);assert.equal(x.constraints.capacity,'low');assert.equal(x.problems[0].priorLearning[0].outcome,'high_burden')});
test('accepted priority becomes invalid for Planning if its problem is no longer supported',()=>{let s=setup();s=write(s,'PROBLEM_UPDATED',{id:'problem:sleep',status:'CONTRADICTED'});assert.throws(()=>projectPlanningInput(s),/must reference supported problem/)});
