'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const{createMemberState}=require('./member-state');const{applyMemberStateUpdate}=require('./member-state-update');const{loadMemberState,saveMemberState,loadOrCreateMemberState}=require('./supabase-persistence');
const at='2026-08-27T20:00:00.000Z';
function fakeClient(initial=null){let row=initial;return{from(name){assert.equal(name,'el8_member_state');return{select(){return{maybeSingle:async()=>({data:row,error:null})}}}},async rpc(name,args){assert.equal(name,'save_el8_member_state');if(row&&Number(row.revision)!==args.expected_revision)return{data:null,error:new Error('member state revision conflict')};if(!row&&args.expected_revision!==-1)return{data:null,error:new Error('member state revision conflict')};row={schema_version:args.next_state.schemaVersion,revision:args.next_state.revision,state:structuredClone(args.next_state)};return{data:structuredClone(row),error:null}},row:()=>row}}
function update(s,type,payload,source='qa'){return applyMemberStateUpdate(s,{type,payload,source,at,expectedRevision:s.revision})}
test('first authenticated load creates canonical revision zero',async()=>{const c=fakeClient();const s=await loadOrCreateMemberState(c,{memberId:'user-1',now:at});assert.equal(s.revision,0);assert.equal(s.memberId,'user-1');assert.equal((await loadMemberState(c)).schemaVersion,'1.0.0')});
test('save then reload preserves immutable baseline exactly',async()=>{const c=fakeClient();let s=await loadOrCreateMemberState(c,{memberId:'user-1',now:at});s=update(s,'EVIDENCE_RECORDED',{id:'e1',provenance:'DISCOVERY',recordedAt:at});s=update(s,'DIMENSION_UPDATED',{dimension:'physical',condition:'NEEDS_ATTENTION',confidence:.8,evidenceRefs:['e1']},'discovery');s=update(s,'BASELINE_ESTABLISHED',{},'discovery');const baseline=structuredClone(s.baseline);await saveMemberState(c,s,{expectedRevision:0});const reloaded=await loadMemberState(c);assert.deepEqual(reloaded,s);assert.deepEqual(reloaded.baseline,baseline)});
test('stale persisted revision is rejected rather than overwriting newer truth',async()=>{const c=fakeClient();let s=await loadOrCreateMemberState(c,{memberId:'user-1',now:at});const a=update(s,'PROFILE_UPDATED',{goals:['sleep']});await saveMemberState(c,a,{expectedRevision:0});const stale=update(s,'PROFILE_UPDATED',{goals:['money']});await assert.rejects(()=>saveMemberState(c,stale,{expectedRevision:0}),/revision conflict/);assert.deepEqual((await loadMemberState(c)).profile.goals,['sleep'])});
test('persisted state cannot be loaded for a different authenticated member identity',async()=>{const c=fakeClient();await loadOrCreateMemberState(c,{memberId:'user-1',now:at});await assert.rejects(()=>loadOrCreateMemberState(c,{memberId:'user-2',now:at}),/does not match/)});
