// Synthetic members are deliberately fictional and contain no production/member data.
export const syntheticMembers=[
 {id:'stable-balanced',label:'Stable, well-understood',context:{activeTriggers:[],uncertainSignals:[],capacity:1,friction:0},expect:{maxQuestions:0}},
 {id:'financial-crisis',label:'Immediate financial pressure',context:{activeTriggers:['financial_pressure_possible','financial_priority','income_increase_needed'],uncertainSignals:['near_term_pressure','income_urgency'],capacity:.75,friction:.15},expect:{dimension:'Financial',minQuestions:1,maxQuestions:2}},
 {id:'financial-unclear',label:'Financial priority but poor visibility',context:{activeTriggers:['financial_priority','data_quality_uncertain'],uncertainSignals:['financial_visibility','available_cash_tightness'],capacity:.8,friction:.1},expect:{dimension:'Financial',minQuestions:1}},
 {id:'emotional-strain',label:'Emotional strain with interference uncertain',context:{activeTriggers:['emotional_pressure_identified','material_emotional_interference'],uncertainSignals:['functional_interference','professional_support_context'],capacity:.7,friction:.2},expect:{dimension:'Emotional',minQuestions:1}},
 {id:'high-friction',label:'Member burden is high',context:{activeTriggers:['financial_priority','income_increase_needed','cashflow_pressure'],uncertainSignals:['financial_visibility','income_path','income_urgency'],capacity:.2,friction:1},expect:{maxQuestions:1}},
 {id:'returning-stale',label:'Returning member with stale evidence',context:{activeTriggers:['financial_priority'],uncertaintyBySignal:{financial_visibility:.65,available_cash_tightness:.65},evidenceAgeDays:{financial_visibility:90,available_cash_tightness:2},capacity:.8,friction:.1,maxQuestions:1},expect:{preferSignal:'financial_visibility'}},
 {id:'priority-tie',label:'Two plausible priority dimensions',context:{activeTriggers:['priority_tie'],uncertaintyBySignal:{member_perceived_leverage:1,member_perceived_feasibility:.6,member_perceived_upstream_leverage:.6},candidateDimensions:['Physical','Emotional'],capacity:.8,friction:.1,maxQuestions:1},expect:{preferPurpose:'adaptive_clarification'}},
 {id:'low-capacity-no-trigger',label:'Low capacity with no unresolved trigger',context:{activeTriggers:[],uncertainSignals:[],capacity:0,friction:1,maxQuestions:0,maxBurden:0},expect:{maxQuestions:0}},
 {id:'debt-specific',label:'Debt pressure needs clarification',context:{activeTriggers:['debt_relevant'],uncertainSignals:['debt_status'],capacity:.8,friction:.1,maxQuestions:1},expect:{preferSignal:'debt_status'}},
 {id:'income-action',label:'Income path is the likely leverage point',context:{activeTriggers:['income_increase_needed'],uncertaintyBySignal:{income_path:1,income_urgency:.65},capacity:.9,friction:.05,maxQuestions:1},expect:{dimension:'Financial',minQuestions:1}},
 {id:'buffer-uncertain',label:'Cash buffer is unknown',context:{activeTriggers:['cash_buffer_uncertain'],uncertainSignals:['available_cash_tightness'],capacity:.9,friction:0,maxQuestions:1},expect:{preferSignal:'available_cash_tightness'}},
 {id:'settled-recent',label:'Recently answered evidence should suppress repetition',context:{activeTriggers:['financial_priority'],uncertaintyBySignal:{financial_visibility:.7,income_stability:.7,cashflow_after_essentials:.7,liquid_runway:.7,debt_status:.7,available_cash_tightness:.7},recentSignals:['financial_visibility'],capacity:.8,friction:.1,maxQuestions:1},expect:{avoidSignal:'financial_visibility'}}
];
