-- Read-only structural fingerprint. No rows, credentials, sequence positions or
-- platform-owned Auth/Storage implementation are read.
select jsonb_build_object(
 'tables',(select jsonb_agg(jsonb_build_object('name',c.relname,'owner',pg_get_userbyid(c.relowner),'rls',c.relrowsecurity,'forceRls',c.relforcerowsecurity,'acl',c.relacl::text,'columns',(select jsonb_agg(jsonb_build_object('name',a.attname,'type',format_type(a.atttypid,a.atttypmod),'notNull',a.attnotnull,'identity',a.attidentity,'generated',a.attgenerated,'default',pg_get_expr(d.adbin,d.adrelid),'acl',a.attacl::text) order by a.attnum) from pg_attribute a left join pg_attrdef d on d.adrelid=a.attrelid and d.adnum=a.attnum where a.attrelid=c.oid and a.attnum>0 and not a.attisdropped)) order by c.relname) from pg_class c where c.relnamespace='public'::regnamespace and c.relkind='r'),
 'constraints',(select jsonb_agg(jsonb_build_object('table',c.conrelid::regclass::text,'name',c.conname,'type',c.contype,'definition',pg_get_constraintdef(c.oid,true)) order by c.conrelid::regclass::text,c.conname) from pg_constraint c where c.connamespace='public'::regnamespace and c.conrelid<>0),
 'functions',(select jsonb_agg(jsonb_build_object('signature',p.oid::regprocedure::text,'owner',pg_get_userbyid(p.proowner),'acl',p.proacl::text,'definition',pg_get_functiondef(p.oid)) order by p.oid::regprocedure::text) from pg_proc p where p.pronamespace='public'::regnamespace and p.prokind='f' and not exists(select 1 from pg_depend d where d.classid='pg_proc'::regclass and d.objid=p.oid and d.deptype='e')),
 'policies',(select jsonb_agg(to_jsonb(p) order by p.tablename,p.policyname) from pg_policies p where p.schemaname='public'),
 'triggers',(select jsonb_agg(jsonb_build_object('table',t.tgrelid::regclass::text,'name',t.tgname,'enabled',t.tgenabled,'definition',pg_get_triggerdef(t.oid,true)) order by t.tgrelid::regclass::text,t.tgname) from pg_trigger t where not t.tgisinternal and (t.tgrelid in (select oid from pg_class where relnamespace='public'::regnamespace) or t.tgfoid in (select oid from pg_proc where pronamespace='public'::regnamespace))),
 'indexes',(select jsonb_agg(jsonb_build_object('table',c.relname,'name',i.relname,'definition',pg_get_indexdef(i.oid)) order by i.relname) from pg_index x join pg_class i on i.oid=x.indexrelid join pg_class c on c.oid=x.indrelid where c.relnamespace='public'::regnamespace and not exists(select 1 from pg_constraint k where k.conindid=x.indexrelid)),
 'sequences',(select jsonb_agg(jsonb_build_object('name',c.relname,'acl',c.relacl::text,'type',format_type(s.seqtypid,null),'start',s.seqstart::text,'min',s.seqmin::text,'max',s.seqmax::text,'increment',s.seqincrement::text,'cache',s.seqcache::text,'cycle',s.seqcycle,'ownedBy',(select d.refobjid::regclass::text||'.'||a.attname from pg_depend d join pg_attribute a on a.attrelid=d.refobjid and a.attnum=d.refobjsubid where d.classid='pg_class'::regclass and d.objid=c.oid and d.deptype in ('a','i') limit 1),'dependency',(select d.deptype from pg_depend d where d.classid='pg_class'::regclass and d.objid=c.oid and d.deptype in ('a','i') limit 1)) order by c.relname) from pg_class c join pg_sequence s on s.seqrelid=c.oid where c.relnamespace='public'::regnamespace),
 'enums',(select jsonb_agg(jsonb_build_object('type',t.typname,'value',e.enumlabel,'order',e.enumsortorder) order by t.typname,e.enumsortorder) from pg_enum e join pg_type t on t.oid=e.enumtypid where t.typnamespace='public'::regnamespace)
) as catalog;
