// Code representation of the Drive Action Library (02.06).
// The registry owns governed Action definitions; Planning consumes this boundary.
import { createActionDefinition } from '../../intelligence/planning/action-contract.js';

const D=['continue','simplify','replace','reassess'];
const dim={PHY:['physical'],EMT:['emotional'],SOC:['social'],OCC:['occupational'],FIN:['financial'],ENV:['environmental'],INT:['intellectual'],SPT:['spiritual'],XDM:[]};
const make=(actionId,name,constructIds,{scope='construct',intent='build',burden='low',tracking='Action-specific completion/usefulness evidence during the active test only.',assessment=null,icon='action',status='provisional',strength='unknown',claim='May be described only as a bounded member-chosen experiment for the stated purpose; do not imply diagnosis, treatment, guaranteed benefit or causality.',review='At the shortest useful decision point.',stop=['member declines','material worsening','Safety or professional boundary changes'],eligibility={},contraindications=[]}={})=>createActionDefinition({actionId,name,actionScope:scope,constructIds,dimensionIds:dim[actionId.split('-')[0]]??[],intent,instruction:name,intendedOutcome:'Generate decision-useful evidence about fit, usefulness or the next action.',rationale:'Selected only when the Focus/Plan context and eligibility evidence justify this bounded action.',eligibility:{minimumEvidenceRefs:[],...eligibility},exclusions:{contraindications},burden:{level:burden},measurement:{decisionUse:'Decide whether to continue, modify, stop, sequence, replace or reassess.',adherence:'action-specific completion',outcome:'declared target signal',burden:'member-reported burden'},review:{trigger:review,allowedDispositions:D},stopReconsider:stop,trackingRequirement:tracking,additionalAssessmentRequirement:assessment,iconKey:icon,evidenceSourceIds:[],evidenceStrength:strength,permittedRationaleClaim:claim,evidenceReviewStatus:'action_specific_review_required',status});

export const INTERVENTION_BANK=Object.freeze([
 make('PHY-A01','Regularize sleep/wake opportunity',['SLEEP_QUALITY'],{icon:'moon-sleep',tracking:'Daily sleep/wake opportunity, wake time, restfulness and daytime function during active test.',assessment:'Clarify persistent symptoms, dangerous sleep loss, possible sleep disorder or Safety/professional boundary when indicated.'}),
 make('PHY-A02','Add a short comfortable movement bout',['ACTIVITY_LEVEL'],{icon:'movement-walk',tracking:'Completion, perceived effort and symptom flag when relevant.',assessment:'Mobility/symptom/suitability clarification when decision-critical.'}),
 make('PHY-A03','Create a simple hydration cue',[],{scope:'plan',icon:'droplet-hydration',tracking:'Cue completion/usefulness only; no mandatory volume log.',assessment:'Fluid restriction or professional-care clarification when indicated.'}),
 make('EMT-A01','Brief daily mood/stress check-in',['EMOTIONAL_STATE','PRESSURE_PATTERN'],{intent:'track',icon:'mood-pulse',tracking:'One brief state entry plus optional trigger/context while useful; monitor tracking burden/distress.',assessment:'Safety/professional assessment only for governed disclosures or deterioration.'}),
 make('SOC-A01','Schedule one wanted social contact',['LONELINESS'],{icon:'people-connection',tracking:'Attempt/completion, connection quality and energy cost after the contact.',assessment:'Relationship safety/context clarification when decision-critical.'}),
 make('OCC-A01','Choose one next work/learning action',['JOB_SECURITY','NEXT_STEP_CLARITY'],{icon:'briefcase-next-step',tracking:'Completion, clarity gained and next dependency.',assessment:'Eligibility/legal/financial clarification only when needed for the selected step.'}),
 make('FIN-A01','Complete a short spending snapshot',['FINANCIAL_STRAIN','FINANCIAL_CONTROL'],{intent:'assess',icon:'wallet-snapshot',tracking:'One-session member-selected recurring obligations/categories; retain only decision-useful fields.',assessment:'Distinguish visibility from urgent material insecurity or regulated advice need when required.'}),
 make('ENV-A01','Remove one recurring environmental friction',['ENVIRONMENTAL_INTERFERENCE'],{intent:'resolve',icon:'home-friction',tracking:'One before/after friction check plus completion/effort.',assessment:'Hazard, tenancy, accessibility or authority clarification when relevant.'}),
 make('INT-A01','Schedule one focused learning block',['FOCUS_FUNCTION'],{icon:'book-focus',tracking:'Block completion, attention/engagement and usefulness.',assessment:'Functional/professional assessment only for material deterioration or scope issue.'}),
 make('SPT-A01','Choose one values/meaning reflection practice',['VALUES_CLARITY','MEANING_PURPOSE'],{icon:'compass-values',tracking:'Completion, perceived meaning/clarity and burden; never score belief content.',assessment:'Only if distress, compulsivity or Safety/scope issue emerges.'}),
 make('XDM-A01','Reduce simultaneous plan demands',[],{scope:'plan',intent:'resolve',icon:'layers-reduce',tracking:'Plan-level burden and completion before/after contraction; no duplicate log.',assessment:'Reassess if narrowing could drop a material need, Safety obligation or professional dependency.'}),
 make('PHY-A04','Anchor a consistent wake-time window',['SLEEP_QUALITY'],{icon:'sunrise-anchor',tracking:'Wake time and brief restfulness during active test.',assessment:'Schedule feasibility only if it changes the action.'}),
 make('PHY-A05','Reduce one identified sleep-environment friction',['SLEEP_QUALITY'],{intent:'resolve',icon:'bedroom-friction',tracking:'One before/after factor check plus brief sleep experience.',assessment:'Factor safety/authority only when unclear.'}),
 make('PHY-A06','Use a movement cue tied to an existing routine',['ACTIVITY_LEVEL'],{icon:'movement-cue',tracking:'Cue-response completion only; symptom flag when relevant.',assessment:'Movement suitability when decision-critical.',strength:'moderate'}),
 make('PHY-A07','Break one long sedentary period',['ACTIVITY_LEVEL'],{icon:'chair-break',tracking:'Binary interruption log for selected sedentary period only.',assessment:'Suitability clarification when indicated.'}),
 make('EMT-A02','Identify one recurring pressure trigger',['PRESSURE_PATTERN'],{intent:'assess',icon:'pressure-trigger',tracking:'Only pressure episodes needed to identify recurring context; no continuous diary.',assessment:'Safety/professional clarification only for governed disclosure.'}),
 make('EMT-A03','Schedule one short recovery block',['PRESSURE_PATTERN'],{icon:'recovery-block',tracking:'Completion and usefulness after each planned block only.'}),
 make('EMT-A04','Remove one avoidable pressure friction',['PRESSURE_PATTERN'],{intent:'resolve',icon:'pressure-friction',tracking:'One before/after target-context check; no broad stress scoring.',assessment:'Clarify contributor only if needed to choose the change.',strength:'moderate'}),
 make('SOC-A02','Ask one trusted person for a specific kind of support',['SUPPORT_AVAILABILITY'],{icon:'support-request',tracking:'Attempt plus usefulness/comfort only; no ongoing relationship surveillance.',assessment:'Relationship safety clarification when decision-critical.'}),
 make('SOC-A03','Try one low-friction connection option',['LONELINESS','SUPPORT_AVAILABILITY'],{icon:'connection-low-friction',tracking:'One post-contact quality/burden check.'}),
 make('SOC-A04','Protect one relationship boundary',['RELATIONSHIP_STRAIN'],{icon:'relationship-boundary',status:'unsupported_experimental',strength:'low',tracking:'One outcome/safety check after attempted boundary.',assessment:'Clarify safety before use when conflict risk is uncertain.',claim:'No efficacy claim permitted. Preserve only the member’s own stated boundary preference as context pending governance review.'}),
 make('OCC-A02','Clarify one work or learning decision',['JOB_SECURITY','NEXT_STEP_CLARITY','DIRECTION_CLARITY'],{intent:'assess',icon:'briefcase-clarify',tracking:'Decision criteria, chosen next information/action and missing dependency.',assessment:'Eligibility/financial clarification only when decision-changing.',strength:'moderate'}),
 make('OCC-A03','Remove one schedule friction',['SCHEDULE_DISRUPTION'],{intent:'resolve',icon:'calendar-friction',tracking:'One before/after schedule-fit check plus target completion.',assessment:'Authority/constraints only when needed.'}),
 make('OCC-A04','Run one small work/learning trial',['JOB_SECURITY','NEXT_STEP_CLARITY','DIRECTION_CLARITY'],{intent:'learn',icon:'briefcase-trial',burden:'low_to_medium',tracking:'Completion, fit and information gained.',assessment:'Eligibility clarification if required for the trial.'}),
 make('FIN-A02','List the next essential obligations',['FINANCIAL_STRAIN','FINANCIAL_CONTROL'],{intent:'assess',icon:'wallet-obligations',tracking:'One-session essential obligations and due timing; retain only decision-useful information.',assessment:'Material insecurity only if urgency is unclear.'}),
 make('FIN-A03','Remove one recurring cost friction',['FINANCIAL_STRAIN'],{intent:'resolve',icon:'wallet-friction',tracking:'Selected recurring cost before/after only.',assessment:'Clarify whether cost is essential only if ambiguous.'}),
 make('FIN-A04','Create one simple spending boundary',['FINANCIAL_STRAIN','FINANCIAL_CONTROL'],{icon:'wallet-boundary',tracking:'Chosen category/boundary adherence during test only.',assessment:'Essential-versus-discretionary status only if unclear.',strength:'moderate'}),
 make('ENV-A02','Create one supportive environmental cue',['ENVIRONMENTAL_INTERFERENCE'],{icon:'environment-cue',tracking:'Cue-response completion only; no unrelated environmental log.',strength:'moderate'}),
 make('ENV-A03','Create one lower-friction setup',['ENVIRONMENTAL_INTERFERENCE'],{intent:'resolve',icon:'environment-setup',tracking:'One before/after friction and completion check.',assessment:'Authority/access only if needed.',strength:'moderate'}),
 make('ENV-A04','Define one protected space or time',['ENVIRONMENTAL_INTERFERENCE'],{icon:'environment-protected',tracking:'Target-session interference and completion only.',assessment:'Authority/household constraints when decision-critical.'}),
 make('INT-A02','Remove one focus friction',['FOCUS_FUNCTION'],{intent:'resolve',icon:'focus-friction',tracking:'One brief post-session focus/friction check.',assessment:'Professional assessment only for material deterioration/scope issue.'}),
 make('INT-A03','Use a defined short focus block',['FOCUS_FUNCTION'],{icon:'focus-block',tracking:'Completion plus brief attention/usefulness per selected block.',strength:'moderate'}),
 make('INT-A04','Choose one curiosity or learning experiment',['COGNITIVE_ENGAGEMENT'],{intent:'learn',icon:'curiosity-experiment',status:'deferred',strength:'low',tracking:'One post-activity engagement/usefulness check.',claim:'May describe only as a member-chosen learning experiment; no deficit or cognitive-health claim.'}),
 make('SPT-A02','Clarify one value for a current decision',['VALUES_CLARITY'],{intent:'assess',icon:'compass-value',tracking:'Member-stated value and whether it clarified the decision; never score belief content.'}),
 make('SPT-A03','Choose one next step aligned with stated direction',['DIRECTION_CLARITY','NEXT_STEP_CLARITY'],{icon:'compass-next-step',tracking:'Completion plus clarity/fit review only.',assessment:'Feasibility only if needed.',strength:'moderate'}),
 make('SPT-A04','Try one personally meaningful activity',['MEANING_PURPOSE'],{icon:'meaning-activity',tracking:'One post-activity meaning/fit check; never score belief content.'}),
 make('XDM-A02','Sequence two competing actions',[],{scope:'plan',intent:'resolve',icon:'layers-sequence',tracking:'Use existing Action logs; add sequence decision and burden check.',assessment:'Only if dependency or Safety status changes.'}),
 make('XDM-A03','Choose the lowest-burden viable action',[],{scope:'plan',intent:'resolve',icon:'layers-low-burden',tracking:'No extra tracking beyond selected Action; record selection rationale.'}),
 make('XDM-A04','Run one action as an information-gathering trial',[],{scope:'plan',intent:'learn',icon:'flask-trial',tracking:'Only the predeclared discriminating signal and burden.',assessment:'Reassess competing hypothesis at Review.'}),
 make('XDM-A05','Pause a nonessential action to protect capacity',[],{scope:'plan',intent:'resolve',icon:'layers-pause',tracking:'Use existing logs; record pause rationale and reconsideration trigger.',assessment:'Only if dependency/capacity changes.'}),
 make('XDM-A06','Use a member-chosen alternative with the same intended signal',[],{scope:'plan',intent:'build',icon:'swap-fit',tracking:'Same intended signal as canonical Action plus alternative identity.',assessment:'Only if equivalence is uncertain.'}),
]);
export const INTERVENTION_BY_ID=Object.freeze(Object.fromEntries(INTERVENTION_BANK.map(action=>[action.actionId,action])));
export { buildTrackingRequirementIndex, getTrackingRequirements } from './trackingRequirements.js';
