import test from'node:test';import assert from'node:assert/strict';import{buildPlan}from'../planning/planningEngine.js';import{createMemberState}from'../state/member-state-contract.js';import{focusConfirmationPlanningInput}from'../prioritization/focus-confirmation.js';import{reviewPlan}from'./review-engine.js';import{routeReview,ADJUST_DISPOSITION}from'./adaptation-router.js';import{applyReviewLearning}from'./member-state-learning.js';
const focus={constructId:'ACTIVITY_LEVEL',decision:'accepted',decidedAt:'2026-08-30T16:30:00Z'};const input={memberStateRevision:1,focuses:[focus],evidenceRefs:['e:activity'],constraintRefs:[],safetyDisposition:'ordinary_flow'};
function proposed(extra={}){return buildPlan(input,{now:'2026-08-30T16:31:00Z',...extra})}
function active(plan=proposed()){return{...plan,status:'active',activeActions:plan.proposedActions}}

test('accelerated loop: Review classifies and Adjust maintains successful sustainable Action',()=>{const first=active();const review=reviewPlan({plan:first,evidence:{adherence:'high',outcome:'improved',burden:'low',qaSimulated:true}});assert.equal(review.status,'CLASSIFIED');const route=routeReview({review,plan:first});assert.equal(route.disposition,ADJUST_DISPOSITION.MAINTAIN);assert.equal(route.route,'continue');assert.equal(route.preservePlan,true)});
test('accelerated loop: incomplete outcome evidence stays in Review',()=>{const first=active();const review=reviewPlan({plan:first,evidence:{adherence:'high',burden:'low',qaSimulated:true}});assert.equal(review.status,'EVIDENCE_INCOMPLETE');assert.equal(routeReview({review,plan:first}).route,'review-deepening')});
test('accelerated loop: Adjust replacement rejects ineffective Action and Planning selects another',()=>{const first=active();const old=first.activeActions[0];const review=reviewPlan({plan:first,evidence:{adherence:'high',outcome:'unchanged',burden:'low',qaSimulated:true}});const route=routeReview({review,plan:first});assert.equal(route.disposition,ADJUST_DISPOSITION.REPLACE);assert.ok(route.rejectedActionIds.includes(old.actionId));const next=proposed({rejectedActionIds:route.rejectedActionIds,previousActionIds:[old.actionId],adaptationConstraint:route.adaptationConstraint});assert.equal(next.status,'proposed');assert.notEqual(next.proposedActions[0].actionId,old.actionId)});
test('accelerated loop: known execution barrier is classified before Adjust simplifies',()=>{const first=active();const review=reviewPlan({plan:first,evidence:{adherence:'low',outcome:'unchanged',burden:'high',barrierKnown:true,qaSimulated:true}});assert.equal(review.status,'CLASSIFIED');const route=routeReview({review,plan:first});assert.equal(route.disposition,ADJUST_DISPOSITION.SIMPLIFY);const next=proposed({adaptationConstraint:route.adaptationConstraint});assert.equal(next.status,'proposed');assert.ok(next.proposedActions.length>=1)});
test('accelerated loop: explicit burden learning persists to Member State and constrains later Planning without changing Focus',()=>{const observedAt='2026-08-30T16:32:00Z';const first=active();const evidence={adherence:'low',outcome:'unchanged',burden:'high',barrierKnown:true,burdenTolerance:'low',evidenceRefs:['review:burden'],qaSimulated:true};const review=reviewPlan({plan:first,evidence});assert.equal(review.status,'CLASSIFIED');const route=routeReview({review,plan:first});assert.equal(route.disposition,ADJUST_DISPOSITION.SIMPLIFY);let state=createMemberState({memberId:'T0001',now:observedAt});state={...state,revision:1,constructs:{...state.constructs,ACTIVITY_LEVEL:{constructId:'ACTIVITY_LEVEL',dimensionIds:['physical'],topicIds:[],status:'need_attention',evidenceConfidence:'limited',sufficiency:'sufficient',unresolvedReasons:[],factIds:[],evidenceRefs:['e:activity'],observationRefs:[],indicatorIds:[],hypothesisIds:[],firstObservedAt:observedAt,lastObservedAt:observedAt,lastDerivedAt:observedAt}},focusDecisions:{ACTIVITY_LEVEL:focus},activeFocusIds:['ACTIVITY_LEVEL']};const learned=applyReviewLearning(state,{reviewCycleId:'review:r1',evidence,observedAt});const confirmation={memberStateRevision:1,accepted:[focus],constraints:[]};const planningInput=focusConfirmationPlanningInput(confirmation,{memberState:learned,evidenceRefs:['e:activity']});const next=buildPlan(planningInput,{now:'2026-08-30T16:33:00Z'});assert.deepEqual(next.focusIds,['ACTIVITY_LEVEL']);assert.equal(next.actionCeiling,1);assert.equal(next.burden.budget,1);assert.ok(next.decisionTrace.whyNow.includes('member_state_low_capacity_or_burden_tolerance'))});
test('accelerated loop: low adherence without known cause does not pretend to know the fix',()=>{const first=active();const review=reviewPlan({plan:first,evidence:{adherence:'low',outcome:'unchanged',burden:'low',barrierKnown:false,qaSimulated:true}});assert.equal(review.status,'CLASSIFIED');const route=routeReview({review,plan:first});assert.equal(route.disposition,null);assert.equal(route.route,'review-deepening')});
test('accelerated loop: worsening after adequate attempt is Adjust authority',()=>{const first=active();const old=first.activeActions[0];const review=reviewPlan({plan:first,evidence:{adherence:'high',outcome:'worse',burden:'low',qaSimulated:true}});assert.equal('decision'in review,false);const route=routeReview({review,plan:first});assert.equal(route.disposition,ADJUST_DISPOSITION.REPLACE);assert.ok(route.rejectedActionIds.includes(old.actionId))});
test('accelerated loop: changed circumstances are classified then routed upstream by Adjust',()=>{const first=active();const review=reviewPlan({plan:first,evidence:{adherence:'high',outcome:'improved',circumstancesChanged:true,qaSimulated:true}});assert.equal(review.status,'CONTEXT_CHANGED');const route=routeReview({review,plan:first});assert.equal(route.route,'discovery');assert.equal(route.preservePlan,false)});
test('accelerated loop: prolonged missing evidence is timebox state then Adjust routes reassessment',()=>{const first={...active(),deepeningStartedAt:'2026-08-01T00:00:00Z'};const review=reviewPlan({plan:first,evidence:{qaSimulated:true},now:new Date('2026-08-20T00:00:00Z').getTime()});assert.equal(review.status,'EVIDENCE_TIMEBOX_EXPIRED');assert.equal(routeReview({review,plan:first}).route,'discovery')});
test('accelerated loop: non-response classification preserves member agency through Adjust',()=>{const first={...active(),lastMemberResponseAt:'2026-08-01T00:00:00Z'};const review=reviewPlan({plan:first,evidence:{qaSimulated:true},now:new Date('2026-08-20T00:00:00Z').getTime()});const route=routeReview({review,plan:first});assert.equal(review.status,'NON_RESPONSE');assert.equal(route.route,'pause-reengage');assert.equal(route.preservePlan,true);assert.equal(route.memberPrompt,'pause_or_reengage')});