import test from'node:test';import assert from'node:assert/strict';import{buildPlan}from'../planning/planningEngine.js';import{reviewPlan}from'./review-engine.js';import{routeReview}from'./adaptation-router.js';
const focus={constructId:'ACTIVITY_LEVEL',decision:'accepted',decidedAt:'2026-08-30T16:30:00Z'};const input={memberStateRevision:1,focuses:[focus],evidenceRefs:['e:activity'],constraintRefs:[],safetyDisposition:'ordinary_flow'};
function proposed(extra={}){return buildPlan(input,{now:'2026-08-30T16:31:00Z',...extra})}
function active(plan=proposed()){return{...plan,status:'active',activeActions:plan.proposedActions}}

test('accelerated loop: successful sustainable Action is preserved',()=>{const first=active();const review=reviewPlan({plan:first,evidence:{adherence:'high',outcome:'improved',burden:'low',qaSimulated:true}});assert.equal(review.decision,'keep');const route=routeReview({review,plan:first});assert.equal(route.route,'continue');assert.equal(route.preservePlan,true);assert.deepEqual(route.actionIds,first.activeActions.map(x=>x.actionId))});
test('accelerated loop: incomplete outcome evidence deepens instead of guessing',()=>{const first=active();const review=reviewPlan({plan:first,evidence:{adherence:'high',burden:'low',qaSimulated:true}});assert.equal(review.decision,'deepen');assert.equal(routeReview({review,plan:first}).route,'review-deepening')});
test('accelerated loop: replace rejects ineffective Action and selects another eligible Action',()=>{const first=active();const old=first.activeActions[0];const review=reviewPlan({plan:first,evidence:{adherence:'high',outcome:'unchanged',burden:'low',qaSimulated:true}});const route=routeReview({review,plan:first});assert.equal(route.adaptationConstraint,'different_action');assert.ok(route.rejectedActionIds.includes(old.actionId));const next=proposed({rejectedActionIds:route.rejectedActionIds,previousActionIds:[old.actionId],adaptationConstraint:route.adaptationConstraint});assert.equal(next.status,'proposed');assert.notEqual(next.proposedActions[0].actionId,old.actionId)});
test('accelerated loop: known execution barrier simplifies without adding unsupported authority',()=>{const first=active();const review=reviewPlan({plan:first,evidence:{adherence:'low',outcome:'unchanged',burden:'high',barrierKnown:true,qaSimulated:true}});const route=routeReview({review,plan:first});assert.equal(route.adaptationConstraint,'reduce_burden');const next=proposed({adaptationConstraint:route.adaptationConstraint});assert.equal(next.status,'proposed');assert.ok(next.proposedActions.length>=1)});
test('accelerated loop: low adherence without known cause does not pretend to know the fix',()=>{const first=active();const review=reviewPlan({plan:first,evidence:{adherence:'low',outcome:'unchanged',burden:'low',barrierKnown:false,qaSimulated:true}});assert.equal(review.decision,'deepen');assert.equal(review.reason,'insufficient_causal_clarity');assert.equal(routeReview({review,plan:first}).route,'review-deepening')});
test('accelerated loop: worsening despite high adherence rejects ineffective Action',()=>{const first=active();const old=first.activeActions[0];const review=reviewPlan({plan:first,evidence:{adherence:'high',outcome:'worse',burden:'low',qaSimulated:true}});const route=routeReview({review,plan:first});assert.ok(route.rejectedActionIds.includes(old.actionId));assert.equal(route.adaptationConstraint,'different_action')});
test('accelerated loop: changed circumstances route upstream instead of silently replanning',()=>{const first=active();const review=reviewPlan({plan:first,evidence:{adherence:'high',outcome:'improved',circumstancesChanged:true,qaSimulated:true}});const route=routeReview({review,plan:first});assert.equal(route.route,'discovery');assert.equal(route.preservePlan,false)});
test('accelerated loop: prolonged missing evidence triggers reassessment rather than endless deepening',()=>{const first={...active(),deepeningStartedAt:'2026-08-01T00:00:00Z'};const review=reviewPlan({plan:first,evidence:{qaSimulated:true},now:new Date('2026-08-20T00:00:00Z').getTime()});assert.equal(review.decision,'reassess');assert.equal(routeReview({review,plan:first}).route,'discovery')});
test('accelerated loop: non-response pauses progression and preserves member agency',()=>{const first={...active(),lastMemberResponseAt:'2026-08-01T00:00:00Z'};const review=reviewPlan({plan:first,evidence:{qaSimulated:true},now:new Date('2026-08-20T00:00:00Z').getTime()});const route=routeReview({review,plan:first});assert.equal(review.decision,'disengaged');assert.equal(route.route,'pause-reengage');assert.equal(route.preservePlan,true);assert.equal(route.memberPrompt,'pause_or_reengage')});