import test from'node:test';import assert from'node:assert/strict';import{reviewPlan}from'./review-engine.js';
const plan={status:'active',focusIds:['FINANCIAL_CONTROL'],activeActions:[{actionId:'FIN-004',focusIds:['FINANCIAL_CONTROL'],measurement:{},review:{}}]};
test('working sustainable Action is kept',()=>assert.equal(reviewPlan({plan,evidence:{adherence:'high',outcome:'improved',burden:'low'}}).decision,'keep'));
test('known execution barrier leads to simplification',()=>assert.equal(reviewPlan({plan,evidence:{adherence:'low',outcome:'unchanged',burden:'high',barrierKnown:true}}).decision,'simplify'));
test('executed Action without benefit is replaced',()=>assert.equal(reviewPlan({plan,evidence:{adherence:'high',outcome:'unchanged',burden:'low'}}).decision,'replace'));
test('missing causal evidence deepens rather than guesses',()=>assert.equal(reviewPlan({plan,evidence:{adherence:'low',outcome:'unchanged',burden:'low',barrierKnown:false}}).decision,'deepen'));
test('changed circumstances route back to reassessment',()=>{const r=reviewPlan({plan,evidence:{adherence:'high',outcome:'improved',circumstancesChanged:true}});assert.equal(r.decision,'reassess');assert.equal(r.requiresDiscovery,true)});
test('Review returns canonical Action IDs and v2 contract',()=>{const r=reviewPlan({plan,evidence:{adherence:'high',outcome:'improved',burden:'low'}});assert.equal(r.contractVersion,'plan-review-v2');assert.deepEqual(r.actionIds,['FIN-004'])});
test('Review refuses non-active Plans',()=>assert.throws(()=>reviewPlan({plan:{status:'proposed',actions:[{actionId:'FIN-004'}]},evidence:{}}),/Active canonical Plan/));
test('Review refuses unidentified active Actions',()=>assert.throws(()=>reviewPlan({plan:{status:'active',activeActions:[{}]},evidence:{}}),/actionId/));
