import assert from'node:assert/strict';
import fs from'node:fs';
const root=new URL('../../',import.meta.url),read=p=>fs.readFileSync(new URL(p,root),'utf8'),exists=p=>fs.existsSync(new URL(p,root));
const index=read('intelligence-test/index.html'),discovery=read('intelligence-test/discovery.html'),snapshot=read('intelligence-test/discovery-snapshot.html'),priorities=read('intelligence-test/priorities.html'),plan=read('intelligence-test/plan.html'),review=read('intelligence-test/review.html'),complete=read('intelligence-test/complete.html'),contract=read('app/research/intelligence-test-contract.js'),testRuntime=read('intelligence-test/intelligence-test.js'),onboardingStart=read('onboarding-start.html');
assert.match(index,/Canonical Intelligence E2E/,'internal QA entry must identify the canonical Intelligence E2E harness');
assert.match(index,/Discovery → Member State → Prioritize → Plan → Act → Review → Learn → Adapt/,'internal QA must expose the canonical full-loop architecture');
assert.match(index,/discovery-snapshot\.html/,'internal Intelligence QA must enter Discovery, not a Baseline stage');
assert.equal(exists('intelligence-test/baseline.html'),false,'obsolete Baseline-first page must remain retired');
assert.equal(exists('intelligence-test/baseline-plan.html'),false,'parallel Baseline→Plan harness must remain retired');
assert.match(onboardingStart,/app\/onboarding\/flow\.js/,'production onboarding entry must use the canonical routing contract');
assert.doesNotMatch(onboardingStart,/universal_baseline|el8_assessment_sessions|assessment\.html/,'production onboarding entry must not restore the legacy Universal Baseline session path');
assert.match(snapshot,/buildDiscoverySnapshotHandoff/,'opening snapshot must use production Discovery handoff');
assert.match(discovery,/app\/onboarding\/discovery-runtime\.js/,'internal Intelligence QA must exercise canonical browser Discovery runtime');
assert.match(discovery,/projectOnboardingMemberState/,'completed Discovery must establish initial Member State baseline');
assert.doesNotMatch(discovery,/initialPlanProposal|baseline_handoff/,'Discovery cannot own Planning or legacy Baseline handoff');
assert.match(priorities,/applyMemberPriorityDecision/,'member priority decision must be a separate Member State transition');
assert.match(priorities,/buildCanonicalBrowserPlan/,'accepted priorities must hand off to canonical Planning');
assert.match(priorities,/planning_outcome:'no_plan_member_choice'/,'member may explicitly finish with no active plan');
assert.match(priorities,/priorities_completed_without_plan/,'no-plan member choice must be observable in telemetry');
assert.doesNotMatch(priorities,/Accept at least one supported priority/,'internal QA must preserve the member choice to have no active plan');
assert.match(review,/runCanonicalBrowserScenario/,'internal accelerated QA must exercise the canonical review/adaptation scenario');
assert.match(complete,/accelerated_review/,'internal completion must report the canonical accelerated closed-loop result');
assert.match(contract,/stage:'discovery'/,'test contract must start in Discovery');
assert.doesNotMatch(contract,/stage:'baseline'/,'Baseline cannot be a process stage');
assert.match(testRuntime,/export function installExitTest/,'shared QA Exit control must remain explicit and reusable');
assert.doesNotMatch(testRuntime,/installExitTest\(\)/,'shared QA runtime must not auto-install Exit; internal pages opt in explicitly');
assert.equal(exists('intelligence-test/external-complete.html'),true,'existing external completion artifact is retained until the later frozen external snapshot is reconciled or retired explicitly');
assert.doesNotMatch(index,/external Intelligence|external test/i,'internal QA entry must not present itself as the external assessment');
console.log('Internal canonical Intelligence E2E architecture regression passed');
