import assert from'node:assert/strict';
import fs from'node:fs';
const root=new URL('../../',import.meta.url),read=p=>fs.readFileSync(new URL(p,root),'utf8'),exists=p=>fs.existsSync(new URL(p,root));
const index=read('intelligence-test/index.html'),discovery=read('intelligence-test/discovery.html'),snapshot=read('intelligence-test/discovery-snapshot.html'),priorities=read('intelligence-test/priorities.html'),plan=read('intelligence-test/plan.html'),externalComplete=read('intelligence-test/external-complete.html'),review=read('intelligence-test/review.html'),complete=read('intelligence-test/complete.html'),contract=read('app/research/intelligence-test-contract.js');
assert.match(index,/discovery-snapshot\.html/,'Intelligence Test must enter Discovery, not a Baseline stage');
assert.equal(exists('intelligence-test/baseline.html'),false,'obsolete Baseline-first page must remain retired');
assert.equal(exists('intelligence-test/baseline-plan.html'),false,'parallel Baseline→Plan harness must remain retired');
assert.match(snapshot,/buildDiscoverySnapshotHandoff/,'opening snapshot must use production Discovery handoff');
assert.match(discovery,/app\/onboarding\/discovery-runtime\.js/,'Intelligence Test must exercise canonical browser Discovery runtime');
assert.match(discovery,/projectOnboardingMemberState/,'completed Discovery must establish initial Member State baseline');
assert.doesNotMatch(discovery,/initialPlanProposal|baseline_handoff/,'Discovery cannot own Planning or legacy Baseline handoff');
assert.match(priorities,/applyMemberPriorityDecision/,'member priority decision must be a separate Member State transition');
assert.match(priorities,/buildCanonicalBrowserPlan/,'Prioritization must hand off to canonical Planning');
assert.doesNotMatch(plan,/applyCanonicalBrowserPlan/,'external Intelligence Test must not activate the proposed plan');
assert.doesNotMatch(plan,/review\.html/,'external Intelligence Test must stop before Review');
assert.match(plan,/external-complete\.html/,'external Intelligence Test must finish at the proposed Plan boundary');
assert.match(plan,/boundary:'discovery_to_plan'/,'external completion telemetry must identify the validated boundary');
assert.match(externalComplete,/Discovery → Plan/,'external completion page must state the tested boundary');
assert.match(review,/runCanonicalBrowserScenario/,'internal accelerated full-loop QA must remain available');
assert.match(complete,/accelerated_review/,'internal completion must still report canonical closed-loop result');
assert.match(contract,/stage:'discovery'/,'test contract must start in Discovery');
assert.doesNotMatch(contract,/stage:'baseline'/,'Baseline cannot be a process stage');
console.log('External Intelligence Discovery-to-Plan boundary regression passed; internal full-loop harness preserved');
