import{INTELLIGENCE_TEST_VERSION,INTELLIGENCE_TEST_HARNESS_VERSION,INTELLIGENCE_TEST_ENGINE_CANDIDATE_SHA,INTELLIGENCE_TEST_INTELLIGENCE_VERSION,INTELLIGENCE_TEST_COMPONENT_VERSIONS}from'../app/research/intelligence-test-version.js';
import{loadTestSession,saveTestSession,event,note}from'./intelligence-test.js';

async function flushPendingTesterNote(session,stage,screenId){const field=document.getElementById('testerNote');const text=field?.value?.trim();if(!session||!text)return true;const saved=await note(session,{stage:''+stage,screenId:''+screenId,questionId:null,text});if(saved)field.value='';return saved}
export function installQaChrome({stage='unknown',screenId='unknown',showExit=true}={}){
 const style=document.createElement('style');style.textContent=`.qa-chrome{position:fixed!important;top:max(10px,env(safe-area-inset-top))!important;right:max(12px,env(safe-area-inset-right))!important;z-index:2147483647!important;display:flex!important;align-items:center;gap:8px;pointer-events:auto!important}.qa-chrome button{display:inline-flex!important;align-items:center;justify-content:center;min-width:56px!important;min-height:44px!important;width:auto!important;border:2px solid #111!important;background:#fff!important;color:#111!important;border-radius:10px!important;padding:8px 12px!important;font:700 13px/1 system-ui,sans-serif!important;box-shadow:0 2px 8px rgba(0,0,0,.28)!important;opacity:1!important;visibility:visible!important}.qa-chrome button:disabled{opacity:.65!important}.qa-version{position:fixed;left:max(8px,env(safe-area-inset-left));bottom:max(8px,env(safe-area-inset-bottom));z-index:2147483646;font:600 11px/1.2 system-ui,sans-serif;color:#111;background:#fff;border:1px solid #c9c9c9;padding:6px 8px;border-radius:7px;box-shadow:0 1px 4px rgba(0,0,0,.12);max-width:calc(100vw - 16px)}`;document.head.appendChild(style);
 const activeEngine=INTELLIGENCE_TEST_COMPONENT_VERSIONS[stage];const engineLabel=activeEngine?` · ${stage[0].toUpperCase()+stage.slice(1)} ${activeEngine}`:'';const version=document.createElement('div');version.className='qa-version';version.setAttribute('aria-label','EL8 human QA build version');version.textContent=`Intelligence ${INTELLIGENCE_TEST_INTELLIGENCE_VERSION}${engineLabel} · Test v${INTELLIGENCE_TEST_VERSION} · ${INTELLIGENCE_TEST_ENGINE_CANDIDATE_SHA.slice(0,7)}`;document.body.appendChild(version);
 if(showExit){const chrome=document.createElement('div');chrome.className='qa-chrome';chrome.setAttribute('role','navigation');chrome.setAttribute('aria-label','Human QA controls');const exit=document.createElement('button');exit.type='button';exit.className='qa-exit';exit.setAttribute('aria-label','Exit human QA test');exit.textContent='Exit';exit.onclick=async()=>{exit.disabled=true;const s=loadTestSession();if(s){const noteSaved=await flushPendingTesterNote(s,stage,screenId);await event(s,'test_exit',''+stage,''+screenId,null,{stageAtExit:s.stage||stage,memberStateRevision:s.member_state?.revision??null,hasDiscovery:Boolean(s.discovery),candidateCount:(s.prioritization?.recommended?.length||0)+(s.prioritization?.alternatives?.length||0),pendingTesterNoteSaved:noteSaved});s.stage='exited';saveTestSession(s)}location.href='index.html'};chrome.appendChild(exit);document.body.appendChild(chrome)}
}
