import assert from 'node:assert/strict';
import fs from 'node:fs';
const discovery=fs.readFileSync(new URL('./discovery.html',import.meta.url),'utf8');
const index=fs.readFileSync(new URL('./index.html',import.meta.url),'utf8');
assert.match(index,/location\.href='discovery\.html'/,'Intelligence Test must enter Discovery directly');
assert.match(discovery,/<span>Discovery<\/span><span>Prioritize<\/span><span>Focus<\/span><span>Plan<\/span>/,'Tester must show the canonical Discovery-to-Planning progression');
assert.match(discovery,/createDiscoverySession\(\)/,'Discovery must create its own session without an upstream assessment dependency');
assert.doesNotMatch(index,/baseline/i,'Intelligence Test entry must not reference the retired pre-Discovery stage');
assert.doesNotMatch(discovery,/baseline/i,'Discovery must not depend on or reference the retired pre-Discovery stage');
assert.doesNotMatch(discovery,/initialPlanProposal/,'Discovery must not select Actions or construct a Plan');
console.log('Discovery-first browser architecture regression passed');
