import assert from 'node:assert/strict';
import fs from 'node:fs';
const discovery=fs.readFileSync(new URL('./discovery.html',import.meta.url),'utf8');
const priorities=fs.readFileSync(new URL('./priorities.html',import.meta.url),'utf8');
const plan=fs.readFileSync(new URL('./plan.html',import.meta.url),'utf8');
const index=fs.readFileSync(new URL('./index.html',import.meta.url),'utf8');
const chrome=fs.readFileSync(new URL('./chrome.js',import.meta.url),'utf8');
const runtime=fs.readFileSync(new URL('../app/onboarding/discovery-runtime.js',import.meta.url),'utf8');
assert.match(index,/location\.href='discovery\.html'/,'Intelligence Test must enter Discovery directly');
assert.match(index,/>Begin assessment</,'Entry action must use member-facing assessment language');
assert.doesNotMatch(index,/Begin Discovery/,'Entry action must not expose internal Discovery terminology');
assert.match(index,/document\.getElementById\('modes'\)/,'Entry bootstrap must explicitly resolve the mode controls');
assert.match(index,/document\.getElementById\('begin'\)/,'Entry bootstrap must explicitly resolve the begin control');
assert.match(index,/addEventListener\('click'/,'Entry controls must use explicit event listeners');
assert.doesNotMatch(chrome,/INTELLIGENCE_TEST_COMPONENT_VERSIONS/,'QA chrome must not depend on retired component semantic versions');
assert.match(discovery,/class="progress"/,'Discovery must retain unobtrusive progress feedback');
assert.match(priorities,/class="progress"/,'Focus confirmation must retain unobtrusive progress feedback');
for(const [name,html] of [['Discovery',discovery],['Focus',priorities],['Plan',plan]]){assert.doesNotMatch(html,/<span>Discovery<\/span><span>Prioritize<\/span><span>Focus<\/span><span>Plan<\/span>/,`${name} must not expose internal Intelligence stage labels as member UI`);assert.match(html,/id="testerNote"/,`${name} must keep the internal QA note field visible during human validation`);assert.doesNotMatch(html,/<details class="qa">/,`${name} QA notes must not be collapsible`)}
assert.match(discovery,/createDiscoverySession\(\)/,'Discovery must create its own session without an upstream assessment dependency');
assert.doesNotMatch(index,/baseline/i,'Intelligence Test entry must not reference the retired pre-Discovery stage');
assert.doesNotMatch(discovery,/initialPlanProposal/,'Discovery must not select Actions or construct a Plan');
assert.match(discovery,/function renderMatrix\(/,'Repeated shared ordered scales must have a dedicated matrix renderer');
assert.match(discovery,/className='response-matrix'/,'Repeated-scale Discovery interactions must render as a matrix');
assert.match(discovery,/if\(current\.type==='matrix'\)\{renderMatrix\(/,'Matrix steps must route to the matrix renderer');
assert.match(discovery,/COMPACT_CHOICE_THRESHOLD=8/,'Distinct answer sets must remain stacked through seven choices and become compact at eight or more');
assert.match(discovery,/function presentedOptions\(raw=\[\]\)/,'Discovery choices must pass through one presentation-normalization boundary');
assert.match(discovery,/seen\.has\(key\)/,'Presentation normalization must collapse repeated semantic answer labels');
assert.match(discovery,/function optionTailRank\(o=\{\}\)/,'Presentation normalization must define governed tail ordering');
assert.match(discovery,/label==='something else'/,'Something-else answers must be recognized');
assert.match(discovery,/className='other-input'/,'Something else must expose a text field');
assert.match(discovery,/Tell EL8 what fits instead/,'Something else must require useful member text');
assert.match(discovery,/padding:9px 11px/,'Ordinary Discovery answers must use tightened human-QA density');
assert.match(discovery,/className='triage-question'/,'Driver and severity triage must display the predicate for each response row');
assert.match(discovery,/q\.text\|\|q\.label/,'Driver and severity triage must show the actual member-facing question');
assert.match(runtime,/showDimensionLabels:true/,'Graph triage must preserve member-facing labels');
assert.match(runtime,/value==='no'\?'reject':value==='yes'\?'accept':'unknown'/,'Not sure must remain unknown rather than being treated as accepted driver evidence');
assert.match(chrome,/matrix-head\{background:transparent!important\}/,'Matrix heading must not have a background fill');
assert.match(chrome,/matrix-head>div:first-child\{font-size:0!important\}/,'Matrix must not show an Area label in its top-left cell');
assert.match(chrome,/matrix-row>div\{border-right:0!important/,'Matrix must not show vertical divider lines');
assert.match(chrome,/matrix-choice button\.selected\{background:#111!important;color:#fff!important/,'Selected matrix answers must be visibly black');
assert.match(chrome,/z-index:2147483647/,'Global QA Exit must remain above page content and dead-end states');
assert.match(priorities,/installQaChrome\(\{stage:'focus',screenId:'focus-confirmation'\}\);const/,'Focus must install QA chrome before loading optional engine modules');
assert.match(priorities,/Best current starting point/,'Focus must expose the best current starting point instead of flattening every candidate to the same label');
assert.match(priorities,/causal leverage/,'Focus must explain causal leverage when Discovery provides it');
assert.doesNotMatch(priorities,/<h1>Choose where you want to start\.<\/h1>/,'Focus must not retain the oversized redundant heading flagged in human QA');
assert.doesNotMatch(plan,/<h1>Your starting plan<\/h1>/,'Plan must not retain the oversized redundant heading flagged in human QA');
assert.doesNotMatch(plan,/id="focusStatus"/,'Plan must not repeat the confirmed Focus as a separate member-facing block');
assert.match(plan,/<strong>Try it for:<\/strong>/,'Plan must expose duration/review information when available');
assert.match(plan,/<strong>Track:<\/strong>/,'Plan must expose tracking requirements when available');
assert.match(plan,/<strong>Toolkit<\/strong>/,'Plan must expose Toolkit content');
assert.match(plan,/memberDescription/,'Toolkit must explain what each tool is for rather than showing only names');
console.log('Full human-QA feedback-ledger presentation regression passed');
