import{createIntelligenceTestSession,beginIntelligenceTest,nextSequence,elapsedMs}from'../app/research/intelligence-test-contract.js';
import{INTELLIGENCE_TEST_STORAGE_KEY}from'../app/research/intelligence-test-version.js';
import{startTelemetry,sendEvent,sendNote}from'./submit.js';
export function loadTestSession(){try{return JSON.parse(sessionStorage.getItem(INTELLIGENCE_TEST_STORAGE_KEY)||'null')}catch{return null}}
export function saveTestSession(session){sessionStorage.setItem(INTELLIGENCE_TEST_STORAGE_KEY,JSON.stringify(session));return session}
export function clearTestSession(){sessionStorage.removeItem(INTELLIGENCE_TEST_STORAGE_KEY)}
export function newTestSession(mode='prefer_not_to_say'){return createIntelligenceTestSession({testerMode:mode})}
export async function start(session){const next=beginIntelligenceTest(session);Object.assign(session,next,{stage:'discovery'});saveTestSession(session);session.telemetry=session.telemetry||{};session.telemetry.started=Boolean(await startTelemetry(session));saveTestSession(session);await event(session,'test_started','discovery','introduction',null,{mode:session.tester_mode});return session}
export async function event(session,eventType,stage,screenId,questionId=null,payload={}){if(!session)return false;session.events=Array.isArray(session.events)?session.events:[];const entry={sequence:nextSequence(session),occurred_at:new Date().toISOString(),event_type:eventType,stage,screen_id:screenId,question_id:questionId,payload};session.events.push(entry);saveTestSession(session);const sent=await sendEvent(session,entry,elapsedMs(session));session.telemetry=session.telemetry||{};session.telemetry.last_event_sequence=entry.sequence;session.telemetry.last_event_sent=Boolean(sent);saveTestSession(session);return Boolean(sent)}
export async function note(session,{stage='unknown',screenId='unknown',questionId=null,text=''}={}){const clean=String(text||'').trim();if(!session||!clean)return false;session.tester_notes=Array.isArray(session.tester_notes)?session.tester_notes:[];const entry={sequence:nextSequence(session),occurred_at:new Date().toISOString(),stage,screen_id:screenId,question_id:questionId,text:clean};session.tester_notes.push(entry);saveTestSession(session);const sent=await sendNote(session,entry,elapsedMs(session));session.telemetry=session.telemetry||{};session.telemetry.last_note_sequence=entry.sequence;session.telemetry.last_note_sent=Boolean(sent);saveTestSession(session);return Boolean(sent)}
function visibleTesterNote(){const field=document.getElementById('testerNote');return field&&'value'in field?String(field.value||'').trim():''}
// QA-only control. Internal harnesses opt in explicitly; external snapshots must not install it.
export function installExitTest({session=null,stage=null,screenId=null,href='index.html'}={}){if(document.getElementById('el8ExitTest'))return;const s=session||loadTestSession(),button=document.createElement('button');button.id='el8ExitTest';button.type='button';button.textContent='Exit test';button.setAttribute('aria-label','Exit Intelligence test');Object.assign(button.style,{position:'fixed',right:'16px',top:'16px',zIndex:'9999',padding:'9px 12px',border:'1px solid var(--line, #ccc)',borderRadius:'999px',background:'var(--card, #fff)',color:'var(--ink, #111)',font:'inherit',cursor:'pointer'});button.onclick=async()=>{button.disabled=true;if(s){const text=visibleTesterNote();if(text)await note(s,{stage:stage||s.stage||'unknown',screenId:screenId||location.pathname.split('/').pop()||'unknown',text});await event(s,'test_exit',stage||s.stage||'unknown',screenId||location.pathname.split('/').pop()||'unknown',null,{memberStateRevision:s.member_state?.revision??null,noteSaved:Boolean(text)});saveTestSession(s)}location.href=href};document.body.appendChild(button)}
