import{createClient}from'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import{INTELLIGENCE_TEST_STORAGE_KEY}from'../app/research/intelligence-test-version.js';
import{createIntelligenceTestSession,beginIntelligenceTest,elapsedMs,nextSequence}from'../app/research/intelligence-test-contract.js';
const supabase=createClient('https://jprdsidxwjkgiqqakwpr.supabase.co','sb_publishable_CkcqWpD6nkzRzBfuJV08TQ_t38C9j34',{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
export function loadTestSession(){try{return JSON.parse(sessionStorage.getItem(INTELLIGENCE_TEST_STORAGE_KEY)||'null')}catch{return null}}
export function saveTestSession(s){sessionStorage.setItem(INTELLIGENCE_TEST_STORAGE_KEY,JSON.stringify(s));return s}
export function newTestSession(testerMode='prefer_not_to_say'){const s=createIntelligenceTestSession({testerMode});return saveTestSession(s)}
export function clearTestSession(){sessionStorage.removeItem(INTELLIGENCE_TEST_STORAGE_KEY)}
export async function config(){const{data,error}=await supabase.rpc('el8_intelligence_test_config');if(error)throw error;return data}
export async function start(session){const s=beginIntelligenceTest(session);saveTestSession(s);const{error}=await supabase.rpc('el8_intelligence_test_start',{p_session:{id:s.id,test_version:s.test_version,build_version:s.build_version,engine_version:s.engine_version,tester_mode:s.tester_mode,client_meta:{browser:navigator.userAgent.includes('Mobile')?'mobile':'desktop',language:navigator.language}}});if(error)throw error;await event(s,'test_started','baseline','baseline-intro');return s}
export async function event(session,eventType,stage,screenId,questionId=null,payload={}){const sequence=nextSequence(session);saveTestSession(session);try{const{error}=await supabase.rpc('el8_intelligence_test_event',{p_event:{session_id:session.id,sequence,event_type:eventType,stage,screen_id:screenId,question_id:questionId,elapsed_ms:elapsedMs(session),payload}});if(error)throw error;return true}catch(e){console.warn('Intelligence Test telemetry event failed',e);return false}}
export async function note(session,{stage,screenId,questionId=null,text=''}){if(!text.trim())return true;try{const{error}=await supabase.rpc('el8_intelligence_test_note',{p_note:{session_id:session.id,stage,screen_id:screenId,question_id:questionId,elapsed_ms:elapsedMs(session),note_text:text.trim(),version_meta:{test_version:session.test_version,engine_version:session.engine_version}}});if(error)throw error;return true}catch(e){console.warn('Intelligence Test note failed',e);return false}}
