import test from 'node:test';
import assert from 'node:assert/strict';
import * as Discovery from '../../intelligence/discovery/discovery-engine.js';
import { answerEffects } from '../../intelligence/discovery/observationNormalizer.js';
import { discoveryOutputToMemberState,memberStateToPrioritizationInput } from '../../intelligence/state/discovery-member-state-adapter.js';
import {applyMemberStateTransition,MEMBER_STATE_EVENT}from'../../intelligence/state/member-state-transition.js';
import { prioritizeCandidates } from '../../intelligence/prioritization/prioritization.js';
import { confirmFocus,applyFocusConfirmation,focusConfirmationPlanningInput } from '../../intelligence/prioritization/focus-confirmation.js';
import { buildPlan } from '../../intelligence/planning/planningEngine.js';
import { reviewPlan } from '../../intelligence/review/review-engine.js';
import { routeReview,ADJUST_DISPOSITION } from '../../intelligence/review/adaptation-router.js';
function answerWithStateEvidence(question){const establishing=question.options.find(option=>answerEffects(question,option.id).some(effect=>['EVIDENCE','STATE'].includes(String(effect['Effect Type']).toUpperCase())));return establishing?.id??question.options.find(option=>answerEffects(question,option.id).length>0)?.id??question.options[0]?.id}
function answerBaseline(session,matrix,{physical='Difficult'}={}){for(const question of matrix.questions){const desired=String(question.dimension).toUpperCase()==='PHYSICAL'?physical:'Going well',option=question.options.find(item=>item.text===desired);assert.ok(option);Discovery.answer(session,question,option.id)}}
function answerDriverTriage(session,step,{questionId='Q000085',answerId='A000549'}={}){assert.equal(step.type,'driver-triage');const question=step.questions.find(item=>item.id===questionId);assert.ok(question);const option=question.options.find(item=>item.id===answerId);assert.ok(option);Discovery.answer(session,question,option.id)}
function establishActivitySession(){const session=Discovery.session();let step=Discovery.next(session);assert.equal(step.type,'matrix');answerBaseline(session,step);step=Discovery.next(session);answerDriverTriage(session,step);let state=Discovery.trace(session).states.find(item=>item.constructId==='ACTIVITY_LEVEL');for(let guard=0;guard<8&&state?.resolutionState!=='sufficient';guard++){step=Discovery.next(session);assert.equal(step.type,'question');Discovery.answer(session,step.question,answerWithStateEvidence(step.question));state=Discovery.trace(session).states.find(item=>item.constructId==='ACTIVITY_LEVEL')}return{session,state}}
function canonicalAfterDiscovery(session){const memberState=discoveryOutputToMemberState(Discovery.trace(session),{memberId:'E01',at:'2026-09-01T11:59:00Z'});return{memberState,prioritization:prioritizeCandidates(memberStateToPrioritizationInput(memberState))}}
test('E01 raw-input lifecycle reaches Review and Adjust through production Intelligence transitions',()=>{const{session,state}=establishActivitySession();assert.equal(state.resolutionState,'sufficient');Discovery.complete(session);const established=Discovery.trace(session).states.find(item=>item.constructId==='ACTIVITY_LEVEL');assert.ok(['established','supported'].includes(established.status));const{memberState,prioritization}=canonicalAfterDiscovery(session);assert.equal(prioritization.recommended[0].constructId,'ACTIVITY_LEVEL');const confirmation=confirmFocus({prioritization,decisions:[{constructId:'ACTIVITY_LEVEL',decision:'accepted',memberRank:1}],decidedAt:'2026-09-01T12:00:00Z'}),confirmedState=applyFocusConfirmation(memberState,confirmation),planningInput=focusConfirmationPlanningInput(confirmation,{memberState:confirmedState,evidenceRefs:established.evidenceRefs,safetyDisposition:'ordinary_flow'}),plan=buildPlan(planningInput,{now:'2026-09-01T12:01:00Z'});assert.equal(planningInput.memberStateRevision,confirmedState.revision);assert.equal(plan.status,'proposed');assert.ok(plan.proposedActions.length>=1);const activePlan={...plan,status:'active',activeActions:plan.proposedActions},review=reviewPlan({plan:activePlan,evidence:{adherence:'high',outcome:'improved',burden:'low',qaSimulated:true}}),route=routeReview({review,plan:activePlan});assert.equal(review.status,'CLASSIFIED');assert.equal('decision'in review,false);assert.equal(route.disposition,ADJUST_DISPOSITION.MAINTAIN);assert.equal(route.route,'continue');assert.equal(route.preservePlan,true)});
test('E01 Member State personalization constrains Planning burden without changing confirmed Focus',()=>{const{session}=establishActivitySession();Discovery.complete(session);let{memberState,prioritization}=canonicalAfterDiscovery(session);memberState=applyMemberStateTransition(memberState,{type:MEMBER_STATE_EVENT.ENGAGEMENT_SIGNAL_UPDATED,payload:{key:'burdenTolerance',value:'low',evidenceRefs:['review:prior'],sourceType:'review_learning',sourceRef:'prior',observedAt:'2026-09-01T11:59:30Z',confidence:'moderate'},source:'review',at:'2026-09-01T11:59:30Z',expectedRevision:memberState.revision});prioritization=prioritizeCandidates(memberStateToPrioritizationInput(memberState));const confirmation=confirmFocus({prioritization,decisions:[{constructId:'ACTIVITY_LEVEL',decision:'accepted',memberRank:1}],decidedAt:'2026-09-01T12:00:00Z'}),confirmed=applyFocusConfirmation(memberState,confirmation),input=focusConfirmationPlanningInput(confirmation,{memberState:confirmed}),plan=buildPlan(input,{now:'2026-09-01T12:01:00Z'});assert.deepEqual(plan.focusIds,['ACTIVITY_LEVEL']);assert.equal(plan.actionCeiling,1);assert.equal(plan.burden.budget,1);assert.ok(plan.decisionTrace.diagnostics.memberStateFit.reasons.includes('member_state_low_capacity_or_burden_tolerance'))});
test('E01 Safety interruption pauses ordinary Discovery until governed confirmation',()=>{const session=Discovery.session();Discovery.setSafetyContext(session,{explicitSafetyConcern:true});let step=Discovery.next(session);assert.equal(step.type,'safety');assert.equal(step.safety.status,'confirmation_required');assert.equal(step.safety.pauseOrdinaryFlow,true);Discovery.setSafetyContext(session,{explicitSafetyConcern:true},{immediateDanger:true,intent:false,canStaySafe:true});step=Discovery.next(session);assert.equal(step.type,'safety');assert.equal(step.safety.status,'escalate');assert.equal(step.safety.pauseOrdinaryFlow,true)});
test('E01 explicit QA outer guardrail stops unresolved evidence as incomplete',()=>{const session=Discovery.session({constructIds:['ACTIVITY_LEVEL'],outerGuardrail:2});let step=Discovery.next(session);assert.equal(step.type,'matrix');answerBaseline(session,step,{physical:'Difficult'});step=Discovery.next(session);answerDriverTriage(session,step);const finish=Discovery.next(session);assert.equal(finish.type,'finish');assert.equal(finish.stop.incomplete,true);const state=Discovery.trace(session).states.find(item=>item.constructId==='ACTIVITY_LEVEL');assert.notEqual(state?.resolutionState,'sufficient');assert.notEqual(state?.status,'established')});
test('E01 member rejection produces explicit no-plan outcome',()=>{const{session,state}=establishActivitySession();Discovery.complete(session);const{memberState,prioritization}=canonicalAfterDiscovery(session),confirmation=confirmFocus({prioritization,decisions:[{constructId:'ACTIVITY_LEVEL',decision:'rejected'}],decidedAt:'2026-09-01T12:00:00Z'});assert.equal(confirmation.accepted.length,0);assert.equal(confirmation.declined[0].constructId,'ACTIVITY_LEVEL');assert.equal(confirmation.memberChangedRecommendation,true);const confirmedState=applyFocusConfirmation(memberState,confirmation),input=focusConfirmationPlanningInput(confirmation,{memberState:confirmedState,evidenceRefs:state.evidenceRefs,safetyDisposition:'ordinary_flow'}),plan=buildPlan(input,{now:'2026-09-01T12:01:00Z'});assert.equal(plan.status,'no_plan');assert.equal(plan.reason,'no_member_accepted_focus');assert.deepEqual(plan.proposedActions,[])});
test('E01 Planning blocks Safety override and cannot emit Actions',()=>{const plan=buildPlan({memberStateRevision:0,focuses:[{constructId:'ACTIVITY_LEVEL',decision:'accepted'}],evidenceRefs:['Q000001'],constraintRefs:[],safetyDisposition:'escalate',planningContext:{}},{now:'2026-09-01T12:01:00Z'});assert.equal(plan.status,'blocked');assert.equal(plan.reason,'safety_override');assert.deepEqual(plan.proposedActions,[])});
