import test from 'node:test';
import assert from 'node:assert/strict';
import {prioritizeCandidates} from '../../intelligence/prioritization/prioritization.js';
import {confirmFocus,applyFocusConfirmation,focusConfirmationPlanningInput} from '../../intelligence/prioritization/focus-confirmation.js';
import {buildPlan} from '../../intelligence/planning/planningEngine.js';
import {createActionRegistry} from '../../intelligence/planning/action-registry.js';
import {createMemberState} from '../../intelligence/state/member-state-contract.js';
import {discoveryOutputToMemberState} from '../../intelligence/state/discovery-member-state-adapter.js';
import {applyContextModifierToMemberState} from '../../intelligence/state/context-modifier-state.js';
import {confirmContextModifier,CONTEXT_MODIFIER_STATUS} from '../../intelligence/state/context-modifier-lifecycle.js';

const NOW='2026-09-02T13:00:00.000Z';
const focuses=['ACTIVITY_LEVEL','SLEEP_QUALITY'];
const accepted=focuses.map((constructId,index)=>({constructId,decision:'accepted',memberRank:index+1}));
const baseInput={memberStateRevision:4,focuses:accepted,evidenceRefs:['e:activity','e:sleep'],constraintRefs:[],safetyDisposition:'ordinary_flow',planningContext:{}};

test('hostile: smallest useful portfolio may use one governed plan Action across multiple confirmed focuses',()=>{const plan=buildPlan(baseInput,{now:NOW,planningConditions:['reduce_simultaneous_demands'],preferredActionIds:['ACT000036']});assert.equal(plan.status,'proposed');assert.equal(plan.proposedActions.length,1);assert.equal(plan.proposedActions[0].actionId,'ACT000036');assert.deepEqual([...plan.proposedActions[0].focusIds].sort(),[...focuses].sort());assert.deepEqual(plan.uncoveredFocusIds,[])});
test('hostile: Action ceiling and capacity never fabricate full focus coverage',()=>{const plan=buildPlan(baseInput,{now:NOW,actionCeiling:1});assert.ok(plan.proposedActions.length<=1);assert.ok(plan.uncoveredFocusIds.length>=1);for(const id of plan.uncoveredFocusIds)assert.ok(focuses.includes(id))});
test('hostile: explicit contraindication remains absolute even when member preference and Subcon favor the Action',()=>{const registry=createActionRegistry(),candidate=registry.forConstruct('ACTIVITY_LEVEL')[0];assert.ok(candidate);const planningContext={byConstruct:{ACTIVITY_LEVEL:{mechanismMatch:1,feasibility:1,memberPreference:1,actionability:1,priorLearning:1,decisionValue:1,evidenceStrength:1,discrimination:1,recencyRelevance:1,sufficiency:1,corroboration:1}}};const plan=buildPlan({...baseInput,focuses:[accepted[0]],planningContext},{now:NOW,preferredActionIds:[candidate.actionId],contraindicatedActionIds:[candidate.actionId]});assert.ok(!plan.proposedActions.some(x=>x.actionId===candidate.actionId));assert.ok(plan.decisionTrace.diagnostics.contraindicatedActionIds.includes(candidate.actionId))});
test('hostile: Conscious member preference can disagree with quantitative Subcon ranking without surrendering authority',()=>{const registry=createActionRegistry(),candidates=registry.forConstruct('ACTIVITY_LEVEL').slice(0,2);assert.equal(candidates.length,2);const preferred=candidates[0],shadowFavored=candidates[1];const low={mechanismMatch:.05,feasibility:.05,actionability:.05,priorLearning:.05,decisionValue:.05,evidenceStrength:.05,discrimination:.05,recencyRelevance:.05,sufficiency:.05,corroboration:.05},high={mechanismMatch:1,feasibility:1,actionability:1,priorLearning:1,decisionValue:1,evidenceStrength:1,discrimination:1,recencyRelevance:1,sufficiency:1,corroboration:1};const input={...baseInput,focuses:[accepted[0]],planningContext:{byConstruct:{ACTIVITY_LEVEL:{byAction:{[preferred.actionId]:low,[shadowFavored.actionId]:high}}}}};const plan=buildPlan(input,{now:NOW,preferredActionIds:[preferred.actionId],actionCeiling:1});assert.equal(plan.proposedActions[0].actionId,preferred.actionId);assert.equal(plan.shadow.authoritative,false);assert.equal(plan.shadow.ranking[0].actionId,shadowFavored.actionId)});
test('hostile: stale Focus confirmation cannot mutate a newer canonical Member State revision',()=>{const state=createMemberState({memberId:'member:hostile',now:NOW});const prioritization=prioritizeCandidates({memberStateRevision:state.revision,candidates:[{constructId:'ACTIVITY_LEVEL',status:'supported',evidenceRefs:['e:activity']}]},{now:NOW});const confirmation=confirmFocus({prioritization,decisions:[{constructId:'ACTIVITY_LEVEL',decision:'accepted'}],decidedAt:NOW});const newer={...state,revision:state.revision+1};assert.throws(()=>applyFocusConfirmation(newer,confirmation),/revision conflict/)});
test('hostile: modifier correction/supersession preserves history semantics and does not manufacture constructs',()=>{let state=createMemberState({memberId:'member:modifier-hostile',now:NOW});state=applyContextModifierToMemberState(state,{modifierId:'injury:old',type:'INJURY',value:{site:'knee'},sourceType:'member_report',sourceRef:'discovery:1',materialToPlanning:true},{source:'discovery',at:NOW,expectedRevision:state.revision});const old=state.memberContext.contextModifiers['injury:old'];const corrected=confirmContextModifier(old,{stillApplies:false,replacement:{modifierId:'injury:new'},confirmedAt:'2026-09-03T13:00:00.000Z'});assert.equal(corrected.status,CONTEXT_MODIFIER_STATUS.SUPERSEDED);assert.equal(corrected.supersededByModifierId,'injury:new');assert.equal(Object.keys(state.constructs).length,0)});
test('hostile: rejection of one near-equivalent focus cannot be silently restored by Planning',()=>{const states=[{constructId:'ACTIVITY_LEVEL',status:'supported',qualitativeConfidence:'WELL_SUPPORTED',resolutionState:'sufficient',evidenceRefs:['e:a']},{constructId:'SLEEP_QUALITY',status:'supported',qualitativeConfidence:'WELL_SUPPORTED',resolutionState:'sufficient',evidenceRefs:['e:s']}];const state=discoveryOutputToMemberState({trace:{states}},{memberId:'member:near-equivalent',at:NOW});const prioritization=prioritizeCandidates({memberStateRevision:state.revision,candidates:[{constructId:'ACTIVITY_LEVEL',status:'supported',evidenceRefs:['e:a']},{constructId:'SLEEP_QUALITY',status:'supported',evidenceRefs:['e:s']}]},{now:NOW,decisionFactors:{ACTIVITY_LEVEL:{urgency:.6,materiality:.6,memberImportance:.6},SLEEP_QUALITY:{urgency:.61,materiality:.61,memberImportance:.61}}});const confirmation=confirmFocus({prioritization,decisions:[{constructId:'ACTIVITY_LEVEL',decision:'rejected'},{constructId:'SLEEP_QUALITY',decision:'accepted'}],decidedAt:NOW});const confirmedState=applyFocusConfirmation(state,confirmation),input=focusConfirmationPlanningInput(confirmation,{memberState:confirmedState,evidenceRefs:['e:a','e:s'],safetyDisposition:'ordinary_flow'});const plan=buildPlan(input,{now:NOW});assert.deepEqual(plan.focusIds,['SLEEP_QUALITY']);assert.ok(plan.proposedActions.every(a=>!a.focusIds.includes('ACTIVITY_LEVEL')))});
