import test from 'node:test';
import assert from 'node:assert/strict';
import * as Discovery from '../../intelligence/discovery/discovery-engine.js';
import { answerEffects } from '../../intelligence/discovery/observationNormalizer.js';
import { prioritizeCandidates,PRIORITIZATION_OUTCOME } from '../../intelligence/prioritization/prioritization.js';
import { confirmFocus, applyFocusConfirmation, focusConfirmationPlanningInput } from '../../intelligence/prioritization/focus-confirmation.js';
import { buildPlan } from '../../intelligence/planning/planningEngine.js';
import { createActionRegistry } from '../../intelligence/planning/action-registry.js';
import { discoveryOutputToMemberState } from '../../intelligence/state/discovery-member-state-adapter.js';
import { applyContextModifierToMemberState } from '../../intelligence/state/context-modifier-state.js';
import { activeContextModifierRefs } from '../../intelligence/state/context-modifier-lifecycle.js';

const NOW='2026-09-02T12:00:00.000Z';
function answerWithStateEvidence(question){const establishing=question.options.find(option=>answerEffects(question,option.id).some(effect=>['EVIDENCE','STATE'].includes(String(effect['Effect Type']).toUpperCase())));return establishing?.id??question.options.find(option=>answerEffects(question,option.id).length>0)?.id??question.options[0]?.id}
function answerBaseline(session,matrix,{physical='Difficult'}={}){assert.equal(matrix.type,'matrix');for(const question of matrix.questions){const desired=String(question.dimension).toUpperCase()==='PHYSICAL'?physical:'Going well';const option=question.options.find(item=>item.text===desired);assert.ok(option);Discovery.answer(session,question,option.id)}}
function answerConcern(session,step,answerId='A000013'){assert.equal(step.type,'question');assert.equal(step.question.id,'Q000001');Discovery.answer(session,step.question,answerId)}
function establishActivity(){const session=Discovery.session();let step=Discovery.next(session);answerBaseline(session,step);step=Discovery.next(session);answerConcern(session,step);step=Discovery.next(session);assert.equal(step.type,'driver-triage');const driver=step.questions.find(q=>q.id==='Q000085');assert.ok(driver);Discovery.answer(session,driver,'A000549');let state=Discovery.trace(session).states.find(x=>x.constructId==='ACTIVITY_LEVEL');for(let guard=0;guard<8&&state?.resolutionState!=='sufficient';guard++){step=Discovery.next(session);assert.equal(step.type,'question');Discovery.answer(session,step.question,answerWithStateEvidence(step.question));state=Discovery.trace(session).states.find(x=>x.constructId==='ACTIVITY_LEVEL')}Discovery.complete(session);return{session,state:Discovery.trace(session).states.find(x=>x.constructId==='ACTIVITY_LEVEL')}}
function activityPipeline({decision='accepted',safetyDisposition='ordinary_flow',planningContext={},planningOptions={}}={}){const{session,state}=establishActivity();assert.equal(state.qualitativeConfidence,'WELL_SUPPORTED');assert.equal(state.resolutionState,'sufficient');const memberState=discoveryOutputToMemberState({trace:{states:[state]}},{memberId:'member:g02-adversarial',at:NOW});const prioritization=prioritizeCandidates({memberStateRevision:memberState.revision,candidates:[{constructId:'ACTIVITY_LEVEL',status:state.status,evidenceRefs:state.evidenceRefs}]},{now:NOW});const confirmation=confirmFocus({prioritization,decisions:[{constructId:'ACTIVITY_LEVEL',decision}],decidedAt:NOW});const confirmedMemberState=applyFocusConfirmation(memberState,confirmation);const input=focusConfirmationPlanningInput(confirmation,{memberState:confirmedMemberState,evidenceRefs:state.evidenceRefs,safetyDisposition,planningContext});return{session,state,memberState,confirmedMemberState,prioritization,confirmation,input,plan:buildPlan(input,{now:NOW,...planningOptions})}}

test('G02 adversarial happy path preserves qualitative authority through Member State and produces an explainable plan',()=>{const x=activityPipeline();assert.equal(x.memberState.constructs.ACTIVITY_LEVEL.evidenceConfidence,'WELL_SUPPORTED');assert.equal(x.prioritization.blockedBySafety,false);assert.equal(x.confirmation.accepted.length,1);assert.equal(x.input.memberStateRevision,x.confirmedMemberState.revision);assert.equal(x.plan.status,'proposed');assert.ok(x.plan.proposedActions.length>=1);assert.equal(x.plan.shadow.authoritative,false);assert.ok(x.plan.decisionTrace.whyThis.length);assert.ok(x.plan.decisionTrace.evidenceRefs.length)});
test('G02 adversarial unknown evidence cannot become a healthy/supported fact or a plan',()=>{const session=Discovery.session({constructIds:['ACTIVITY_LEVEL'],outerGuardrail:2});let step=Discovery.next(session);answerBaseline(session,step,{physical:'Going well'});step=Discovery.next(session);answerConcern(session,step);step=Discovery.next(session);assert.equal(step.type,'finish');const state=Discovery.trace(session).states.find(x=>x.constructId==='ACTIVITY_LEVEL');assert.notEqual(state?.qualitativeConfidence,'WELL_SUPPORTED');assert.notEqual(state?.status,'established');assert.notEqual(state?.status,'supported');assert.equal(step.stop.incomplete,true)});
test('G02 adversarial Safety override prevents Prioritization authority and Planning Actions',()=>{const{state}=establishActivity();const p=prioritizeCandidates({memberStateRevision:1,candidates:[{constructId:'ACTIVITY_LEVEL',status:state.status,evidenceRefs:state.evidenceRefs}]},{now:NOW,safetyDisposition:{disposition:'pause_ordinary_flow'}});assert.equal(p.blockedBySafety,true);assert.deepEqual(p.recommended,[]);assert.equal(p.shadow,null);const plan=buildPlan({memberStateRevision:1,focuses:[{constructId:'ACTIVITY_LEVEL',decision:'accepted'}],evidenceRefs:state.evidenceRefs,constraintRefs:[],safetyDisposition:'pause_ordinary_flow',planningContext:{}},{now:NOW});assert.equal(plan.status,'blocked');assert.deepEqual(plan.proposedActions,[])});
test('G02 adversarial member rejection is authoritative even when EL8 recommended the focus',()=>{const x=activityPipeline({decision:'rejected'});assert.equal(x.prioritization.recommended[0].constructId,'ACTIVITY_LEVEL');assert.equal(x.confirmation.accepted.length,0);assert.equal(x.confirmation.memberChangedRecommendation,true);assert.equal(x.plan.status,'no_plan');assert.deepEqual(x.plan.proposedActions,[])});
test('G02 adversarial near-equivalent priorities expose member preference without manufacturing a core Focus',()=>{const p=prioritizeCandidates({memberStateRevision:3,candidates:[{constructId:'SLEEP_QUALITY',status:'supported',evidenceRefs:['e:sleep']},{constructId:'PRESSURE_PATTERN',status:'supported',evidenceRefs:['e:pressure']}]},{now:NOW,decisionFactors:{SLEEP_QUALITY:{urgency:.61,materiality:.61,memberImportance:.60},PRESSURE_PATTERN:{urgency:.60,materiality:.60,memberImportance:.61}}});assert.equal(p.decisionOutcome,PRIORITIZATION_OUTCOME.NEAR_EQUIVALENT);assert.ok(p.rationaleCodes.includes('member_preference_discriminator'));assert.equal(p.recommended.length,0);assert.equal(p.alternatives.length,2);assert.ok(p.alternatives.every(x=>x.rationaleCodes.includes('near_equivalent_member_preference')));assert.equal(p.shadow.authoritative,false);assert.ok(p.alternatives.every(x=>!('score'in x)))});
test('G02 adversarial Planning hard gate defeats a high quantitative Subcon recommendation',()=>{const action=createActionRegistry().forConstruct('ACTIVITY_LEVEL')[0];assert.ok(action);const planningContext={byConstruct:{ACTIVITY_LEVEL:{mechanismMatch:1,feasibility:1,memberPreference:1,actionability:1,priorLearning:1,decisionValue:1,evidenceStrength:1,discrimination:1,recencyRelevance:1,sufficiency:1,corroboration:1,byAction:{[action.actionId]:{requiredEvidenceSatisfied:false,mechanismMatch:1,feasibility:1,actionability:1,decisionValue:1,evidenceStrength:1,sufficiency:1}}}}};const x=activityPipeline({planningContext,planningOptions:{preferredActionIds:[action.actionId]}});assert.ok(!x.plan.proposedActions.some(a=>a.actionId===action.actionId));assert.ok(x.plan.decisionTrace.whyNot.some(item=>item.actionId===action.actionId&&item.reasonCodes.includes('hard_gate:requiredEvidence')))});
test('G02 adversarial time-bounded modifier changes Planning context without manufacturing a concern',()=>{const x=activityPipeline();let state=x.confirmedMemberState;const before=Object.keys(state.constructs);state=applyContextModifierToMemberState(state,{modifierId:'injury:knee:1',type:'INJURY',value:{site:'knee',limitation:'temporary'},sourceType:'member_report',sourceRef:'discovery:context',knownSince:'2026-08-20T00:00:00.000Z',expectedReviewAt:'2026-09-10T00:00:00.000Z',materialToPlanning:true},{source:'discovery',at:NOW,expectedRevision:state.revision});assert.deepEqual(Object.keys(state.constructs),before);const refs=activeContextModifierRefs(state.memberContext.contextModifiers);assert.deepEqual(refs,['context_modifier:injury:knee:1']);const input=focusConfirmationPlanningInput(x.confirmation,{memberState:state,evidenceRefs:x.state.evidenceRefs,safetyDisposition:'ordinary_flow',planningContext:{contextModifierRefs:refs}});assert.deepEqual(input.planningContext.contextModifierRefs,refs);assert.equal(input.memberStateRevision,state.revision)});
test('G02 adversarial zero capacity can legitimately produce zero Actions without fabricating coverage',()=>{const x=activityPipeline({planningOptions:{burdenBudget:0}});assert.equal(x.plan.status,'no_plan');assert.deepEqual(x.plan.proposedActions,[]);assert.deepEqual(x.plan.uncoveredFocusIds,['ACTIVITY_LEVEL']);assert.equal(x.plan.burden.used,0)});
