create table if not exists public.el8_qa_runs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  member_code text,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  status text not null default 'active' check (status in ('active','completed','abandoned')),
  app_commit text,
  context jsonb not null default '{}'::jsonb
);

create table if not exists public.el8_qa_events (
  id bigint generated by default as identity primary key,
  run_id uuid not null references public.el8_qa_runs(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  occurred_at timestamptz not null default now(),
  event_type text not null,
  step text,
  payload jsonb not null default '{}'::jsonb
);

create index if not exists el8_qa_events_run_time_idx on public.el8_qa_events(run_id, occurred_at);

alter table public.el8_qa_runs enable row level security;
alter table public.el8_qa_events enable row level security;

create policy "qa testers own runs" on public.el8_qa_runs for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "qa testers own events" on public.el8_qa_events for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
