import assert from 'node:assert/strict';
import { ACTION_DEFINITIONS, createActionRegistry } from './action-registry.js';

assert.equal(ACTION_DEFINITIONS.length,41);
assert.equal(new Set(ACTION_DEFINITIONS.map(x=>x.actionId)).size,41);
for(const action of ACTION_DEFINITIONS){
 assert.match(action.actionId,/^ACT\d{6}$/);
 assert.ok(action.trackingRequirement,`${action.actionId} tracking required`);assert.ok(action.iconKey,`${action.actionId} icon required`);assert.ok(action.permittedRationaleClaim,`${action.actionId} claim ceiling required`);assert.ok(action.evidenceReviewStatus,`${action.actionId} evidence review status required`);assert.ok(action.review.trigger,`${action.actionId} review trigger required`);assert.ok(action.measurement.decisionUse,`${action.actionId} decision-use measurement required`);assert.equal(action.measurement.trackingContractId,action.trackingRequirement,`${action.actionId} measurement handoff must retain governed tracking contract`);assert.deepEqual(action.measurement.requiredReviewSignals,['adherence','outcome'],`${action.actionId} Review must receive distinct attempt and outcome requirements`);assert.equal(action.measurement.additionalAssessmentTrigger,action.additionalAssessmentRequirement,`${action.actionId} measurement handoff must retain additional-assessment trigger`);assert.notEqual(String(action.review.trigger).trim().toLowerCase(),'7 days',`${action.actionId} review timing must be decision-driven, not universally hard-coded to seven days`);assert.ok(!/generic.*check.?in/i.test(`${action.instruction||''} ${action.trackingRequirement||''}`),`${action.actionId} must not use generic check-ins instead of decision-useful measurement`);if(action.actionScope==='construct')assert.ok(action.constructIds.length>0,`${action.actionId} construct mapping required`);if(action.actionScope==='plan')assert.equal(action.constructIds.length,0,`${action.actionId} plan Action must not fake construct relevance`);
}
const byId=Object.fromEntries(ACTION_DEFINITIONS.map(x=>[x.actionId,x]));
assert.equal(byId.ACT000015.status,'unsupported_experimental');assert.equal(byId.ACT000031.status,'deferred');assert.equal(byId.ACT000036.name,'Reduce plan to one primary action');assert.equal(byId.ACT000003.actionScope,'plan');
const registry=createActionRegistry();let r=registry.eligibleFor({focusIds:['ACTIVITY_LEVEL']});assert.ok(r.eligible.some(x=>x.actionId==='ACT000002'));assert.ok(r.rejected.find(x=>x.actionId==='ACT000036').reasonCodes.includes('requires_explicit_planning_condition'));r=registry.eligibleFor({focusIds:['ACTIVITY_LEVEL'],approvedPlanActionIds:['ACT000036']});assert.ok(r.eligible.some(x=>x.actionId==='ACT000036'));
const relationshipAvailable=registry.forConstruct('RELATIONSHIP_STRAIN');assert.ok(relationshipAvailable.some(x=>x.actionId==='ACT000013'));assert.ok(!relationshipAvailable.some(x=>x.actionId==='ACT000015'));assert.ok(registry.forConstruct('RELATIONSHIP_STRAIN',{includeUnavailable:true}).some(x=>x.actionId==='ACT000015'));
assert.equal(registry.forConstruct('COGNITIVE_ENGAGEMENT').length,0);assert.equal(registry.forConstruct('COGNITIVE_ENGAGEMENT',{includeUnavailable:true})[0].actionId,'ACT000031');
console.log('All 41 Drive Actions retain governed tracking, measurement and Review handoff contracts without legacy alias authority');
