import assert from 'node:assert/strict';
import {decidePlanAdaptation} from './adaptation-policy.js';
const r=adaptation=>({decision:{adaptation}});
assert.equal(decidePlanAdaptation([]).adaptation,'observe');
assert.equal(decidePlanAdaptation([r('reassess')]).adaptation,'observe','one poor review must not churn the plan');
assert.deepEqual(decidePlanAdaptation([r('reassess'),r('reassess')]),{adaptation:'reassess',reason:'repeated_poor_outcome_despite_adherence',automatic:false,requiresConfirmation:true});
assert.equal(decidePlanAdaptation([r('simplify_or_reschedule'),r('simplify_or_reschedule')]).adaptation,'modify');
assert.equal(decidePlanAdaptation([r('maintain'),r('maintain')]).adaptation,'maintain');
assert.equal(decidePlanAdaptation([r('deepen_measurement')]).reason,'measurement_insufficient');
assert.deepEqual(decidePlanAdaptation([r('maintain'),r('escalate')]),{adaptation:'safety_hold',reason:'safety_change',automatic:true});
assert.equal(decidePlanAdaptation([r('reprioritize')]).requiresConfirmation,true);
console.log('bounded adaptation policy tests passed');
