// Canonical Discovery → Planning boundary.
// Discovery owns evidence and focus; Planning owns intervention selection.
const freeze=x=>Object.freeze(x);
const IMMEDIACY_TO_URGENCY=freeze({routine:1,'time-sensitive':3,acute:5});
const IMPORTANCE_TO_NUMBER=freeze({low:1,moderate:2,high:4,'very-high':5});
const CONCERN_TO_DRIVER=freeze({money:'money_pressure',work:'work_instability',sleep:'poor_sleep',health:'low_activity',energy:'low_energy',focus:'low_focus',relationships:'relationship_strain',support:'low_support',home:'home_instability',direction:'lack_direction'});
export const planningDriverId=concernId=>CONCERN_TO_DRIVER[concernId]||concernId;
const importanceNumber=v=>Number.isFinite(Number(v))?Math.max(1,Math.min(5,Number(v)+1)):IMPORTANCE_TO_NUMBER[v]??null;
export function concernToPlanningDriver(state={}){if(!state.concernId)throw new Error('concernId required');return freeze({id:planningDriverId(state.concernId),sourceConcernId:state.concernId,confidence:state.evidenceConfidence??state.confidence??null,memberImportance:importanceNumber(state.memberImportance),memberPrioritySelected:Boolean(state.memberPrioritySelected||state.memberSelected),urgency:IMMEDIACY_TO_URGENCY[state.immediacyClass]??null,readiness:state.readiness??null,feasibility:state.feasibility??freeze({constraints:freeze([]),supports:freeze([]),values:freeze({}),evidenceRefs:freeze([])}),temporality:state.temporality??'unknown',specificityFrontier:state.specificityFrontier??0,discoveryResolutionState:state.resolutionState??null,safetyEscalationLevel:state.safetyEscalationLevel??0,evidenceRefs:freeze([...(state.evidenceRefs||[])])})}
export function buildPlanningHandoff(priorityResult={}){const selected=priorityResult.selected||[],backlog=priorityResult.backlog||[];return freeze({contractVersion:'discovery-planning-v1',ranked:freeze(selected.map(concernToPlanningDriver)),discoveryBacklog:freeze(backlog.map(concernToPlanningDriver)),semantics:freeze({id:'Planning driver translated once from the confirmed Discovery focus.',sourceConcernId:'Original Discovery concern retained for traceability.',confidence:'Discovery evidence confidence; Planning thresholds but does not recompute it.',memberImportance:'Member-stated importance normalized only at this boundary.',memberPrioritySelected:'Explicit member choice; never inferred by Planning.',urgency:'Mechanical projection of Discovery immediacy.',readiness:'Discovery-derived readiness used only for action eligibility/fit.',feasibility:'Discovery-derived constraints, supports and capacity.',safetyEscalationLevel:'Discovery safety signal; safety routing remains upstream.'})})}
