// Canonical Discovery → Planning boundary.
// Discovery owns evidence and focus; Planning owns intervention selection.
import {canonicalProblemId} from './problem-registry-adapter.js';
const freeze=x=>Object.freeze(x);
const IMMEDIACY_TO_URGENCY=freeze({routine:1,'time-sensitive':3,acute:5});
const IMPORTANCE_TO_NUMBER=freeze({low:1,moderate:2,high:4,'very-high':5});
const CONCERN_TO_PROBLEM=freeze({money:'P03',work:'P05',sleep:'P02',health:'P01',focus:'P04',support:'P07',home:'P08'});
export const planningProblemId=concernId=>CONCERN_TO_PROBLEM[concernId]||canonicalProblemId(concernId);
const importanceNumber=v=>Number.isFinite(Number(v))?Math.max(1,Math.min(5,Number(v)+1)):IMPORTANCE_TO_NUMBER[v]??null;
export function concernToPlanningProblem(state={}){if(!state.concernId)throw new Error('concernId required');const problemId=planningProblemId(state.concernId);if(!problemId)throw new Error(`No canonical planning problem for concern: ${state.concernId}`);return freeze({id:problemId,problem_id:problemId,sourceConcernId:state.concernId,confidence:state.evidenceConfidence??state.confidence??null,memberImportance:importanceNumber(state.memberImportance),memberPrioritySelected:Boolean(state.memberPrioritySelected||state.memberSelected),urgency:IMMEDIACY_TO_URGENCY[state.immediacyClass]??null,readiness:state.readiness??null,feasibility:state.feasibility??freeze({constraints:freeze([]),supports:freeze([]),values:freeze({}),evidenceRefs:freeze([])}),temporality:state.temporality??'unknown',specificityFrontier:state.specificityFrontier??0,discoveryResolutionState:state.resolutionState??null,safetyEscalationLevel:state.safetyEscalationLevel??0,evidenceRefs:freeze([...(state.evidenceRefs||[])])})}
// Temporary alias for downstream imports during the canonical-ID migration.
export const concernToPlanningDriver=concernToPlanningProblem;
export const planningDriverId=planningProblemId;
export function buildPlanningHandoff(priorityResult={}){const selected=priorityResult.selected||[],backlog=priorityResult.backlog||[];return freeze({contractVersion:'discovery-planning-v2',ranked:freeze(selected.map(concernToPlanningProblem)),discoveryBacklog:freeze(backlog.map(concernToPlanningProblem)),semantics:freeze({id:'Canonical Problem Registry ID for the confirmed Discovery focus.',problem_id:'Canonical Problem Registry ID; authoritative for Planning.',sourceConcernId:'Original Discovery concern retained only for traceability.',confidence:'Discovery evidence confidence; Planning thresholds but does not recompute it.',memberImportance:'Member-stated importance normalized only at this boundary.',memberPrioritySelected:'Explicit member choice; never inferred by Planning.',urgency:'Mechanical projection of Discovery immediacy.',readiness:'Discovery-derived readiness used only for action eligibility/fit.',feasibility:'Discovery-derived constraints, supports and capacity.',safetyEscalationLevel:'Discovery safety signal; safety routing remains upstream.'})})}
