// EL8 MVP intervention + evidence-gathering library.
// Each action is independently eligible and measurable. deepeningRequirements declare
// only post-selection facts that can materially change activation, tailoring or evaluation.

const item=(x)=>({scope:'general_wellness',eligibility:{minReadiness:1},contraindications:[],bct:[],deepeningRequirements:[],mechanism:x.type==='data'?'observation':'behavior_change',...x});
const req=(id,evidenceKey,purpose,decisionImpact,prompt,requiredBeforeActivation=true)=>({id,evidenceKey,purpose,decisionImpact,prompt,requiredBeforeActivation});

export const LIBRARY={
 poor_sleep:[item({id:'sleep_log',type:'data',mechanism:'self_monitoring',dimension:'physical',title:'Log when you sleep and wake each day',effort:1,cadence:{type:'daily',target:7,period:'week'},measurement:'Sleep start, end and optional quality',successSignal:'Produces enough recent observations to characterize the current sleep pattern.',reviewDays:7,evidenceStrength:'supported',bct:['2.3 self-monitoring of behaviour']}),item({id:'stabilize_sleep_window',type:'intervention',mechanism:'routine_stabilization',dimension:'physical',title:'Keep a more consistent sleep window',effort:2,cadence:{type:'daily',target:7,period:'week'},measurement:'Log whether sleep/wake timing stayed near the chosen window',successSignal:'Timing consistency improves without unacceptable burden.',reviewDays:7,evidenceStrength:'supported',bct:['1.4 action planning','2.3 self-monitoring of behaviour','8.3 habit formation'],deepeningRequirements:[req('sleep-baseline','baseline.sleep_window','baseline_measurement','Defines the member-specific starting pattern and permits comparison after the action.','What time have you usually been falling asleep and waking up recently?'),req('sleep-window-fit','preference.sleep_window','personalization','Changes the proposed sleep/wake window so it fits the member’s real schedule.','What sleep and wake window would be realistic for you most days?',false)]})],
 schedule_disruption:[item({id:'anchor_daily_schedule',type:'intervention',mechanism:'routine_anchor',dimension:'occupational',title:'Choose one daily anchor and log whether it happens',effort:2,cadence:{type:'daily',target:7,period:'week'},measurement:'Log whether the anchor happened',successSignal:'The chosen anchor occurs more consistently and improves perceived manageability.',reviewDays:7,evidenceStrength:'evidence_informed',bct:['1.4 action planning','7.1 prompts/cues','8.3 habit formation']})],
 stress:[item({id:'stress_check',type:'data',mechanism:'self_monitoring',dimension:'emotional',title:'Log your stress level and what was happening',effort:1,cadence:{type:'daily',target:7,period:'week'},measurement:'Stress level plus what was happening',successSignal:'Produces enough observations to identify repeatable stress contexts without assuming causality.',reviewDays:7,evidenceStrength:'evidence_informed'}),item({id:'short_decompression',type:'intervention',mechanism:'acute_recovery',dimension:'emotional',title:'Take a short decompression break on five days this week',effort:1,cadence:{type:'weekly_target',target:5,period:'week'},measurement:'Completion and stress before/after',successSignal:'Repeated completion is feasible and stress is directionally lower afterward.',reviewDays:7,evidenceStrength:'evidence_informed'})],
 low_energy:[item({id:'energy_observation',type:'data',mechanism:'self_monitoring',dimension:'physical',title:'Log when your energy drops and what came before it',effort:1,cadence:{type:'daily',target:7,period:'week'},measurement:'Low-energy time and preceding activity',successSignal:'Produces enough observations to identify candidate patterns for later testing.',reviewDays:7,evidenceStrength:'evidence_informed'})],
 low_focus:[item({id:'focus_pattern_log',type:'data',mechanism:'self_monitoring',dimension:'occupational',title:'Log when focus feels easiest and hardest',effort:1,cadence:{type:'weekly_target',target:3,period:'week'},measurement:'Time, task and context when focus was strong or weak',successSignal:'Produces enough observations to identify candidate focus conditions.',reviewDays:7,evidenceStrength:'evidence_informed'}),item({id:'protected_focus_block',type:'intervention',mechanism:'environmental_protection',dimension:'occupational',title:'Protect one focus block three times this week',effort:2,cadence:{type:'weekly_target',target:3,period:'week'},measurement:'Log completion and approximate duration',successSignal:'Protected blocks are completed at a sustainable rate and support useful work.',reviewDays:7,evidenceStrength:'evidence_informed'})],
 low_activity:[item({id:'activity_baseline',type:'data',mechanism:'self_monitoring',dimension:'physical',title:'Log the minutes you intentionally walk or exercise each day',effort:1,cadence:{type:'daily',target:7,period:'week'},measurement:'Record intentional movement and approximate duration',successSignal:'Produces a usable recent movement baseline.',reviewDays:7,evidenceStrength:'supported'}),item({id:'walk',type:'intervention',mechanism:'graded_activity',dimension:'physical',title:'Take a walk three times this week',effort:2,cadence:{type:'weekly_target',target:3,period:'week'},measurement:'Log walk completion and approximate duration',successSignal:'Walking occurs at a sustainable frequency without unacceptable burden.',reviewDays:7,evidenceStrength:'supported'}),item({id:'strength_activity',type:'intervention',mechanism:'graded_activity',dimension:'physical',title:'Complete two strength-training sessions this week',effort:3,cadence:{type:'weekly_target',target:2,period:'week'},measurement:'Log completed session',successSignal:'Sessions are completed sustainably without new contraindication or unacceptable burden.',reviewDays:7,evidenceStrength:'supported',eligibility:{minReadiness:2}})],
 work_instability:[item({id:'work_barrier_snapshot',type:'data',mechanism:'problem_clarification',dimension:'occupational',title:'Write down your main work or income barrier',effort:1,cadence:{type:'one_time',target:1,period:'once'},measurement:'Record the main barrier and one factor affecting it',successSignal:'Produces a member-confirmed barrier specific enough to guide the next action.',reviewDays:7,evidenceStrength:'evidence_informed'}),item({id:'income_action',type:'intervention',mechanism:'direct_action',dimension:'occupational',title:'Take two concrete income actions this week',effort:3,cadence:{type:'weekly_target',target:2,period:'week'},measurement:'Record completed action and result',successSignal:'Concrete income actions are completed and produce interpretable results or learning.',reviewDays:7,evidenceStrength:'evidence_informed'})],
 money_pressure:[item({id:'money_snapshot',type:'data',mechanism:'problem_clarification',dimension:'financial',title:'List your available cash, required payments and due dates',effort:2,cadence:{type:'one_time',target:1,period:'once'},measurement:'Available cash, required payments and due dates',successSignal:'Produces a current snapshot sufficient to identify the next manageable financial decision.',reviewDays:7,evidenceStrength:'evidence_informed'}),item({id:'financial_next_step',type:'intervention',mechanism:'direct_action',dimension:'financial',title:'Complete one manageable financial action this week',effort:2,cadence:{type:'weekly_target',target:1,period:'week'},measurement:'Record the action taken and immediate result',successSignal:'A feasible financial action is completed and its immediate result is known.',reviewDays:7,evidenceStrength:'evidence_informed'})],
 relationship_strain:[item({id:'relationship_context_log',type:'data',mechanism:'self_monitoring',dimension:'social',title:'Log three moments when relationship strain shows up',effort:1,cadence:{type:'weekly_target',target:3,period:'week'},measurement:'Record situation, trigger and outcome without diagnosing motive',successSignal:'Produces enough observations to identify repeatable contexts without inferring another person’s motives.',reviewDays:7,evidenceStrength:'evidence_informed'}),item({id:'relationship_repair_step',type:'intervention',mechanism:'direct_action',dimension:'social',title:'Take one relationship repair step',effort:3,cadence:{type:'one_time',target:1,period:'once'},measurement:'Record action and result',successSignal:'A member-chosen repair step is attempted and its result can be reviewed.',reviewDays:7,evidenceStrength:'evidence_informed',eligibility:{minReadiness:2}})],
 low_support:[item({id:'support_map',type:'data',mechanism:'resource_mapping',dimension:'social',title:'Identify one person or service you could realistically turn to',effort:1,cadence:{type:'one_time',target:1,period:'once'},measurement:'Identify at least one available source of practical or emotional support',successSignal:'Identifies at least one realistic support option or establishes that none is currently available.',reviewDays:7,evidenceStrength:'supported'}),item({id:'support_contact',type:'intervention',mechanism:'social_connection',dimension:'social',title:'Make one meaningful support contact this week',effort:2,cadence:{type:'weekly_target',target:1,period:'week'},measurement:'Log one meaningful support contact',successSignal:'A member-selected support contact occurs and its usefulness can be reviewed.',reviewDays:7,evidenceStrength:'supported'})],
 home_instability:[item({id:'environment_barrier_log',type:'data',mechanism:'problem_clarification',dimension:'environmental',title:'Write down the home or environment barrier affecting you most',effort:1,cadence:{type:'one_time',target:1,period:'once'},measurement:'Record the barrier and how it interferes with the current plan',successSignal:'Produces one concrete member-confirmed environmental barrier suitable for action.',reviewDays:7,evidenceStrength:'evidence_informed'}),item({id:'home_stability_step',type:'intervention',mechanism:'environmental_change',dimension:'environmental',title:'Take one step to reduce a home or environment barrier',effort:3,cadence:{type:'one_time',target:1,period:'once'},measurement:'Record completed stability action',successSignal:'One member-selected environmental barrier is materially reduced or clarified.',reviewDays:7,evidenceStrength:'evidence_informed'})],
 lack_direction:[item({id:'values_prompt',type:'data',mechanism:'values_clarification',dimension:'spiritual',title:'Write down what matters most to you right now',effort:1,cadence:{type:'one_time',target:1,period:'once'},measurement:'Record one value or direction that currently matters',successSignal:'Produces a member-stated value or direction specific enough to guide a next step.',reviewDays:7,evidenceStrength:'evidence_informed'}),item({id:'direction_next_step',type:'intervention',mechanism:'values_aligned_action',dimension:'spiritual',title:'Complete one step tied to what matters most this week',effort:2,cadence:{type:'weekly_target',target:1,period:'week'},measurement:'Complete one step tied to what matters now',successSignal:'A member-chosen step connected to a stated value is completed or yields useful learning.',reviewDays:7,evidenceStrength:'evidence_informed'})]
};
export function candidatesForDriver(driverId){return(LIBRARY[driverId]||[]).map(x=>({...x,cadence:{...x.cadence},eligibility:{...x.eligibility},contraindications:[...x.contraindications],bct:[...x.bct],deepeningRequirements:(x.deepeningRequirements||[]).map(r=>({...r}))}));}
export function allLibraryItems(){return Object.entries(LIBRARY).flatMap(([driver,items])=>items.map(item=>({driver,...item,cadence:{...item.cadence},eligibility:{...item.eligibility},contraindications:[...item.contraindications],bct:[...item.bct],deepeningRequirements:(item.deepeningRequirements||[]).map(r=>({...r}))})));}
