// EL8 MVP intervention + evidence-gathering library.
// Each action is independently eligible and measurable. deepeningRequirements declare
// only post-selection facts that can materially change activation, tailoring or evaluation.

const item=(x)=>({scope:'general_wellness',eligibility:{minReadiness:1},contraindications:[],bct:[],deepeningRequirements:[],...x});
const req=(id,evidenceKey,purpose,decisionImpact,prompt,requiredBeforeActivation=true)=>({id,evidenceKey,purpose,decisionImpact,prompt,requiredBeforeActivation});

export const LIBRARY={
 poor_sleep:[
  item({id:'sleep_log',type:'data',dimension:'physical',title:'Log your sleep',effort:1,cadence:{type:'daily',target:7,period:'week'},measurement:'Sleep start, end and optional quality',successSignal:'Produces enough recent observations to characterize the current sleep pattern.',reviewDays:7,evidenceStrength:'supported',bct:['2.3 self-monitoring of behaviour']}),
  item({id:'stabilize_sleep_window',type:'intervention',dimension:'physical',title:'Keep a more consistent sleep window',effort:2,cadence:{type:'daily',target:7,period:'week'},measurement:'Log whether sleep/wake timing stayed near the chosen window',successSignal:'Timing consistency improves without unacceptable burden.',reviewDays:7,evidenceStrength:'supported',bct:['1.4 action planning','2.3 self-monitoring of behaviour','8.3 habit formation'],deepeningRequirements:[req('sleep-baseline','baseline.sleep_window','baseline_measurement','Defines the member-specific starting pattern and permits comparison after the action.','What time have you usually been falling asleep and waking up recently?'),req('sleep-window-fit','preference.sleep_window','personalization','Changes the proposed sleep/wake window so it fits the member’s real schedule.','What sleep and wake window would be realistic for you most days?',false)]})
 ],
 schedule_disruption:[item({id:'anchor_daily_schedule',type:'intervention',dimension:'occupational',title:'Create one daily anchor',effort:2,cadence:{type:'daily',target:7,period:'week'},measurement:'Log whether the anchor happened',successSignal:'The chosen anchor occurs more consistently and improves perceived manageability.',reviewDays:7,evidenceStrength:'evidence_informed',bct:['1.4 action planning','7.1 prompts/cues','8.3 habit formation'],deepeningRequirements:[req('anchor-choice','schedule.anchor_candidate','personalization','Determines which recurring event is feasible enough to use as the anchor.','Which part of your day is most predictable right now?',false)]})],
 stress:[
  item({id:'stress_check',type:'data',dimension:'emotional',title:'Log stress and context',effort:1,cadence:{type:'daily',target:7,period:'week'},measurement:'Stress level plus what was happening',successSignal:'Produces enough observations to identify repeatable stress contexts without assuming causality.',reviewDays:7,evidenceStrength:'evidence_informed',bct:['2.4 self-monitoring of outcomes','4.2 information about antecedents']}),
  item({id:'short_decompression',type:'intervention',dimension:'emotional',title:'Use a short decompression block',effort:1,cadence:{type:'weekly_target',target:5,period:'week'},measurement:'Completion and stress before/after',successSignal:'Repeated completion is feasible and stress is directionally lower afterward.',reviewDays:7,evidenceStrength:'evidence_informed',bct:['1.4 action planning','2.4 self-monitoring of outcomes'],deepeningRequirements:[req('decompression-context','stress.decompression_window','personalization','Determines when the decompression action is most feasible and relevant.','When would a short decompression break fit most naturally?',false)]})
 ],
 low_energy:[item({id:'energy_observation',type:'data',dimension:'physical',title:'Track when energy drops',effort:1,cadence:{type:'daily',target:7,period:'week'},measurement:'Low-energy time and preceding activity',successSignal:'Produces enough observations to identify candidate patterns for later testing.',reviewDays:7,evidenceStrength:'evidence_informed',bct:['2.4 self-monitoring of outcomes','4.2 information about antecedents']})],
 low_focus:[
  item({id:'focus_pattern_log',type:'data',dimension:'occupational',title:'Track when focus is easiest and hardest',effort:1,cadence:{type:'weekly_target',target:3,period:'week'},measurement:'Time, task and context when focus was strong or weak',successSignal:'Produces enough observations to identify candidate focus conditions.',reviewDays:7,evidenceStrength:'evidence_informed',bct:['2.3 self-monitoring of behaviour','4.2 information about antecedents']}),
  item({id:'protected_focus_block',type:'intervention',dimension:'occupational',title:'Protect one focus block',effort:2,cadence:{type:'weekly_target',target:3,period:'week'},measurement:'Log completion and approximate duration',successSignal:'Protected blocks are completed at a sustainable rate and support useful work.',reviewDays:7,evidenceStrength:'evidence_informed',bct:['1.4 action planning','12.1 restructuring physical environment'],deepeningRequirements:[req('focus-window','focus.best_available_window','personalization','Determines when a protected block is realistically schedulable.','When is the most realistic time for a protected focus block?',false)]})
 ],
 low_activity:[
  item({id:'activity_baseline',type:'data',dimension:'physical',title:'Track your intentional movement',effort:1,cadence:{type:'daily',target:7,period:'week'},measurement:'Record intentional movement and approximate duration',successSignal:'Produces a usable recent movement baseline.',reviewDays:7,evidenceStrength:'supported',bct:['2.3 self-monitoring of behaviour']}),
  item({id:'walk',type:'intervention',dimension:'physical',title:'Go for a walk',effort:2,cadence:{type:'weekly_target',target:3,period:'week'},measurement:'Log walk completion and approximate duration',successSignal:'Walking occurs at a sustainable frequency without unacceptable burden.',reviewDays:7,evidenceStrength:'supported',bct:['1.1 goal setting behaviour','1.4 action planning','2.3 self-monitoring of behaviour','8.7 graded tasks'],deepeningRequirements:[req('walk-dose','activity.walk_starting_dose','personalization','Changes the starting duration/frequency so the action fits current ability and capacity.','What walk duration feels comfortably realistic right now?',false)]}),
  item({id:'strength_activity',type:'intervention',dimension:'physical',title:'Do a strength-training session',effort:3,cadence:{type:'weekly_target',target:2,period:'week'},measurement:'Log completed session',successSignal:'Sessions are completed sustainably without new contraindication or unacceptable burden.',reviewDays:7,evidenceStrength:'supported',eligibility:{minReadiness:2},bct:['1.1 goal setting behaviour','1.4 action planning','2.3 self-monitoring of behaviour','8.7 graded tasks'],deepeningRequirements:[req('strength-access','activity.strength_access','eligibility','Determines whether the proposed strength action is feasible with available environment/equipment.','What strength-training equipment or space do you realistically have access to?')]})
 ],
 work_instability:[
  item({id:'work_barrier_snapshot',type:'data',dimension:'occupational',title:'Identify the main work or income barrier',effort:1,cadence:{type:'one_time',target:1,period:'once'},measurement:'Record the main barrier and one factor affecting it',successSignal:'Produces a member-confirmed barrier specific enough to guide the next action.',reviewDays:7,evidenceStrength:'evidence_informed',bct:['1.2 problem solving']}),
  item({id:'income_action',type:'intervention',dimension:'occupational',title:'Take one concrete income action',effort:3,cadence:{type:'weekly_target',target:2,period:'week'},measurement:'Record completed action and result',successSignal:'Concrete income actions are completed and produce interpretable results or learning.',reviewDays:7,evidenceStrength:'evidence_informed',bct:['1.1 goal setting behaviour','1.4 action planning','2.3 self-monitoring of behaviour'],deepeningRequirements:[req('income-route','work.current_income_route','personalization','Determines which type of income action is relevant rather than generating a generic task.','Which income route are you actively willing to pursue right now?')]})
 ],
 money_pressure:[
  item({id:'money_snapshot',type:'data',dimension:'financial',title:'Create a current money snapshot',effort:2,cadence:{type:'one_time',target:1,period:'once'},measurement:'Available cash, required payments and due dates',successSignal:'Produces a current snapshot sufficient to identify the next manageable financial decision.',reviewDays:7,evidenceStrength:'evidence_informed',bct:['2.4 self-monitoring of outcomes']}),
  item({id:'financial_next_step',type:'intervention',dimension:'financial',title:'Take one manageable financial next step',effort:2,cadence:{type:'weekly_target',target:1,period:'week'},measurement:'Record the action taken and immediate result',successSignal:'A feasible financial action is completed and its immediate result is known.',reviewDays:7,evidenceStrength:'evidence_informed',bct:['1.2 problem solving','1.4 action planning'],deepeningRequirements:[req('money-baseline','financial.current_snapshot','baseline_measurement','Determines which financial action is actually relevant and provides the starting state for review.','What are the key numbers or obligations that matter for this financial step right now?')]})
 ],
 relationship_strain:[
  item({id:'relationship_context_log',type:'data',dimension:'social',title:'Notice when relationship strain shows up',effort:1,cadence:{type:'weekly_target',target:3,period:'week'},measurement:'Record situation, trigger and outcome without diagnosing motive',successSignal:'Produces enough observations to identify repeatable contexts without inferring another person’s motives.',reviewDays:7,evidenceStrength:'evidence_informed',bct:['2.4 self-monitoring of outcomes','4.2 information about antecedents']}),
  item({id:'relationship_repair_step',type:'intervention',dimension:'social',title:'Take one relationship repair step',effort:3,cadence:{type:'one_time',target:1,period:'once'},measurement:'Record action and result',successSignal:'A member-chosen repair step is attempted and its result can be reviewed.',reviewDays:7,evidenceStrength:'evidence_informed',eligibility:{minReadiness:2},bct:['1.4 action planning','3.3 social support emotional'],deepeningRequirements:[req('repair-goal','relationship.repair_goal','personalization','Determines what kind of repair action is appropriate to the member’s stated goal.','What would you most like to improve in this relationship right now?')]})
 ],
 low_support:[
  item({id:'support_map',type:'data',dimension:'social',title:'Map who you can realistically turn to',effort:1,cadence:{type:'one_time',target:1,period:'once'},measurement:'Identify at least one available source of practical or emotional support',successSignal:'Identifies at least one realistic support option or establishes that none is currently available.',reviewDays:7,evidenceStrength:'supported',bct:['3.1 social support unspecified']}),
  item({id:'support_contact',type:'intervention',dimension:'social',title:'Strengthen one support connection',effort:2,cadence:{type:'weekly_target',target:1,period:'week'},measurement:'Log one meaningful support contact',successSignal:'A member-selected support contact occurs and its usefulness can be reviewed.',reviewDays:7,evidenceStrength:'supported',bct:['3.1 social support unspecified','1.4 action planning'],deepeningRequirements:[req('support-choice','support.selected_contact','personalization','Determines whom the member actually wants to contact rather than selecting for them.','Who would feel most realistic to reach out to?',false)]})
 ],
 home_instability:[
  item({id:'environment_barrier_log',type:'data',dimension:'environmental',title:'Identify one environmental barrier',effort:1,cadence:{type:'one_time',target:1,period:'once'},measurement:'Record the barrier and how it interferes with the current plan',successSignal:'Produces one concrete member-confirmed environmental barrier suitable for action.',reviewDays:7,evidenceStrength:'evidence_informed',bct:['1.2 problem solving','4.2 information about antecedents']}),
  item({id:'home_stability_step',type:'intervention',dimension:'environmental',title:'Resolve one home stability issue',effort:3,cadence:{type:'one_time',target:1,period:'once'},measurement:'Record completed stability action',successSignal:'One member-selected environmental barrier is materially reduced or clarified.',reviewDays:7,evidenceStrength:'evidence_informed',bct:['1.2 problem solving','12.1 restructuring physical environment'],deepeningRequirements:[req('home-barrier','environment.current_barrier','personalization','Determines which environmental issue the action should target.','Which home or environment issue is interfering with you most right now?')]})
 ],
 lack_direction:[
  item({id:'values_prompt',type:'data',dimension:'spiritual',title:'Clarify what matters most right now',effort:1,cadence:{type:'one_time',target:1,period:'once'},measurement:'Record one value or direction that currently matters',successSignal:'Produces a member-stated value or direction specific enough to guide a next step.',reviewDays:7,evidenceStrength:'evidence_informed',bct:['13.4 valued self-identity']}),
  item({id:'direction_next_step',type:'intervention',dimension:'spiritual',title:'Take one meaningful next step',effort:2,cadence:{type:'weekly_target',target:1,period:'week'},measurement:'Complete one step tied to what matters now',successSignal:'A member-chosen step connected to a stated value is completed or yields useful learning.',reviewDays:7,evidenceStrength:'evidence_informed',bct:['1.1 goal setting behaviour','1.4 action planning'],deepeningRequirements:[req('direction-value','values.current_direction','personalization','Ensures the action is tied to a member-stated value rather than an inferred purpose.','What matters enough right now that you would like your next step to support?')]})
 ]
};

export function candidatesForDriver(driverId){return(LIBRARY[driverId]||[]).map(x=>({...x,cadence:{...x.cadence},eligibility:{...x.eligibility},contraindications:[...x.contraindications],bct:[...x.bct],deepeningRequirements:(x.deepeningRequirements||[]).map(r=>({...r}))}));}
export function allLibraryItems(){return Object.entries(LIBRARY).flatMap(([driver,items])=>items.map(item=>({driver,...item,cadence:{...item.cadence},eligibility:{...item.eligibility},contraindications:[...item.contraindications],bct:[...item.bct],deepeningRequirements:(item.deepeningRequirements||[]).map(r=>({...r}))})));}
