import test from 'node:test';
import assert from 'node:assert/strict';
import {buildPlan,MIN_ACTION_CONFIDENCE} from './plan-engine.js';

const selectionEvidence={'baseline.sleep_pattern':'Usually 5–6 hours with inconsistent timing','baseline.activity_level':'About one short walk per week','financial.current_snapshot':'Increase income'};
const ctx=(extra={})=>({selectionEvidence,...extra});

test('material selection evidence is required before intervention choice',()=>{const plan=buildPlan({ranked:[{id:'poor_sleep',confidence:.9}]},{capacity:'medium'});assert.equal(plan.status,'deepen');assert.equal(plan.reason,'selection_evidence_required');assert.equal(plan.active.length,0);assert.equal(plan.selectionDeepening.required,true);assert.equal(plan.selectionDeepening.requirements[0].evidenceKey,'baseline.sleep_pattern');});
test('buildPlan creates at most two independently justified active actions after selection evidence',()=>{const plan=buildPlan({ranked:[{id:'poor_sleep',confidence:.9,memberImportance:5,readiness:4},{id:'low_activity',confidence:.8,memberImportance:4,readiness:4}]},ctx({capacity:'medium'}));assert.equal(plan.status,'active');assert.ok(plan.active.length<=2);assert.deepEqual(plan.decisionTrace.selectedActionIds,plan.active.map(x=>x.id));});
test('two supported confirmed focuses receive coverage before one focus receives a second action',()=>{const plan=buildPlan({ranked:[{id:'low_activity',confidence:.95,memberImportance:5,readiness:4},{id:'money_pressure',confidence:.75,memberImportance:5,readiness:4}]},ctx({capacity:'medium'}));assert.equal(plan.active.length,2);assert.deepEqual(new Set(plan.active.map(x=>x.driver)),new Set(['low_activity','money_pressure']));assert.deepEqual(plan.decisionTrace.uncoveredDrivers,[]);assert.equal(plan.decisionTrace.coverageRule,'one-action-per-supported-focus-before-second-action');});
test('low capacity hard-throttles plan to one action',()=>{const plan=buildPlan({ranked:[{id:'poor_sleep',confidence:.9},{id:'low_activity',confidence:.8}]},ctx({capacity:'low'}));assert.equal(plan.status,'active');assert.equal(plan.active.length,1);});
test('no capacity creates no active optimization action once selection evidence is complete',()=>{const plan=buildPlan({ranked:[{id:'poor_sleep',confidence:.9}]},ctx({capacity:'none'}));assert.equal(plan.reason,'capacity_hold');assert.equal(plan.active.length,0);});
test('safety and consent remain higher-order hard gates',()=>{assert.equal(buildPlan({ranked:[{id:'poor_sleep',confidence:.9}],safetyHold:true},{}).status,'escalate');assert.equal(buildPlan({ranked:[{id:'poor_sleep',confidence:.9}]},{consent:false}).reason,'member_consent_required');});
test('unsupported confidence cannot silently create action certainty or unnecessary deepening',()=>{const plan=buildPlan({ranked:[{id:'poor_sleep',confidence:MIN_ACTION_CONFIDENCE-.01}]},{});assert.equal(plan.reason,'insufficient_evidence');assert.equal(plan.active.length,0);});
test('explicitly rejected action cannot be silently reinserted',()=>{const plan=buildPlan({ranked:[{id:'low_activity',confidence:.9}]},ctx({rejectedActionIds:['walk']}));assert.equal(plan.status,'active');assert.ok(!plan.active.some(x=>x.id==='walk'));assert.deepEqual(plan.decisionTrace.rejectedActionIds,['walk']);});
test('rejecting an active action preserves the confirmed focus and recomposes to another supported action',()=>{const first=buildPlan({ranked:[{id:'low_activity',confidence:.9,memberImportance:5}]},ctx({capacity:'medium'}));assert.equal(first.status,'active');const rejected=first.active[0].id;const second=buildPlan({ranked:[{id:'low_activity',confidence:.9,memberImportance:5}]},ctx({capacity:'medium',rejectedActionIds:[rejected]}));assert.equal(second.status,'active');assert.equal(second.active[0].driver,'low_activity');assert.notEqual(second.active[0].id,rejected);assert.ok(second.decisionTrace.rejectedActionIds.includes(rejected));});
test('Review different-mechanism constraint is respected without a second adaptation engine',()=>{const plan=buildPlan({ranked:[{id:'low_activity',confidence:.9}]},ctx({capacity:'low',adaptationConstraint:'different_mechanism',previousMechanisms:['graded_activity']}));assert.equal(plan.status,'active');assert.notEqual(plan.active[0].mechanism,'graded_activity');assert.equal(plan.decisionTrace.adaptationConstraint,'different_mechanism');});
test('Review reduced-burden constraint is respected',()=>{const plan=buildPlan({ranked:[{id:'low_activity',confidence:.9}]},ctx({capacity:'low',adaptationConstraint:'reduce_burden',previousMaxEffort:1}));assert.equal(plan.status,'active');assert.ok(plan.active.every(x=>Number(x.effort)<=1));});
test('Discovery feasibility changes friction budget and evidence provenance is preserved',()=>{const low=buildPlan({ranked:[{id:'low_activity',confidence:.9,feasibility:{values:{capacity:'low'},constraints:[],supports:[]}}]},ctx());const high=buildPlan({ranked:[{id:'low_activity',confidence:.9,feasibility:{values:{capacity:'high'},constraints:[],supports:[]}}]},ctx());assert.ok(low.active[0].friction.budget<high.active[0].friction.budget);assert.equal(low.evidenceUsed[0].feasibility.values.capacity,'low');});
