// EL8 Plan Composer — canonical Problem Registry path.
import {REGISTRY,REGISTRY_VERSION} from './problem-intervention-registry.js';
import {problemHypothesesFromDiscovery,eligibleRegistryInterventions} from './problem-registry-adapter.js';
import {missingSelectionRequirements} from './selection-evidence.js';
import {applyPlanDeepening} from './plan-deepening.js';

export const MIN_ACTION_CONFIDENCE=.55;
const confidenceSufficient=h=>Number.isFinite(Number(h.confidence))&&Number(h.confidence)>=MIN_ACTION_CONFIDENCE;
const activeLimit=c=>c.capacity==='none'?0:c.capacity==='low'?1:2;
const purposeRank={ESCALATE:0,DEEPEN:1,RESOLVE:2,ACT:3,CONNECT:3,TRACK:4,LEARN:5};
const LEGACY_ACTION_IDS=Object.freeze({I01_GRADED_ACTIVITY:'walk',I01_ACTIVITY_BASELINE:'activity_baseline',I02_SLEEP_PATTERN_DEEPEN:'sleep_log',I02_SLEEP_CARE_ROUTE:'stabilize_sleep_window',I03_MONEY_SNAPSHOT:'money_snapshot',I03_FINANCIAL_NEXT_STEP:'financial_next_step',I05_FUNNEL_ACTION:'income_action',I07_VALUED_CONTACT:'support_contact',I07_ACCESS_BARRIER:'support_map',I08_REMOVE_FRICTION:'home_stability_step'});
const INTERVENTION_MECHANISMS=Object.freeze({I01_GRADED_ACTIVITY:'graded_activity',I01_ACTIVITY_BASELINE:'activity_measurement',I02_SLEEP_PATTERN_DEEPEN:'sleep_pattern_discrimination',I02_SLEEP_CARE_ROUTE:'appropriate_sleep_care',I03_MONEY_SNAPSHOT:'financial_visibility',I03_FINANCIAL_NEXT_STEP:'financial_problem_solving',I04_NEXT_ACTION:'execution_specificity',I04_REMOVE_BLOCKER:'barrier_reduction',I05_FUNNEL_ACTION:'opportunity_funnel_execution',I05_INCOME_EXPERIMENT:'income_route_experiment',I06_RESOLVE_STRESSOR:'stressor_reduction',I06_COPING_SKILL:'coping_skill_practice',I07_VALUED_CONTACT:'valued_social_contact',I07_RECURRING_CONNECTION:'repeated_social_exposure',I07_ACCESS_BARRIER:'social_access_barrier_reduction',I08_REMOVE_FRICTION:'environment_friction_reduction',I08_ADD_CUE:'environment_cueing'});
function reviewDays(rule={}){const s=String(rule.window||'').toLowerCase();const m=s.match(/(\d+)\s*[–-]\s*(\d+)\s*days?/);if(m)return Number(m[1]);const d=s.match(/(\d+)\s*days?/);return d?Number(d[1]):null;}
function legacyEvidence(hs=[]){return hs.map((h,i)=>({id:h.legacy_driver||h.problem_id,problem_id:h.problem_id,confidence:h.confidence,memberImportance:h.member_importance,readiness:h.readiness,feasibility:h.feasibility,rank:h.rank||i+1}));}
function mechanismFromSelection(h,a={}){const v=k=>String(a?.[k]??'').toLowerCase();switch(h.problem_id){case'P01':return v('baseline.activity_level')?'activity_level_established':h.mechanism_id;case'P02':return v('baseline.sleep_pattern')?'sleep_pattern_established':h.mechanism_id;case'P03':{const x=v('financial.current_snapshot');if(x.includes('increase income'))return'insufficient_income';if(x.includes('bill')||x.includes('due date'))return'obligation_pressure';if(x.includes('debt'))return'debt_pressure';if(x.includes('where my money'))return'visibility_uncertainty';return h.mechanism_id||'financial_state_established';}case'P05':return v('work.current_income_route')?'income_route_established':h.mechanism_id;case'P06':return v('stress.current_context')?'stress_context_established':h.mechanism_id;case'P07':return v('support.available')?'support_access_established':h.mechanism_id;case'P08':return v('environment.current_barrier')?'environment_barrier_established':h.mechanism_id;default:return h.mechanism_id;}}
function legacyDeepening(interventionId){if(interventionId==='I02_SLEEP_CARE_ROUTE')return[{id:'sleep-baseline',evidenceKey:'baseline.sleep_window',purpose:'baseline_measurement',decisionImpact:'Defines the member-specific starting sleep pattern before activation.',prompt:'What time have you usually been falling asleep and waking up recently?',requiredBeforeActivation:true}];return[];}
function component(h,i,status='backlog'){const p=REGISTRY.problems[h.problem_id],legacyId=LEGACY_ACTION_IDS[i.id]||i.id,interventionMechanism=INTERVENTION_MECHANISMS[i.id]||i.id.toLowerCase();return{plan_component_id:`${h.problem_id}:${i.id}`,id:legacyId,canonical_id:i.id,driver:h.legacy_driver||h.problem_id,problem_id:h.problem_id,problem_label:p.label,selection_mechanism_id:h.mechanism_id||null,mechanism_id:interventionMechanism,mechanism:interventionMechanism,intervention_id:i.id,registry_version:REGISTRY_VERSION,purpose:i.purpose,title:i.memberFacingName,rationale:i.rationale||`Selected to address ${p.label} using the current evidence and member-confirmed focus.`,evidence_strength:i.evidenceStrength,action_templates:[...(i.actionTemplates||[])],measurement:{...(i.measurement||{})},deepeningRequirements:legacyDeepening(i.id),review_rule:{...(i.reviewRule||{})},reviewDays:reviewDays(i.reviewRule),expected_affected_area_hypotheses:[...(p.crossDimensionalHypotheses||[])],confidence:+Number(h.confidence).toFixed(3),member_importance:h.member_importance,status,progress:0,decision_trace:{problem_id:h.problem_id,selection_mechanism_id:h.mechanism_id||null,intervention_mechanism_id:interventionMechanism,intervention_id:i.id,discovery_evidence_ids:[...(h.evidence_ids||[])],registry_version:REGISTRY_VERSION}};}
function candidatesFor(h,c={}){const rejected=[...(c.rejectedInterventionIds||[]),...(c.rejectedActionIds||[])],previousMechanisms=new Set(c.previousMechanisms||[]);return eligibleRegistryInterventions(h.problem_id,{mechanismId:h.mechanism_id,rejectedInterventionIds:rejected}).filter(i=>!rejected.includes(LEGACY_ACTION_IDS[i.id]||i.id)&&!(c.contraindications||[]).includes(i.id)).filter(i=>c.adaptationConstraint!=='different_mechanism'||!previousMechanisms.has(INTERVENTION_MECHANISMS[i.id]||i.id.toLowerCase())).sort((a,b)=>(purposeRank[a.purpose]??99)-(purposeRank[b.purpose]??99)).map(i=>component(h,i));}
function selectCovered(groups,limit){const active=[],backlog=[];for(const g of groups){if(active.length<limit&&g.items.length){active.push({...g.items[0],status:'active'});backlog.push(...g.items.slice(1));}else backlog.push(...g.items);}return{active,backlog};}
export function buildPlan(discovery={},context={}){
 if(context.safetyHold||discovery.safetyHold)return{status:'escalate',reason:'safety_hold',active:[],backlog:[],registry_version:REGISTRY_VERSION};
 if(context.consent===false)return{status:'observe',reason:'member_consent_required',active:[],backlog:[],registry_version:REGISTRY_VERSION};
 let supported=problemHypothesesFromDiscovery(discovery).filter(confidenceSufficient);
 if(!supported.length)return{status:'observe',reason:'insufficient_evidence',active:[],backlog:[],registry_version:REGISTRY_VERSION};
 const compat=legacyEvidence(supported),missing=missingSelectionRequirements(compat,context.selectionEvidence||{});
 if(missing.length)return{status:'deepen',reason:'selection_evidence_required',active:[],backlog:[],registry_version:REGISTRY_VERSION,selectionDeepening:{required:true,requirements:missing.map(r=>({...r,problem_id:compat.find(e=>missingSelectionRequirements([e],context.selectionEvidence||{}).some(m=>m.evidenceKey===r.evidenceKey))?.problem_id||null}))},evidenceUsed:supported};
 supported=supported.map(h=>({...h,mechanism_id:mechanismFromSelection(h,context.selectionEvidence||{})}));
 const groups=supported.map(h=>({h,items:candidatesFor(h,context)})).filter(g=>g.items.length);
 if(!groups.length)return{status:'observe',reason:'no_eligible_registry_intervention',active:[],backlog:[],registry_version:REGISTRY_VERSION,evidenceUsed:supported};
 const limit=activeLimit(context);if(!limit)return{status:'observe',reason:'capacity_hold',active:[],backlog:groups.flatMap(g=>g.items),registry_version:REGISTRY_VERSION,evidenceUsed:supported};
 const {active,backlog}=selectCovered(groups,limit),coveredProblems=[...new Set(active.map(x=>x.problem_id))],uncoveredProblems=supported.map(h=>h.problem_id).filter(id=>!coveredProblems.includes(id)),rejected=[...(context.rejectedInterventionIds||[]),...(context.rejectedActionIds||[])];
 const windows=active.map(x=>x.reviewDays).filter(Number.isFinite);
 const plan={status:'active',reason:'registry_evidence_informed_priority',registry_version:REGISTRY_VERSION,active,actions:active,backlog,history:[],reviewDays:windows.length?Math.min(...windows):null,selectionEvidence:{...(context.selectionEvidence||{})},evidenceUsed:supported,decisionTrace:{selectedInterventionIds:active.map(x=>x.intervention_id),selectedActionIds:active.map(x=>x.id),coveredProblems,coveredDrivers:[...new Set(active.map(x=>x.driver))],uncoveredProblems,uncoveredDrivers:supported.map(h=>h.legacy_driver||h.problem_id).filter(id=>!active.some(a=>a.driver===id)),coverageRule:'one-purposeful-component-per-supported-focus-before-second-component',rejectedInterventionIds:rejected,rejectedActionIds:rejected,adaptationConstraint:context.adaptationConstraint||null},memberFit:{capacity:context.capacity||'medium'}};
 return applyPlanDeepening(plan,context.evidence||{});
}
export const LIBRARY=REGISTRY.interventions;
