import test from 'node:test';
import assert from 'node:assert/strict';
import {buildPlan,respondToItem,recordProgress,adaptPlan,MIN_ACTION_CONFIDENCE} from './plan-engine.js';

test('buildPlan creates at most two independently justified active actions',()=>{const plan=buildPlan({ranked:[{id:'poor_sleep',confidence:.9,memberImportance:5,readiness:4},{id:'low_activity',confidence:.8,memberImportance:4,readiness:4}]},{capacity:'medium'});assert.equal(plan.status,'active');assert.ok(plan.active.length<=2);assert.deepEqual(plan.decisionTrace.selectedActionIds,plan.active.map(x=>x.id));});
test('low capacity hard-throttles plan to one action',()=>{const plan=buildPlan({ranked:[{id:'poor_sleep',confidence:.9},{id:'low_activity',confidence:.8}]},{capacity:'low'});assert.equal(plan.active.length,1);});
test('no capacity creates no active optimization action',()=>{const plan=buildPlan({ranked:[{id:'poor_sleep',confidence:.9}]},{capacity:'none'});assert.equal(plan.reason,'capacity_hold');assert.equal(plan.active.length,0);});
test('safety and consent are hard gates',()=>{assert.equal(buildPlan({ranked:[{id:'poor_sleep',confidence:.9}],safetyHold:true},{}).status,'escalate');assert.equal(buildPlan({ranked:[{id:'poor_sleep',confidence:.9}]},{consent:false}).reason,'member_consent_required');});
test('unsupported confidence cannot silently create action certainty',()=>{const plan=buildPlan({ranked:[{id:'poor_sleep',confidence:MIN_ACTION_CONFIDENCE-.01}]},{});assert.equal(plan.reason,'insufficient_evidence');assert.equal(plan.active.length,0);});
test('explicitly rejected action cannot be silently reinserted',()=>{const plan=buildPlan({ranked:[{id:'low_activity',confidence:.9}]},{rejectedActionIds:['walk']});assert.ok(!plan.active.some(x=>x.id==='walk'));assert.deepEqual(plan.decisionTrace.rejectedActionIds,['walk']);});
test('respondToItem evaluates one action without failing the remaining plan',()=>{const plan=buildPlan({ranked:[{id:'poor_sleep',confidence:.9},{id:'low_activity',confidence:.8}]},{capacity:'medium'});const id=plan.active[0].id;const next=respondToItem(plan,id,{decision:'complete'},{});assert.ok(next.history.some(x=>x.id===id));assert.ok(!next.active.some(x=>x.id===id));});
test('recordProgress completes cadence target independently',()=>{const plan=buildPlan({ranked:[{id:'low_activity',confidence:.9}]},{capacity:'low'}),item=plan.active[0];const next=recordProgress(plan,item.id,item.cadence.target,{capacity:'low'});assert.ok(next.history.some(x=>x.id===item.id));});
test('adaptation separates adherence/barrier from poor outcome after adherence',()=>{const plan=buildPlan({ranked:[{id:'poor_sleep',confidence:.9}]},{});assert.equal(adaptPlan(plan,{adherence:.3}).failureAttribution,'adherence_or_barrier');assert.equal(adaptPlan(plan,{adherence:.8,benefit:0}).failureAttribution,'action_or_hypothesis');assert.equal(adaptPlan(plan,{adherence:.8,benefit:.5}).adaptation,'maintain');});
test('Discovery feasibility changes friction budget and is preserved',()=>{const low=buildPlan({ranked:[{id:'low_activity',confidence:.9,feasibility:{values:{capacity:'low'},constraints:[],supports:[]}}]},{});const high=buildPlan({ranked:[{id:'low_activity',confidence:.9,feasibility:{values:{capacity:'high'},constraints:[],supports:[]}}]},{});assert.ok(low.active[0].friction.budget<high.active[0].friction.budget);assert.equal(low.evidenceUsed[0].feasibility.values.capacity,'low');});
