// EL8 Adaptive Plan Composer — MVP.
// Dynamically composes 1–2 independently justified actions from current evidence.
import { LIBRARY, candidatesForDriver } from './intervention-library.js';
import { applyPlanDeepening } from './plan-deepening.js';
import { missingSelectionRequirements } from './selection-evidence.js';
const clamp=(n,min,max)=>Math.max(min,Math.min(max,n)),MIN_ACTION_CONFIDENCE=.55;
function normalizeEvidence(input={}){const ranked=input.ranked||input.drivers||[];return ranked.map((x,i)=>typeof x==='string'?{id:x,confidence:null,rank:i+1}:{rank:i+1,...x,confidence:x.confidence??x.score??x.evidenceConfidence??null});}
function adherenceEstimate(c={}){const raw=c.adherence??c.recentAdherence??c.adherenceScore;return raw==null?.6:clamp(Number(raw),0,1)}
function driverFeasibility(d={}){return d.feasibility?.values||d.feasibility||{}}
function mergedContext(d={},c={}){const f=driverFeasibility(d);return{...c,...f,capacity:f.capacity??c.capacity,supports:[...(c.supports||[]),...(d.feasibility?.supports||[])],constraints:[...(c.constraints||[]),...(d.feasibility?.constraints||[])]}}
function frictionBudget(c={}){const a=adherenceEstimate(c),base=c.capacity==='low'?1.6:c.capacity==='high'?4.4:3;return clamp(base+((a-.6)*2.5),1,5)}
function evidenceWeight(s){return s==='supported'?.5:s==='evidence_informed'?.15:0}
function constraintTokens(d={},c={}){const f=d.feasibility||{};return new Set([...(c.contraindications||[]),...(c.constraints||[]),...(d.contraindications||[]),...(f.constraints||[])].map(String))}
function confidenceSufficient(d={}){return Number.isFinite(Number(d.confidence))&&Number(d.confidence)>=MIN_ACTION_CONFIDENCE}
function text(v){return String(v??'').trim().toLowerCase()}
function selectionFit(driver,action,context={}){const e=context.selectionEvidence||{},v=key=>text(e[key]);let score=0,exclude=false,reasons=[];const add=(n,r)=>{score+=n;if(r)reasons.push(r)};
 if(driver.id==='money_pressure'){const x=v('financial.current_snapshot');if(x.includes('where my money')||x.includes('cash')||x.includes('bills and due'))add(action.id==='money_snapshot'?4:-1,'financial need fit');else if(x.includes('specific bill')||x.includes('debt'))add(action.id==='financial_next_step'?4:1,'specific obligation fit');else if(x.includes('increase income')){exclude=true;reasons.push('financial intervention does not match stated income need')}}
 if(driver.id==='poor_sleep'){const x=v('baseline.sleep_pattern');if(x&&(/inconsisten|irregular|vary|timing|bedtime|wake/.test(x)))add(action.id==='stabilize_sleep_window'?3:0,'sleep timing fit');else if(x)add(action.id==='sleep_log'?2:0,'sleep pattern requires observation')}
 if(driver.id==='schedule_disruption'){const x=v('schedule.current_pattern');if(x)add(action.id==='schedule_anchor'?3:0,'schedule disruption fit')}
 if(driver.id==='stress'){const x=v('stress.current_context');if(x.startsWith('no'))add(action.id==='stress_log'?4:action.id==='decompression_block'?-2:0,'stress pattern needs observation');else if(x.startsWith('yes'))add(action.id==='decompression_block'?4:action.id==='stress_log'?-1:0,'stress pattern already understood');else if(x.startsWith('partly'))add(action.id==='stress_log'?2:action.id==='decompression_block'?1:0,'partial stress pattern evidence')}
 if(driver.id==='low_focus'){const x=v('focus.current_pattern');if(x.startsWith('no'))add(action.id==='focus_log'?4:action.id==='focus_block'?-2:0,'focus pattern needs observation');else if(x.startsWith('yes'))add(action.id==='focus_block'?4:action.id==='focus_log'?-1:0,'focus pattern already understood');else if(x.startsWith('partly'))add(action.id==='focus_log'?2:action.id==='focus_block'?1:0,'partial focus pattern evidence')}
 if(driver.id==='low_activity'){const x=v('baseline.activity_level');if(x){const veryLow=/none|no intentional|sedentary|rare|one short|0\b/.test(x);if(veryLow)add(action.id==='activity_baseline'?2:action.id==='walk'?1:action.id==='strength_activity'?-2:0,'current activity fit');else add(action.id==='walk'?2:action.id==='strength_activity'?1:0,'current activity fit')}}
 if(driver.id==='work_instability'){const x=v('work.current_income_route');if(x)add(action.id==='income_action'?3:0,'member-selected income route')}
 if(driver.id==='relationship_strain'&&v('relationship.repair_goal'))add(action.id==='relationship_repair_step'?3:0,'member-stated repair goal');
 if(driver.id==='low_support'){const x=v('support.available');if(/no|none|not/.test(x))add(action.id==='support_map'?4:action.id==='support_contact'?-4:0,'support availability fit');else if(x)add(action.id==='support_contact'?3:0,'available support fit')}
 if(driver.id==='home_instability'&&v('environment.current_barrier'))add(action.id==='home_stability_step'?3:0,'member-stated barrier');
 if(driver.id==='lack_direction'&&v('values.current_direction'))add(action.id==='direction_next_step'?3:0,'member-stated direction');
 return{score,exclude,reasons}}
function isEligible(d,a,c={}){if(!confidenceSufficient(d))return false;const sf=selectionFit(d,a,c);if(sf.exclude)return false;const fit=mergedContext(d,c),readiness=clamp(Number(d.readiness??fit.readiness??3),1,5),min=Number(a.eligibility?.minReadiness??1);if(readiness<min)return false;const blocked=constraintTokens(d,fit);if((a.contraindications||[]).some(x=>blocked.has(String(x))))return false;if(c.rejectedActionIds?.includes(a.id))return false;return true}
function adaptationAdjustment(a={},c={}){if(c.adaptationConstraint==='reduce_burden')return (6-clamp(Number(a.effort),1,5))*2.5;if(c.adaptationConstraint==='different_mechanism'&&c.previousActionIds?.includes(a.id))return-100;return 0}
function priorityScore(d,a,c={}){const fit=mergedContext(d,c),confidence=clamp(Number(d.confidence)||0,0,1),importance=clamp(Number(d.memberImportance??d.importance??3),1,5),leverage=clamp(Number(d.breadth??d.downstreamCount??1),1,5),urgency=clamp(Number(d.urgency??3),1,5),readiness=clamp(Number(d.readiness??fit.readiness??3),1,5),effort=clamp(Number(a.effort),1,5),feasibility=6-effort,budget=frictionBudget(fit),over=Math.max(0,effort-budget),under=Math.max(0,budget-effort),sf=selectionFit(d,a,c);return +(urgency+importance+confidence*5+leverage+readiness+feasibility+evidenceWeight(a.evidenceStrength)+under*.2-over*2.25-(fit.capacity==='low'?effort*.35:fit.capacity==='high'?0:effort*.15)+sf.score+adaptationAdjustment(a,c)).toFixed(3)}
function toCandidate(d,a,p,c={},support=[d]){const fit=mergedContext(d,c),sf=selectionFit(d,a,c);return{...a,cadence:{...a.cadence},driver:d.id,supportingDrivers:support.map(x=>({id:x.id,confidence:+Number(x.confidence).toFixed(3)})),confidence:+Number(d.confidence).toFixed(3),priority:p,status:'backlog',progress:0,friction:{effort:clamp(Number(a.effort),1,5),budget:+frictionBudget(fit).toFixed(2),recentAdherence:+adherenceEstimate(fit).toFixed(2)},feasibilityUsed:d.feasibility||null,selectionFit:{score:sf.score,reasons:sf.reasons},goal:d.goal||`Improve the situation related to ${d.id.replaceAll('_',' ')}`,rationale:sf.reasons.length?`Selected because current member evidence fits this action: ${sf.reasons.join(', ')}.`:'Selected from current evidence, member fit, capacity and feasibility. This action remains an independently testable hypothesis.'}}
function activeLimit(c={}){if(c.capacity==='none')return 0;return c.capacity==='low'?1:2}
function buildCandidates(e,c){const raw=e.flatMap(d=>candidatesForDriver(d.id).filter(a=>isEligible(d,a,c)).map(a=>({driver:d,action:a,priority:priorityScore(d,a,c)}))),by=new Map();for(const x of raw){const old=by.get(x.action.id);if(!old)by.set(x.action.id,{...x,supportingDrivers:[x.driver]});else{old.supportingDrivers.push(x.driver);if(x.priority>old.priority)Object.assign(old,{driver:x.driver,action:x.action,priority:x.priority})}}return[...by.values()].sort((a,b)=>b.priority-a.priority).map(x=>toCandidate(x.driver,x.action,x.priority,c,x.supportingDrivers))}
function evidenceSnapshot(e=[]){return e.map(x=>({id:x.id,confidence:x.confidence,feasibility:x.feasibility||null}))}
function activationEvidence(context={}){return{...(context.selectionEvidence||{}),...(context.evidence||{})}}
export function buildPlan(discovery={},context={}){if(context.safetyHold||discovery.safetyHold)return{status:'escalate',reason:'safety_hold',active:[],backlog:[],history:[],reviewDays:null};if(context.consent===false)return{status:'observe',reason:'member_consent_required',active:[],backlog:[],history:[],reviewDays:null};const evidence=normalizeEvidence(discovery),supported=evidence.filter(confidenceSufficient);if(!supported.length)return{status:'observe',reason:'insufficient_evidence',active:[],backlog:[],history:[],reviewDays:7,evidenceUsed:evidenceSnapshot(evidence)};const missing=missingSelectionRequirements(supported,context.selectionEvidence||{});if(missing.length)return{status:'deepen',reason:'selection_evidence_required',active:[],backlog:[],history:[],reviewDays:null,evidenceUsed:evidenceSnapshot(supported),selectionDeepening:{required:true,requirements:missing}};const backlog=buildCandidates(supported,context);if(!backlog.length)return{status:'observe',reason:'no_eligible_authorized_action',active:[],backlog:[],history:[],reviewDays:7,evidenceUsed:evidenceSnapshot(supported)};const limit=activeLimit(context);if(limit===0)return{status:'observe',reason:'capacity_hold',active:[],backlog,history:[],reviewDays:7,evidenceUsed:evidenceSnapshot(supported)};const active=backlog.splice(0,limit).map(x=>({...x,status:'active'}));const plan={status:'active',reason:'evidence_informed_priority',active,backlog,history:[],actions:active,reviewDays:Math.min(...active.map(a=>a.reviewDays)),evidenceUsed:evidenceSnapshot(supported),selectionEvidence:{...(context.selectionEvidence||{})},decisionTrace:{candidateActionIds:[...active,...backlog].map(x=>x.id),selectedActionIds:active.map(x=>x.id),excludedEvidenceIds:evidence.filter(x=>!confidenceSufficient(x)).map(x=>x.id),capacity:context.capacity||'medium',rejectedActionIds:[...(context.rejectedActionIds||[])],adaptationConstraint:context.adaptationConstraint||null},memberFit:{recentAdherence:+adherenceEstimate(context).toFixed(2),frictionBudget:+frictionBudget(context).toFixed(2),capacity:context.capacity||'medium'},uncertainty:'Each action is a hypothesis to test; grouping does not establish causality or package-level success.'};return applyPlanDeepening(plan,activationEvidence(context))}
export function respondToItem(plan={},itemId,response={},context={}){if(plan.status!=='active')return plan;const active=[...(plan.active||plan.actions||[])],backlog=[...(plan.backlog||[])],history=[...(plan.history||[])],index=active.findIndex(x=>x.id===itemId);if(index<0)return plan;const item=active[index],decision=response.decision||'complete';active.splice(index,1);history.push({...item,status:decision,reason:response.reason||null,respondedAt:response.respondedAt||null});if(decision==='defer')backlog.push({...item,status:'backlog',deferred:true});while(active.length<activeLimit(context)&&backlog.length)active.push({...backlog.shift(),status:'active',deferred:false});return applyPlanDeepening({...plan,active,actions:active,backlog,history},activationEvidence(context))}
export function recordProgress(plan={},itemId,amount=1,context={}){const active=[...(plan.active||[])],i=active.findIndex(x=>x.id===itemId);if(i<0)return plan;const item={...active[i]},target=Number(item.cadence?.target||1);item.progress=Math.min(target,Number(item.progress||0)+amount);active[i]=item;let next={...plan,active,actions:active};if(item.progress>=target)next=respondToItem(next,itemId,{decision:'complete'},context);return next}
export function planView(plan={}){const groups={daily:[],thisWeek:[],scheduled:[],oneTime:[]};for(const item of plan.active||[]){const c=item.cadence||{},view={...item,progressLabel:`${item.progress||0}/${c.target||1}`};if(c.type==='daily')groups.daily.push(view);else if(c.type==='weekly_target')groups.thisWeek.push(view);else if(c.type==='specific_days')groups.scheduled.push(view);else groups.oneTime.push(view)}return{...groups,backlogCount:(plan.backlog||[]).length}}
export function adaptPlan(plan={},feedback={}){if(plan.status!=='active')return{...plan,adaptation:'no_active_plan'};const adherence=clamp(Number(feedback.adherence??1),0,1),benefit=clamp(Number(feedback.benefit??0),-1,1);if(feedback.safetyHold)return{...plan,status:'escalate',active:[],actions:[],adaptation:'escalate'};if(feedback.circumstancesChanged)return{...plan,adaptation:'reprioritize'};if(feedback.blocked||adherence<.5)return{...plan,adaptation:'simplify_or_reschedule',failureAttribution:'adherence_or_barrier'};if(adherence>=.7&&benefit>0)return{...plan,adaptation:'maintain',failureAttribution:null};if(adherence>=.7&&benefit<=0)return{...plan,adaptation:'reassess',failureAttribution:'action_or_hypothesis'};return{...plan,adaptation:'continue_observation',failureAttribution:'insufficient_observation'}}
export{LIBRARY,MIN_ACTION_CONFIDENCE};