import test from 'node:test';
import assert from 'node:assert/strict';
import {canonicalProblemId,problemHypothesesFromDiscovery,eligibleRegistryInterventions,selectRegistryIntervention,registryPlanningCandidates,registryMetadata} from './problem-registry-adapter.js';

test('legacy and canonical Member State problems map to stable registry IDs',()=>{assert.equal(canonicalProblemId('low_activity'),'P01');assert.equal(canonicalProblemId('problem:low_activity'),'P01');assert.equal(canonicalProblemId('problem:financial_strain'),'P03');assert.equal(canonicalProblemId('problem:income_gap'),'P05');assert.equal(canonicalProblemId('problem:social_disconnection'),'P07');assert.equal(canonicalProblemId('P06'),'P06');assert.equal(canonicalProblemId('problem:unknown'),null);});
test('canonical Member State problem becomes registry hypothesis with provenance',()=>{const [h]=problemHypothesesFromDiscovery({ranked:[{problemId:'problem:financial_strain',confidence:.91,memberImportance:.9,evidenceRefs:['money.current']}]});assert.equal(h.problem_id,'P03');assert.equal(h.confidence,.91);assert.deepEqual(h.evidence_ids,['money.current']);});
test('mechanism filtering changes eligible intervention set',()=>{const xs=eligibleRegistryInterventions('P03',{mechanismId:'visibility_uncertainty'});assert.ok(xs.some(x=>x.id==='I03_MONEY_SNAPSHOT'));assert.ok(xs.every(x=>!(x.mechanismIds||[]).length||x.mechanismIds.includes('visibility_uncertainty')));});
test('selected component carries problem, intervention, purpose, registry version and review measurement',()=>{const c=selectRegistryIntervention({problem_id:'P01',confidence:.9,evidence_ids:['activity.low']});assert.equal(c.problem_id,'P01');assert.ok(c.intervention_id);assert.ok(c.purpose);assert.ok(c.registry_version);assert.ok(c.measurement.adherence);assert.ok(c.measurement.outcome);assert.ok(c.review_rule.window);assert.deepEqual(c.decision_trace.discovery_evidence_ids,['activity.low']);});
test('rejected intervention stays rejected and exposes a meaningful alternative when available',()=>{const first=selectRegistryIntervention({problem_id:'P04',confidence:.9});const second=selectRegistryIntervention({problem_id:'P04',confidence:.9},{rejectedInterventionIds:[first.intervention_id]});assert.ok(second);assert.notEqual(second.intervention_id,first.intervention_id);assert.ok(second.decision_trace.rejected_intervention_ids.includes(first.intervention_id));});
test('multiple supported problems remain separate planning candidates',()=>{const xs=registryPlanningCandidates({ranked:[{problemId:'problem:low_activity',confidence:.9},{problemId:'problem:financial_strain',confidence:.85}]});assert.deepEqual(xs.map(x=>x.problem_id),['P01','P03']);});
test('registry metadata is persisted-ready',()=>{const m=registryMetadata();assert.match(m.registry_version,/wave1/);assert.ok(m.evidence_review_date);});
