import test from 'node:test';
import assert from 'node:assert/strict';
import {canonicalProblemId,problemHypothesesFromDiscovery,eligibleRegistryInterventions,selectRegistryIntervention,registryPlanningCandidates,registryMetadata} from './problem-registry-adapter.js';

const trace=(states)=>({trace:{states}});
test('legacy and canonical Member State problems map to stable registry IDs',()=>{assert.equal(canonicalProblemId('low_activity'),'P01');assert.equal(canonicalProblemId('problem:low_activity'),'P01');assert.equal(canonicalProblemId('problem:financial_strain'),'P03');assert.equal(canonicalProblemId('problem:income_gap'),'P05');assert.equal(canonicalProblemId('problem:social_disconnection'),'P07');assert.equal(canonicalProblemId('P06'),'P06');assert.equal(canonicalProblemId('problem:unknown'),null);});
test('canonical Discovery state becomes registry hypothesis without fabricated numeric authority',()=>{const [h]=problemHypothesesFromDiscovery(trace([{problemId:'problem:financial_strain',evidenceConfidence:'Well-supported',memberImportance:'high',readiness:'moderate',evidenceRefs:['money.current']}]));assert.equal(h.problem_id,'P03');assert.equal(h.evidence_confidence,'Well-supported');assert.equal(h.member_importance,'high');assert.equal(h.readiness,'moderate');assert.deepEqual(h.evidence_ids,['money.current']);});
test('missing qualitative factors remain unknown rather than defaulting to zero',()=>{const [h]=problemHypothesesFromDiscovery(trace([{problemId:'problem:poor_sleep'}]));assert.equal(h.evidence_confidence,null);assert.equal(h.member_importance,null);assert.equal(h.readiness,null);});
test('obsolete ranked/priorities/candidates Discovery shapes do not feed canonical Planning',()=>{assert.deepEqual(problemHypothesesFromDiscovery({ranked:[{problemId:'problem:poor_sleep'}]}),[]);assert.deepEqual(problemHypothesesFromDiscovery({priorities:[{problemId:'problem:poor_sleep'}]}),[]);assert.deepEqual(problemHypothesesFromDiscovery({candidates:[{problemId:'problem:poor_sleep'}]}),[]);});
test('mechanism filtering changes eligible intervention set',()=>{const xs=eligibleRegistryInterventions('P03',{mechanismId:'visibility_uncertainty'});assert.ok(xs.some(x=>x.id==='I03_MONEY_SNAPSHOT'));assert.ok(xs.every(x=>!(x.mechanismIds||[]).length||x.mechanismIds.includes('visibility_uncertainty')));});
test('selected component carries problem, intervention, purpose, registry version and review measurement',()=>{const c=selectRegistryIntervention({problem_id:'P01',evidence_confidence:'Well-supported',evidence_ids:['activity.low']});assert.equal(c.problem_id,'P01');assert.ok(c.intervention_id);assert.ok(c.purpose);assert.ok(c.registry_version);assert.ok(c.measurement.adherence);assert.ok(c.measurement.outcome);assert.ok(c.review_rule.window);assert.deepEqual(c.decision_trace.discovery_evidence_ids,['activity.low']);assert.equal(c.decision_trace.evidence_confidence,'Well-supported');});
test('rejected intervention stays rejected and exposes a meaningful alternative when available',()=>{const first=selectRegistryIntervention({problem_id:'P04'});const second=selectRegistryIntervention({problem_id:'P04'},{rejectedInterventionIds:[first.intervention_id]});assert.ok(second);assert.notEqual(second.intervention_id,first.intervention_id);assert.ok(second.decision_trace.rejected_intervention_ids.includes(first.intervention_id));});
test('multiple supported problems remain separate planning candidates',()=>{const xs=registryPlanningCandidates(trace([{problemId:'problem:low_activity',evidenceConfidence:'Moderate evidence'},{problemId:'problem:financial_strain',evidenceConfidence:'Well-supported'}]));assert.deepEqual(xs.map(x=>x.problem_id),['P01','P03']);});
test('registry metadata is persisted-ready',()=>{const m=registryMetadata();assert.match(m.registry_version,/wave1/);assert.ok(m.evidence_review_date);});
