import test from 'node:test';
import assert from 'node:assert/strict';
import {buildCanonicalPlan} from './canonical-plan-engine.js';
import {PROBLEMS,INTERVENTIONS,REGISTRY_VERSION} from './problem-intervention-registry.js';
import {eligibleRegistryInterventions} from './problem-registry-adapter.js';

const PROBLEM_IDS=Object.keys(PROBLEMS);
const evidenceByProblem={P01:{'baseline.activity_level':'Almost none'},P02:{'baseline.sleep_pattern':'Timing changes a lot'},P03:{'financial.current_snapshot':'Get clear on cash, bills and due dates'},P04:{'focus.current_pattern':'Yes — the useful pattern is fairly clear'},P05:{'work.current_income_route':'Apply for jobs'},P06:{'stress.current_context':'Yes — the pattern is fairly clear'},P07:{'support.available':'Yes'},P08:{'environment.current_barrier':'Clutter or organization'}};
const inputFor=(problemIds,{capacity='low',revision=12}={})=>({memberStateRevision:revision,confirmedPriorityIds:problemIds.map(id=>`priority:${id}`),priorityOrder:problemIds.map((id,index)=>({priorityId:`priority:${id}`,rank:index+1})),priorityOrderResolved:true,problems:problemIds.map(id=>({priorityId:`priority:${id}`,problemId:id,evidenceRefs:[`${id}.signal`]})),constraints:{capacity,safety:{disposition:'ORDINARY_FLOW'},throttle:{active:false}}});
const mergedEvidence=ids=>Object.assign({},...ids.map(id=>evidenceByProblem[id]));

for(const problemId of PROBLEM_IDS)test(`canonical scenario parity: ${problemId} produces an authorized bounded intervention`,()=>{const p=buildCanonicalPlan(inputFor([problemId]),{selectionEvidence:evidenceByProblem[problemId]});assert.equal(p.status,'active');assert.equal(p.memberStateRevision,12);assert.equal(p.active.length,1);const c=p.active[0];assert.equal(c.problem_id,problemId);assert.equal(c.priorityId,`priority:${problemId}`);assert.equal(c.registry_version,REGISTRY_VERSION);assert.ok(PROBLEMS[problemId].interventionIds.includes(c.intervention_id));assert.ok(INTERVENTIONS[c.intervention_id].problemIds.includes(problemId));assert.ok(c.purpose);assert.ok(c.measurement?.adherence);assert.ok(c.measurement?.outcome);assert.ok(c.reviewRule?.window);assert.deepEqual(c.evidenceRefs,[`${problemId}.signal`]);assert.ok(p.decisionTrace.selectedInterventionIds.includes(c.intervention_id));});

test('all P01-P08 scenarios stop at the selection evidence gate when evidence is absent',()=>{for(const problemId of PROBLEM_IDS){const p=buildCanonicalPlan(inputFor([problemId]));assert.equal(p.status,'deepen',`${problemId} should deepen before intervention selection`);assert.equal(p.reason,'selection_evidence_required');assert.ok(p.selectionDeepening?.requirements?.length,`${problemId} should declare missing evidence`);}});
test('financial visibility evidence selects the mechanism-specific money snapshot',()=>{const evidence={'financial.current_snapshot':'Understand where my money is going'};const p=buildCanonicalPlan(inputFor(['P03']),{selectionEvidence:evidence});assert.equal(p.status,'active');assert.equal(p.active[0].selectionMechanism,'visibility_uncertainty');assert.equal(p.active[0].intervention_id,'I03_MONEY_SNAPSHOT');});
test('alternative-income evidence selects the mechanism-specific income experiment',()=>{const evidence={'work.current_income_route':'Build or sell something'};const p=buildCanonicalPlan(inputFor(['P05']),{selectionEvidence:evidence});assert.equal(p.status,'active');assert.equal(p.active[0].selectionMechanism,'alternative_income_route');assert.equal(p.active[0].intervention_id,'I05_INCOME_EXPERIMENT');});
test('mechanism-specific eligibility cannot cross problem boundaries',()=>{const xs=eligibleRegistryInterventions('P03',{mechanismId:'visibility_uncertainty'});assert.deepEqual(xs.map(x=>x.id),['I03_MONEY_SNAPSHOT']);assert.ok(xs.every(x=>x.problemIds.includes('P03')));});
test('two accepted priorities remain bounded and preserve independent provenance',()=>{const ids=['P02','P07'];const p=buildCanonicalPlan(inputFor(ids,{capacity:'medium'}),{selectionEvidence:mergedEvidence(ids)});assert.equal(p.status,'active');assert.equal(p.active.length,2);assert.deepEqual(new Set(p.active.map(x=>x.problem_id)),new Set(ids));assert.deepEqual(new Set(p.active.map(x=>x.priorityId)),new Set(ids.map(id=>`priority:${id}`)));assert.ok(p.active.every(x=>x.evidenceRefs.length===1));});
test('low capacity never activates more than one accepted priority',()=>{const ids=['P02','P01','P07'];const p=buildCanonicalPlan(inputFor(ids,{capacity:'low'}),{selectionEvidence:mergedEvidence(ids)});assert.equal(p.status,'active');assert.equal(p.active.length,1);assert.equal(p.active[0].problem_id,'P02');});
test('different intervention adaptation excludes the previous intervention',()=>{const evidence=evidenceByProblem.P04;const first=buildCanonicalPlan(inputFor(['P04']),{selectionEvidence:evidence});assert.equal(first.status,'active');const previous=first.active[0].intervention_id;const next=buildCanonicalPlan(inputFor(['P04'],{revision:13}),{selectionEvidence:evidence,adaptationConstraint:'different_intervention',previousInterventionIds:[previous]});assert.equal(next.status,'active');assert.notEqual(next.active[0].intervention_id,previous);assert.equal(next.decisionTrace.adaptationConstraint,'different_intervention');});
test('reduce burden adaptation respects the maximum effort',()=>{const p=buildCanonicalPlan(inputFor(['P01'],{revision:14}),{selectionEvidence:evidenceByProblem.P01,adaptationConstraint:'reduce_burden',maxEffort:1});assert.equal(p.status,'active');assert.ok(p.active.every(x=>x.effort==null||x.effort<=1));assert.equal(p.active[0].intervention_id,'I01_ACTIVITY_BASELINE');});
test('rejected interventions remain excluded during adaptation',()=>{const p=buildCanonicalPlan(inputFor(['P04'],{revision:15}),{selectionEvidence:evidenceByProblem.P04,rejectedInterventionIds:['I04_NEXT_ACTION']});assert.equal(p.status,'active');assert.equal(p.active[0].intervention_id,'I04_REMOVE_BLOCKER');assert.ok(!p.active.some(x=>x.intervention_id==='I04_NEXT_ACTION'));});
